.TH "lib/Modules Directory Reference" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Modules Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCalibrator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCloverSpectra\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCobaltCalorimeter\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEvolutionPeaks\&.hpp\fP"
.br
.ti -1c
.RI "file \fBFaster2Histo\&.hpp\fP"
.br
.ti -1c
.RI "file \fBFaster2Root\&.hpp\fP"
.br
.ti -1c
.RI "file \fBNearLine\&.hpp\fP"
.br
.ti -1c
.RI "file \fBRunMatrixator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTimeshifts\&.hpp\fP"
.br
.in -1c
