.TH "lib/Modules Directory Reference" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Modules Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCalibration\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCloverSpectra\&.hpp\fP"
.br
.ti -1c
.RI "file \fBFaster2Histo\&.hpp\fP"
.br
.ti -1c
.RI "file \fBFaster2Root\&.hpp\fP"
.br
.ti -1c
.RI "file \fBHistogramor\&.hpp\fP"
.br
.ti -1c
.RI "file \fBNearLine\&.hpp\fP"
.br
.ti -1c
.RI "file \fBRunMatrixator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTimeshifts\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTimewalk\&.hpp\fP"
.br
.in -1c
