.TH "lib/Analyse Directory Reference" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Analyse Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBArrays\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAnalysedSpectra\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCloverModule\&.hpp\fP"
.br
.ti -1c
.RI "file \fBClovers\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCounters\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDSSD\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEventAnalyse\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParis\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParisBidimAngles\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParisCluster\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParisLabel\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParisModule\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParisPhoswitch\&.hpp\fP"
.br
.ti -1c
.RI "file \fBParisXY\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPositionXY\&.hpp\fP"
.br
.ti -1c
.RI "file \fBRecalibration\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSorted_Event\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSpectraAlignator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSpectraCo\&.hpp\fP"
.br
.in -1c
