.TH "lib/Classes/AnalysisEvent.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/AnalysisEvent.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnalysisEvent\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
