.TH "BiggestPeakFitter" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiggestPeakFitter \- Allows one to find the most significant peak in the range [low_edge, high_edge]\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libRoot\&.hpp>\fP
.PP
Inherits \fBPeakFitter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBiggestPeakFitter\fP (TH1 *histo, double low_edge=\-1, double high_edge=\-1, int const &order_background=3)"
.br
.RI "Allows one to find the most significant peak in the range [low_edge, high_edge]\&. "
.ti -1c
.RI "void \fBfit\fP ()"
.br
.RI "Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&. "
.ti -1c
.RI "void \fBfit\fP (TH1 *histo, double low_edge, double high_edge, double mean=\-1, double sigma=\-1, double constante=\-1)"
.br
.RI "Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&. "
.ti -1c
.RI "auto \fBgetBackground\fP () const"
.br
.ti -1c
.RI "auto \fBgetConstante\fP () const"
.br
.ti -1c
.RI "auto const  & \fBgetFit\fP () const"
.br
.ti -1c
.RI "auto \fBgetMean\fP () const"
.br
.ti -1c
.RI "auto \fBgetSigma\fP () const"
.br
.ti -1c
.RI "auto \fBoperator\->\fP ()"
.br
.ti -1c
.RI "auto \fBsetBackgroundOrder\fP (int const &order_background)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "TF1 * \fBfinal_fit\fP = nullptr"
.br
.ti -1c
.RI "double \fBm_high_edge\fP = 0\&.0"
.br
.ti -1c
.RI "TH1 * \fBm_histo\fP"
.br
.ti -1c
.RI "bool \fBm_low_binning\fP = true"
.br
.ti -1c
.RI "double \fBm_low_edge\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBm_order_background\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows one to find the most significant peak in the range [low_edge, high_edge]\&. 

Requires little background so you may need to make a background substraction first requires the number of counts of the most significant bin to be at least 1\&.2x higher than in the other peaks 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BiggestPeakFitter::BiggestPeakFitter (TH1 * histo, double low_edge = \fC\-1\fP, double high_edge = \fC\-1\fP, int const & order_background = \fC3\fP)\fC [inline]\fP"

.PP
Allows one to find the most significant peak in the range [low_edge, high_edge]\&. 
.SH "Member Function Documentation"
.PP 
.SS "void PeakFitter::fit ()\fC [inline]\fP, \fC [inherited]\fP"

.PP
Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&. 
.SS "void PeakFitter::fit (TH1 * histo, double low_edge, double high_edge, double mean = \fC\-1\fP, double sigma = \fC\-1\fP, double constante = \fC\-1\fP)\fC [inline]\fP, \fC [inherited]\fP"

.PP
Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&. 
.SS "auto PeakFitter::getBackground () const\fC [inline]\fP, \fC [inherited]\fP"

.SS "auto PeakFitter::getConstante () const\fC [inline]\fP, \fC [inherited]\fP"

.SS "auto const& PeakFitter::getFit () const\fC [inline]\fP, \fC [inherited]\fP"

.SS "auto PeakFitter::getMean () const\fC [inline]\fP, \fC [inherited]\fP"

.SS "auto PeakFitter::getSigma () const\fC [inline]\fP, \fC [inherited]\fP"

.SS "auto PeakFitter::operator\-> ()\fC [inline]\fP, \fC [inherited]\fP"

.SS "auto PeakFitter::setBackgroundOrder (int const & order_background)\fC [inline]\fP, \fC [inherited]\fP"

.SH "Member Data Documentation"
.PP 
.SS "TF1* PeakFitter::final_fit = nullptr\fC [protected]\fP, \fC [inherited]\fP"

.SS "double PeakFitter::m_high_edge = 0\&.0\fC [protected]\fP, \fC [inherited]\fP"

.SS "TH1* PeakFitter::m_histo\fC [protected]\fP, \fC [inherited]\fP"

.SS "bool PeakFitter::m_low_binning = true\fC [protected]\fP, \fC [inherited]\fP"

.SS "double PeakFitter::m_low_edge = 0\&.0\fC [protected]\fP, \fC [inherited]\fP"

.SS "double PeakFitter::m_order_background = 3\fC [protected]\fP, \fC [inherited]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
