.TH "Bools" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bools
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libCo\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBbegin\fP ()"
.br
.ti -1c
.RI "auto \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBBools\fP ()"
.br
.ti -1c
.RI "\fBBools\fP (\fBBools\fP &&other) noexcept"
.br
.ti -1c
.RI "\fBBools\fP (const \fBBools\fP &other)"
.br
.ti -1c
.RI "\fBBools\fP (\fBsize_t\fP \fBsize\fP, bool const &value=false)"
.br
.ti -1c
.RI "auto \fBend\fP ()"
.br
.ti -1c
.RI "auto \fBend\fP () const"
.br
.ti -1c
.RI "\fBBools\fP & \fBoperator=\fP (\fBBools\fP &&other) noexcept"
.br
.ti -1c
.RI "\fBBools\fP & \fBoperator=\fP (const \fBBools\fP &other)"
.br
.ti -1c
.RI "bool & \fBoperator[]\fP (\fBsize_t\fP const &index)"
.br
.ti -1c
.RI "bool const  & \fBoperator[]\fP (\fBsize_t\fP const &index) const"
.br
.ti -1c
.RI "\fBsize_t\fP const  & \fBresize\fP (\fBsize_t\fP \fBsize\fP, bool const &value=false)"
.br
.ti -1c
.RI "\fBsize_t\fP const  & \fBsize\fP () const"
.br
.ti -1c
.RI "\fB~Bools\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool * \fBm_data\fP = nullptr"
.br
.ti -1c
.RI "\fBsize_t\fP \fBm_size\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bools::Bools ()\fC [inline]\fP"

.SS "Bools::Bools (\fBsize_t\fP size, bool const & value = \fCfalse\fP)\fC [inline]\fP"

.SS "Bools::Bools (const \fBBools\fP & other)\fC [inline]\fP"

.SS "Bools::Bools (\fBBools\fP && other)\fC [inline]\fP, \fC [noexcept]\fP"

.SS "Bools::~Bools ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "auto Bools::begin ()\fC [inline]\fP"

.SS "auto Bools::begin () const\fC [inline]\fP"

.SS "auto Bools::end ()\fC [inline]\fP"

.SS "auto Bools::end () const\fC [inline]\fP"

.SS "\fBBools\fP& Bools::operator= (\fBBools\fP && other)\fC [inline]\fP, \fC [noexcept]\fP"

.SS "\fBBools\fP& Bools::operator= (const \fBBools\fP & other)\fC [inline]\fP"

.SS "bool& Bools::operator[] (\fBsize_t\fP const & index)\fC [inline]\fP"

.SS "bool const& Bools::operator[] (\fBsize_t\fP const & index) const\fC [inline]\fP"

.SS "\fBsize_t\fP const& Bools::resize (\fBsize_t\fP size, bool const & value = \fCfalse\fP)\fC [inline]\fP"

.SS "\fBsize_t\fP const& Bools::size () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool* Bools::m_data = nullptr\fC [private]\fP"

.SS "\fBsize_t\fP Bools::m_size = 0\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
