.TH "lib/Classes/Calibration.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/Calibration.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libCo\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Hit\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Detectors\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalibration\fP"
.br
.RI "A convenient class for handling coefficient calibration up to 3rd order\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, \fBCalibration\fP const &calib)"
.br
.RI "Displays the calibration coefficients\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & out, \fBCalibration\fP const & calib)"

.PP
Displays the calibration coefficients\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
