.TH "Calibration::histograms" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calibration::histograms
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Calibration\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBsetBins\fP (std::string const &parameters)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector_MTTHist\fP< TH2F > \fBall_calib\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBall_raw_spectra\fP"
.br
.ti -1c
.RI "\fBVector_MTTHist\fP< TH1F > \fBcalib_spectra\fP"
.br
.ti -1c
.RI "bool \fBinitialized\fP = false"
.br
.ti -1c
.RI "\fBVector_MTTHist\fP< TH1F > \fBraw_spectra\fP"
.br
.ti -1c
.RI "std::map< int, TH1F * > \fBspectra\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Calibration::histograms::Initialize ()"

.SS "void Calibration::histograms::setBins (std::string const & parameters)"

.SH "Member Data Documentation"
.PP 
.SS "\fBVector_MTTHist\fP<TH2F> Calibration::histograms::all_calib"

.SS "\fBMTTHist\fP<TH2F> Calibration::histograms::all_raw_spectra"

.SS "\fBVector_MTTHist\fP<TH1F> Calibration::histograms::calib_spectra"

.SS "bool Calibration::histograms::initialized = false"

.SS "\fBVector_MTTHist\fP<TH1F> Calibration::histograms::raw_spectra"

.SS "std::map<int, TH1F*> Calibration::histograms::spectra"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
