.TH "Calibrator::histograms" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calibrator::histograms
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Calibrator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialise\fP ()"
.br
.ti -1c
.RI "void \fBsetTypeBins\fP (std::string const &parameters)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector_MTTHist\fP< TH2F > \fBall_calib\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBall_raw_spectra\fP"
.br
.ti -1c
.RI "\fBVector_MTTHist\fP< TH1F > \fBcalib_spectra\fP"
.br
.ti -1c
.RI "bool \fBInitialised\fP = false"
.br
.ti -1c
.RI "\fBVector_MTTHist\fP< TH1F > \fBraw_spectra\fP"
.br
.ti -1c
.RI "std::map< \fBLabel\fP, \fBSpectraCo\fP > \fBspectra\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Calibrator::histograms::Initialise ()"

.SS "void Calibrator::histograms::setTypeBins (std::string const & parameters)"

.SH "Member Data Documentation"
.PP 
.SS "\fBVector_MTTHist\fP<TH2F> Calibrator::histograms::all_calib"

.SS "\fBMTTHist\fP<TH2F> Calibrator::histograms::all_raw_spectra"

.SS "\fBVector_MTTHist\fP<TH1F> Calibrator::histograms::calib_spectra"

.SS "bool Calibrator::histograms::Initialised = false"

.SS "\fBVector_MTTHist\fP<TH1F> Calibrator::histograms::raw_spectra"

.SS "std::map<\fBLabel\fP, \fBSpectraCo\fP> Calibrator::histograms::spectra"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
