.TH "lib/Modules/Calibrator.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Modules/Calibrator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libRoot\&.hpp'\fP
.br
\fC#include '\&.\&./Analyse/SpectraCo\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Hit\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Fit\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Calibration\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Detectors\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Event\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/FilesManager\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTFasterReader\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTRootReader\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTTHist\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalibrator\fP"
.br
.RI "Allows one to calculate and verify calibration coefficients for various sources and detectors for Nuball2\&. "
.ti -1c
.RI "struct \fBCalibrator::histograms\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBisTripleAlpha\fP (std::string const &source_name)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool isTripleAlpha (std::string const & source_name)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
