.TH "CloverSpectra" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CloverSpectra \- Make usefull calibrated spectra from data in \&.fast or \&.root format\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CloverSpectra\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCloverSpectra\fP ()=default"
.br
.ti -1c
.RI "\fBCloverSpectra\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBfillHisto\fP (std::string const &datapath='', int nb_files=\-1)"
.br
.ti -1c
.RI "void \fBInitialise\fP ()"
.br
.ti -1c
.RI "void \fBInitialise\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBloadCalibration\fP (std::string const &calibFile)"
.br
.ti -1c
.RI "void \fBloadTimeshifts\fP (std::string const &dTfile)"
.br
.ti -1c
.RI "void \fBprintParameters\fP ()"
.br
.ti -1c
.RI "void \fBsetCalibration\fP (\fBCalibration\fP const &calibration)"
.br
.ti -1c
.RI "void \fBsetDataPath\fP (std::string const &datapath)"
.br
.ti -1c
.RI "void \fBsetNbFiles\fP (int const &nb_files=\-1)"
.br
.ti -1c
.RI "void \fBsetNbThreads\fP (int const &nb_threads=\-1)"
.br
.ti -1c
.RI "void \fBsetOutName\fP (std::string const &outname)"
.br
.ti -1c
.RI "void \fBsetTimeshifts\fP (\fBTimeshifts\fP const &timeshifts)"
.br
.ti -1c
.RI "void \fBsetTimeWindow_ns\fP (int const &timewindow=1500)"
.br
.ti -1c
.RI "void \fBwriteHisto\fP (std::string const &outName='')"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBrunFasterReader\fP (\fBHit\fP &hit, \fBAlignator\fP &tree)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunMTFasterReader\fP (\fBHit\fP &hit, \fBAlignator\fP &tree, \fBCloverSpectra\fP &ce)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "char \fBdataKind\fP = \-1"
.br
.ti -1c
.RI "\fBCalibration\fP \fBm_calibration\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBm_clovers\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBm_clovers_bidim\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBm_clovers_crystal\fP"
.br
.ti -1c
.RI "\fBPath\fP \fBm_dataPath\fP"
.br
.ti -1c
.RI "int \fBm_nb_files\fP = \-1"
.br
.ti -1c
.RI "int \fBm_nb_threads\fP = 1"
.br
.ti -1c
.RI "\fBFile\fP \fBm_outName\fP"
.br
.ti -1c
.RI "bool \fBm_throw_single\fP = false"
.br
.ti -1c
.RI "\fBTimeshifts\fP \fBm_timeshifts\fP"
.br
.ti -1c
.RI "\fBTime\fP \fBm_timewindow\fP = 100000"
.br
.ti -1c
.RI "bool \fBm_writeHisto\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Make usefull calibrated spectra from data in \&.fast or \&.root format\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CloverSpectra::CloverSpectra ()\fC [default]\fP"

.SS "CloverSpectra::CloverSpectra (int argc, char ** argv)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CloverSpectra::fillHisto (std::string const & datapath = \fC''\fP, int nb_files = \fC\-1\fP)\fC [inline]\fP"

.SS "void CloverSpectra::Initialise ()\fC [inline]\fP"

.SS "void CloverSpectra::Initialise (int argc, char ** argv)\fC [inline]\fP"

.SS "void CloverSpectra::loadCalibration (std::string const & calibFile)\fC [inline]\fP"

.SS "void CloverSpectra::loadTimeshifts (std::string const & dTfile)\fC [inline]\fP"

.SS "void CloverSpectra::printParameters ()\fC [inline]\fP"

.SS "void CloverSpectra::runFasterReader (\fBHit\fP & hit, \fBAlignator\fP & tree)\fC [inline]\fP, \fC [private]\fP"

.SS "static void CloverSpectra::runMTFasterReader (\fBHit\fP & hit, \fBAlignator\fP & tree, \fBCloverSpectra\fP & ce)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.SS "void CloverSpectra::setCalibration (\fBCalibration\fP const & calibration)\fC [inline]\fP"

.SS "void CloverSpectra::setDataPath (std::string const & datapath)\fC [inline]\fP"

.SS "void CloverSpectra::setNbFiles (int const & nb_files = \fC\-1\fP)\fC [inline]\fP"

.SS "void CloverSpectra::setNbThreads (int const & nb_threads = \fC\-1\fP)\fC [inline]\fP"

.SS "void CloverSpectra::setOutName (std::string const & outname)\fC [inline]\fP"

.SS "void CloverSpectra::setTimeshifts (\fBTimeshifts\fP const & timeshifts)\fC [inline]\fP"

.SS "void CloverSpectra::setTimeWindow_ns (int const & timewindow = \fC1500\fP)\fC [inline]\fP"

.SS "void CloverSpectra::writeHisto (std::string const & outName = \fC''\fP)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char CloverSpectra::dataKind = \-1\fC [private]\fP"

.SS "\fBCalibration\fP CloverSpectra::m_calibration\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CloverSpectra::m_clovers\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CloverSpectra::m_clovers_bidim\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CloverSpectra::m_clovers_crystal\fC [private]\fP"

.SS "\fBPath\fP CloverSpectra::m_dataPath\fC [private]\fP"

.SS "int CloverSpectra::m_nb_files = \-1\fC [private]\fP"

.SS "int CloverSpectra::m_nb_threads = 1\fC [private]\fP"

.SS "\fBFile\fP CloverSpectra::m_outName\fC [private]\fP"

.SS "bool CloverSpectra::m_throw_single = false\fC [private]\fP"

.SS "\fBTimeshifts\fP CloverSpectra::m_timeshifts\fC [private]\fP"

.SS "\fBTime\fP CloverSpectra::m_timewindow = 100000\fC [private]\fP"

.SS "bool CloverSpectra::m_writeHisto = false\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
