.TH "lib/Modules/CloverSpectra.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Modules/CloverSpectra.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Analyse/Clovers\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/CoincBuilder\&.hpp'\fP
.br
\fC#include 'Timeshifts\&.hpp'\fP
.br
\fC#include 'Calibration\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCloverSpectra\fP"
.br
.RI "Make usefull calibrated spectra from data in \&.fast or \&.root format\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
