.TH "Clovers::PromptGate" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clovers::PromptGate
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Clovers\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (double const &time)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (double const &time, float const &energy)"
.br
.RI "Is the hit in the gate\&. "
.ti -1c
.RI "\fBPromptGate\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "float \fBintermediate_start\fP (float const energy)"
.br
.ti -1c
.RI "float \fBintermediate_stop\fP (float const energy)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBm_high_E\fP = 200"
.br
.ti -1c
.RI "\fBGate\fP \fBm_high_E_gate\fP = {\-15\&.0, 7\&.0 }"
.br
.ti -1c
.RI "float \fBm_low_E\fP = 50"
.br
.ti -1c
.RI "\fBGate\fP \fBm_low_E_gate\fP = {\-20\&.0, 40\&.0}"
.br
.ti -1c
.RI "float \fBm_start_coeff\fP = 0\&.f"
.br
.ti -1c
.RI "float \fBm_start_intercept\fP = 0\&.f"
.br
.ti -1c
.RI "float \fBm_stop_coeff\fP = 0\&.f"
.br
.ti -1c
.RI "float \fBm_stop_intercept\fP = 0\&.f"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Clovers::PromptGate::PromptGate ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "float Clovers::PromptGate::intermediate_start (float const energy)\fC [inline]\fP, \fC [private]\fP"

.SS "float Clovers::PromptGate::intermediate_stop (float const energy)\fC [inline]\fP, \fC [private]\fP"

.SS "bool Clovers::PromptGate::operator() (double const & time)\fC [inline]\fP"

.SS "bool Clovers::PromptGate::operator() (double const & time, float const & energy)\fC [inline]\fP"

.PP
Is the hit in the gate\&. Three zones : high energy, intermediate energy and lower energy\&. The intermediate energies, links the high and low by a straight line whose parameters ax+b are calculated in the constructor
.PP
if in normal mode, simple time gates 
.SH "Member Data Documentation"
.PP 
.SS "float Clovers::PromptGate::m_high_E = 200\fC [private]\fP"

.SS "\fBGate\fP Clovers::PromptGate::m_high_E_gate = {\-15\&.0, 7\&.0 }\fC [private]\fP"

.SS "float Clovers::PromptGate::m_low_E = 50\fC [private]\fP"

.SS "\fBGate\fP Clovers::PromptGate::m_low_E_gate = {\-20\&.0, 40\&.0}\fC [private]\fP"

.SS "float Clovers::PromptGate::m_start_coeff = 0\&.f\fC [private]\fP"

.SS "float Clovers::PromptGate::m_start_intercept = 0\&.f\fC [private]\fP"

.SS "float Clovers::PromptGate::m_stop_coeff = 0\&.f\fC [private]\fP"

.SS "float Clovers::PromptGate::m_stop_intercept = 0\&.f\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
