.TH "CoAnalyse" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoAnalyse
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBProjectionsBins\fP = std::vector< std::pair< double, double > >"
.br
.RI "Vector of pairs of min and max bins\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< double > \fBextractBackgroundArray\fP (std::vector< double > &source, int const &nsmooth=10)"
.br
.ti -1c
.RI "std::vector< double > \fBextractBackgroundArray\fP (TH1F *histo, int const &nsmooth=10)"
.br
.ti -1c
.RI "void \fBnormalizeBidim\fP (TH2 *matrix, double const &factor=1\&.0)"
.br
.RI "Normalise the whole bidim\&. "
.ti -1c
.RI "void \fBnormalizeY\fP (TH2 *matrix, double const &factor=1)"
.br
.RI "For each X bin, normalise the Y histogram\&. "
.ti -1c
.RI "void \fBprojectX\fP (TH2 *matrix, TH1 *proj)"
.br
.RI "Project the whole matrix on the X axis\&. This fills proj\&. "
.ti -1c
.RI "void \fBprojectX\fP (TH2 *matrix, TH1 *proj, double const &binYmin, double const &binYmax)"
.br
.RI "Project on Y axis between values binYmin and binYmax included [binYmin;binYmax]\&. This fills proj\&. "
.ti -1c
.RI "void \fBprojectX\fP (TH2 *matrix, TH1 *proj, int const &binY)"
.br
.RI "Project on X axis at a given Y bin\&. This fills proj\&. "
.ti -1c
.RI "void \fBprojectX\fP (TH2 *matrix, TH1 *proj, int const &binYmin, int const &binYmax)"
.br
.RI "Project on X axis between bin binYmin included and binYmax excluded [binYmin;binYmax[\&. This fills proj\&. "
.ti -1c
.RI "void \fBprojectY\fP (TH2 *matrix, TH1 *proj, double const &valueXmin, double const &valueXmax)"
.br
.RI "Project matrix on Y axis between values valueXmin and valueXmax included [valueXmin;valueXmax]\&. This fills proj\&. "
.ti -1c
.RI "void \fBprojectY\fP (TH2 *matrix, TH1 *proj, int const &binX)"
.br
.RI "Project matrix on Y axis at a given X bin\&. This fills proj\&. "
.ti -1c
.RI "void \fBprojectY\fP (TH2 *matrix, TH1 *proj, int const &binXmin, int const &binXmax)"
.br
.RI "Project matrix on Y axis between bin binXmin included and binXmax excluded [binXmin;binXmax[\&. This fills proj\&. "
.ti -1c
.RI "void \fBremoveBackground\fP (TH1 *histo, int const &niter=10, std::string const &fit_options='', std::string const &bidim_options='X') noexcept"
.br
.RI "Remove the background in the given histo\&. "
.ti -1c
.RI "void \fBremoveRandomBidim\fP (TH2 *matrix, int iterations=1, bool save_intermediate=false, \fBProjectionsBins\fP projectionsY={{}}, \fBProjectionsBins\fP projectionsX={{}})"
.br
.ti -1c
.RI "void \fBremoveRandomY\fP (TH2 *matrix, int _stopX=\-1, int _stopY=\-1, bool writeIntermediate=false, \fBProjectionsBins\fP projections={{}})"
.br
.RI "LEGACY\&. "
.ti -1c
.RI "void \fBsetX\fP (TH2 *matrix, TH1 *proj, int const &binX)"
.br
.RI "Set Y histogram proj in matrix at binX\&. "
.ti -1c
.RI "void \fBsetY\fP (TH2 *matrix, TH1 *proj, int const &binY)"
.br
.RI "Set X histogram proj in matrix at binY\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBCoAnalyse::ProjectionsBins\fP = typedef std::vector<std::pair<double,double> >"

.PP
Vector of pairs of min and max bins\&. 
.SH "Function Documentation"
.PP 
.SS "std::vector<double> CoAnalyse::extractBackgroundArray (std::vector< double > & source, int const & nsmooth = \fC10\fP)"

.PP
\fBDeprecated\fP
.RS 4

.RE
.PP

.SS "std::vector<double> CoAnalyse::extractBackgroundArray (TH1F * histo, int const & nsmooth = \fC10\fP)"

.PP
\fBDeprecated\fP
.RS 4

.RE
.PP

.SS "void CoAnalyse::normalizeBidim (TH2 * matrix, double const & factor = \fC1\&.0\fP)"

.PP
Normalise the whole bidim\&. 
.SS "void CoAnalyse::normalizeY (TH2 * matrix, double const & factor = \fC1\fP)"

.PP
For each X bin, normalise the Y histogram\&. 
.SS "void CoAnalyse::projectX (TH2 * matrix, TH1 * proj)"

.PP
Project the whole matrix on the X axis\&. This fills proj\&. 
.SS "void CoAnalyse::projectX (TH2 * matrix, TH1 * proj, double const & binYmin, double const & binYmax)"

.PP
Project on Y axis between values binYmin and binYmax included [binYmin;binYmax]\&. This fills proj\&. 
.SS "void CoAnalyse::projectX (TH2 * matrix, TH1 * proj, int const & binY)"

.PP
Project on X axis at a given Y bin\&. This fills proj\&. 
.SS "void CoAnalyse::projectX (TH2 * matrix, TH1 * proj, int const & binYmin, int const & binYmax)"

.PP
Project on X axis between bin binYmin included and binYmax excluded [binYmin;binYmax[\&. This fills proj\&. 
.SS "void CoAnalyse::projectY (TH2 * matrix, TH1 * proj, double const & valueXmin, double const & valueXmax)"

.PP
Project matrix on Y axis between values valueXmin and valueXmax included [valueXmin;valueXmax]\&. This fills proj\&. 
.SS "void CoAnalyse::projectY (TH2 * matrix, TH1 * proj, int const & binX)"

.PP
Project matrix on Y axis at a given X bin\&. This fills proj\&. 
.SS "void CoAnalyse::projectY (TH2 * matrix, TH1 * proj, int const & binXmin, int const & binXmax)"

.PP
Project matrix on Y axis between bin binXmin included and binXmax excluded [binXmin;binXmax[\&. This fills proj\&. 
.SS "void CoAnalyse::removeBackground (TH1 * histo, int const & niter = \fC10\fP, std::string const & fit_options = \fC''\fP, std::string const & bidim_options = \fC'X'\fP)\fC [noexcept]\fP"

.PP
Remove the background in the given histo\&. 
.PP
\fBParameters\fP
.RS 4
\fIhisto\fP Can be TH1 or TH2 histogram 
.br
\fIniter\fP Choose a higher number of iterations if the peaks have high resultion (5-10 for LaBr3, 20 for Ge) 
.br
\fIfit_options\fP options from TH1::ShowBackground 
.br
\fIbidim_options\fP 
.IP "\(bu" 2
'X' (default) : Loop through the X bins, find the background on the Y projection
.IP "\(bu" 2
'Y' : Loop through the Y bins, find the background on the X projection
.IP "\(bu" 2
'S' (symmetric): Loop through the X bins, find the background on the Y projection, then symmetrise the bidim 
.PP
.RE
.PP

.SS "void CoAnalyse::removeRandomBidim (TH2 * matrix, int iterations = \fC1\fP, bool save_intermediate = \fCfalse\fP, \fBProjectionsBins\fP projectionsY = \fC{{}}\fP, \fBProjectionsBins\fP projectionsX = \fC{{}}\fP)"

.PP
\fBDeprecated\fP
.RS 4

.RE
.PP

.SS "void CoAnalyse::removeRandomY (TH2 * matrix, int _stopX = \fC\-1\fP, int _stopY = \fC\-1\fP, bool writeIntermediate = \fCfalse\fP, \fBProjectionsBins\fP projections = \fC{{}}\fP)"

.PP
LEGACY\&. 
.SS "void CoAnalyse::setX (TH2 * matrix, TH1 * proj, int const & binX)"

.PP
Set Y histogram proj in matrix at binX\&. 
.SS "void CoAnalyse::setY (TH2 * matrix, TH1 * proj, int const & binY)"

.PP
Set X histogram proj in matrix at binY\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
