.TH "lib/Modules/CobaltCalorimeter.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Modules/CobaltCalorimeter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./MTObjects/MTObject\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Detectors\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Calibration\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Event\&.hpp'\fP
.br
\fC#include '\&.\&./Modules/Timeshifts\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTFasterReader\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTRootReader\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTTHist\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCobaltCalorimeter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcalibBGO\fP (\fBHit\fP &hit)"
.br
.ti -1c
.RI "bool \fBinGate\fP (double const &value, double const &min, double const &max)"
.br
.ti -1c
.RI "float \fBsmear\fP (float const &nrj, \fBLabel\fP const &label, TRandom *random)"
.br
.ti -1c
.RI "float \fBsmear\fP (float const &nrj, TRandom *random)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void calibBGO (\fBHit\fP & hit)"

.SS "bool inGate (double const & value, double const & min, double const & max)"

.SS "float smear (float const & nrj, \fBLabel\fP const & label, TRandom * random)"

.SS "float smear (float const & nrj, TRandom * random)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
