.TH "CoBazar" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoBazar
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlong_progress_bar\fP (float const &progress_procent)"
.br
.ti -1c
.RI "template<class\&.\&.\&. ARGS> double \fBmean\fP (ARGS\&.\&.\&. args)"
.br
.ti -1c
.RI "void \fBprogress_bar\fP (float const &progress_procent, int width=50)"
.br
.ti -1c
.RI "void \fBshort_progress_bar\fP (float const &progress_procent)"
.br
.ti -1c
.RI "template<class T , class\&.\&.\&. ARGS> T \fBsum\fP (T i, ARGS\&.\&.\&. args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void CoBazar::long_progress_bar (float const & progress_procent)"

.SS "template<class\&.\&.\&. ARGS> double CoBazar::mean (ARGS\&.\&.\&. args)\fC [inline]\fP"

.SS "void CoBazar::progress_bar (float const & progress_procent, int width = \fC50\fP)"

.SS "void CoBazar::short_progress_bar (float const & progress_procent)"

.SS "template<class T , class\&.\&.\&. ARGS> T CoBazar::sum (T i, ARGS\&.\&.\&. args)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
