.TH "CobaltCalorimeter" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CobaltCalorimeter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CobaltCalorimeter\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCobaltCalorimeter\fP ()"
.br
.ti -1c
.RI "void \fBInitialise\fP ()"
.br
.ti -1c
.RI "void \fBlaunchFaster\fP (std::string const &foldername, int nb_files=\-1)"
.br
.RI "legacy "
.ti -1c
.RI "void \fBlaunchRoot\fP (std::string const &foldername, int nb_files=\-1)"
.br
.ti -1c
.RI "void \fBloadCalibration\fP (\fBCalibration\fP calib)"
.br
.ti -1c
.RI "void \fBloadID\fP (std::string const &filename)"
.br
.ti -1c
.RI "void \fBloadTimeshifts\fP (\fBTimeshifts\fP timeshifts)"
.br
.ti -1c
.RI "void \fBsetOutName\fP (std::string const &outfilename)"
.br
.ti -1c
.RI "void \fBsetTimewindow_ns\fP (\fBTime_ns\fP const &time_ns)"
.br
.ti -1c
.RI "void \fBwork\fP (\fBHit\fP &hit, \fBAlignator\fP &reader)"
.br
.RI "legacy "
.ti -1c
.RI "void \fBwork\fP (\fBNuball2Tree\fP &tree, \fBEvent\fP &event)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBAnalyse\fP ()"
.br
.ti -1c
.RI "bool \fBNaI_pid\fP (float nrj, float nrj2)"
.br
.ti -1c
.RI "bool \fBNaI_pid\fP (\fBHit\fP &hit)"
.br
.ti -1c
.RI "void \fBwrite\fP ()"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdispatch_workFaster\fP (\fBHit\fP &hit, \fBAlignator\fP &reader, \fBCobaltCalorimeter\fP &cb)"
.br
.ti -1c
.RI "static void \fBdispatch_workRoot\fP (\fBNuball2Tree\fP &tree, \fBEvent\fP &event, \fBCobaltCalorimeter\fP &cb)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBBGO_calo_VS_Clover_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBBGO_calo_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBBGO_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBcalo_double_cascades_VS_multiplicity\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBcalorimetry_BGO_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBcalorimetry_Ge_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBcalorimetry_LaBr_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBcalorimetry_NaI_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBClover_calo_VS_BGO_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBClover_calo_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBClover_calo_without_Paris\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBClover_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_BGO\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_BGO_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_calo_VS_BGO_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_calo_VS_Clover_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_calo_VS_Paris_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_calo_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_Ge\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_Ge_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_LaBr\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_LaBr_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_NaI\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_NaI_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_VS_BGO_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBGe_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBlabels\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBlabels2D_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBLaBr3_calo_VS_BGO_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBLaBr3_calo_VS_Clover_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBLaBr3_calo_VS_Paris_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBLaBr_calo_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBLaBr_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBCalibration\fP \fBm_calib\fP"
.br
.ti -1c
.RI "double \fBm_calo_totale\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBm_calo_totale_BGO\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBm_calo_totale_Ge\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBm_calo_totale_LaBr3\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBm_calo_totale_NaI\fP = 0\&.0"
.br
.ti -1c
.RI "std::string \fBm_IDfilename\fP"
.br
.ti -1c
.RI "int \fBm_maxE\fP = 1339"
.br
.ti -1c
.RI "int \fBm_minE\fP = 1326"
.br
.ti -1c
.RI "int \fBm_nb_missed\fP = 0"
.br
.ti -1c
.RI "int \fBm_nb_trigg\fP = 0"
.br
.ti -1c
.RI "int \fBm_nb_trigg_BGO\fP = 0"
.br
.ti -1c
.RI "int \fBm_nb_trigg_Ge\fP = 0"
.br
.ti -1c
.RI "int \fBm_nb_trigg_LaBr\fP = 0"
.br
.ti -1c
.RI "int \fBm_nb_trigg_NaI\fP = 0"
.br
.ti -1c
.RI "std::string \fBm_outfilename\fP = 'CobaltCalorimetry\&.root'"
.br
.ti -1c
.RI "\fBTimeshifts\fP \fBm_timeshifts\fP"
.br
.ti -1c
.RI "\fBTime\fP \fBm_timewindow\fP = 100000"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBNaI_calo_VS_BGO_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBNaI_calo_VS_Clover_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBNaI_calo_VS_LaBr_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBNaI_calo_VS_Paris_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBNaI_calo_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBNaI_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBnrj_each\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBnrj_each_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBParis_calo_VS_BGO_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBParis_calo_VS_Clover_calo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBParis_calo_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBParis_calo_without_Clover\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBparis_pid\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBParis_VS_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBsmeared_calorimetry_BGO_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBsmeared_calorimetry_BGO_histo_VS_cristalMult\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBsmeared_calorimetry_Clover_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBsmeared_calorimetry_Clover_histo_VS_cristalMult\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBsmeared_calorimetry_Ge_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBsmeared_calorimetry_Ge_histo_VS_cristalMult\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBsmeared_calorimetry_LaBr_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBsmeared_calorimetry_LaBr_histo_VS_cristalMult\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBsmeared_calorimetry_NaI_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBsmeared_calorimetry_NaI_histo_VS_cristalMult\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBsmeared_calorimetry_Paris_histo\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBsmeared_calorimetry_Paris_histo_VS_cristalMult\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBspectra_NaI_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBspectra_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_BGO\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_BGO_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_Ge\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_Ge_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_LaBr3\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_LaBr3_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_NaI\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_NaI_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_smeared_calorimetry\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBspectrum_smeared_calorimetry_double_cascade\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBspectrum_smeared_calorimetry_VS_Multiplicity\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBtimewalk_BGO\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBtimewalk_Ge\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBtimewalk_LaBr\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBtimewalk_NaI\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBtiming_VS_ref\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH2F > \fBtiming_VS_trigger\fP"
.br
.ti -1c
.RI "\fBMTTHist\fP< TH1F > \fBtotal_energy_per_detector\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CobaltCalorimeter::CobaltCalorimeter ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CobaltCalorimeter::Analyse ()\fC [private]\fP"

.SS "static void CobaltCalorimeter::dispatch_workFaster (\fBHit\fP & hit, \fBAlignator\fP & reader, \fBCobaltCalorimeter\fP & cb)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.SS "static void CobaltCalorimeter::dispatch_workRoot (\fBNuball2Tree\fP & tree, \fBEvent\fP & event, \fBCobaltCalorimeter\fP & cb)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.SS "void CobaltCalorimeter::Initialise ()"

.SS "void CobaltCalorimeter::launchFaster (std::string const & foldername, int nb_files = \fC\-1\fP)"

.PP
legacy Deprecated\&.
.PP
\fBDeprecated\fP
.RS 4
.RE
.PP

.SS "void CobaltCalorimeter::launchRoot (std::string const & foldername, int nb_files = \fC\-1\fP)"

.SS "void CobaltCalorimeter::loadCalibration (\fBCalibration\fP calib)\fC [inline]\fP"

.SS "void CobaltCalorimeter::loadID (std::string const & filename)\fC [inline]\fP"

.SS "void CobaltCalorimeter::loadTimeshifts (\fBTimeshifts\fP timeshifts)\fC [inline]\fP"

.SS "bool CobaltCalorimeter::NaI_pid (float nrj, float nrj2)\fC [private]\fP"

.SS "bool CobaltCalorimeter::NaI_pid (\fBHit\fP & hit)\fC [private]\fP"

.SS "void CobaltCalorimeter::setOutName (std::string const & outfilename)\fC [inline]\fP"

.SS "void CobaltCalorimeter::setTimewindow_ns (\fBTime_ns\fP const & time_ns)\fC [inline]\fP"

.SS "void CobaltCalorimeter::work (\fBHit\fP & hit, \fBAlignator\fP & reader)"

.PP
legacy Deprecated\&.
.PP
\fBDeprecated\fP
.RS 4
.RE
.PP

.SS "void CobaltCalorimeter::work (\fBNuball2Tree\fP & tree, \fBEvent\fP & event)"

.SS "void CobaltCalorimeter::write ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::BGO_calo_VS_Clover_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::BGO_calo_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::BGO_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::calo_double_cascades_VS_multiplicity\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::calorimetry_BGO_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::calorimetry_Ge_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::calorimetry_LaBr_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::calorimetry_NaI_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Clover_calo_VS_BGO_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Clover_calo_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::Clover_calo_without_Paris\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Clover_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_BGO\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_BGO_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_calo_VS_BGO_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_calo_VS_Clover_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_calo_VS_Paris_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_calo_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_Ge\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_Ge_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_LaBr\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_LaBr_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_NaI\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_NaI_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_VS_BGO_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Ge_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::labels\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::labels2D_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::LaBr3_calo_VS_BGO_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::LaBr3_calo_VS_Clover_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::LaBr3_calo_VS_Paris_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::LaBr_calo_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::LaBr_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBCalibration\fP CobaltCalorimeter::m_calib\fC [private]\fP"

.SS "double CobaltCalorimeter::m_calo_totale = 0\&.0\fC [private]\fP"

.SS "double CobaltCalorimeter::m_calo_totale_BGO = 0\&.0\fC [private]\fP"

.SS "double CobaltCalorimeter::m_calo_totale_Ge = 0\&.0\fC [private]\fP"

.SS "double CobaltCalorimeter::m_calo_totale_LaBr3 = 0\&.0\fC [private]\fP"

.SS "double CobaltCalorimeter::m_calo_totale_NaI = 0\&.0\fC [private]\fP"

.SS "std::string CobaltCalorimeter::m_IDfilename\fC [private]\fP"

.SS "int CobaltCalorimeter::m_maxE = 1339\fC [private]\fP"

.SS "int CobaltCalorimeter::m_minE = 1326\fC [private]\fP"

.SS "int CobaltCalorimeter::m_nb_missed = 0\fC [private]\fP"

.SS "int CobaltCalorimeter::m_nb_trigg = 0\fC [private]\fP"

.SS "int CobaltCalorimeter::m_nb_trigg_BGO = 0\fC [private]\fP"

.SS "int CobaltCalorimeter::m_nb_trigg_Ge = 0\fC [private]\fP"

.SS "int CobaltCalorimeter::m_nb_trigg_LaBr = 0\fC [private]\fP"

.SS "int CobaltCalorimeter::m_nb_trigg_NaI = 0\fC [private]\fP"

.SS "std::string CobaltCalorimeter::m_outfilename = 'CobaltCalorimetry\&.root'\fC [private]\fP"

.SS "\fBTimeshifts\fP CobaltCalorimeter::m_timeshifts\fC [private]\fP"

.SS "\fBTime\fP CobaltCalorimeter::m_timewindow = 100000\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::NaI_calo_VS_BGO_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::NaI_calo_VS_Clover_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::NaI_calo_VS_LaBr_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::NaI_calo_VS_Paris_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::NaI_calo_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::NaI_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::nrj_each\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::nrj_each_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Paris_calo_VS_BGO_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Paris_calo_VS_Clover_calo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Paris_calo_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::Paris_calo_without_Clover\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::paris_pid\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::Paris_VS_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::smeared_calorimetry_BGO_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::smeared_calorimetry_BGO_histo_VS_cristalMult\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::smeared_calorimetry_Clover_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::smeared_calorimetry_Clover_histo_VS_cristalMult\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::smeared_calorimetry_Ge_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::smeared_calorimetry_Ge_histo_VS_cristalMult\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::smeared_calorimetry_LaBr_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::smeared_calorimetry_LaBr_histo_VS_cristalMult\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::smeared_calorimetry_NaI_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::smeared_calorimetry_NaI_histo_VS_cristalMult\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::smeared_calorimetry_Paris_histo\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::smeared_calorimetry_Paris_histo_VS_cristalMult\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::spectra_NaI_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::spectra_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_BGO\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_BGO_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_Ge\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_Ge_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_LaBr3\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_LaBr3_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_NaI\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_NaI_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_smeared_calorimetry\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::spectrum_smeared_calorimetry_double_cascade\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::spectrum_smeared_calorimetry_VS_Multiplicity\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::timewalk_BGO\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::timewalk_Ge\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::timewalk_LaBr\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::timewalk_NaI\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::timing_VS_ref\fC [private]\fP"

.SS "\fBMTTHist\fP<TH2F> CobaltCalorimeter::timing_VS_trigger\fC [private]\fP"

.SS "\fBMTTHist\fP<TH1F> CobaltCalorimeter::total_energy_per_detector\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
