.TH "CoDataFrame< Index, T >" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoDataFrame< Index, T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <files_functions\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoDataFrame\fP ()=default"
.br
.ti -1c
.RI "\fBCoDataFrame\fP (std::string const &\fBfilename\fP, std::string const &type='csv')"
.br
.ti -1c
.RI "auto const  & \fBfilename\fP () const"
.br
.ti -1c
.RI "void \fBload\fP (std::string const &\fBfilename\fP, std::string const &type)"
.br
.ti -1c
.RI "void \fBoperator<<\fP (std::istringstream &iss)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBgood\fP = false"
.br
.ti -1c
.RI "std::vector< std::vector< T > > \fBm_data\fP"
.br
.ti -1c
.RI "std::string \fBm_filename\fP"
.br
.ti -1c
.RI "std::vector< Index > \fBm_index\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBsize\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Index , class T > \fBCoDataFrame\fP< Index, T >::\fBCoDataFrame\fP ()\fC [default]\fP"

.SS "template<class Index , class T > \fBCoDataFrame\fP< Index, T >::\fBCoDataFrame\fP (std::string const & filename, std::string const & type = \fC'csv'\fP)"

.SH "Member Function Documentation"
.PP 
.SS "template<class Index , class T > auto const& \fBCoDataFrame\fP< Index, T >::filename () const\fC [inline]\fP"

.SS "template<class Index , class T > void \fBCoDataFrame\fP< Index, T >::load (std::string const & filename, std::string const & type)"

.SS "template<class Index , class T > void \fBCoDataFrame\fP< Index, T >::operator<< (std::istringstream & iss)"

.SH "Member Data Documentation"
.PP 
.SS "template<class Index , class T > bool \fBCoDataFrame\fP< Index, T >::good = false\fC [private]\fP"

.SS "template<class Index , class T > std::vector<std::vector<T> > \fBCoDataFrame\fP< Index, T >::m_data\fC [private]\fP"

.SS "template<class Index , class T > std::string \fBCoDataFrame\fP< Index, T >::m_filename\fC [private]\fP"

.SS "template<class Index , class T > std::vector<Index> \fBCoDataFrame\fP< Index, T >::m_index\fC [private]\fP"

.SS "template<class Index , class T > \fBsize_t\fP \fBCoDataFrame\fP< Index, T >::size = 0\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
