.TH "Counters" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Counters
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Counters\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBclover_analyse\fP ()"
.br
.ti -1c
.RI "void \fBcount_event\fP (\fBEvent\fP const &event)"
.br
.ti -1c
.RI "\fBCounters\fP ()"
.br
.ti -1c
.RI "\fBCounters\fP ()"
.br
.ti -1c
.RI "void \fBcountEvent\fP (\fBEvent\fP const &event)"
.br
.ti -1c
.RI "bool \fBhasTrigged\fP ()"
.br
.ti -1c
.RI "bool \fBhasTrigged\fP ()"
.br
.ti -1c
.RI "void \fBset_hit\fP (\fBEvent\fP const &event, int const &i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::array< Bool_t, 24 > \fBBGO_Clover\fP"
.br
.ti -1c
.RI "\fBuchar\fP \fBClovers\fP =0"
.br
.ti -1c
.RI "\fBuchar\fP \fBDSSDMult\fP =0"
.br
.ti -1c
.RI "std::array< Bool_t, 24 > \fBGe_Clover\fP"
.br
.ti -1c
.RI "\fBuchar\fP \fBGeCleanClovers\fP =0"
.br
.ti -1c
.RI "\fBuchar\fP \fBGeClovers\fP =0"
.br
.ti -1c
.RI "\fBuchar\fP \fBLaBr3Mult\fP =0"
.br
.ti -1c
.RI "\fBStaticVector\fP< \fBuchar\fP, 24 > \fBlist_clovers\fP"
.br
.ti -1c
.RI "\fBStaticVector\fP< \fBuchar\fP > \fBlist_clovers\fP = \fBStaticVector\fP<\fBuchar\fP>(24)"
.br
.ti -1c
.RI "\fBuchar\fP \fBModules\fP =0"
.br
.ti -1c
.RI "\fBuchar\fP \fBmult\fP = 0"
.br
.ti -1c
.RI "\fBuchar\fP \fBParisMult\fP =0"
.br
.ti -1c
.RI "\fBuchar\fP \fBRawBGO\fP =0"
.br
.ti -1c
.RI "\fBuchar\fP \fBRawGe\fP =0"
.br
.ti -1c
.RI "bool \fBtrig\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Counters::Counters ()\fC [inline]\fP"

.SS "Counters::Counters ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Counters::clear ()"

.SS "void Counters::clear ()"

.SS "void Counters::clover_analyse ()"

.SS "void Counters::count_event (\fBEvent\fP const & event)"

.SS "void Counters::countEvent (\fBEvent\fP const & event)"

.SS "bool Counters::hasTrigged ()"

.SS "bool Counters::hasTrigged ()"

.SS "void Counters::set_hit (\fBEvent\fP const & event, int const & i)"

.SH "Member Data Documentation"
.PP 
.SS "std::array< Bool_t, 24 > Counters::BGO_Clover"

.SS "\fBuchar\fP Counters::Clovers =0"

.SS "\fBuchar\fP Counters::DSSDMult =0"

.SS "std::array< Bool_t, 24 > Counters::Ge_Clover"

.SS "\fBuchar\fP Counters::GeCleanClovers =0"

.SS "\fBuchar\fP Counters::GeClovers =0"

.SS "\fBuchar\fP Counters::LaBr3Mult =0"

.SS "\fBStaticVector\fP<\fBuchar\fP,24> Counters::list_clovers"

.SS "\fBStaticVector\fP<\fBuchar\fP> Counters::list_clovers = \fBStaticVector\fP<\fBuchar\fP>(24)"

.SS "\fBuchar\fP Counters::Modules =0"

.SS "\fBuchar\fP Counters::mult = 0"

.SS "\fBuchar\fP Counters::ParisMult =0"

.SS "\fBuchar\fP Counters::RawBGO =0"

.SS "\fBuchar\fP Counters::RawGe =0"

.SS "bool Counters::trig = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
