.TH "DataFileReader" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataFileReader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataFileReader\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcd\fP ()"
.br
.ti -1c
.RI "\fBDataFileReader\fP ()"
.br
.ti -1c
.RI "\fBDataFileReader\fP (\fBHit\fP *_hit)"
.br
.ti -1c
.RI "\fBDataFileReader\fP (\fBHit\fP *_hit, std::string _filename)"
.br
.ti -1c
.RI "\fBDataFileReader\fP (std::string _filename)"
.br
.ti -1c
.RI "\fBHit\fP * \fBgetHit\fP () const"
.br
.ti -1c
.RI "Bool_t \fBInitialize\fP ()"
.br
.ti -1c
.RI "Bool_t \fBInitialize\fP (std::string const &_filename)"
.br
.ti -1c
.RI "Bool_t const  & \fBisReady\fP () const"
.br
.ti -1c
.RI "std::string const  & \fBisRootOrFast\fP () const"
.br
.ti -1c
.RI "Bool_t const  & \fBisWritable\fP () const"
.br
.ti -1c
.RI "Bool_t \fBRead\fP ()"
.br
.ti -1c
.RI "Bool_t \fBRead\fP (\fBHit\fP *hit)"
.br
.ti -1c
.RI "Bool_t \fBReadFast\fP ()"
.br
.ti -1c
.RI "Bool_t \fBReadFastData\fP (faster_data_p const &_data)"
.br
.ti -1c
.RI "Bool_t \fBReadFastGroup\fP ()"
.br
.ti -1c
.RI "void \fBreadFastGroup\fP (faster_data_p const &_data)"
.br
.ti -1c
.RI "Bool_t \fBReadRoot\fP (Int_t const &pos)"
.br
.ti -1c
.RI "void \fBswitch_alias\fP (\fBuchar\fP const &_alias, faster_data_p const &_data, Bool_t &_write)"
.br
.ti -1c
.RI "\fB~DataFileReader\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "Bool_t \fBInitializeFasterRead\fP ()"
.br
.ti -1c
.RI "Bool_t \fBInitializeRootRead\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBuchar\fP \fBm_alias\fP = 0"
.br
.ti -1c
.RI "ULong64_t \fBm_cursor\fP = 0"
.br
.ti -1c
.RI "faster_data_p \fBm_data\fP"
.br
.ti -1c
.RI "\fBHit\fP * \fBm_empty_hit\fP = nullptr"
.br
.ti -1c
.RI "std::string \fBm_filename\fP = ''"
.br
.ti -1c
.RI "Buffer_ptr \fBm_group_buffer\fP"
.br
.ti -1c
.RI "UShort_t \fBm_group_read_cursor\fP = 0"
.br
.ti -1c
.RI "UShort_t \fBm_group_write_cursor\fP = 0"
.br
.ti -1c
.RI "\fBHit\fP * \fBm_hit\fP = nullptr"
.br
.ti -1c
.RI "Bool_t \fBm_isGroup\fP = false"
.br
.ti -1c
.RI "Bool_t \fBm_kReady\fP = true"
.br
.ti -1c
.RI "Bool_t \fBm_QDCx\fP [4] = {1,0,0,0}"
.br
.ti -1c
.RI "char \fBm_quick_rootOrFast\fP = 0"
.br
.ti -1c
.RI "faster_file_reader_p \fBm_reader\fP = NULL"
.br
.ti -1c
.RI "TTree * \fBm_ReadTree\fP = nullptr"
.br
.ti -1c
.RI "std::string \fBm_rootORfast\fP = ''"
.br
.ti -1c
.RI "std::unique_ptr< TFile > \fBm_TFile\fP"
.br
.ti -1c
.RI "bool \fBm_verbose\fP = false"
.br
.ti -1c
.RI "Bool_t \fBm_write\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataFileReader::DataFileReader ()\fC [inline]\fP"

.SS "DataFileReader::DataFileReader (\fBHit\fP * _hit)\fC [inline]\fP"

.SS "DataFileReader::DataFileReader (std::string _filename)\fC [inline]\fP"

.SS "DataFileReader::DataFileReader (\fBHit\fP * _hit, std::string _filename)\fC [inline]\fP"

.SS "DataFileReader::~DataFileReader ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void DataFileReader::cd ()"

.SS "\fBHit\fP* DataFileReader::getHit () const\fC [inline]\fP"

.SS "Bool_t DataFileReader::Initialize ()"

.SS "Bool_t DataFileReader::Initialize (std::string const & _filename)"

.SS "Bool_t DataFileReader::InitializeFasterRead ()\fC [private]\fP"

.SS "Bool_t DataFileReader::InitializeRootRead ()\fC [private]\fP"

.SS "Bool_t const& DataFileReader::isReady () const\fC [inline]\fP"

.SS "std::string const& DataFileReader::isRootOrFast () const\fC [inline]\fP"

.SS "Bool_t const& DataFileReader::isWritable () const\fC [inline]\fP"

.SS "Bool_t DataFileReader::Read ()"

.SS "Bool_t DataFileReader::Read (\fBHit\fP * hit)"

.SS "Bool_t DataFileReader::ReadFast ()"

.SS "Bool_t DataFileReader::ReadFastData (faster_data_p const & _data)"

.SS "Bool_t DataFileReader::ReadFastGroup ()"

.SS "void DataFileReader::readFastGroup (faster_data_p const & _data)"
= NULL)
.SS "Bool_t DataFileReader::ReadRoot (Int_t const & pos)"

.SS "void DataFileReader::switch_alias (\fBuchar\fP const & _alias, faster_data_p const & _data, Bool_t & _write)"
!
.PP
!
.PP
!
.PP
!
.PP
!
.PP
!
.SH "Member Data Documentation"
.PP 
.SS "\fBuchar\fP DataFileReader::m_alias = 0\fC [private]\fP"

.SS "ULong64_t DataFileReader::m_cursor = 0\fC [private]\fP"

.SS "faster_data_p DataFileReader::m_data\fC [private]\fP"

.SS "\fBHit\fP* DataFileReader::m_empty_hit = nullptr\fC [private]\fP"

.SS "std::string DataFileReader::m_filename = ''\fC [private]\fP"

.SS "Buffer_ptr DataFileReader::m_group_buffer\fC [private]\fP"

.SS "UShort_t DataFileReader::m_group_read_cursor = 0\fC [private]\fP"

.SS "UShort_t DataFileReader::m_group_write_cursor = 0\fC [private]\fP"

.SS "\fBHit\fP* DataFileReader::m_hit = nullptr\fC [private]\fP"

.SS "Bool_t DataFileReader::m_isGroup = false\fC [private]\fP"

.SS "Bool_t DataFileReader::m_kReady = true\fC [private]\fP"

.SS "Bool_t DataFileReader::m_QDCx[4] = {1,0,0,0}\fC [private]\fP"

.SS "char DataFileReader::m_quick_rootOrFast = 0\fC [private]\fP"

.SS "faster_file_reader_p DataFileReader::m_reader = NULL\fC [private]\fP"

.SS "TTree* DataFileReader::m_ReadTree = nullptr\fC [private]\fP"

.SS "std::string DataFileReader::m_rootORfast = ''\fC [private]\fP"

.SS "std::unique_ptr<TFile> DataFileReader::m_TFile\fC [private]\fP"

.SS "bool DataFileReader::m_verbose = false\fC [private]\fP"

.SS "Bool_t DataFileReader::m_write = false\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
