.TH "lib/Classes/DataFile.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/DataFile.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libCo\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataFile< Index, T >\fP"
.br
.RI "NOT FUNCTIONNAL !!! This is a homemade \&.data reader\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBDataLine\fP = std::vector< std::string >"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Index , class T > std::ostream & \fBoperator<<\fP (std::ostream &out, \fBDataFile\fP< Index, T > const &data)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBDataLine\fP =  std::vector<std::string>"

.SH "Function Documentation"
.PP 
.SS "template<class Index , class T > std::ostream& operator<< (std::ostream & out, \fBDataFile\fP< Index, T > const & data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
