.TH "deprecated" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBCoAnalyse::extractBackgroundArray\fP (std::vector< double > &source, int const &nsmooth=10)\fP" 1c
  
.IP "\fBMember \fBCoAnalyse::extractBackgroundArray\fP (TH1F *histo, int const &nsmooth=10)\fP" 1c
  
.IP "\fBMember \fBCoAnalyse::removeRandomBidim\fP (TH2 *matrix, int iterations=1, bool save_intermediate=false, ProjectionsBins projectionsY={{}}, ProjectionsBins projectionsX={{}})\fP" 1c
  
.IP "\fBMember \fBCobaltCalorimeter::launchFaster\fP (std::string const &foldername, int nb_files=-1)\fP" 1c
  
.IP "\fBMember \fBCobaltCalorimeter::work\fP (\fBHit\fP &hit, \fBAlignator\fP &reader)\fP" 1c
  
.IP "\fBMember \fBFaster2Root::Faster2Root\fP (\fBPath\fP const &inputFolder, \fBPath\fP const &outputFolder, int const &nb_files=-1, bool const &buildEvents=false)\fP" 1c
  
.IP "\fBMember \fBFasterReader::getHit\fP () const\fP" 1c
Get the current \fBHit\fP  
.IP "\fBMember \fBManip::setDataPath\fP (std::string const &datapath)\fP" 1c
Set the path of the list file containing the list of folders  
.IP "\fBMember \fBManip::setManipName\fP (std::string const &manipname)\fP" 1c
Set the name of the folder inside the datapath containing the list file containing the list of folders  
.IP "\fBClass \fBSpectraAlignator\fP \fP" 1c
  
.IP "\fBMember \fBSpectraAlignator::newAlignement\fP (TH1 *_spectra, TH1 *spectra_output)\fP" 1c
  
.IP "\fBClass \fBStaticVector< T >\fP \fP" 1c
With optimisation option, std::vector is almost as efficient as this class \&.\&.\&. 
.PP

