.TH "Detectors::Error" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Detectors::Error
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Detectors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBError\fP () noexcept"
.br
.ti -1c
.RI "\fBError\fP (std::string const &message) noexcept"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Detectors::Error::Error ()\fC [inline]\fP, \fC [noexcept]\fP"

.SS "Detectors::Error::Error (std::string const & message)\fC [inline]\fP, \fC [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
