.TH "lib/Classes/EventBuilder.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/EventBuilder.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Builder\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEventBuilder\fP"
.br
.RI "NOT UP TO DATE !! LATEST STABLE IS EventBuilder_136\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
