.TH "EventAnalyse" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventAnalyse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EventAnalyse\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventAnalyse\fP ()"
.br
.ti -1c
.RI "\fBClovers\fP & \fBgetClovers\fP ()"
.br
.ti -1c
.RI "\fBDSSD\fP & \fBgetDSSD\fP ()"
.br
.ti -1c
.RI "\fBParis\fP & \fBgetParis\fP ()"
.br
.ti -1c
.RI "void \fBSet\fP (\fBEvent\fP const &event)"
.br
.ti -1c
.RI "\fB~EventAnalyse\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBClovers\fP \fBm_Clovers\fP"
.br
.ti -1c
.RI "\fBDSSD\fP \fBm_DSSD\fP"
.br
.ti -1c
.RI "\fBParis\fP \fBm_Paris\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EventAnalyse::EventAnalyse ()"

.SS "EventAnalyse::~EventAnalyse ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBClovers\fP& EventAnalyse::getClovers ()\fC [inline]\fP"

.SS "\fBDSSD\fP& EventAnalyse::getDSSD ()\fC [inline]\fP"

.SS "\fBParis\fP& EventAnalyse::getParis ()\fC [inline]\fP"

.SS "void EventAnalyse::Set (\fBEvent\fP const & event)"

.SH "Member Data Documentation"
.PP 
.SS "\fBClovers\fP EventAnalyse::m_Clovers\fC [private]\fP"

.SS "\fBDSSD\fP EventAnalyse::m_DSSD\fC [private]\fP"

.SS "\fBParis\fP EventAnalyse::m_Paris\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
