.TH "lib/Modules/Faster2Histo.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Modules/Faster2Histo.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./MTObjects/MTObject\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Detectors\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/FilesManager\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Timer\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Calibration\&.hpp'\fP
.br
\fC#include '\&.\&./Modules/Timeshifts\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTFasterReader\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTTHist\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTList\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFaster2Histo\fP"
.br
.RI "Convert faster data to histograms\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQDC1MAX\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QDC1MAX"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
