.TH "lib/Modules/Faster2Root.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Modules/Faster2Root.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libCo\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Detectors\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/CoincBuilder\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Nuball2Tree\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Timer\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Alignator\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTFasterReader\&.hpp'\fP
.br
\fC#include 'Timeshifts\&.hpp'\fP
.br
\fC#include 'Calibration\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFaster2Root\fP"
.br
.RI "Basic class to perform faster to root tree data conversion\&. "
.ti -1c
.RI "class \fBMySimpleConvertor\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBTrigger\fP = std::function< bool(const \fBEvent\fP &)>"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBTrigger\fP =  std::function<bool(const \fBEvent\fP&)>"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
