.TH "lib/Classes/FasterReader.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/FasterReader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Hit\&.hpp'\fP
.br
\fC#include 'fasterac/adc\&.h'\fP
.br
\fC#include 'fasterac/group\&.h'\fP
.br
\fC#include 'fasterac/qdc\&.h'\fP
.br
\fC#include 'fasterac/rf\&.h'\fP
.br
\fC#include 'fasterac/utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFasterReader\fP"
.br
.RI "Class used to read \&.fast files\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
