.TH "Filename" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Filename \- EXPERIMENTAL Contains the short name and the extension of a given file, without any knowledge of its path\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <files_functions\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBc_str\fP () const"
.br
.ti -1c
.RI "std::string const  & \fBextension\fP () const"
.br
.ti -1c
.RI "\fBFilename\fP ()"
.br
.ti -1c
.RI "\fBFilename\fP (\fBFilename\fP const &_filename)"
.br
.ti -1c
.RI "\fBFilename\fP (std::string const &_filename)"
.br
.ti -1c
.RI "std::string const  & \fBfullName\fP () const"
.br
.RI "Full name stands for the file name with the path nor the extension\&. "
.ti -1c
.RI "std::string const  & \fBget\fP () const"
.br
.ti -1c
.RI "\fBoperator std::string\fP () const &"
.br
.ti -1c
.RI "\fBFilename\fP & \fBoperator=\fP (const char *_filename)"
.br
.ti -1c
.RI "\fBFilename\fP & \fBoperator=\fP (\fBFilename\fP const &_filename)"
.br
.ti -1c
.RI "\fBFilename\fP & \fBoperator=\fP (std::string const &_filename)"
.br
.ti -1c
.RI "void \fBsetExtension\fP (std::string const &new_extension)"
.br
.ti -1c
.RI "std::string const  & \fBshortName\fP () const"
.br
.RI "Short name stands for the file name withpout the path nor the extension\&. "
.ti -1c
.RI "std::string const  & \fBstring\fP () const"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBfill\fP (std::string const &filename)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_extension\fP"
.br
.ti -1c
.RI "std::string \fBm_fullName\fP"
.br
.ti -1c
.RI "std::string \fBm_shortName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
EXPERIMENTAL Contains the short name and the extension of a given file, without any knowledge of its path\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Filename::Filename ()\fC [inline]\fP"

.SS "Filename::Filename (std::string const & _filename)\fC [inline]\fP"

.SS "Filename::Filename (\fBFilename\fP const & _filename)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string Filename::c_str () const\fC [inline]\fP"

.SS "std::string const& Filename::extension () const\fC [inline]\fP"

.SS "void Filename::fill (std::string const & filename)\fC [inline]\fP, \fC [private]\fP"

.SS "std::string const& Filename::fullName () const\fC [inline]\fP"

.PP
Full name stands for the file name with the path nor the extension\&. 
.SS "std::string const& Filename::get () const\fC [inline]\fP"

.SS "Filename::operator std::string () const &\fC [inline]\fP"

.SS "\fBFilename\fP& Filename::operator= (const char * _filename)\fC [inline]\fP"

.SS "\fBFilename\fP& Filename::operator= (\fBFilename\fP const & _filename)\fC [inline]\fP"

.SS "\fBFilename\fP& Filename::operator= (std::string const & _filename)\fC [inline]\fP"

.SS "void Filename::setExtension (std::string const & new_extension)\fC [inline]\fP"

.SS "std::string const& Filename::shortName () const\fC [inline]\fP"

.PP
Short name stands for the file name withpout the path nor the extension\&. 
.SS "std::string const& Filename::string () const\fC [inline]\fP"

.SS "void Filename::update ()\fC [inline]\fP, \fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Filename::m_extension\fC [private]\fP"

.SS "std::string Filename::m_fullName\fC [private]\fP"

.SS "std::string Filename::m_shortName\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
