.TH "lib/Classes/Fit.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/Fit.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libCo\&.hpp'\fP
.br
\fC#include 'Hit\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFit\fP"
.br
.RI "Allows one to manipulate the results of peak fitting\&. "
.ti -1c
.RI "class \fBFits\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ofstream & \fBoperator<<\fP (std::ofstream &fout, \fBFit\fP const &fit)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ofstream& operator<< (std::ofstream & fout, \fBFit\fP const & fit)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
