.TH "Fits" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fits
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Fit\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBbegin\fP ()"
.br
.RI "Returns the iterator to the start of the vector\&. "
.ti -1c
.RI "auto \fBbegin\fP () const"
.br
.RI "Returns the iterator to the start of the vector\&. "
.ti -1c
.RI "auto \fBend\fP ()"
.br
.RI "Returns the iterator to the end of the vector\&. "
.ti -1c
.RI "auto \fBend\fP () const"
.br
.RI "Returns the iterator to the end of the vector\&. "
.ti -1c
.RI "\fBFits\fP ()=default"
.br
.ti -1c
.RI "\fBFits\fP (int const &_size)"
.br
.ti -1c
.RI "auto & \fBget\fP ()"
.br
.RI "Accesses the vector of fits\&. "
.ti -1c
.RI "auto const  & \fBget\fP () const"
.br
.RI "Accesses the vector of fits\&. "
.ti -1c
.RI "auto & \fBoperator[]\fP (\fBsize_t\fP const &i)"
.br
.RI "Directly access the fit : "
.ti -1c
.RI "auto const  & \fBoperator[]\fP (\fBsize_t\fP const &i) const"
.br
.RI "Directly access the fit : "
.ti -1c
.RI "void \fBreserve\fP (\fBsize_t\fP const &i=0)"
.br
.ti -1c
.RI "void \fBresize\fP (\fBsize_t\fP const &i=0)"
.br
.ti -1c
.RI "auto \fBsize\fP ()"
.br
.ti -1c
.RI "auto \fBsize\fP () const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBFit\fP > \fBm_fits\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fits::Fits ()\fC [default]\fP"

.SS "Fits::Fits (int const & _size)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "auto Fits::begin ()\fC [inline]\fP"

.PP
Returns the iterator to the start of the vector\&. 
.SS "auto Fits::begin () const\fC [inline]\fP"

.PP
Returns the iterator to the start of the vector\&. 
.SS "auto Fits::end ()\fC [inline]\fP"

.PP
Returns the iterator to the end of the vector\&. 
.SS "auto Fits::end () const\fC [inline]\fP"

.PP
Returns the iterator to the end of the vector\&. 
.SS "auto& Fits::get ()\fC [inline]\fP"

.PP
Accesses the vector of fits\&. 
.SS "auto const& Fits::get () const\fC [inline]\fP"

.PP
Accesses the vector of fits\&. 
.SS "auto& Fits::operator[] (\fBsize_t\fP const & i)\fC [inline]\fP"

.PP
Directly access the fit : 
.SS "auto const& Fits::operator[] (\fBsize_t\fP const & i) const\fC [inline]\fP"

.PP
Directly access the fit : 
.SS "void Fits::reserve (\fBsize_t\fP const & i = \fC0\fP)\fC [inline]\fP"

.SS "void Fits::resize (\fBsize_t\fP const & i = \fC0\fP)\fC [inline]\fP"

.SS "auto Fits::size ()\fC [inline]\fP"

.SS "auto Fits::size () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBFit\fP> Fits::m_fits\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
