.TH "fParameters< nb_param, T >" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fParameters< nb_param, T > \- Functions parameter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timewalk\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfParameters\fP ()"
.br
.ti -1c
.RI "T & \fBget\fP (\fBsize_t\fP const &i)"
.br
.ti -1c
.RI "\fBoperator std::vector< T >\fP ()"
.br
.ti -1c
.RI "T const  & \fBoperator[]\fP (\fBsize_t\fP const &i) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< T > \fBm_parameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uchar nb_param, typename T>
.br
class fParameters< nb_param, T >"
Functions parameter\&. 

A wrapper around a vector of parameters 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uchar nb_param, typename T > \fBfParameters\fP< nb_param, T >::\fBfParameters\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<uchar nb_param, typename T > T& \fBfParameters\fP< nb_param, T >::get (\fBsize_t\fP const & i)\fC [inline]\fP"

.SS "template<uchar nb_param, typename T > \fBfParameters\fP< nb_param, T >::operator std::vector< T > ()\fC [inline]\fP"

.SS "template<uchar nb_param, typename T > T const& \fBfParameters\fP< nb_param, T >::operator[] (\fBsize_t\fP const & i) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<uchar nb_param, typename T > std::vector<T> \fBfParameters\fP< nb_param, T >::m_parameters\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
