.TH "Gate_t< T >" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gate_t< T > \- Convenient gate class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Gate\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGate_t\fP ()"
.br
.ti -1c
.RI "\fBGate_t\fP (std::Initialiser_list< T > inputs)"
.br
.ti -1c
.RI "bool \fBisIn\fP (T const &e)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (T const &e)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBGate_t\fP const &timegate)"
.br
.ti -1c
.RI "void \fBoperator=\fP (std::pair< T, T > const &gate)"
.br
.ti -1c
.RI "void \fBuse\fP (bool const &_use=true)"
.br
.ti -1c
.RI "bool const  & \fBused\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBstart\fP = 0\&."
.br
.ti -1c
.RI "T \fBstop\fP = 0\&."
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_use\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Gate_t< T >"
Convenient gate class\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type of the data 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBGate_t\fP< T >::\fBGate_t\fP ()\fC [inline]\fP"

.SS "template<typename T > \fBGate_t\fP< T >::\fBGate_t\fP (std::Initialiser_list< T > inputs)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > bool \fBGate_t\fP< T >::isIn (T const & e)\fC [inline]\fP"

.SS "template<typename T > bool \fBGate_t\fP< T >::operator() (T const & e)\fC [inline]\fP"

.SS "template<typename T > void \fBGate_t\fP< T >::operator= (\fBGate_t\fP< T > const & timegate)\fC [inline]\fP"

.SS "template<typename T > void \fBGate_t\fP< T >::operator= (std::pair< T, T > const & gate)\fC [inline]\fP"

.SS "template<typename T > void \fBGate_t\fP< T >::use (bool const & _use = \fCtrue\fP)\fC [inline]\fP"

.SS "template<typename T > bool const& \fBGate_t\fP< T >::used () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > bool \fBGate_t\fP< T >::m_use = false\fC [private]\fP"

.SS "template<typename T > T \fBGate_t\fP< T >::start = 0\&."

.SS "template<typename T > T \fBGate_t\fP< T >::stop = 0\&."


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
