.TH "lib/Classes/Gate.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/Gate.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libCo\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGate_t< T >\fP"
.br
.ti -1c
.RI "class \fBGates_t< T >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBGate\fP = \fBGate_t\fP< float >"
.br
.ti -1c
.RI "using \fBGates\fP = \fBGates_t\fP< float >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBGate\fP =  \fBGate_t\fP<float>"

.SS "using \fBGates\fP =  \fBGates_t\fP<float>"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
