.TH "lib/Modules/Histogramor.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Modules/Histogramor.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libRoot\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTFasterReader\&.hpp'\fP
.br
\fC#include '\&.\&./MTObjects/MTTHist\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHistogramor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHistogramor\fP (int argc, char **argv)"
.br
.ti -1c
.RI "bool \fBload_binning\fP (std::string const &filename)"
.br
.ti -1c
.RI "\fBprint\fP ('')"
.br
.ti -1c
.RI "\fBprint\fP ('\-b [binning_file] : Load \&.binning file')"
.br
.ti -1c
.RI "\fBprint\fP ('\-i [ID_file]      : Load ID file')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBHistogramor\fP (int argc, char ** argv)"

.SS "bool load_binning (std::string const & filename)"

.SS "print ('')"

.SS "print ('\-b  : Load \&.binning file'[binning_file])"

.SS "print ('\-i  : Load ID file'[ID_file])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
