.TH "lib/Analyse/HistoAnalyse.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Analyse/HistoAnalyse.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <Gate\&.hpp>\fP
.br
\fC#include <MTTHist\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHistoAnalyse< THist >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class THist > void \fBNormalizeX\fP (\fBMTTHist\fP< THist > &histo, Float_t const &factor=1)"
.br
.ti -1c
.RI "template<class THist > void \fBNormalizeY\fP (\fBMTTHist\fP< THist > &histo, Float_t const &factor=1)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class THist > void NormalizeX (\fBMTTHist\fP< THist > & histo, Float_t const & factor = \fC1\fP)"

.SS "template<class THist > void NormalizeY (\fBMTTHist\fP< THist > & histo, Float_t const & factor = \fC1\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
