.TH "HistoAnalyse< THist >" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HistoAnalyse< THist >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HistoAnalyse\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoAnalyse\fP (\fBMTTHist\fP< THist > &histo)"
.br
.ti -1c
.RI "\fBHistoAnalyse\fP (THist *histo)"
.br
.ti -1c
.RI "void \fBnormalizeX\fP (Float_t const &factor=1)"
.br
.ti -1c
.RI "void \fBnormalizeXY\fP (Float_t const &factor=1, int const &min_x=0, int const &min_y=0)"
.br
.ti -1c
.RI "void \fBnormalizeY\fP (Float_t const &factor=1)"
.br
.ti -1c
.RI "THist * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "Float_t \fBpeaksOverBackground\fP (std::vector< \fBGate\fP > gates)"
.br
.ti -1c
.RI "void \fBremoveBackground\fP (int const &nsmooth=10)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP (\fBMTTHist\fP< THist > &histo)"
.br
.ti -1c
.RI "void \fBreset\fP (THist *histo)"
.br
.ti -1c
.RI "\fB~HistoAnalyse\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_exists\fP = false"
.br
.ti -1c
.RI "THist * \fBm_histo\fP = nullptr"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class THist > \fBHistoAnalyse\fP< THist >::\fBHistoAnalyse\fP (THist * histo)\fC [inline]\fP"

.SS "template<class THist > \fBHistoAnalyse\fP< THist >::\fBHistoAnalyse\fP (\fBMTTHist\fP< THist > & histo)\fC [inline]\fP"

.SS "template<class THist > \fBHistoAnalyse\fP< THist >::~\fBHistoAnalyse\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class THist > void \fBHistoAnalyse\fP< THist >::normalizeX (Float_t const & factor = \fC1\fP)"

.SS "template<class THist > void \fBHistoAnalyse\fP< THist >::normalizeXY (Float_t const & factor = \fC1\fP, int const & min_x = \fC0\fP, int const & min_y = \fC0\fP)"

.SS "template<class THist > void \fBHistoAnalyse\fP< THist >::normalizeY (Float_t const & factor = \fC1\fP)"

.SS "template<class THist > THist* \fBHistoAnalyse\fP< THist >::operator\-> ()\fC [inline]\fP"

.SS "template<class THist > Float_t \fBHistoAnalyse\fP< THist >::peaksOverBackground (std::vector< \fBGate\fP > gates)"

.SS "template<class THist > void \fBHistoAnalyse\fP< THist >::removeBackground (int const & nsmooth = \fC10\fP)"

.SS "template<class THist > void \fBHistoAnalyse\fP< THist >::reset ()\fC [inline]\fP"

.SS "template<class THist > void \fBHistoAnalyse\fP< THist >::reset (\fBMTTHist\fP< THist > & histo)\fC [inline]\fP"

.SS "template<class THist > void \fBHistoAnalyse\fP< THist >::reset (THist * histo)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<class THist > bool \fBHistoAnalyse\fP< THist >::m_exists = false\fC [private]\fP"

.SS "template<class THist > THist* \fBHistoAnalyse\fP< THist >::m_histo = nullptr\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
