.TH "lib/Classes/Manip.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/Manip.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./MTObjects/MTList\&.hpp'\fP
.br
\fC#include '\&.\&./libCo\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBManip\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &cout, \fBManip\fP const &manip)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & cout, \fBManip\fP const & manip)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
