.TH "Manip" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Manip \- Loads the list file containing the list of the names of the folder containing the faster files to convert\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Manip\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddFolder\fP (std::string const &folder)"
.br
.RI "Clears the previously set list of folders and replace it with folder\&. "
.ti -1c
.RI "auto const  & \fBget\fP () const"
.br
.ti -1c
.RI "bool \fBgetNext\fP (std::string &run)"
.br
.ti -1c
.RI "\fBManip\fP ()"
.br
.ti -1c
.RI "\fBManip\fP (std::string const &runs_file)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const &"
.br
.ti -1c
.RI "bool \fBoperator>>\fP (std::string &string)"
.br
.ti -1c
.RI "void \fBreadFile\fP ()"
.br
.RI "Reads the list file containing the list of folders\&. "
.ti -1c
.RI "void \fBreadFile\fP (std::string const &runs_file)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBsetDataPath\fP (std::string const &datapath)"
.br
.ti -1c
.RI "void \fBsetFileName\fP (std::string const &filename)"
.br
.ti -1c
.RI "void \fBsetFolder\fP (std::string const &folder)"
.br
.RI "Clears the previously set list of folders and replace it with folder\&. "
.ti -1c
.RI "void \fBsetManipName\fP (std::string const &manipname)"
.br
.ti -1c
.RI "bool \fBsetMT\fP (bool const &MTOn=true)"
.br
.RI "To allow several threads to work on different runs on parallel\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBuint\fP \fBi\fP = 0"
.br
.ti -1c
.RI "std::vector< std::string > \fBlist_runs\fP"
.br
.ti -1c
.RI "\fBMTList\fP \fBlist_runs_MT\fP"
.br
.ti -1c
.RI "\fBPath\fP \fBm_datapath\fP"
.br
.ti -1c
.RI "std::string \fBm_file\fP"
.br
.ti -1c
.RI "\fBFolder\fP \fBm_manip\fP"
.br
.ti -1c
.RI "bool \fBm_MTOn\fP = false"
.br
.ti -1c
.RI "bool \fBm_ok\fP"
.br
.ti -1c
.RI "std::string \fBm_runs_files\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Loads the list file containing the list of the names of the folder containing the faster files to convert\&. 


.PP
\fBTodo\fP
.RS 4
make it better !! 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Manip::Manip ()\fC [inline]\fP"

.SS "Manip::Manip (std::string const & runs_file)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Manip::addFolder (std::string const & folder)\fC [inline]\fP"

.PP
Clears the previously set list of folders and replace it with folder\&. 
.SS "auto const& Manip::get () const\fC [inline]\fP"

.SS "bool Manip::getNext (std::string & run)\fC [inline]\fP"

.SS "Manip::operator bool () const &\fC [inline]\fP"

.SS "bool Manip::operator>> (std::string & string)\fC [inline]\fP"

.SS "void Manip::readFile ()\fC [inline]\fP"

.PP
Reads the list file containing the list of folders\&. 
.SS "void Manip::readFile (std::string const & runs_file)\fC [inline]\fP"

.SS "void Manip::reset ()\fC [inline]\fP"

.SS "void Manip::setDataPath (std::string const & datapath)\fC [inline]\fP"

.PP
\fBDeprecated\fP
.RS 4
Set the path of the list file containing the list of folders 
.RE
.PP

.SS "void Manip::setFileName (std::string const & filename)\fC [inline]\fP"

.SS "void Manip::setFolder (std::string const & folder)\fC [inline]\fP"

.PP
Clears the previously set list of folders and replace it with folder\&. 
.SS "void Manip::setManipName (std::string const & manipname)\fC [inline]\fP"

.PP
\fBDeprecated\fP
.RS 4
Set the name of the folder inside the datapath containing the list file containing the list of folders 
.RE
.PP

.SS "bool Manip::setMT (bool const & MTOn = \fCtrue\fP)\fC [inline]\fP"

.PP
To allow several threads to work on different runs on parallel\&. \fBMTObject\fP needs to have been Initialised before creating the 
.br
 
.SH "Member Data Documentation"
.PP 
.SS "\fBuint\fP Manip::i = 0\fC [private]\fP"

.SS "std::vector<std::string> Manip::list_runs\fC [private]\fP"

.SS "\fBMTList\fP Manip::list_runs_MT\fC [private]\fP"

.SS "\fBPath\fP Manip::m_datapath\fC [private]\fP"

.SS "std::string Manip::m_file\fC [private]\fP"

.SS "\fBFolder\fP Manip::m_manip\fC [private]\fP"

.SS "bool Manip::m_MTOn = false\fC [private]\fP"

.SS "bool Manip::m_ok\fC [private]\fP"

.SS "std::string Manip::m_runs_files\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
