.TH "Minimisator::NelderMeadParameters" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minimisator::NelderMeadParameters
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SpectraAlignator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadjustToDimension\fP (double const &n)"
.br
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBa_contract\fP = 0\&.5"
.br
.ti -1c
.RI "double \fBa_expand\fP = 1\&.3"
.br
.ti -1c
.RI "double \fBa_extend\fP = 2"
.br
.ti -1c
.RI "double \fBa_reflect\fP = 1"
.br
.ti -1c
.RI "double \fBa_shrink\fP = 0\&.5"
.br
.ti -1c
.RI "bool \fBadjusted\fP = false"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Minimisator::NelderMeadParameters::adjustToDimension (double const & n)\fC [inline]\fP"

.SS "void Minimisator::NelderMeadParameters::Print ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double Minimisator::NelderMeadParameters::a_contract = 0\&.5"

.SS "double Minimisator::NelderMeadParameters::a_expand = 1\&.3"

.SS "double Minimisator::NelderMeadParameters::a_extend = 2"

.SS "double Minimisator::NelderMeadParameters::a_reflect = 1"

.SS "double Minimisator::NelderMeadParameters::a_shrink = 0\&.5"

.SS "bool Minimisator::NelderMeadParameters::adjusted = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
