.TH "Minimisator" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minimisator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SpectraAlignator\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNelderMeadParameters\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto const  & \fBgetMinimum\fP () const"
.br
.ti -1c
.RI "\fBMinimisator\fP ()=default"
.br
.ti -1c
.RI "void \fBnelderMead\fP (\fBObjectiveFunction\fP const &function)"
.br
.ti -1c
.RI "void \fBsetInitialGuess\fP (\fBVertice\fP const &init_vertice)"
.br
.ti -1c
.RI "void \fBsetInitialSteps\fP (\fBVertice\fP const &steps)"
.br
.ti -1c
.RI "void \fBsimpleGrad\fP (\fBObjectiveFunction\fP &func)"
.br
.RI "C'est peut-être une fausse piste \&.\&.\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVertices\fP \fBg_minima_history\fP"
.br
.ti -1c
.RI "std::vector< double > \fBg_minimums\fP"
.br
.ti -1c
.RI "std::vector< \fBSimplex\fP > \fBg_simplex_history\fP"
.br
.ti -1c
.RI "struct \fBMinimisator::NelderMeadParameters\fP \fBnmParam\fP"
.br
.ti -1c
.RI "double \fBtolerance\fP = 1\&.e\-3"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBg_nb_rounds\fP = 5"
.br
.ti -1c
.RI "static int \fBg_order\fP = 3"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBVertices\fP \fBm_grad_vertices\fP"
.br
.ti -1c
.RI "\fBVertice\fP \fBm_initial_vertice\fP"
.br
.ti -1c
.RI "\fBVertice\fP \fBm_minimum\fP = 0\&.0"
.br
.ti -1c
.RI "int \fBm_nb_steps_grad\fP = 10"
.br
.ti -1c
.RI "\fBVertice\fP \fBm_steps\fP"
.br
.ti -1c
.RI "\fBVertice\fP \fBm_weights\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Minimisator::Minimisator ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "auto const& Minimisator::getMinimum () const\fC [inline]\fP"

.SS "void Minimisator::nelderMead (\fBObjectiveFunction\fP const & function)\fC [inline]\fP"

.SS "void Minimisator::setInitialGuess (\fBVertice\fP const & init_vertice)\fC [inline]\fP"

.SS "void Minimisator::setInitialSteps (\fBVertice\fP const & steps)\fC [inline]\fP"

.SS "void Minimisator::simpleGrad (\fBObjectiveFunction\fP & func)\fC [inline]\fP"

.PP
C'est peut-être une fausse piste \&.\&.\&. 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP 
.br
 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBVertices\fP Minimisator::g_minima_history"

.SS "std::vector<double> Minimisator::g_minimums"

.SS "int Minimisator::g_nb_rounds = 5\fC [static]\fP"

.SS "int Minimisator::g_order = 3\fC [static]\fP"

.SS "std::vector<\fBSimplex\fP> Minimisator::g_simplex_history"

.SS "\fBVertices\fP Minimisator::m_grad_vertices\fC [private]\fP"

.SS "\fBVertice\fP Minimisator::m_initial_vertice\fC [private]\fP"

.SS "\fBVertice\fP Minimisator::m_minimum = 0\&.0\fC [private]\fP"

.SS "int Minimisator::m_nb_steps_grad = 10\fC [private]\fP"

.SS "\fBVertice\fP Minimisator::m_steps\fC [private]\fP"

.SS "\fBVertice\fP Minimisator::m_weights\fC [private]\fP"

.SS "struct \fBMinimisator::NelderMeadParameters\fP Minimisator::nmParam"

.SS "double Minimisator::tolerance = 1\&.e\-3"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
