.TH "lib/MTObjects/MTFasterReader.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/MTObjects/MTFasterReader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Classes/FasterReader\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Alignator\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/FilesManager\&.hpp'\fP
.br
\fC#include 'MTObject\&.hpp'\fP
.br
\fC#include 'MTList\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMTFasterReader\fP"
.br
.RI "Class used to read in parallel \&.fast files of the same run\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
