.TH "lib/MTObjects/MTList.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/MTObjects/MTList.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MTObject\&.hpp'\fP
.br
\fC#include '\&.\&./libCo\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMTVector< T >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBMTList\fP = \fBMTVector\fP< std::string >"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > std::ostream & \fBoperator<<\fP (std::ostream &cout, \fBMTVector\fP< T > const &list)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBMTList\fP =  \fBMTVector\fP<std::string>"

.SH "Function Documentation"
.PP 
.SS "template<class T > std::ostream& operator<< (std::ostream & cout, \fBMTVector\fP< T > const & list)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
