.TH "lib/MTObjects/MTObject.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/MTObjects/MTObject.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <csignal>\fP
.br
\fC#include <future>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'TROOT\&.h'\fP
.br
\fC#include 'TThread\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMTObject\fP"
.br
.RI "Class handeling an easy multi threading\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMULTITHREADING\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBlock_mutex\fP = const std::lock_guard< std::mutex >"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::mutex \fBMTmutex\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MULTITHREADING"

.SH "Typedef Documentation"
.PP 
.SS "using \fBlock_mutex\fP =  const std::lock_guard<std::mutex>"

.SH "Variable Documentation"
.PP 
.SS "std::mutex MTmutex"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
