.TH "lib/MTObjects/MTTHist.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/MTObjects/MTTHist.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MTObject\&.hpp'\fP
.br
\fC#include 'MTCounter\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMTTHist< THist >\fP"
.br
.RI "Multithreading wrapper for all THist spectra of root library\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<class THist > using \fBVector_MTTHist\fP = std::vector< \fBMTTHist\fP< THist > >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "template<class THist > using \fBVector_MTTHist\fP =  std::vector<\fBMTTHist\fP<THist> >"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
