.TH "MTTHist< THist >::CopyError" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MTTHist< THist >::CopyError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MTTHist\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyError\fP (\fBMTTHist\fP< THist > const &histo)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class THist > \fBMTTHist\fP< THist >::CopyError::CopyError (\fBMTTHist\fP< THist > const & histo)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
