.TH "lib/MTObjects/MTVariable.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/MTObjects/MTVariable.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MTObject\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMTVariable< T >\fP"
.br
.RI "UNUSED\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
