.TH "NearLine" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NearLine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NearLine\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNearLine\fP (int argc, char **argv)"
.br
.ti -1c
.RI "bool \fBreadParam\fP (int argc, char **argv)"
.br
.ti -1c
.RI "\fB~NearLine\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_hr\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NearLine::NearLine (int argc, char ** argv)"

.SS "NearLine::~NearLine ()"

.SH "Member Function Documentation"
.PP 
.SS "bool NearLine::readParam (int argc, char ** argv)"

.SH "Member Data Documentation"
.PP 
.SS "bool NearLine::m_hr = false\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
