.TH "lib/Modules/NearLine.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Modules/NearLine.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libRoot\&.hpp'\fP
.br
\fC#include 'Histogramor\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Detectors\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNearLine\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
