.TH "lib/Classes/Nuball2Tree.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/Nuball2Tree.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libCo\&.hpp'\fP
.br
\fC#include 'Event\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNuball2Tree\fP"
.br
.RI "test _ not finished "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
