.TH "lib/Classes/Nuball2Tree.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/Nuball2Tree.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libRoot\&.hpp'\fP
.br
\fC#include 'Event\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNuball2Tree\fP"
.br
.RI "Access to the underlying TTree using -> operator (e\&.g\&. nuball2tree->GetEntry(n);) "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, \fBNuball2Tree\fP const &tree)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & out, \fBNuball2Tree\fP const & tree)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
