.TH "OutputTFile" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutputTFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OutputTFile\&.hpp>\fP
.PP
Inherits TFile\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutputTFile\fP (std::string filename, std::string option='', std::string title='', Int_t compress=1)"
.br
.ti -1c
.RI "template<class\&.\&.\&. ARGS> \fBWrite\fP (ARGS\&.\&.\&. args) override"
.br
.ti -1c
.RI "virtual \fB~OutputTFile\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OutputTFile::OutputTFile (std::string filename, std::string option = \fC''\fP, std::string title = \fC''\fP, Int_t compress = \fC1\fP)\fC [inline]\fP"

.SS "virtual OutputTFile::~OutputTFile ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class\&.\&.\&. ARGS> OutputTFile::Write (ARGS\&.\&.\&. args)\fC [inline]\fP, \fC [override]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
