.TH "OverwriteError" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OverwriteError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <errors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOverwriteError\fP (std::string const &message) noexcept"
.br
.ti -1c
.RI "auto \fBwhat\fP ()"
.br
.ti -1c
.RI "auto const  & \fBwhat\fP () const noexcept"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_message\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OverwriteError::OverwriteError (std::string const & message)\fC [inline]\fP, \fC [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "auto OverwriteError::what ()\fC [inline]\fP"

.SS "auto const& OverwriteError::what () const\fC [inline]\fP, \fC [noexcept]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string OverwriteError::m_message\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
