.TH "lib/Analyse/ParisXY.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Analyse/ParisXY.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ParisLabel\&.hpp'\fP
.br
\fC#include 'Arrays/Paris\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParisXY\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
