.TH "ParisPhoswitch" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParisPhoswitch
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParisPhoswitch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFill\fP (\fBEvent\fP const &event, int const &i)"
.br
.ti -1c
.RI "auto const  & \fBlabel\fP () const"
.br
.ti -1c
.RI "\fBoperator bool\fP ()"
.br
.ti -1c
.RI "\fBParisPhoswitch\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "auto \fBsetLabel\fP (\fBuchar\fP const &\fBlabel\fP)"
.br
.ti -1c
.RI "char \fBtest_gate_classic\fP ()"
.br
.ti -1c
.RI "char \fBtest_gate_tan\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNRJ\fP \fBnrj\fP = 0\&."
.br
.ti -1c
.RI "\fBNRJ\fP \fBnrj2\fP = 0\&."
.br
.ti -1c
.RI "\fBNRJ\fP \fBratio\fP = 0\&."
.br
.ti -1c
.RI "\fBTime_ns\fP \fBtime\fP = 0\&."
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBuchar\fP \fBm_label\fP = \-1"
.br
.ti -1c
.RI "char \fBm_state\fP = \-1"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParisPhoswitch::ParisPhoswitch ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ParisPhoswitch::Fill (\fBEvent\fP const & event, int const & i)"

.SS "auto const& ParisPhoswitch::label () const\fC [inline]\fP"

.SS "ParisPhoswitch::operator bool ()\fC [inline]\fP"

.SS "void ParisPhoswitch::Reset ()\fC [inline]\fP"

.SS "auto ParisPhoswitch::setLabel (\fBuchar\fP const & label)\fC [inline]\fP"

.SS "char ParisPhoswitch::test_gate_classic ()\fC [inline]\fP"

.SS "char ParisPhoswitch::test_gate_tan ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBuchar\fP ParisPhoswitch::m_label = \-1\fC [private]\fP"

.SS "char ParisPhoswitch::m_state = \-1\fC [private]\fP"

.SS "\fBNRJ\fP ParisPhoswitch::nrj = 0\&."

.SS "\fBNRJ\fP ParisPhoswitch::nrj2 = 0\&."

.SS "\fBNRJ\fP ParisPhoswitch::ratio = 0\&."

.SS "\fBTime_ns\fP ParisPhoswitch::time = 0\&."


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
