.TH "ParisBidimAngles" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParisBidimAngles
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParisBidimAngles\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileError\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBangleLaBr\fP (std::string name)"
.br
.ti -1c
.RI "double const  & \fBangleLaBr\fP (std::string name) const"
.br
.ti -1c
.RI "double \fBangleNaI\fP (std::string name)"
.br
.ti -1c
.RI "double const  & \fBangleNaI\fP (std::string name) const"
.br
.ti -1c
.RI "std::unordered_map< std::string, double > const  & \fBLaBr_angles\fP ()"
.br
.ti -1c
.RI "void \fBload\fP (std::string const &filename)"
.br
.ti -1c
.RI "std::unordered_map< std::string, double > const  & \fBNaI_angles\fP ()"
.br
.ti -1c
.RI "auto \fBnames\fP ()"
.br
.ti -1c
.RI "auto const  & \fBnames\fP () const"
.br
.ti -1c
.RI "std::pair< double, double > const  & \fBoperator[]\fP (std::string name)"
.br
.ti -1c
.RI "\fBParisBidimAngles\fP () noexcept=default"
.br
.ti -1c
.RI "\fBParisBidimAngles\fP (std::string const &filename)"
.br
.ti -1c
.RI "void \fBprintDeg\fP ()"
.br
.ti -1c
.RI "void \fBset\fP (std::string const &name, double const &\fBangleLaBr\fP, double const &\fBangleNaI\fP)"
.br
.ti -1c
.RI "void \fBsortNames\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (std::string const &filename)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::unordered_map< std::string, double > \fBm_angleLaBr\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, double > \fBm_angleNaI\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::pair< double, double > > \fBm_angles\fP"
.br
.ti -1c
.RI "std::string \fBm_filename\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBm_names\fP"
.br
.ti -1c
.RI "bool \fBm_ok\fP = false"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static std::string \fBm_extension\fP = 'angles'"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParisBidimAngles::ParisBidimAngles ()\fC [default]\fP, \fC [noexcept]\fP"

.SS "ParisBidimAngles::ParisBidimAngles (std::string const & filename)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "double ParisBidimAngles::angleLaBr (std::string name)\fC [inline]\fP"

.SS "double const& ParisBidimAngles::angleLaBr (std::string name) const\fC [inline]\fP"

.SS "double ParisBidimAngles::angleNaI (std::string name)\fC [inline]\fP"

.SS "double const& ParisBidimAngles::angleNaI (std::string name) const\fC [inline]\fP"

.SS "std::unordered_map<std::string, double> const& ParisBidimAngles::LaBr_angles ()\fC [inline]\fP"

.SS "void ParisBidimAngles::load (std::string const & filename)"

.SS "std::unordered_map<std::string, double> const& ParisBidimAngles::NaI_angles ()\fC [inline]\fP"

.SS "auto ParisBidimAngles::names ()\fC [inline]\fP"

.SS "auto const& ParisBidimAngles::names () const\fC [inline]\fP"

.SS "std::pair<double, double> const& ParisBidimAngles::operator[] (std::string name)\fC [inline]\fP"

.SS "void ParisBidimAngles::printDeg ()\fC [inline]\fP"

.SS "void ParisBidimAngles::set (std::string const & name, double const & angleLaBr, double const & angleNaI)"

.SS "void ParisBidimAngles::sortNames ()\fC [inline]\fP"

.SS "void ParisBidimAngles::write (std::string const & filename)"

.SH "Member Data Documentation"
.PP 
.SS "std::unordered_map<std::string, double> ParisBidimAngles::m_angleLaBr\fC [private]\fP"

.SS "std::unordered_map<std::string, double> ParisBidimAngles::m_angleNaI\fC [private]\fP"

.SS "std::unordered_map<std::string, std::pair<double, double> > ParisBidimAngles::m_angles\fC [private]\fP"

.SS "std::string ParisBidimAngles::m_extension = 'angles'\fC [static]\fP, \fC [private]\fP"

.SS "std::string ParisBidimAngles::m_filename\fC [private]\fP"

.SS "std::vector<std::string> ParisBidimAngles::m_names\fC [private]\fP"

.SS "bool ParisBidimAngles::m_ok = false\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
