.TH "ParisXY" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParisXY
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParisXY\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParisXY\fP (Paris_Label const &l)"
.br
.ti -1c
.RI "int const  & \fBx\fP () const"
.br
.ti -1c
.RI "int const  & \fBy\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Float_t \fBdistance\fP (\fBParisXY\fP const &coord_1, \fBParisXY\fP const &coord_2)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_x\fP = 0"
.br
.ti -1c
.RI "int \fBm_y\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParisXY::ParisXY (Paris_Label const & l)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static Float_t ParisXY::distance (\fBParisXY\fP const & coord_1, \fBParisXY\fP const & coord_2)\fC [inline]\fP, \fC [static]\fP"

.SS "int const& ParisXY::x () const\fC [inline]\fP"

.SS "int const& ParisXY::y () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ParisXY::m_x = 0\fC [private]\fP"

.SS "int ParisXY::m_y = 0\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
