.TH "ParisCluster< nb_phoswitch >" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParisCluster< nb_phoswitch >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParisCluster\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAnalyse\fP ()"
.br
.ti -1c
.RI "void \fBFill\fP (\fBEvent\fP const &event, int const &i, \fBuchar\fP const &\fBlabel\fP)"
.br
.ti -1c
.RI "void \fBInitialise\fP ()"
.br
.ti -1c
.RI "void \fBInitialiseBidims\fP ()"
.br
.ti -1c
.RI "auto const  & \fBlabel\fP () const"
.br
.ti -1c
.RI "\fBParisPhoswitch\fP & \fBoperator[]\fP (int const &i)"
.br
.ti -1c
.RI "\fBParisCluster\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "auto const  & \fBsize\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static auto const  & \fBnb_clusters\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStaticVector\fP< \fBuchar\fP > \fBHits\fP = \fBStaticVector\fP<\fBuchar\fP>(nb_phoswitch)"
.br
.ti -1c
.RI "\fBStaticVector\fP< \fBuchar\fP > \fBhits_LaBr3\fP = \fBStaticVector\fP<\fBuchar\fP>(nb_phoswitch)"
.br
.ti -1c
.RI "\fBStaticVector\fP< \fBuchar\fP > \fBhits_NaI\fP = \fBStaticVector\fP<\fBuchar\fP>(nb_phoswitch)"
.br
.ti -1c
.RI "std::vector< \fBParisPhoswitch\fP > \fBphoswitches\fP = std::vector<\fBParisPhoswitch\fP>(nb_phoswitch)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBuchar\fP const \fBm_label\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static thread_local \fBuchar\fP \fBglabel\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<std::size_t nb_phoswitch> \fBParisCluster\fP< nb_phoswitch >::\fBParisCluster\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<std::size_t nb_phoswitch> void \fBParisCluster\fP< nb_phoswitch >::Analyse"

.SS "template<std::size_t nb_phoswitch> void \fBParisCluster\fP< nb_phoswitch >::Fill (\fBEvent\fP const & event, int const & i, \fBuchar\fP const & label)\fC [inline]\fP"

.SS "template<std::size_t nb_phoswitch> void \fBParisCluster\fP< nb_phoswitch >::Initialise"

.SS "template<std::size_t nb_phoswitch> void \fBParisCluster\fP< nb_phoswitch >::InitialiseBidims"

.SS "template<std::size_t nb_phoswitch> auto const& \fBParisCluster\fP< nb_phoswitch >::label () const\fC [inline]\fP"

.SS "template<std::size_t nb_phoswitch> static auto const& \fBParisCluster\fP< nb_phoswitch >::nb_clusters ()\fC [inline]\fP, \fC [static]\fP"

.SS "template<std::size_t nb_phoswitch> \fBParisPhoswitch\fP& \fBParisCluster\fP< nb_phoswitch >::operator[] (int const & i)\fC [inline]\fP"

.SS "template<std::size_t nb_phoswitch> void \fBParisCluster\fP< nb_phoswitch >::Reset"

.SS "template<std::size_t nb_phoswitch> auto const& \fBParisCluster\fP< nb_phoswitch >::size () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<std::size_t nb_phoswitch> thread_local \fBuchar\fP \fBParisCluster\fP< nb_phoswitch >::glabel = 0\fC [static]\fP, \fC [private]\fP"

.SS "template<std::size_t nb_phoswitch> \fBStaticVector\fP<\fBuchar\fP> \fBParisCluster\fP< nb_phoswitch >::Hits = \fBStaticVector\fP<\fBuchar\fP>(nb_phoswitch)"

.SS "template<std::size_t nb_phoswitch> \fBStaticVector\fP<\fBuchar\fP> \fBParisCluster\fP< nb_phoswitch >::hits_LaBr3 = \fBStaticVector\fP<\fBuchar\fP>(nb_phoswitch)"

.SS "template<std::size_t nb_phoswitch> \fBStaticVector\fP<\fBuchar\fP> \fBParisCluster\fP< nb_phoswitch >::hits_NaI = \fBStaticVector\fP<\fBuchar\fP>(nb_phoswitch)"

.SS "template<std::size_t nb_phoswitch> \fBuchar\fP const \fBParisCluster\fP< nb_phoswitch >::m_label\fC [private]\fP"

.SS "template<std::size_t nb_phoswitch> std::vector<\fBParisPhoswitch\fP> \fBParisCluster\fP< nb_phoswitch >::phoswitches = std::vector<\fBParisPhoswitch\fP>(nb_phoswitch)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
