.TH "lib/Analyse/ParisCluster.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Analyse/ParisCluster.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libRoot\&.hpp'\fP
.br
\fC#include 'ParisPhoswitch\&.hpp'\fP
.br
\fC#include 'PositionXY\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParisCluster< nb_phoswitch >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
