.TH "lib/Analyse/Paris.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Analyse/Paris.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Classes/Event\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Detectors\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/CoProgressBar\&.hpp'\fP
.br
\fC#include 'Arrays/Paris\&.h'\fP
.br
\fC#include 'ParisCluster\&.hpp'\fP
.br
\fC#include 'ParisBidimAngles\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParis\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPositionXY\fP \fBparis_getPositionModule\fP (\fBstd::size_t\fP const &module_label)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPositionXY\fP paris_getPositionModule (\fBstd::size_t\fP const & module_label)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
