.TH "PeakFitter" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeakFitter \- Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libRoot\&.hpp>\fP
.PP
Inherited by \fBBiggestPeakFitter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBfit\fP ()"
.br
.RI "Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&. "
.ti -1c
.RI "void \fBfit\fP (TH1 *histo, double low_edge, double high_edge, double mean=\-1, double sigma=\-1, double constante=\-1)"
.br
.RI "Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&. "
.ti -1c
.RI "auto \fBgetBackground\fP () const"
.br
.ti -1c
.RI "auto \fBgetConstante\fP () const"
.br
.ti -1c
.RI "auto const  & \fBgetFit\fP () const"
.br
.ti -1c
.RI "auto \fBgetMean\fP () const"
.br
.ti -1c
.RI "auto \fBgetSigma\fP () const"
.br
.ti -1c
.RI "auto \fBoperator\->\fP ()"
.br
.ti -1c
.RI "\fBPeakFitter\fP ()=default"
.br
.ti -1c
.RI "\fBPeakFitter\fP (TH1 *histo, double low_edge, double high_edge)"
.br
.ti -1c
.RI "auto \fBsetBackgroundOrder\fP (int const &order_background)"
.br
.ti -1c
.RI "\fB~PeakFitter\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "TF1 * \fBfinal_fit\fP = nullptr"
.br
.ti -1c
.RI "double \fBm_high_edge\fP = 0\&.0"
.br
.ti -1c
.RI "TH1 * \fBm_histo\fP"
.br
.ti -1c
.RI "bool \fBm_low_binning\fP = true"
.br
.ti -1c
.RI "double \fBm_low_edge\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBm_order_background\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&. 


.PP
\fBAttention\fP
.RS 4
The edges must be well centered, this is not a peak finder\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "PeakFitter::PeakFitter ()\fC [default]\fP"

.SS "PeakFitter::~PeakFitter ()\fC [inline]\fP"

.SS "PeakFitter::PeakFitter (TH1 * histo, double low_edge, double high_edge)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void PeakFitter::fit ()\fC [inline]\fP"

.PP
Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&. 
.SS "void PeakFitter::fit (TH1 * histo, double low_edge, double high_edge, double mean = \fC\-1\fP, double sigma = \fC\-1\fP, double constante = \fC\-1\fP)\fC [inline]\fP"

.PP
Allows one to fit a peak of a histogram in the range [low_edge, high_edge]\&. 
.SS "auto PeakFitter::getBackground () const\fC [inline]\fP"

.SS "auto PeakFitter::getConstante () const\fC [inline]\fP"

.SS "auto const& PeakFitter::getFit () const\fC [inline]\fP"

.SS "auto PeakFitter::getMean () const\fC [inline]\fP"

.SS "auto PeakFitter::getSigma () const\fC [inline]\fP"

.SS "auto PeakFitter::operator\-> ()\fC [inline]\fP"

.SS "auto PeakFitter::setBackgroundOrder (int const & order_background)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "TF1* PeakFitter::final_fit = nullptr\fC [protected]\fP"

.SS "double PeakFitter::m_high_edge = 0\&.0\fC [protected]\fP"

.SS "TH1* PeakFitter::m_histo\fC [protected]\fP"

.SS "bool PeakFitter::m_low_binning = true\fC [protected]\fP"

.SS "double PeakFitter::m_low_edge = 0\&.0\fC [protected]\fP"

.SS "double PeakFitter::m_order_background = 3\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
