.TH "Performances" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Performances
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Performances\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerformances\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMTCounter\fP \fBnb_events\fP"
.br
.ti -1c
.RI "\fBMTCounter\fP \fBnb_hits\fP"
.br
.ti -1c
.RI "\fBMTCounter\fP \fBnb_kept_events\fP"
.br
.ti -1c
.RI "\fBMTCounter\fP \fBnb_raw_events\fP"
.br
.ti -1c
.RI "\fBMTCounter\fP \fBnb_total_events\fP"
.br
.ti -1c
.RI "\fBMTCounter\fP \fBnb_total_hits\fP"
.br
.ti -1c
.RI "\fBMTCounter\fP \fBnb_total_kept_events\fP"
.br
.ti -1c
.RI "\fBMTCounter\fP \fBnb_total_raw_events\fP"
.br
.ti -1c
.RI "\fBMTCounter\fP \fBtotal_read_size_file\fP"
.br
.ti -1c
.RI "\fBMTCounter\fP \fBtotal_written_size_file\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Performances::Performances ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMTCounter\fP Performances::nb_events"

.SS "\fBMTCounter\fP Performances::nb_hits"

.SS "\fBMTCounter\fP Performances::nb_kept_events"

.SS "\fBMTCounter\fP Performances::nb_raw_events"

.SS "\fBMTCounter\fP Performances::nb_total_events"

.SS "\fBMTCounter\fP Performances::nb_total_hits"

.SS "\fBMTCounter\fP Performances::nb_total_kept_events"

.SS "\fBMTCounter\fP Performances::nb_total_raw_events"

.SS "\fBMTCounter\fP Performances::total_read_size_file"

.SS "\fBMTCounter\fP Performances::total_written_size_file"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
