.TH "lib/random.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/random.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <random>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::mt19937 \fBgen\fP (\fBrd\fP())"
.br
.ti -1c
.RI "double \fBrandom_uniform\fP ()"
.br
.ti -1c
.RI "std::uniform_real_distribution< double > \fBuniform_random_generator_double\fP (0, 1)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::random_device \fBrd\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::mt19937 gen (\fBrd\fP())"

.SS "double random_uniform ()"

.SS "std::uniform_real_distribution<double> uniform_random_generator_double (0, 1)"

.SH "Variable Documentation"
.PP 
.SS "std::random_device rd"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
