.TH "lib/Classes/ReaderManager.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/ReaderManager.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DataMultiReader\&.h'\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReaderManager\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< \fBHit\fP > \fBBuffer\fP"
.br
.ti -1c
.RI "typedef std::vector< std::string > \fBListfiles\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<\fBHit\fP> \fBBuffer\fP"

.SS "typedef std::vector<std::string> \fBListfiles\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
