.TH "RF_Extractor" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RF_Extractor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RF_Manager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto const  & \fBcursor\fP () const"
.br
.ti -1c
.RI "\fBoperator bool\fP () const &"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_cursor\fP = 0"
.br
.ti -1c
.RI "bool \fBm_ok\fP = false"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "auto const& RF_Extractor::cursor () const\fC [inline]\fP"

.SS "RF_Extractor::operator bool () const &\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int RF_Extractor::m_cursor = 0\fC [private]\fP"

.SS "bool RF_Extractor::m_ok = false\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
