.TH "RWMat" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RWMat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RWMat\&.hxx>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRWMat\fP * \fBAdd\fP (\fBRWMat\fP *Matrix, double val)"
.br
.ti -1c
.RI "void \fBFill\fP (unsigned short i, unsigned short j)"
.br
.ti -1c
.RI "int \fBFindMinChan\fP ()"
.br
.ti -1c
.RI "double \fBFindMinMax\fP ()"
.br
.ti -1c
.RI "double \fBGet\fP (unsigned short i, unsigned short j)"
.br
.ti -1c
.RI "double \fBIntegral\fP ()"
.br
.ti -1c
.RI "void \fBRead\fP (std::string \fBFilename\fP='', bool IsInteger=true)"
.br
.ti -1c
.RI "template<class THist > void \fBReset\fP (THist *RootMat)"
.br
.ti -1c
.RI "void \fBReSymmetrise\fP ()"
.br
.ti -1c
.RI "template<class T > \fBRWMat\fP (\fBMTTHist\fP< T > &MTRootMat)"
.br
.ti -1c
.RI "\fBRWMat\fP (std::string name='test\&.m4b', int nchans=4096)"
.br
.ti -1c
.RI "\fBRWMat\fP (TH2F *RootMat)"
.br
.ti -1c
.RI "void \fBSet\fP (unsigned short i, unsigned short j, double val)"
.br
.ti -1c
.RI "void \fBSet\fP (unsigned short i, unsigned short j, int val)"
.br
.ti -1c
.RI "void \fBWrite\fP (std::string name='', std::string path='\&./')"
.br
.ti -1c
.RI "\fB~RWMat\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBdeleted\fP = false"
.br
.ti -1c
.RI "double \fBfMaxCounts\fP"
.br
.ti -1c
.RI "std::string \fBfName\fP"
.br
.ti -1c
.RI "unsigned short \fBfNChannels\fP"
.br
.ti -1c
.RI "int ** \fBfRWMat\fP"
.br
.ti -1c
.RI "double \fBfTotalCounts\fP"
.br
.ti -1c
.RI "bool \fBm_ok\fP = true"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RWMat::RWMat (std::string name = \fC'test\&.m4b'\fP, int nchans = \fC4096\fP)"

.SS "RWMat::RWMat (TH2F * RootMat)"

.SS "template<class T > RWMat::RWMat (\fBMTTHist\fP< T > & MTRootMat)"

.SS "RWMat::~RWMat ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBRWMat\fP * RWMat::Add (\fBRWMat\fP * Matrix, double val)"

.SS "void RWMat::Fill (unsigned short i, unsigned short j)"

.SS "int RWMat::FindMinChan ()"

.SS "double RWMat::FindMinMax ()"

.SS "double RWMat::Get (unsigned short i, unsigned short j)\fC [inline]\fP"

.SS "double RWMat::Integral ()"

.SS "void RWMat::Read (std::string Filename = \fC''\fP, bool IsInteger = \fCtrue\fP)"

.SS "template<class THist > void RWMat::Reset (THist * RootMat)"

.SS "void RWMat::ReSymmetrise ()"

.SS "void RWMat::Set (unsigned short i, unsigned short j, double val)\fC [inline]\fP"

.SS "void RWMat::Set (unsigned short i, unsigned short j, int val)\fC [inline]\fP"

.SS "void RWMat::Write (std::string name = \fC''\fP, std::string path = \fC'\&./'\fP)"

.SH "Member Data Documentation"
.PP 
.SS "bool RWMat::deleted = false\fC [protected]\fP"

.SS "double RWMat::fMaxCounts\fC [protected]\fP"

.SS "std::string RWMat::fName\fC [protected]\fP"

.SS "unsigned short RWMat::fNChannels\fC [protected]\fP"

.SS "int** RWMat::fRWMat\fC [protected]\fP"

.SS "double RWMat::fTotalCounts\fC [protected]\fP"

.SS "bool RWMat::m_ok = true\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
