.TH "Sorted_Event" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sorted_Event
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sorted_Event\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddGeGateTrig\fP (Float_t const &minE, Float_t const &\fBmaxE\fP)"
.br
.ti -1c
.RI "void \fBaddGeGateTrig\fP (std::pair< Float_t, Float_t > const &Egate)"
.br
.ti -1c
.RI "void \fBfillEvent\fP (\fBEvent\fP &event)"
.br
.ti -1c
.RI "int const  & \fBgateGe\fP () const"
.br
.ti -1c
.RI "auto const  & \fBgetGatedClover\fP () const"
.br
.ti -1c
.RI "void \fBinitialise\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBsetEvent\fP (\fBEvent\fP *event)"
.br
.ti -1c
.RI "void \fBsetRF\fP (\fBRF_Manager\fP *rf)"
.br
.ti -1c
.RI "\fBSorted_Event\fP ()"
.br
.ti -1c
.RI "\fBSorted_Event\fP (\fBEvent\fP *event)"
.br
.ti -1c
.RI "void \fBsortEvent\fP ()"
.br
.ti -1c
.RI "void \fBsortEvent\fP (\fBEvent\fP const &event)"
.br
.ti -1c
.RI "bool \fBsortGeClover\fP (\fBEvent\fP const &event, int const &i)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitialise\fP ()"
.br
.ti -1c
.RI "static void \fBsetDSSDVeto\fP (Float_t const &min_time, Float_t const &max_time, Float_t const &max_E)"
.br
.ti -1c
.RI "static void \fBsetMaxTime\fP (Float_t const &max_time)"
.br
.ti -1c
.RI "static void \fBsetTWcorrectionsDSSD\fP (std::string const &filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::array< Int_t, 24 > \fBBGO\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBBGOMult\fP =0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBCleanGeMult\fP =0"
.br
.ti -1c
.RI "std::vector< \fBuchar\fP > \fBclover_hits\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBCloverGeMult\fP =0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBCloverMult\fP =0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBComptonVetoMult\fP =0"
.br
.ti -1c
.RI "std::array< Bool_t, 24 > \fBdelayed_Ge\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBDelayedGeMult\fP =0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBDelayedMult\fP =0"
.br
.ti -1c
.RI "std::vector< \fBuchar\fP > \fBDSSD_hits\fP"
.br
.ti -1c
.RI "std::vector< char > \fBDSSD_is_Prompt\fP"
.br
.ti -1c
.RI "std::vector< char > \fBDSSD_is_Ring\fP"
.br
.ti -1c
.RI "std::vector< \fBuchar\fP > \fBDSSD_Rings\fP"
.br
.ti -1c
.RI "std::vector< \fBuchar\fP > \fBDSSD_Sectors\fP"
.br
.ti -1c
.RI "bool \fBdssd_veto\fP = false"
.br
.ti -1c
.RI "\fBsize_t\fP \fBDSSDMult\fP =0"
.br
.ti -1c
.RI "Bool_t \fBDSSDPrompt\fP =false"
.br
.ti -1c
.RI "\fBsize_t\fP \fBDSSDRingMult\fP =0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBDSSDSectorMult\fP =0"
.br
.ti -1c
.RI "std::array< Int_t, 24 > \fBGe\fP"
.br
.ti -1c
.RI "\fBLaBr3_Event\fP \fBLaBr3_event\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBLaBr3Mult\fP =0"
.br
.ti -1c
.RI "\fBRF_Manager\fP * \fBm_rf\fP = nullptr"
.br
.ti -1c
.RI "std::array< Float_t, 24 > \fBmaxE\fP"
.br
.ti -1c
.RI "std::array< Int_t, 24 > \fBmaxE_hit\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBModuleDelayedMult\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBModulePromptMult\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBModulesMult\fP =0"
.br
.ti -1c
.RI "std::array< Float_t, 24 > \fBnrj_clover\fP"
.br
.ti -1c
.RI "std::vector< \fBuchar\fP > \fBparis_hits\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBParisLaBr3Mult\fP =0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBParisMult\fP =0"
.br
.ti -1c
.RI "std::array< Bool_t, 24 > \fBprompt_Ge\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBPromptGeMult\fP =0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBPromptMult\fP =0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBRawGeMult\fP =0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBRawMult\fP =0"
.br
.ti -1c
.RI "std::array< Float_t, 2000 > \fBtime2s\fP"
.br
.ti -1c
.RI "std::array< Float_t, 24 > \fBtime_clover\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static float \fBm_max_E_dssd\fP = 1\&.E+12"
.br
.ti -1c
.RI "static float \fBm_max_time_dssd\fP = \-100"
.br
.ti -1c
.RI "static float \fBm_min_time_dssd\fP = 400"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsize_t\fP \fBm_CloverTrig\fP = 0\&."
.br
.ti -1c
.RI "\fBEvent\fP * \fBm_event\fP"
.br
.ti -1c
.RI "bool \fBm_gateON\fP = false"
.br
.ti -1c
.RI "int \fBm_Ge_gate\fP = 0"
.br
.ti -1c
.RI "std::vector< std::pair< Float_t, Float_t > > \fBm_Ge_gates\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static Float_t \fBm_max_time\fP = 9999999\&."
.br
.ti -1c
.RI "static \fBTimewalks\fP \fBm_Timewalks_DSSD\fP"
.br
.ti -1c
.RI "static bool \fBm_TW_DSSD\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sorted_Event::Sorted_Event ()\fC [inline]\fP"

.SS "Sorted_Event::Sorted_Event (\fBEvent\fP * event)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Sorted_Event::addGeGateTrig (Float_t const & minE, Float_t const & maxE)\fC [inline]\fP"

.SS "void Sorted_Event::addGeGateTrig (std::pair< Float_t, Float_t > const & Egate)\fC [inline]\fP"

.SS "void Sorted_Event::fillEvent (\fBEvent\fP & event)"

.SS "int const& Sorted_Event::gateGe () const\fC [inline]\fP"

.SS "auto const& Sorted_Event::getGatedClover () const\fC [inline]\fP"

.SS "static void Sorted_Event::Initialise ()\fC [inline]\fP, \fC [static]\fP"

.SS "void Sorted_Event::initialise ()"

.SS "void Sorted_Event::reset ()"

.SS "static void Sorted_Event::setDSSDVeto (Float_t const & min_time, Float_t const & max_time, Float_t const & max_E)\fC [inline]\fP, \fC [static]\fP"

.SS "void Sorted_Event::setEvent (\fBEvent\fP * event)\fC [inline]\fP"

.SS "void Sorted_Event::setMaxTime (Float_t const & max_time)\fC [static]\fP"

.SS "void Sorted_Event::setRF (\fBRF_Manager\fP * rf)\fC [inline]\fP"

.SS "void Sorted_Event::setTWcorrectionsDSSD (std::string const & filename)\fC [static]\fP"

.SS "void Sorted_Event::sortEvent ()\fC [inline]\fP"

.SS "void Sorted_Event::sortEvent (\fBEvent\fP const & event)"

.SS "bool Sorted_Event::sortGeClover (\fBEvent\fP const & event, int const & i)"

.SH "Member Data Documentation"
.PP 
.SS "std::array< Int_t, 24 > Sorted_Event::BGO"

.SS "\fBsize_t\fP Sorted_Event::BGOMult =0"

.SS "\fBsize_t\fP Sorted_Event::CleanGeMult =0"

.SS "std::vector<\fBuchar\fP> Sorted_Event::clover_hits"

.SS "\fBsize_t\fP Sorted_Event::CloverGeMult =0"

.SS "\fBsize_t\fP Sorted_Event::CloverMult =0"

.SS "\fBsize_t\fP Sorted_Event::ComptonVetoMult =0"

.SS "std::array< Bool_t, 24 > Sorted_Event::delayed_Ge"

.SS "\fBsize_t\fP Sorted_Event::DelayedGeMult =0"

.SS "\fBsize_t\fP Sorted_Event::DelayedMult =0"

.SS "std::vector<\fBuchar\fP> Sorted_Event::DSSD_hits"

.SS "std::vector<char> Sorted_Event::DSSD_is_Prompt"

.SS "std::vector<char> Sorted_Event::DSSD_is_Ring"

.SS "std::vector<\fBuchar\fP> Sorted_Event::DSSD_Rings"

.SS "std::vector<\fBuchar\fP> Sorted_Event::DSSD_Sectors"

.SS "bool Sorted_Event::dssd_veto = false"

.SS "\fBsize_t\fP Sorted_Event::DSSDMult =0"

.SS "Bool_t Sorted_Event::DSSDPrompt =false"

.SS "\fBsize_t\fP Sorted_Event::DSSDRingMult =0"

.SS "\fBsize_t\fP Sorted_Event::DSSDSectorMult =0"

.SS "std::array< Int_t, 24 > Sorted_Event::Ge"

.SS "\fBLaBr3_Event\fP Sorted_Event::LaBr3_event"

.SS "\fBsize_t\fP Sorted_Event::LaBr3Mult =0"

.SS "\fBsize_t\fP Sorted_Event::m_CloverTrig = 0\&.\fC [private]\fP"

.SS "\fBEvent\fP* Sorted_Event::m_event\fC [private]\fP"

.SS "bool Sorted_Event::m_gateON = false\fC [private]\fP"

.SS "int Sorted_Event::m_Ge_gate = 0\fC [private]\fP"

.SS "std::vector<std::pair<Float_t,Float_t> > Sorted_Event::m_Ge_gates\fC [private]\fP"

.SS "float Sorted_Event::m_max_E_dssd = 1\&.E+12\fC [static]\fP"

.SS "Float_t Sorted_Event::m_max_time = 9999999\&.\fC [static]\fP, \fC [private]\fP"

.SS "float Sorted_Event::m_max_time_dssd = \-100\fC [static]\fP"

.SS "float Sorted_Event::m_min_time_dssd = 400\fC [static]\fP"

.SS "\fBRF_Manager\fP* Sorted_Event::m_rf = nullptr"

.SS "\fBTimewalks\fP Sorted_Event::m_Timewalks_DSSD\fC [static]\fP, \fC [private]\fP"

.SS "bool Sorted_Event::m_TW_DSSD = false\fC [static]\fP, \fC [private]\fP"

.SS "std::array< Float_t, 24 > Sorted_Event::maxE"

.SS "std::array< Int_t, 24 > Sorted_Event::maxE_hit"

.SS "\fBsize_t\fP Sorted_Event::ModuleDelayedMult"

.SS "\fBsize_t\fP Sorted_Event::ModulePromptMult"

.SS "\fBsize_t\fP Sorted_Event::ModulesMult =0"

.SS "std::array< Float_t, 24 > Sorted_Event::nrj_clover"

.SS "std::vector<\fBuchar\fP> Sorted_Event::paris_hits"

.SS "\fBsize_t\fP Sorted_Event::ParisLaBr3Mult =0"

.SS "\fBsize_t\fP Sorted_Event::ParisMult =0"

.SS "std::array< Bool_t, 24 > Sorted_Event::prompt_Ge"

.SS "\fBsize_t\fP Sorted_Event::PromptGeMult =0"

.SS "\fBsize_t\fP Sorted_Event::PromptMult =0"

.SS "\fBsize_t\fP Sorted_Event::RawGeMult =0"

.SS "\fBsize_t\fP Sorted_Event::RawMult =0"

.SS "std::array<Float_t, 2000> Sorted_Event::time2s"

.SS "std::array< Float_t, 24 > Sorted_Event::time_clover"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
