.TH "lib/Analyse/Sorted_Event.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Analyse/Sorted_Event.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <Event\&.hpp>\fP
.br
\fC#include <Timewalk\&.hpp>\fP
.br
\fC#include <Clovers\&.hpp>\fP
.br
\fC#include <DSSD\&.hpp>\fP
.br
\fC#include <RF_Manager\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLaBr3_Hit\fP"
.br
.ti -1c
.RI "class \fBSorted_Event\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBLaBr3_Event\fP = std::vector< \fBLaBr3_Hit\fP >"
.br
.in -1c
.SH "Class Documentation"
.PP 
.SH "struct LaBr3_Hit"
.PP 
\fBClass Members:\fP
.RS 4
\fBuchar\fP \fIlabel\fP 
.br
.PP
Float_t \fInrjcal\fP 
.br
.PP
ULong64_t \fItime\fP 
.br
.PP
.RE
.PP
.SH "Typedef Documentation"
.PP 
.SS "using \fBLaBr3_Event\fP =  std::vector < \fBLaBr3_Hit\fP >"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
