.TH "SpectraCo::HistoNull" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpectraCo::HistoNull
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SpectraCo\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoNull\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpectraCo::HistoNull::HistoNull ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
