.TH "SpectraAlignator" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpectraAlignator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SpectraAlignator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecalibration\fP const  & \fBalignSpectra\fP (TH1 *_spectra, TH1 *spectra_output, int const &degreesOfFreedom=3, double const &energyThreshold=0)"
.br
.ti -1c
.RI "void \fBsetBruteForce\fP (bool const &brute_force=true)"
.br
.ti -1c
.RI "void \fBsetIterations\fP (int const &iterations)"
.br
.ti -1c
.RI "\fBSpectraAlignator\fP (TH1 *ref)"
.br
.ti -1c
.RI "void \fBwriteChi2Spectra\fP (TFile *file)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_brute_force\fP = false"
.br
.ti -1c
.RI "TH3F * \fBm_chi2_spectra\fP = nullptr"
.br
.ti -1c
.RI "std::vector< double > \fBm_chi2s\fP"
.br
.ti -1c
.RI "std::vector< \fBMinimisator\fP > \fBm_minimisator\fP"
.br
.ti -1c
.RI "int \fBm_nb_iterations\fP = 20"
.br
.ti -1c
.RI "std::vector< \fBRecalibration\fP > \fBm_recals\fP"
.br
.ti -1c
.RI "\fBSpectraCo\fP \fBm_ref_spectra\fP"
.br
.ti -1c
.RI "std::vector< \fBSpectraCo\fP > \fBm_spectra\fP"
.br
.ti -1c
.RI "int \fBm_spectra_threshold\fP = 0"
.br
.ti -1c
.RI "TH2F * \fBsurface_chi2\fP = nullptr"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpectraAlignator::SpectraAlignator (TH1 * ref)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBRecalibration\fP const& SpectraAlignator::alignSpectra (TH1 * _spectra, TH1 * spectra_output, int const & degreesOfFreedom = \fC3\fP, double const & energyThreshold = \fC0\fP)\fC [inline]\fP"

.SS "void SpectraAlignator::setBruteForce (bool const & brute_force = \fCtrue\fP)\fC [inline]\fP"

.SS "void SpectraAlignator::setIterations (int const & iterations)\fC [inline]\fP"

.SS "void SpectraAlignator::writeChi2Spectra (TFile * file)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool SpectraAlignator::m_brute_force = false\fC [private]\fP"

.SS "TH3F* SpectraAlignator::m_chi2_spectra = nullptr\fC [private]\fP"

.SS "std::vector<double> SpectraAlignator::m_chi2s\fC [private]\fP"

.SS "std::vector<\fBMinimisator\fP> SpectraAlignator::m_minimisator\fC [private]\fP"

.SS "int SpectraAlignator::m_nb_iterations = 20\fC [private]\fP"

.SS "std::vector<\fBRecalibration\fP> SpectraAlignator::m_recals\fC [private]\fP"

.SS "\fBSpectraCo\fP SpectraAlignator::m_ref_spectra\fC [private]\fP"

.SS "std::vector<\fBSpectraCo\fP> SpectraAlignator::m_spectra\fC [private]\fP"

.SS "int SpectraAlignator::m_spectra_threshold = 0\fC [private]\fP"

.SS "TH2F* SpectraAlignator::surface_chi2 = nullptr\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
