.TH "lib/Analyse/SpectraCo.hpp" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Analyse/SpectraCo.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libRoot\&.hpp'\fP
.br
\fC#include 'Recalibration\&.hpp'\fP
.br
\fC#include '\&.\&./Classes/Calibration\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpectraCo::HistoNull\fP"
.br
.ti -1c
.RI "class \fBSpectraCo::HistoZombie\fP"
.br
.ti -1c
.RI "class \fBMyError\fP"
.br
.ti -1c
.RI "class \fBSpectraCo::SizeMissmatch\fP"
.br
.ti -1c
.RI "class \fBSpectraCo\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBSpectraPoint\fP = std::pair< int, double >"
.br
.ti -1c
.RI "using \fBSpectraPoints\fP = std::vector< \fBSpectraPoint\fP >"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBgoingAbove\fP (std::vector< double > &m_spectra, int &bin, int const &threshold, int const &nb_above)"
.br
.RI "Returns the position where the histogram goes under the threshold\&. "
.ti -1c
.RI "bool \fBgoingBelow\fP (std::vector< double > &m_spectra, int &bin, int const &threshold, int const &nb_below)"
.br
.RI "Returns the position where the histogram goes under the threshold\&. "
.ti -1c
.RI "\fBSpectraPoint\fP \fBmaximum_in_range\fP (std::vector< double > &m_spectra, int bin_min, int const &bin_max)"
.br
.ti -1c
.RI "\fBSpectraPoint\fP \fBminimum_in_range\fP (std::vector< double > &m_spectra, int bin_min, int const &bin_max)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, \fBSpectraCo\fP const &spectra)"
.br
.ti -1c
.RI "template<> std::string \fBtype_of< SpectraCo >\fP (\fBSpectraCo\fP const &spectra)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBSpectraPoint\fP =  std::pair<int, double>"

.SS "using \fBSpectraPoints\fP =  std::vector<\fBSpectraPoint\fP>"

.SH "Function Documentation"
.PP 
.SS "bool goingAbove (std::vector< double > & m_spectra, int & bin, int const & threshold, int const & nb_above)"

.PP
Returns the position where the histogram goes under the threshold\&. Must start above threshold\&. There must be at least nb_below points below the threshold 
.SS "bool goingBelow (std::vector< double > & m_spectra, int & bin, int const & threshold, int const & nb_below)"

.PP
Returns the position where the histogram goes under the threshold\&. Must start above threshold\&. There must be at least nb_below points below the threshold 
.SS "\fBSpectraPoint\fP maximum_in_range (std::vector< double > & m_spectra, int bin_min, int const & bin_max)"

.SS "\fBSpectraPoint\fP minimum_in_range (std::vector< double > & m_spectra, int bin_min, int const & bin_max)"

.SS "std::ostream& operator<< (std::ostream & out, \fBSpectraCo\fP const & spectra)"

.SS "template<> std::string \fBtype_of\fP< \fBSpectraCo\fP > (\fBSpectraCo\fP const & spectra)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
