.TH "TestObjectiveFunction" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestObjectiveFunction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SpectraAlignator\&.hpp>\fP
.PP
Inherits \fBObjectiveFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBevaluate\fP (std::vector< double > const &coefficients) const override"
.br
.ti -1c
.RI "\fBTestObjectiveFunction\fP () noexcept=default"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestObjectiveFunction::TestObjectiveFunction ()\fC [default]\fP, \fC [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "double TestObjectiveFunction::evaluate (std::vector< double > const & coefficients) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBObjectiveFunction\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
