.TH "test" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- Test List 

.IP "\fBMember \fBFasterReader::setHit\fP (\fBHit\fP *hit)\fP" 1c
Set the \fBHit\fP object \\nNever tested, but should work !  
.IP "\fBClass \fBMTTHist< THist >\fP \fP" 1c
In mono mode (MTTHIST_MONO), only one histogram is created UNDER DEVELOPPEMENT
.PP

