.TH "THBinning" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
THBinning \- Binning of a root histogram (TH1) : number of bins, min value, max value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libRoot\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTHBinning\fP ()=default"
.br
.ti -1c
.RI "\fBTHBinning\fP (double _bins, double _min, double _max)"
.br
.ti -1c
.RI "\fBTHBinning\fP (std::initializer_list< double > initList)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBbins\fP = 0"
.br
.ti -1c
.RI "float \fBmax\fP = 0\&.f"
.br
.ti -1c
.RI "float \fBmin\fP = 0\&.f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Binning of a root histogram (TH1) : number of bins, min value, max value\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "THBinning::THBinning ()\fC [default]\fP"

.SS "THBinning::THBinning (std::initializer_list< double > initList)\fC [inline]\fP"

.SS "THBinning::THBinning (double _bins, double _min, double _max)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int THBinning::bins = 0"

.SS "float THBinning::max = 0\&.f"

.SS "float THBinning::min = 0\&.f"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
