.TH "TheTChain" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TheTChain \- Not functionnal yet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libRoot\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (std::string const &expression)"
.br
.ti -1c
.RI "auto \fBbegin\fP ()"
.br
.ti -1c
.RI "auto \fBend\fP ()"
.br
.ti -1c
.RI "TTree * \fBoperator[]\fP (int const &i)"
.br
.ti -1c
.RI "bool \fBread\fP ()"
.br
.ti -1c
.RI "void \fBset\fP ()"
.br
.ti -1c
.RI "template<class\&.\&.\&. ARGS> void \fBSetBranchAddress\fP (ARGS &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBTheTChain\fP (std::string const &name, std::string const &expression='', std::string const &readMode='READ')"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBnewTTree\fP (std::string const &fileName)"
.br
.ti -1c
.RI "void \fBset\fP (std::string const &expression)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ULong64_t \fBm_evt_cursor\fP = 0"
.br
.ti -1c
.RI "std::vector< TFile * > \fBm_files\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBm_files_vec\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBm_input_files_expressions\fP"
.br
.ti -1c
.RI "std::string \fBm_name\fP = ''"
.br
.ti -1c
.RI "std::string \fBm_read_mode\fP = 'READ'"
.br
.ti -1c
.RI "ULong64_t \fBm_size\fP = 0"
.br
.ti -1c
.RI "UInt_t \fBm_tree_cursor\fP = 0"
.br
.ti -1c
.RI "std::vector< TTree * > \fBm_trees\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Not functionnal yet\&. 


.PP
\fBTodo\fP
.RS 4
maybe
.RE
.PP
.PP
1: Add all the files \fBTheTChain\fP chain('Nuball', '/path/to/data/files*\&.root'); chain\&.Add('/other_path/to/data/files*\&.root')
.PP
2: Setup the chain : chain\&.set();
.PP
3: Links all the variables chain\&.SetBranchAddress('branch', &variable); 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TheTChain::TheTChain (std::string const & name, std::string const & expression = \fC''\fP, std::string const & readMode = \fC'READ'\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void TheTChain::Add (std::string const & expression)\fC [inline]\fP"

.SS "auto TheTChain::begin ()\fC [inline]\fP"

.SS "auto TheTChain::end ()\fC [inline]\fP"

.SS "void TheTChain::newTTree (std::string const & fileName)\fC [inline]\fP, \fC [private]\fP"

.SS "TTree* TheTChain::operator[] (int const & i)\fC [inline]\fP"

.SS "bool TheTChain::read ()\fC [inline]\fP"

.SS "void TheTChain::set ()"

.SS "void TheTChain::set (std::string const & expression)\fC [private]\fP"

.SS "template<class\&.\&.\&. ARGS> void TheTChain::SetBranchAddress (ARGS &&\&.\&.\&. args)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ULong64_t TheTChain::m_evt_cursor = 0\fC [private]\fP"

.SS "std::vector<TFile*> TheTChain::m_files\fC [private]\fP"

.SS "std::vector<std::string> TheTChain::m_files_vec\fC [private]\fP"

.SS "std::vector<std::string> TheTChain::m_input_files_expressions\fC [private]\fP"

.SS "std::string TheTChain::m_name = ''\fC [private]\fP"

.SS "std::string TheTChain::m_read_mode = 'READ'\fC [private]\fP"

.SS "ULong64_t TheTChain::m_size = 0\fC [private]\fP"

.SS "UInt_t TheTChain::m_tree_cursor = 0\fC [private]\fP"

.SS "std::vector<TTree*> TheTChain::m_trees\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
