.TH "Timeshifts::EmptyError" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timeshifts::EmptyError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timeshifts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmptyError\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Timeshifts::EmptyError::EmptyError ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
