.TH "Timer" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtime_point_t\fP const  & \fBNow\fP ()"
.br
.ti -1c
.RI "auto \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBtime_point_t\fP const  & \fBRestart\fP ()"
.br
.ti -1c
.RI "\fBtime_point_t\fP const  & \fBStop\fP ()"
.br
.ti -1c
.RI "auto \fBTime\fP ()"
.br
.ti -1c
.RI "auto \fBTimeElapsed\fP ()"
.br
.ti -1c
.RI "auto \fBTimeElapsedSec\fP ()"
.br
.ti -1c
.RI "\fBTimer\fP ()"
.br
.ti -1c
.RI "auto \fBTimeSec\fP ()"
.br
.ti -1c
.RI "std::string \fBunit\fP ()"
.br
.ti -1c
.RI "float \fBUnit\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBduration_milli_t\fP \fBd_milli\fP"
.br
.ti -1c
.RI "\fBhr_clock_t\fP \fBm_clock\fP"
.br
.ti -1c
.RI "\fBtime_point_t\fP \fBm_now\fP"
.br
.ti -1c
.RI "\fBtime_point_t\fP \fBm_start\fP"
.br
.ti -1c
.RI "\fBtime_point_t\fP \fBm_stop\fP"
.br
.ti -1c
.RI "std::string \fBm_unit\fP = 'ms'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExamples\fP
.in +1c
\fB/media/sf_OneDrive/CNRS/Nuball2/lib/Classes/CoProgressBar\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Timer::Timer ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBtime_point_t\fP const& Timer::Now ()\fC [inline]\fP"

.SS "auto Timer::operator() ()\fC [inline]\fP"

.SS "\fBtime_point_t\fP const& Timer::Restart ()\fC [inline]\fP"

.SS "\fBtime_point_t\fP const& Timer::Stop ()\fC [inline]\fP"

.SS "auto Timer::Time ()\fC [inline]\fP"

.SS "auto Timer::TimeElapsed ()\fC [inline]\fP"

.SS "auto Timer::TimeElapsedSec ()\fC [inline]\fP"

.SS "auto Timer::TimeSec ()\fC [inline]\fP"

.SS "std::string Timer::unit ()\fC [inline]\fP"

.SS "float Timer::Unit ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBduration_milli_t\fP Timer::d_milli\fC [private]\fP"

.SS "\fBhr_clock_t\fP Timer::m_clock\fC [private]\fP"

.SS "\fBtime_point_t\fP Timer::m_now\fC [private]\fP"

.SS "\fBtime_point_t\fP Timer::m_start\fC [private]\fP"

.SS "\fBtime_point_t\fP Timer::m_stop\fC [private]\fP"

.SS "std::string Timer::m_unit = 'ms'\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
