.TH "lib/Classes/Timer.hpp" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Classes/Timer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBduration_milli_t\fP = std::chrono::duration< double, std::milli >"
.br
.ti -1c
.RI "using \fBhr_clock_t\fP = std::chrono::high_resolution_clock"
.br
.ti -1c
.RI "using \fBtime_point_t\fP = std::chrono::time_point< \fBhr_clock_t\fP >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBduration_milli_t\fP =  std::chrono::duration<double, std::milli>"

.SS "using \fBhr_clock_t\fP =  std::chrono::high_resolution_clock"

.SS "using \fBtime_point_t\fP =  std::chrono::time_point<\fBhr_clock_t\fP>"

.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
