.TH "Timeshifts::NotFoundError" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timeshifts::NotFoundError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timeshifts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto const  & \fBgetFilename\fP () const"
.br
.ti -1c
.RI "\fBNotFoundError\fP (std::string const &filename)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_filename\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Timeshifts::NotFoundError::NotFoundError (std::string const & filename)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "auto const& Timeshifts::NotFoundError::getFilename () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Timeshifts::NotFoundError::m_filename\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
