.TH "Timewalk" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timewalk
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timewalk\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float const  & \fBget\fP (float const &nrj)"
.br
.ti -1c
.RI "void \fBloadFile\fP (std::string const &filename)"
.br
.ti -1c
.RI "auto & \fBoperator[]\fP (int const &i)"
.br
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.ti -1c
.RI "void \fBresize\fP ()"
.br
.ti -1c
.RI "void \fBresize\fP (\fBsize_t\fP const &size, float const &value=0\&.)"
.br
.ti -1c
.RI "\fBTimewalk\fP ()"
.br
.ti -1c
.RI "\fBTimewalk\fP (std::string const &filename)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static float const  & \fBgetMax\fP ()"
.br
.ti -1c
.RI "static void \fBsetMax\fP (float const &_max)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBisON\fP"
.br
.ti -1c
.RI "float \fBm_float_zero\fP = 0\&."
.br
.ti -1c
.RI "float \fBm_keVperBin\fP = 1\&."
.br
.ti -1c
.RI "std::vector< float > \fBm_Timewalk\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static float \fBmax\fP = 10000\&.f"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Timewalk::Timewalk ()\fC [inline]\fP"

.SS "Timewalk::Timewalk (std::string const & filename)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "float const  & Timewalk::get (float const & nrj)\fC [inline]\fP"

.SS "static float const& Timewalk::getMax ()\fC [inline]\fP, \fC [static]\fP"

.SS "void Timewalk::loadFile (std::string const & filename)"

.SS "auto& Timewalk::operator[] (int const & i)\fC [inline]\fP"

.SS "void Timewalk::Print ()\fC [inline]\fP"

.SS "void Timewalk::resize ()\fC [inline]\fP"

.SS "void Timewalk::resize (\fBsize_t\fP const & size, float const & value = \fC0\&.\fP)\fC [inline]\fP"

.SS "static void Timewalk::setMax (float const & _max)\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool Timewalk::isON\fC [private]\fP"

.SS "float Timewalk::m_float_zero = 0\&.\fC [private]\fP"

.SS "float Timewalk::m_keVperBin = 1\&.\fC [private]\fP"

.SS "std::vector<float> Timewalk::m_Timewalk\fC [private]\fP"

.SS "float Timewalk::max = 10000\&.f\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
