.TH "todo" 3 "Tue Dec 5 2023" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBClass \fBCalibration\fP \fP" 1c
\fBCalibration::verify()\fP DO NOT SUPPORT \fBMTObject\fP !!  
.IP "\fBClass \fBFile\fP \fP" 1c
rethink the checkMode logic \&.\&.\&.  
.IP "\fBClass \fBMTTHist< THist >\fP \fP" 1c
better memory management 
.PP

