.TH "TypeRootMap" 3 "Mon Mar 25 2024" "Nuball2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeRootMap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libRoot\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T > std::string \fBoperator()\fP (T const &t) const"
.br
.ti -1c
.RI "\fBTypeRootMap\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::unordered_map< std::type_index, std::string > \fBm_typeRootMap\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static bool \fBInitialised\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TypeRootMap::TypeRootMap ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > std::string TypeRootMap::operator() (T const & t) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool TypeRootMap::Initialised = false\fC [static]\fP, \fC [private]\fP"

.SS "std::unordered_map<std::type_index, std::string> TypeRootMap::m_typeRootMap\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nuball2 from the source code\&.
