CobaltCalorimeter.hpp
void calibBGO(Hit &hit)
References isBGO, Hit::label, Hit::nrj.
Referenced by CobaltCalorimeter::work.
bool inGate(double const &value, double const &min, double const &max)
Referenced by CobaltCalorimeter::work.
float smear(float const &nrj, Label const &label, TRandom *random)
References isGe, isParis.
float smear(float const &nrj, TRandom *random)
Referenced by CobaltCalorimeter::work.