Histogramor.hpp
Histogramor(int argc, char **argv)
bool load_binning(std::string const &filename)
print("")
print("-b [binning_file] : Load .binning file")
print("-i [ID_file] : Load ID file")
Referenced by FilesManager::addFolder, AddTH1, MTObject::adjustThreadsNumber, SpectraAlignator::alignSpectra, Timeshifts::analyse, Calibration::analyse, Faster2Root::buildEvents, Calibration::calculate, Timeshifts::calculate, File::check, Timeshifts::CheckParameters, Faster2Root::convert, Faster2Root::convertFile, create_folder_if_none, draw_all_TH1F_with_X_window, MTRootReader::execute, CoAnalyse::extractBackgroundArray, Faster2Root::Faster2Root, Filename::fill, Calibration::fillRootDataHisto, fuse_all_histo, getMeanPeak, DataFileReader::Initialise, Calibration::histograms::Initialise, RunMatrixator::Initialise, MTObject::Initialise, Timeshifts::Initialise, CloverSpectra::Initialise, Clovers::InitialiseArrays, DSSD::InitialiseArrays, Paris::InitialiseArrays, Event::isCalibrated, listFileReader, Path::load, Faster2Root::load, Faster2Histo::load, Calibration::load, Timeshifts::load, Calibration::loadFasterData, Timewalk::loadFile, Timewalks::loadFile, Alignator::loadNewIndex, Calibration::loadRootData, MTTHist< THist >::Merged, Minimisator::minimise, HistoAnalyse< THist >::normalizeX, HistoAnalyse< THist >::normalizeY, Nuball2Tree::Open, operator<<, MTObject::parallelise_function, ParisXY::ParisXY, Calibration::peakFinder, PositionXY::Print, FilesManager::Print, Manip::Print, Timewalk::Print, MTVector< T >::Print, MTTHist< THist >::Print, Event::Print, Clovers::PrintClean, FilesManager::printFolders, printMT, MTFasterReader::printMTFiles, CloverSpectra::printParameters, Faster2Root::printParameters, Faster2Histo::printParameters, Event::push_back, Event::push_front, MTFasterReader::readAligned, Detectors::readFile, Manip::readFile, Event::reading, Hit::reading, NearLine::readParam, MTFasterReader::readRaw, CoAnalyse::removeBackground, HistoAnalyse< THist >::reset, RWMat::Reset, Detectors::resize, RunMatrixator::run, CloverSpectra::runFasterReader, RWMat::RWMat, Calibration::setCalibrationTables, Manip::setMT, IOptions::setOptions, Timeshifts::setParameters, Timeshifts::setTimeWindow_ns, Timeshifts::shiftTimeSpectra, Timeshifts::treatFasterFile, Faster2Histo::treatFile, Timeshifts::treatFolder, Timeshifts::verify, Calibration::verify, RunMatrixator::Write, MTTHist< THist >::Write, Faster2Histo::write, RWMat::Write, MTTHist< THist >::Write_i, Calibration::writeCalibratedData, Calibration::writeCalibratedHisto, Timeshifts::writeData, Calibration::writeData, CloverSpectra::writeHisto, Calibration::writePosPeaks, Calibration::writeRawRoot, Timeshifts::writeRoot, Hit::writting, Event::writting, RWMat::~RWMat, StaticVector< T >::~StaticVector.