Hit.hpp
using ADC = int
using ADC_vec = std::vector<ADC >
using Energy_vec = std::vector<NRJ >
using Label = ushort
Data types ///.
using Label_vec = std::vector<Label >
Data vectors ///.
using NRJ = float
using Pileup = bool
using Pileup_vec = std::vector<Pileup >
using Time = Long64_t
using Time_ns = float
using Time_ns_vec = std::vector<Time_ns>
using Time_vec = std::vector<Time >
using Timestamp = ULong64_t
using TriggerHit = std::function<bool(const Hit&)>
Trigger definition ///.
ADC ADC_cast(T const &t)
Casts a number into unsigned ADC.
Referenced by Calibrator::peakFinder, FasterReader::TreatRF.
Label Label_cast(T const &t)
Data casts ///.
Casts a number into unsigned Label
Referenced by DSSD::InitialiseArrays, Timeshifts::setTimeReference, Detectors::size.
NRJ NRJ_cast(T const &t)
Casts a number into unsigned NRJ.
Referenced by ParisPhoswitch::Fill, Timeshifts::treatFasterFile.
std::ostream& operator<<(std::ostream &cout, Hit const &hit)
References Hit::adc, Hit::label, Hit::nrj, Hit::nrj2, Hit::nrj3, Hit::pileup, Hit::qdc2, Hit::qdc3, Hit::stamp.
Time Time_cast(T const &t)
Casts a number into unsigned Time.
Referenced by Timeshifts::analyse, CoincBuilder::coincidence, Timeshifts::Fill, RF_Manager::pulse_ToF, Event::push_back, Event::push_front, RF_Manager::set, Timeshifts::setRFOffset_ns, Event::setT0, CobaltCalorimeter::setTimewindow_ns, Timeshifts::setTimeWindow_ns, CobaltCalorimeter::work.
Time_ns Time_ns_cast(T const &t)
Casts a number into unsigned Time_ns.
Referenced by ParisPhoswitch::Fill, Timeshifts::setTimeWindow_ns, Event::time_ns.
Timestamp Timestamp_cast(T const &t)
Casts a number into unsigned Timestamp.
Referenced by FasterReader::ReadData, RF_Manager::setHit.