SpectraCo.hpp
using SpectraPoint = std::pair<int, double>
using SpectraPoints = std::vector<SpectraPoint>
bool goingAbove(std::vector< double > &m_spectra, int &bin, int const &threshold, int const &nb_above)
Returns the position where the histogram goes under the threshold.
Must start above threshold. There must be at least nb_below points below the threshold
References int_cast.
Referenced by SpectraCo::findPeaks.
bool goingBelow(std::vector< double > &m_spectra, int &bin, int const &threshold, int const &nb_below)
Returns the position where the histogram goes under the threshold.
Must start above threshold. There must be at least nb_below points below the threshold
References int_cast.
Referenced by SpectraCo::findPeaks.
SpectraPoint maximum_in_range(std::vector< double > &m_spectra, int bin_min, int const &bin_max)
SpectraPoint minimum_in_range(std::vector< double > &m_spectra, int bin_min, int const &bin_max)
Referenced by SpectraCo::findPeaks.
std::ostream& operator<<(std::ostream &out, SpectraCo const &spectra)
References SpectraCo::integral, SpectraCo::name, SpectraCo::peaks.
std::string type_of< SpectraCo >(SpectraCo const &spectra)
References SpectraCo::minX, type_of.