Timeshifts.hpp
std::vector<Time> forced_shifts
Referenced by Timeshifts::analyse.
void get_first_RF_of_file(FasterReader &reader, Hit &hit, RF_Manager &rf)
References Hit::label, RF_Manager::label, FasterReader::Read, RF_Manager::setHit.
Referenced by Timeshifts::treatFasterFile, Timeshifts::treatRootFile.
void get_first_RF_of_file(TTree *tree, Event &event, RF_Manager &rf)
References RF_Manager::setHit.
double getRFGammaPrompt(TH1F *hist, bool const &check_preprompt)
Referenced by Timeshifts::analyse.
std::ostream& operator<<(std::ostream &cout, Timeshifts const &ts)
References Timeshifts::get.
Time Timeshift_cast(T const &t)
Casts a number into unsigned Time.
Referenced by Timeshifts::analyse, Timeshifts::shiftTimeSpectra.