SpectraCo
SpectraCo* SpectraCo::m_derivative
Referenced by calibrate, calibrateX, deleteDerivative, derivative, derivativeData, rebin, recalibrate, resizeBin, ~SpectraCo.
SpectraCo* SpectraCo::m_derivative2
Referenced by derivative2, derivative2Data, findPeaks.
double SpectraCo::m_factor
Referenced by factor, operator*, operator/.
int SpectraCo::m_integral
Referenced by integral, load, operator=, resizeBin, SpectraCo.
double SpectraCo::m_intercept
Referenced by calculateCoeff, getBin.
TH1* SpectraCo::m_loaded_TH1
Referenced by load, operator=.
double SpectraCo::m_max_x
Referenced by calculateCoeff, calibrate, calibrateX, getX, load, maxX, operator=, resizeBin, setMaxX, setRangeX, SpectraCo.
double SpectraCo::m_min_x
Referenced by calculateCoeff, calibrate, calibrateX, load, minX, operator=, setMinX, setRangeX, SpectraCo.
std::string SpectraCo::m_name
Referenced by calibrate, createTH1D, createTH1F, derivative, derivative2, draw, load, name, operator=, SpectraCo.
SpectraPoints SpectraCo::m_peaks
Referenced by findPeaks, peaks.
double SpectraCo::m_rebin
Referenced by rebin.
int SpectraCo::m_size
Referenced by calculateCoeff, calibrate, createTH1D, createTH1F, firstBinWithValue, getX, lastBinWithValue, load, operator*, operator*=, operator+, operator-, operator/, operator=, recalibrate, resizeBin, size, SpectraCo.
double SpectraCo::m_slope
Referenced by calculateCoeff, getBin.
std::vector<double> SpectraCo::m_spectra
Referenced by back, calibrate, chi2, createTH1D, createTH1F, data, firstBinWithValue, get, inverse, lastBin, lastBinWithValue, load, operator*=, operator=, operator[], recalibrate, resizeBin, SpectraCo.
std::string SpectraCo::m_title
Referenced by calibrate, createTH1D, createTH1F, load, operator=, SpectraCo, title.
int SpectraCo::nb_histo_drawn
Referenced by draw.
std::vector<TH1*> SpectraCo::root_spectra_pointers
Referenced by createTH1D, createTH1F, draw.
auto& SpectraCo::back()
References m_spectra.
auto const& SpectraCo::back() const
References m_spectra.
void SpectraCo::calibrate(Calibration const &calib, Label const &label)
References Calibration::apply, calculateCoeff, calibrate, interpolate, m_derivative, m_max_x, m_min_x, m_name, m_size, m_spectra, m_title, Calibration::order, replace.
Referenced by calibrate, calibrateAndScale, SpectraCo.
void SpectraCo::calibrate(std::vector< double > const &coeffs)
References calculateCoeff, calibrate, calibrateX, error, int_cast, interpolate, m_derivative, m_name, m_size, m_spectra, m_title, replace.
void SpectraCo::calibrateAndScale(std::vector< double > const &coeffs)
Calibrates using the coeffs[0:n-1] coefficient then scale it using the coeffs.back() coefficient (spectra*=coeffs.back())
coeffs The last coefficient is used to scale, the other firsts to calibrate the x axis
References calibrate, sub_vec, throw_error.
Referenced by ObjectiveFunctionChi2::evaluate.
void SpectraCo::calibrateX(double const &intercept, double const &slope=1)
First order calibration.
References calculateCoeff, calibrateX, m_derivative, m_max_x, m_min_x.
Referenced by calibrate, calibrateX.
double SpectraCo::chi2(SpectraCo &other)
Calculates the chi2 between this spectra and another one.
References error, m_spectra, size.
TH1D * SpectraCo::createTH1D(std::string newName="", std::string newTitle="")
References double_cast, m_name, m_size, m_spectra, m_title, root_spectra_pointers.
Referenced by writeTH1D.
TH1F * SpectraCo::createTH1F(std::string newName="", std::string newTitle="")
References m_name, m_size, m_spectra, m_title, root_spectra_pointers.
Referenced by draw, rebin, write.
auto& SpectraCo::data()
References m_spectra.
auto const& SpectraCo::data() const
References m_spectra.
Referenced by derivative2Data, derivativeData, findPeaks.
void SpectraCo::deleteDerivative()
References m_derivative.
SpectraCo * SpectraCo::derivate(int smooth=1) noexcept
SpectraCo * SpectraCo::derivate2(int smooth=1) noexcept
Referenced by findPeaks.
SpectraCo* SpectraCo::derivative()
References m_derivative.
SpectraCo * SpectraCo::derivative(std::string const &name)
References error, m_derivative, m_name, name.
SpectraCo* SpectraCo::derivative2()
References m_derivative2.
SpectraCo * SpectraCo::derivative2(std::string const &name)
References error, m_derivative2, m_name, name.
std::vector<double> const& SpectraCo::derivative2Data()
One has to check that the second derivative has already been calculated;
References data, m_derivative2.
std::vector<double> const& SpectraCo::derivativeData()
One has to check that the derivative has already been calculated;
References data, m_derivative.
void SpectraCo::draw(const char *param="")
Creates a new TH1F to be drawn.
References concatenate, createTH1F, m_name, name, nb_histo_drawn, root_spectra_pointers.
auto& SpectraCo::factor()
References m_factor.
auto const& SpectraCo::factor() const
References m_factor.
Referenced by operator*, operator*=, operator/, rebin.
void SpectraCo::fill(double const &X) noexcept
Fills a bin of the spectra based on the X value.
Has not been tested Todotest it
SpectraPoints const & SpectraCo::findPeaks(int const &threshold, int const &nb_bins_below_threshold)
Uses the second derivative spectra to get the peaks.
threshold nb_bins_below_threshold SpectraPoints: a vector<pair<int, double>> with the keys the bin and the values the height of the second derivative peak
References data, error, goingAbove, goingBelow, m_derivative2, m_peaks, minimum_in_range.
Referenced by findPeaks.
SpectraPoints const & SpectraCo::findPeaks(int const &threshold, int const &nb_bins_below_threshold, int const &smooth)
The spectra must not have had background substraction yet.
References derivate2, findPeaks, removeBackground.
int SpectraCo::firstBinWithValue() const noexcept
References m_size, m_spectra.
auto& SpectraCo::get()
References m_spectra.
auto const& SpectraCo::get() const
References m_spectra.
auto const& SpectraCo::get(int const &bin) const noexcept
References m_spectra.
double SpectraCo::getBin(double const &x) const
References int_cast, m_intercept, m_slope.
Referenced by operator-.
double SpectraCo::getX(double const &bin)
References m_max_x, m_size.
Referenced by operator-.
auto& SpectraCo::integral()
References m_integral.
auto const& SpectraCo::integral() const
References m_integral.
Referenced by operator<<.
double SpectraCo::integralInRange(double const &value_min, double const &value_max) noexcept
double SpectraCo::integralInRangeBin(int const &bin_min, int const &bin_max) noexcept
double SpectraCo::interpolate(double const &bin) const noexcept
Referenced by calibrate, operator[], recalibrate.
void SpectraCo::inverse()
Inverses the spectra : negative values become positive and positive values become negative.
Do not touch the derivatives
References m_spectra.
auto& SpectraCo::lastBin()
References m_spectra.
auto const& SpectraCo::lastBin() const
References m_spectra.
int SpectraCo::lastBinWithValue() const noexcept
References m_size, m_spectra.
Referenced by setActualRange.
void SpectraCo::load(TH1 *root_spectra)
References calculateCoeff, double_cast, m_integral, m_loaded_TH1, m_max_x, m_min_x, m_name, m_size, m_spectra, m_title, throw_error.
Referenced by operator=, rebin, SpectraCo.
auto& SpectraCo::maxX()
References m_max_x.
auto const& SpectraCo::maxX() const
References m_max_x.
Referenced by resizeX.
double SpectraCo::meanInRange(double const &value_min, double const &value_max) noexcept
References CoBazar::mean.
double SpectraCo::meanInRangeBin(int const &bin_min, int const &bin_max) noexcept
References CoBazar::mean.
auto& SpectraCo::minX()
References m_min_x.
auto const& SpectraCo::minX() const
References m_min_x.
Referenced by resizeX, type_of< SpectraCo >.
auto& SpectraCo::name()
References m_name.
auto const& SpectraCo::name() const
References m_name.
Referenced by derivative, derivative2, draw, name, rebin, SpectraCo, write, writeTH1D.
auto SpectraCo::name(std::string const &name)
References m_name, name.
Referenced by derivative, derivative2, operator+, operator-, operator<<.
SpectraCo SpectraCo::operator*(double const &factor)
Todocan be optimized
References factor, m_factor, m_size.
SpectraCo & SpectraCo::operator*=(double const &factor)
References factor, m_size, m_spectra.
SpectraCo SpectraCo::operator+(SpectraCo const &other) const
References m_size, name, title.
SpectraCo SpectraCo::operator-(SpectraCo const &other) const
References getBin, getX, m_size, name, title.
SpectraCo SpectraCo::operator/(double const &factor)
Todocan be optimized
References error, factor, m_factor, m_size.
SpectraCo& SpectraCo::operator=(SpectraCo const &other)
References calculateCoeff, m_integral, m_loaded_TH1, m_max_x, m_min_x, m_name, m_size, m_spectra, m_title.
SpectraCo& SpectraCo::operator=(TH1 *root_spectra)
References load.
double SpectraCo::operator[](double const &bin) const noexcept
References interpolate.
double SpectraCo::operator[](double const &bin) noexcept
References interpolate.
auto const& SpectraCo::operator[](int const &bin) const noexcept
References m_spectra.
auto& SpectraCo::operator[](int const &bin) noexcept
References m_spectra.
auto& SpectraCo::peaks()
References m_peaks.
auto const& SpectraCo::peaks() const
References m_peaks.
Referenced by operator<<.
void SpectraCo::rebin(int const &factor, bool const &rebin_derivatives=false)
TODO.
Uses the TH1::Rebin method;. Todocreate a custom method without the use of ROOT (attempt commented at the bottom of the file)
References concatenate, createTH1F, factor, load, m_derivative, m_rebin, name, rebin.
Referenced by rebin.
void SpectraCo::recalibrate(Recalibration const &recal)
References Recalibration::calculate, calculateCoeff, interpolate, m_derivative, m_size, m_spectra, recalibrate.
Referenced by recalibrate, SpectraCo.
void SpectraCo::removeBackground(int const &smooth, std::string const &fit_options="") noexcept
TodoTry to adapt not to have to use root for this function smooth fit_options
References CoAnalyse::removeBackground.
Referenced by findPeaks.
void SpectraCo::resizeBin(size_t const &new_size)
Resize allows one to select the number of bins. Affects only the maximum bin.
References calculateCoeff, double_cast, m_derivative, m_integral, m_max_x, m_size, m_spectra, resizeBin, sum.
Referenced by resizeBin, setActualRange.
void SpectraCo::resizeX(double const &maxX)
References maxX, print.
void SpectraCo::resizeX(double const &minX, double const &maxX)
Carefull, this resize leads to a copy of the data.
minX maxX
References maxX, minX, print.
void SpectraCo::setActualRange()
Remove the bins after the last bin with content (= detector's output max range)
References lastBinWithValue, resizeBin.
void SpectraCo::setMaxX(double const &_max_x)
References calculateCoeff, m_max_x.
void SpectraCo::setMinX(double const &_min_x)
References calculateCoeff, m_min_x.
void SpectraCo::setRangeX(double const &_min_x, double const &_max_x)
References calculateCoeff, m_max_x, m_min_x.
auto& SpectraCo::size()
References m_size.
auto const& SpectraCo::size() const
References m_size.
Referenced by chi2, ObjectiveFunctionChi2::evaluate, SpectraCo.
SpectraCo::SpectraCo() noexcept=default
SpectraCo::SpectraCo(size_t const &size)
References m_spectra, size.
SpectraCo::SpectraCo(SpectraCo *other, Calibration const &cal, Label const &label)
References calibrate.
SpectraCo::SpectraCo(SpectraCo *other, Recalibration const &recal)
References calculateCoeff, recalibrate.
SpectraCo::SpectraCo(SpectraCo *other, std::string name="", std::string title="")
References calculateCoeff, m_name, m_title, name, title.
SpectraCo::SpectraCo(SpectraCo const &other, Calibration const &cal, Label const &label)
References calculateCoeff, calibrate.
SpectraCo::SpectraCo(SpectraCo const &other, Recalibration const &recal)
References calculateCoeff, recalibrate.
SpectraCo::SpectraCo(SpectraCo const &other, std::string name="", std::string title="")
References calculateCoeff, m_name, m_title, name, title.
SpectraCo::SpectraCo(std::nullptr_t) noexcept
References m_integral, m_max_x, m_min_x, m_name, m_size, m_title.
SpectraCo::SpectraCo(std::vector< double > const &_data)
References calculateCoeff.
SpectraCo::SpectraCo(std::vector< double > const &spectra, float const &min_value=0, float const &max_value=0, std::string name="", std::string title="")
References calculateCoeff.
SpectraCo::SpectraCo(std::vector< float > const &spectra, float const &min_value=0, float const &max_value=0, std::string name="", std::string title="")
References calculateCoeff, double_cast, m_size, m_spectra.
SpectraCo::SpectraCo(TH1 *root_spectra, std::string name="", std::string title="")
References load, m_name, m_title, name, title.
auto& SpectraCo::title()
References m_title.
auto const& SpectraCo::title() const
References m_title.
Referenced by SpectraCo, title.
auto SpectraCo::title(std::string const &title)
References m_title, title.
Referenced by operator+, operator-.
void SpectraCo::write()
References createTH1F, name.
void SpectraCo::write(TDirectory *directory)
References createTH1F, name.
void SpectraCo::writeTH1D()
References createTH1D, name.
void SpectraCo::writeTH1D(TDirectory *directory)
References createTH1D, name.
SpectraCo::~SpectraCo() noexcept
Todo
References m_derivative.
void SpectraCo::calculateCoeff()
References m_intercept, m_max_x, m_min_x, m_size, m_slope.
Referenced by calibrate, calibrateX, load, operator=, recalibrate, resizeBin, setMaxX, setMinX, setRangeX, SpectraCo.