Timewalk
bool Timewalk::isON
Referenced by get, loadFile.
float Timewalk::m_float_zero
Referenced by get.
float Timewalk::m_keVperBin
Referenced by get, loadFile, Print.
std::vector<float> Timewalk::m_Timewalk
Referenced by get, loadFile, operator[], Print, resize.
float Timewalk::max
Referenced by get, getMax, loadFile, resize, setMax.
float const & Timewalk::get(float const &nrj)
References isON, m_float_zero, m_keVperBin, m_Timewalk, max.
void Timewalk::loadFile(std::string const &filename)
References isON, m_keVperBin, m_Timewalk, max, print, rmPathAndExt, Timewalk.
Referenced by Timewalk.
auto& Timewalk::operator[](int const &i)
References m_Timewalk.
void Timewalk::Print()
References m_keVperBin, m_Timewalk, print.
void Timewalk::resize()
References m_Timewalk, max.
void Timewalk::resize(size_t const &size, float const &value=0.)
References m_Timewalk.
Timewalk::Timewalk()
Referenced by loadFile.
Timewalk::Timewalk(std::string const &filename)
References loadFile.
static float const& Timewalk::getMax()
References max.
static void Timewalk::setMax(float const &_max)
References max.
Referenced by Timewalks::setMax.