Vertice
std::vector<double> Vertice::m_coordinates
Referenced by begin, cleanMove, copy, end, fill, get, operator*=, operator+, operator-, operator[], resize, set.
size_t Vertice::m_dim
Referenced by cleanMove, copy, operator+, operator-, resize, set, size.
double Vertice::m_value
Referenced by cleanMove, copy, evaluate, getValue, operator<, operator<=, operator>, operator>=, set, setValue.
auto Vertice::begin()
References m_coordinates.
auto Vertice::begin() const
References m_coordinates.
void Vertice::cleanMove(Vertice &_vertice)
References m_coordinates, m_dim, m_value.
Referenced by copy, set.
void Vertice::copy(std::vector< double > const &point)
References m_coordinates, m_dim, m_value, throw_error.
void Vertice::copy(Vertice &&other)
References cleanMove, m_coordinates, m_dim, m_value, throw_error.
void Vertice::copy(Vertice const &other)
References m_coordinates, m_dim, m_value, throw_error.
Referenced by Minimisator::nelderMead.
auto Vertice::end()
References m_coordinates.
auto Vertice::end() const
References m_coordinates.
auto const& Vertice::evaluate(std::function< double(const Vertice &)> objective_function)
References m_value.
Referenced by Minimisator::nelderMead.
void Vertice::fill(double const &value)
References m_coordinates.
Referenced by resize.
auto& Vertice::get()
References m_coordinates.
auto const& Vertice::get() const
References m_coordinates.
Referenced by operator*, operator*, operator<<.
auto& Vertice::get(int const &coordinate_i)
References m_coordinates.
auto const& Vertice::get(int const &coordinate_i) const
References m_coordinates.
auto Vertice::getValue()
References m_value.
auto const& Vertice::getValue() const
References m_value.
Referenced by operator<<.
Vertice Vertice::operator*(double const &constant) const
References get.
Vertice Vertice::operator*(Vertice const &other) const
References get, throw_error.
Vertice& Vertice::operator*=(double const &constant)
References m_coordinates.
Vertice Vertice::operator+(Vertice const &other) const
References m_coordinates, m_dim, size, throw_error, Vertice.
Vertice Vertice::operator-(Vertice const &other) const
References m_coordinates, m_dim, size, throw_error, Vertice.
bool Vertice::operator<(Vertice const &other) const
References m_value.
bool Vertice::operator<=(Vertice const &other) const
References m_value.
Vertice& Vertice::operator=(std::vector< double > const &point)
References set.
Vertice& Vertice::operator=(Vertice &&vertice)
References set.
Vertice& Vertice::operator=(Vertice const &vertice)
References set.
bool Vertice::operator>(Vertice const &other) const
References m_value.
bool Vertice::operator>=(Vertice const &other) const
References m_value.
auto& Vertice::operator[](int const &i)
References m_coordinates.
auto const& Vertice::operator[](int const &i) const
References m_coordinates.
void Vertice::resize(size_t const &size)
References m_coordinates, m_dim, size.
Referenced by resize.
void Vertice::resize(size_t const &size, double const &value)
References fill, resize.
void Vertice::set(int const &coordinate_i, double const &coordinate)
References m_coordinates.
void Vertice::set(std::vector< double > const &point)
References m_coordinates, m_dim, m_value.
void Vertice::set(Vertice &&other)
References cleanMove, m_coordinates, m_dim, m_value.
void Vertice::set(Vertice const &other)
References m_coordinates, m_dim, m_value.
Referenced by Minimisator::nelderMead, operator=.
void Vertice::setValue(double const &_value)
References m_value.
auto& Vertice::size()
References m_dim.
Referenced by Simplex::centroid, operator+, operator-, resize, Minimisator::setInitialGuess, Simplex::Simplex.
auto const& Vertice::size() const
References m_dim.
Vertice::Vertice()=default
Referenced by operator+, operator-.
Vertice::Vertice(size_t size)
Vertice::Vertice(std::Initialiser_list< double > const &init_list)
Vertice::Vertice(std::vector< double > const &coords)
Vertice::Vertice(Vertice &&_vertice)
Vertice::Vertice(Vertice const &_vertice)