MTVector
std::vector<T> MTVector< T >::m_collection
Referenced by MTVector< T >::begin, MTVector< T >::clear, MTVector< T >::end, MTVector< T >::get, MTVector< std::string >::operator std::vector< std::string >, MTVector< T >::operator[], MTVector< T >::Print, MTVector< T >::push_back, MTVector< T >::resize, MTVector< T >::set.
std::mutex MTVector< T >::m_mutex
Referenced by MTVector< T >::operator=, MTVector< T >::Print, MTVector< T >::resize, MTVector< T >::set.
size_t MTVector< T >::m_read_index
Referenced by MTVector< T >::getIndex, MTVector< T >::resetRead.
size_t MTVector< T >::m_size
Referenced by MTVector< T >::push_back, MTVector< T >::resize, MTVector< T >::set, MTVector< T >::size.
auto MTVector< T >::begin()
References MTVector< T >::m_collection.
void MTVector< T >::clear()
References MTVector< T >::m_collection.
Referenced by MTVector< T >::operator=.
auto MTVector< T >::end()
References MTVector< T >::m_collection.
std::vector<T> const& MTVector< T >::get() const
References MTVector< T >::m_collection.
Referenced by operator<<.
auto& MTVector< T >::getIndex()
References MTVector< T >::m_read_index.
bool MTVector< T >::getNext(T &t)
Referenced by Manip::getNext, Calibrator::loadRootDataThread, MTFasterReader::nextFilename, MTRootReader::nextFilename, Timeshifts::treatFilesMT.
bool MTVector< T >::getNext(T &t, size_t &index)
MTVector< T >::MTVector()=default
MTVector< T >::MTVector(std::vector< T > const &collection)
MTVector< T >::operator std::vector< T >() &
void MTVector< T >::operator=(std::vector< T > const &collection)
References MTVector< T >::set.
MTVector& MTVector< T >::operator=(T const &t)
References MTVector< T >::clear, MTVector< T >::m_mutex, MTVector< T >::push_back.
T const& MTVector< T >::operator[](size_t const &i)
References MTVector< T >::m_collection.
void MTVector< T >::Print()
References MTVector< T >::m_collection, MTVector< T >::m_mutex, print.
void MTVector< T >::push_back(T const &t)
References MTVector< T >::m_collection, MTVector< T >::m_size.
Referenced by Manip::addFolder, MTVector< T >::operator=.
void MTVector< T >::resetRead()
References MTVector< T >::m_read_index.
Referenced by MTVector< T >::resize, MTVector< T >::set.
void MTVector< T >::resize(size_t const &i=0)
References MTVector< T >::m_collection, MTVector< T >::m_mutex, MTVector< T >::m_size, MTVector< T >::resetRead.
void MTVector< T >::set(std::vector< T > const &collection)
References MTVector< T >::m_collection, MTVector< T >::m_mutex, MTVector< T >::m_size, MTVector< T >::resetRead.
Referenced by MTVector< T >::operator=.
size_t const& MTVector< T >::size() const
References MTVector< T >::m_size.