MySimpleConvertor
void Faster2Root::buildEvents(int time_window_ns)
References Faster2Root::m_eventbuilding, Faster2Root::m_time_window, print.
Referenced by Faster2Root::Faster2Root, Faster2Root::load.
void Faster2Root::convert(std::string const &dataFolder, std::string const &outputFolder, int const &nb_files=-1)
References Faster2Root::dispatch_threads, Faster2Root::m_nb_files, print, MTFasterReader::readRaw.
Referenced by Faster2Root::Faster2Root, Faster2Root::load.
void MySimpleConvertor::convertFile(Hit &hit, FasterReader &reader, Path const &outPath) override
hit reader outPath
References FasterReader::Read, Hit::writting.
void Faster2Root::loadCalibration(std::string const &calibFile)
References Calibration::load, Faster2Root::m_calibration.
Referenced by Faster2Root::load.
void Faster2Root::loadTimeshifts(std::string const &dTfile)
References Timeshifts::load, Faster2Root::m_timeshifts.
Referenced by Faster2Root::load.
void Faster2Root::loadTriggerFile(std::string const &file)
Loads a trigger file.
A trigger file contains a list of the detectors's labels (the number, not the name) that are required in the event (e.g. a germanium trigger file would list all the labels of the germaniums). If you want more specific trigger you have to create your own executable, include Faster2Root and follow the example 2 of the documentation of the class.
References found, Event::labels, Faster2Root::m_loaded_trigger, Faster2Root::m_trigger_file, Faster2Root::m_triggering_labels, Faster2Root::setTrigger.
Referenced by Faster2Root::load.
MySimpleConvertor::MySimpleConvertor(ARGS &&... args)
void Faster2Root::overwrite(bool const &_overwrite)
References Faster2Root::m_overwrite.
Referenced by Faster2Root::load.
void Faster2Root::setCalibration(Calibration const &calibration)
References Faster2Root::m_calibration.
void Faster2Root::setNbFiles(int const &nb_files=-1)
References Faster2Root::m_nb_files.
Referenced by Faster2Root::Faster2Root, Faster2Root::load.
void Faster2Root::setNbThreads(int const &nb_threads=-1)
References Faster2Root::m_nb_threads.
Referenced by Faster2Root::load.
void Faster2Root::setTimeshifts(Timeshifts const &timeshifts)
References Faster2Root::m_timeshifts.
void Faster2Root::setTrigger(TriggerEvent other)
References Faster2Root::m_trigger, Faster2Root::m_use_trigger.
Referenced by Faster2Root::Faster2Root, Faster2Root::loadTriggerFile.
void Faster2Root::throwSingles(bool const &_throw_single=true)
References Faster2Root::m_throw_single.
bool Faster2Root::m_calibrate
Calibration Faster2Root::m_calibration
Referenced by Faster2Root::convertFile, Faster2Root::loadCalibration, Faster2Root::setCalibration.
bool Faster2Root::m_eventbuilding
Referenced by Faster2Root::buildEvents, Faster2Root::convertFile, Faster2Root::load.
bool Faster2Root::m_loaded_trigger
Referenced by Faster2Root::convertFile, Faster2Root::loadTriggerFile.
int Faster2Root::m_nb_files
Referenced by Faster2Root::convert, Faster2Root::setNbFiles.
int Faster2Root::m_nb_threads
Referenced by Faster2Root::load, Faster2Root::setNbThreads.
bool Faster2Root::m_ok
Referenced by Faster2Root::Faster2Root.
bool Faster2Root::m_overwrite
Referenced by Faster2Root::convertFile, Faster2Root::overwrite.
bool Faster2Root::m_throw_single
Referenced by Faster2Root::convertFile, Faster2Root::load, Faster2Root::throwSingles.
Long64_t Faster2Root::m_time_window
Referenced by Faster2Root::buildEvents, Faster2Root::convertFile.
Timeshifts Faster2Root::m_timeshifts
Referenced by Faster2Root::convertFile, Faster2Root::load, Faster2Root::loadTimeshifts, Faster2Root::setTimeshifts.
MTCounter Faster2Root::m_total_events
Referenced by Faster2Root::convertFile, Faster2Root::load.
MTCounter Faster2Root::m_total_hits
Referenced by Faster2Root::convertFile, Faster2Root::load.
Timer Faster2Root::m_total_timer
Referenced by Faster2Root::load.
MTCounter Faster2Root::m_trigg_events
Referenced by Faster2Root::convertFile.
TriggerEvent Faster2Root::m_trigger
Referenced by Faster2Root::convertFile, Faster2Root::setTrigger.
std::string Faster2Root::m_trigger_file
Referenced by Faster2Root::convertFile, Faster2Root::loadTriggerFile.
std::vector<Label> Faster2Root::m_triggering_labels
Referenced by Faster2Root::loadTriggerFile.
bool Faster2Root::m_use_RF
Referenced by Faster2Root::load.
bool Faster2Root::m_use_trigger
Referenced by Faster2Root::convertFile, Faster2Root::load, Faster2Root::setTrigger.
void Faster2Root::load(int argc, char **argv)
References Faster2Root::buildEvents, Faster2Root::convert, detectors, error_message, MTObject::Initialise, Detectors::load, Faster2Root::loadCalibration, Faster2Root::loadTimeshifts, Faster2Root::loadTriggerFile, Faster2Root::m_eventbuilding, Faster2Root::m_nb_threads, Faster2Root::m_throw_single, Faster2Root::m_timeshifts, Faster2Root::m_total_events, Faster2Root::m_total_hits, Faster2Root::m_total_timer, Faster2Root::m_use_RF, Faster2Root::m_use_trigger, Faster2Root::overwrite, print, Faster2Root::printParameters, FasterReader::setMaxHits, Faster2Root::setNbFiles, Faster2Root::setNbThreads, Path::string, throw_error, Timer::TimeSec.
Referenced by Faster2Root::Faster2Root.
void Faster2Root::printParameters() const
References print.
Referenced by Faster2Root::load.
static void Faster2Root::dispatch_threads(Hit &hit, FasterReader &reader, Faster2Root &convertor, Path const &outPath)
Dispatch the Faster2Root::convertFile() method through the threads.
References Faster2Root::convertFile.
Referenced by Faster2Root::convert.