Faster2Histo
std::unordered_map<Label, MTTHist<TH2F> > Faster2Histo::m_bidim
Referenced by fillHisto.
bool Faster2Histo::m_bidim_paris
Referenced by fillHisto, load.
double Faster2Histo::m_bin_max
Referenced by fillHisto, load.
double Faster2Histo::m_bin_max_paris
Referenced by fillHisto, load.
Calibration Faster2Histo::m_calibration
Referenced by fillHisto, loadCalibration, treatFile.
FilesManager Faster2Histo::m_files
Referenced by addFile, addFolder, load, multirun.
std::vector<Label> Faster2Histo::m_labels
Referenced by fillHisto.
int Faster2Histo::m_maximum_hits
Referenced by load.
MTFasterReader Faster2Histo::m_MTreader
Referenced by multirun.
int Faster2Histo::m_nb_bins
Referenced by fillHisto, load.
int Faster2Histo::m_nb_bins_paris
Referenced by fillHisto, load.
int Faster2Histo::m_nb_files
Referenced by setNbFiles.
File Faster2Histo::m_outFile
Referenced by addFolder, load, setOutFilename.
Path Faster2Histo::m_outPath
Referenced by setOutPath.
int Faster2Histo::m_overwrite
Referenced by load, overwrite.
std::unordered_map<Label, MTTHist<TH1F> > Faster2Histo::m_spectra
Referenced by fillHisto.
Timeshifts Faster2Histo::m_timeshifts
Referenced by loadTimeshifts.
TriggerHit Faster2Histo::m_trigger
Referenced by setTrigger.
const char* Faster2Histo::write_mode
Referenced by setWriteMode.
void Faster2Histo::addFile(std::string const &file)
Adds one file to convert at the list. Option -f.
References FilesManager::addFile, m_files, rmPathAndExt, setOutFilename.
Referenced by load.
void Faster2Histo::addFolder(Path folder, int const &nb_files=-1)
Adds [nb_files] files to convert inside of [folder].
References FilesManager::addFolder, m_files, m_outFile, rmPathAndExt, setOutFilename, Path::string.
Referenced by load.
Faster2Histo::Faster2Histo()
Faster2Histo::Faster2Histo(int argc, char **argv)
To launch the application at instanciation.
References load, multirun, write.
void Faster2Histo::fillHisto(Hit const &hit)
Handles each hit and fills the correct histogram.
References Hit::adc, detectors, error, found, int_cast, Hit::label, m_bidim, m_bidim_paris, m_bin_max, m_bin_max_paris, m_calibration, m_labels, m_nb_bins, m_nb_bins_paris, m_spectra, MTObject::mutex, Hit::nrj, Hit::nrj2, Hit::qdc2.
Referenced by treatFile.
void Faster2Histo::load(int const &argc, char **argv)
To launch the application after instanciation.
References addFile, addFolder, detectors, Detectors::load, loadCalibration, loadTimeshifts, m_bidim_paris, m_bin_max, m_bin_max_paris, m_files, m_maximum_hits, m_nb_bins, m_nb_bins_paris, m_outFile, m_overwrite, overwrite, print, printParameters, FasterReader::setMaxHits, setNbThreads, setOutFilename, setOutPath, FilesManager::size, File::string, throw_error.
Referenced by Faster2Histo.
void Faster2Histo::loadCalibration(std::string const &calibration_file)
Loads the .calib file needed. Option -c.
References Calibration::load, m_calibration.
Referenced by load.
void Faster2Histo::loadTimeshifts(Timeshifts const &timeshifts)
Loads the .dT file needed. Option -t.
References m_timeshifts.
Referenced by load.
void Faster2Histo::multirun(int const &nb_threads=-1)
Setup the threads and launched the application.
References dispatch_threads, MTFasterReader::files, MTObject::Initialise, m_files, m_MTreader, MTFasterReader::readRaw.
Referenced by Faster2Histo.
void Faster2Histo::overwrite(bool const &_overwrite) noexcept
Allows to overwrite the output file if it exists. Option -o.
References m_overwrite.
Referenced by load.
void Faster2Histo::setNbFiles(int const &_nb_files) noexcept
Set the number of files to read in the folder. Second argument of option -F.
References m_nb_files.
void Faster2Histo::setNbThreads(int const &_nb_threads) noexcept
Set the number of threads to write down. Option -m.
References MTObject::setThreadsNb.
Referenced by load.
void Faster2Histo::setOutFilename(std::string const &out_filename) noexcept
Set the name of the output file.
References m_outFile.
Referenced by addFile, addFolder, load.
void Faster2Histo::setOutPath(Path const &path) noexcept
Set the full output path. Option out_path.
References m_outPath, Path::make.
Referenced by load.
void Faster2Histo::setTrigger(TriggerHit trigger)
TodoUNUSED until event building is done
References m_trigger.
void Faster2Histo::setWriteMode(const char *mode) noexcept
Interface with the ROOT write mode. Default = "RECREATE".
If you want to use "APPEND" for instance, you have to use the overwrite option (-o)
References write_mode.
void Faster2Histo::treatFile(Hit &hit, FasterReader &reader)
Treats the file with already configured Hit and FasterReader object.
References fillHisto, FasterReader::getFilename, m_calibration, print, FasterReader::Read, File::size, Timer::TimeSec, Timer::unit.
void Faster2Histo::write(std::string const &out_filename="") noexcept
Write down a [out_filename].root file containing the spectra of the data.
References bubble_sort, File::c_str, File::makePath, File::path, print, File::setExtension.
Referenced by Faster2Histo.
void Faster2Histo::printParameters() const noexcept
References print.
Referenced by load.
static void Faster2Histo::dispatch_threads(Hit &hit, FasterReader &reader, Faster2Histo &f2h)
Referenced by multirun.