Recalibration
std::vector<double> Recalibration::m_parameters
Referenced by a0, a1, a2, a3, aSqrt, getParameter, operator[], Recalibration, setParameter.
auto& Recalibration::a0()
References m_parameters.
auto const& Recalibration::a0() const
References m_parameters.
Referenced by a0, calculate, operator<<.
auto& Recalibration::a0(double const &a0)
References a0, m_parameters.
auto& Recalibration::a1()
References m_parameters.
auto const& Recalibration::a1() const
References m_parameters.
Referenced by a1, calculate, operator<<.
auto& Recalibration::a1(double const &a1)
References a1, m_parameters.
auto& Recalibration::a2()
References m_parameters.
auto const& Recalibration::a2() const
References m_parameters.
Referenced by a2, calculate, operator<<.
auto& Recalibration::a2(double const &a2)
References a2, m_parameters.
auto& Recalibration::a3()
References m_parameters.
auto const& Recalibration::a3() const
References m_parameters.
Referenced by a3, operator<<.
auto& Recalibration::a3(double const &a3)
References a3, m_parameters.
auto& Recalibration::aSqrt()
References m_parameters.
auto const& Recalibration::aSqrt() const
References m_parameters.
Referenced by aSqrt, operator<<.
auto& Recalibration::aSqrt(double const &aSqrt)
References aSqrt, m_parameters.
double Recalibration::calculate(double const &x)
References a0, a1, a2.
double Recalibration::calculate(double const &x) const
References a0, a1, a2.
Referenced by Minimisator::chi2, operator(), SpectraCo::recalibrate.
auto& Recalibration::getParameter(int const &i)
References m_parameters.
auto const& Recalibration::getParameter(int const &i) const
References m_parameters.
double Recalibration::operator()(double const &x)
References calculate.
double Recalibration::operator()(double const &x) const
References calculate.
auto& Recalibration::operator[](int const &i)
References m_parameters.
auto const& Recalibration::operator[](int const &i) const
References m_parameters.
Recalibration::Recalibration(double const &_a0=0, double const &_a1=1, double const &_a2=0, double const &_a3=0, double const &_aSqrt=0)
Recalibration::Recalibration(Recalibration const &other)
References m_parameters.
auto& Recalibration::setParameter(int const &i, double const &a)
References m_parameters.
Referenced by Minimisator::chi2.
auto& Recalibration::setParameter(size_t const &i, double const &a)
References m_parameters.