File
bool File::check_verif
Referenced by check, checkMode.
std::string File::m_file
Referenced by c_str, check, exists, get, operator std::string, operator=, operator==, size, string, update.
Filename File::m_filename
Referenced by extension, filename, fill, name, operator=, setExtension, shortName, update.
bool File::m_ok
Referenced by check, ok, operator bool, operator=.
Path File::m_path
Referenced by check, fill, folder, makePath, operator=, path, update.
auto File::c_str()
References m_file.
Referenced by Faster2Root::convertFile, EvolutionPeaks::run, CobaltCalorimeter::write, Faster2Histo::write, CloverSpectra::writeHisto.
auto File::c_str() const
References m_file.
void File::checkMode(std::string const &mode)
References check_verif.
Referenced by File.
bool File::exists() const
References file_exists, m_file.
Referenced by Faster2Root::convertFile, ParisBidimAngles::load, EvolutionPeaks::run, ParisBidimAngles::write.
std::string const& File::extension() const
References Filename::extension, m_filename.
File::File()
File::File(const char *file, std::string const &mode="")
References check, checkMode, fill.
File::File(File const &file)
File::File(Path const &path, Filename const &filename, std::string const &mode="")
References check, checkMode, update.
File::File(std::string const &file, std::string const &mode="")
References check, checkMode, fill.
Filename& File::filename()
Filename stands for the file name without the path but with the extension.
References m_filename.
Filename const& File::filename() const
Filename stands for the file name without the path but with the extension.
References m_filename.
Folder const& File::folder() const
References Path::folder, m_path.
std::string const& File::get() const
References m_file.
Referenced by operator<<.
void File::makePath()
References m_path, Path::make.
Referenced by ParisBidimAngles::write, Faster2Histo::write, Calibration::write, Calibrator::writeData, Calibrator::writePosPeaks.
Filename const& File::name() const
References m_filename.
bool const& File::ok()
References m_ok.
File::operator bool() const &
References m_ok.
File::operator std::string() const &
References m_file.
File& File::operator=(const char *file)
References check, fill.
File& File::operator=(File const &file)
References m_file, m_filename, m_ok, m_path.
File& File::operator=(std::string const &file)
References check, fill.
bool File::operator==(File const &other) const
References m_file.
Path const& File::path() const
References m_path.
Referenced by Faster2Histo::write.
void File::setExtension(std::string const &new_extension)
References m_filename, Filename::setExtension, update.
Referenced by ParisBidimAngles::load, CobaltCalorimeter::write, ParisBidimAngles::write, Faster2Histo::write, Calibration::write, Timeshifts::writeData, Calibrator::writeData, Calibrator::writePosPeaks.
std::string const& File::shortName() const
Short name stands for the file name withpout the path nor the extension.
References m_filename, Filename::shortName.
Referenced by Faster2Root::convertFile.
auto File::size(std::string const &unit="o") const
References m_file, size_file.
Referenced by Faster2Histo::treatFile.
std::string const& File::string() const
References m_file.
Referenced by MTFasterReader::addFile, Faster2Histo::load, ParisBidimAngles::load, ParisBidimAngles::write, Calibration::write.
void File::check()
References check_verif, Path::exists, file_exists, m_file, m_ok, m_path, print.
Referenced by File, operator=, update.
void File::fill(std::string const &file)
References getPath, hasPath, m_filename, m_path, Path::pwd, removePath, update.
Referenced by File, operator=.
void File::update()
References check, m_file, m_filename, m_path, Path::string, Filename::string.
Referenced by File, fill, setExtension.