PeakFitter
TF1* PeakFitter::final_fit
Referenced by fit, getBackground, getConstante, getFit, getMean, getSigma, operator->.
double PeakFitter::m_high_edge
Referenced by fit.
TH1* PeakFitter::m_histo
Referenced by fit.
bool PeakFitter::m_low_binning
Referenced by BiggestPeakFitter::BiggestPeakFitter, fit.
double PeakFitter::m_low_edge
Referenced by fit.
double PeakFitter::m_order_background
Referenced by fit, setBackgroundOrder.
void PeakFitter::fit()
Allows one to fit a peak of a histogram in the range [low_edge, high_edge].
References fit, m_high_edge, m_histo, m_low_edge.
Referenced by BiggestPeakFitter::BiggestPeakFitter, fit, PeakFitter.
void PeakFitter::fit(TH1 *histo, double low_edge, double high_edge, double mean=-1, double sigma=-1, double constante=-1)
Allows one to fit a peak of a histogram in the range [low_edge, high_edge].
References final_fit, m_low_binning, m_order_background, CoBazar::mean.
auto PeakFitter::getBackground() const
References final_fit.
Referenced by CobaltCalorimeter::Analyse.
auto PeakFitter::getConstante() const
References final_fit.
Referenced by AnalysedSpectra::fitPeak, AnalysedSpectra::fitPeaks.
auto const& PeakFitter::getFit() const
References final_fit.
auto PeakFitter::getMean() const
References final_fit.
Referenced by CobaltCalorimeter::Analyse, Timeshifts::analyse, Paris::findAngles, AnalysedSpectra::fitPeak, AnalysedSpectra::fitPeaks.
auto PeakFitter::getSigma() const
References final_fit.
Referenced by AnalysedSpectra::fitPeak, AnalysedSpectra::fitPeaks.
auto PeakFitter::operator->()
References final_fit.
PeakFitter::PeakFitter()=default
PeakFitter::PeakFitter(TH1 *histo, double low_edge, double high_edge)
References fit.
auto PeakFitter::setBackgroundOrder(int const &order_background)
References m_order_background.
Referenced by BiggestPeakFitter::BiggestPeakFitter.
PeakFitter::~PeakFitter()