Path
bool Path::m_exists
Referenced by exists, loadPath, make.
std::string Path::m_path
Referenced by addFolder, c_str, cleanPath, get, loadPath, make, makeFolderList, nbFiles, operator bool, operator+, operator+=, operator=, operator==, path.
Folders Path::m_recursive_folders
Referenced by addFolder, cleanPath, folder, getFolders, loadPath, makeFolderList, operator[], size.
Path& Path::addFolder(Folder const &folder)
References file_exists, folder, Folder::get, m_path, m_recursive_folders, Folder::name, Folders::push_back.
auto Path::c_str()
References m_path.
bool Path::exists()
References m_exists.
Referenced by File::check, EvolutionPeaks::run.
Folder const& Path::folder() const
References Folders::get, m_recursive_folders.
Referenced by addFolder, cleanPath, File::folder, operator+, RunMatrixator::Write.
std::string const& Path::get() const
References m_path.
Referenced by operator+, string.
Folders const& Path::getFolders() const
References m_recursive_folders.
bool Path::make()
References create_folder_if_none, m_exists, m_path.
Referenced by loadPath, File::makePath, Faster2Histo::setOutPath.
void Path::makeFolderList()
References getList, m_path, m_recursive_folders.
Referenced by loadPath.
int Path::nbFiles()
References m_path, nb_files_in_folder.
Path::operator bool() const
References folder_exists, m_path.
std::string Path::operator+(const char *addString)
References m_path.
Path Path::operator+(Folder const &folder)
References folder, Folder::get, m_path, Path.
std::string Path::operator+(std::string const &addString)
References m_path.
Path& Path::operator+=(std::string const &addString)
References m_path, push_back_if_none.
Path& Path::operator=(const char *path)
References loadPath, m_path, path.
Path& Path::operator=(Path &path)
References loadPath, m_path, path.
Path& Path::operator=(Path const &path)
References loadPath, m_path, path.
Path& Path::operator=(std::string const &inputString)
References loadPath, m_path.
bool Path::operator==(std::string const &cmprStr)
References m_path.
Folder const& Path::operator[](uint const &i) const
References m_recursive_folders.
Path::Path()
Referenced by home, operator+, pwd.
std::string const& Path::path() const
References m_path.
Referenced by operator<<, operator=.
Path::Path(const char *c_str, bool const &create=false)
Turns a C string to a path, creating it if create = true and it doesn't already exists.
References loadPath.
Path::Path(Path const &path)
Path::Path(std::string const &path, bool const &create=false)
Turns a string to a path, creating it if create = true and it doesn't already exists.
References loadPath.
auto Path::size() const
References m_recursive_folders, Folders::size.
std::string const& Path::string() const
References get.
Referenced by Faster2Histo::addFolder, Faster2Root::Faster2Root, FilesManager::FilesManager, CloverSpectra::fillHisto, Faster2Root::load, File::update.
static Path Path::home()
References Path.
Referenced by loadPath.
static Path Path::pwd()
References Path.
Referenced by File::fill, loadPath.
void Path::cleanPath()
To remove extraneous ./ or ../.
References Folders::erase, folder, m_path, m_recursive_folders, Folders::size, Folders::string.
Referenced by loadPath.
void Path::loadPath(bool const &create=false)
References cleanPath, Folders::clear, folder_exists, home, m_exists, m_path, m_recursive_folders, make, makeFolderList, print, push_back_if_none, pwd.
Referenced by operator=, Path.