Fit
double Fit::chi2
Referenced by clear, Calibrator::fitCalibration.
std::vector<double> Fit::cmeasures
Referenced by clear, Calibrator::fitCalibration, resize.
std::vector<double> Fit::ex
Referenced by clear, Calibrator::fitCalibration.
std::vector<double> Fit::ey
Referenced by clear, Calibrator::fitCalibration.
double Fit::integral
Referenced by clear.
double Fit::keVperADC
Referenced by clear.
std::vector<double> Fit::mean
Referenced by clear, resize.
std::string Fit::name
Referenced by clear, Calibrator::fitCalibration.
uchar Fit::order
Referenced by clear, Calibrator::fitCalibration.
double Fit::parameter0
Referenced by clear, Calibrator::fitCalibration, operator<<, PeaksCalibrator::PeaksCalibrator.
double Fit::parameter1
Referenced by clear, Calibrator::fitCalibration, operator<<, PeaksCalibrator::PeaksCalibrator.
double Fit::parameter2
Referenced by clear, Calibrator::fitCalibration, operator<<, PeaksCalibrator::PeaksCalibrator.
double Fit::parameter3
Referenced by clear, operator<<.
std::vector<double> Fit::peaks
Referenced by clear, Calibrator::fitCalibration, resize, size.
double Fit::scalefactor
Referenced by clear, Calibrator::fitCalibration.
std::vector<double> Fit::sigma
Referenced by clear, resize.
std::vector<double> Fit::x
Referenced by clear, Calibrator::fitCalibration.
std::vector<double> Fit::y
Referenced by clear, Calibrator::fitCalibration.
bool Fit::m_enough_counts
Referenced by clear, enough_counts, too_few_counts.
bool Fit::m_exist
Referenced by clear, exists.
Label Fit::m_label
Referenced by clear, label, setLabel.
bool Fit::m_peaks_found
Referenced by clear, found_peaks, peaks_found.
void Fit::clear()
References chi2, cmeasures, ex, ey, integral, keVperADC, m_enough_counts, m_exist, m_label, m_peaks_found, mean, name, order, parameter0, parameter1, parameter2, parameter3, peaks, scalefactor, sigma, x, y.
auto Fit::enough_counts() const
Returns true if fit had enough counts.
References m_enough_counts.
auto const& Fit::exists() const
Returns true if fit succeeded.
References m_exist.
Referenced by Calibrator::fitCalibration.
bool const& Fit::exists(bool exist)
Set if the fit succeeded :
References bool_cast, m_exist.
Fit::Fit()
auto Fit::found_peaks() const
Returns true if the fit found the peaks.
References m_peaks_found.
auto const& Fit::label() const
References m_label.
Referenced by operator<<, setLabel.
bool Fit::peaks_found(bool found)
Set if there was not enough counts :
References bool_cast, found, m_peaks_found.
void Fit::resize(int size)
References cmeasures, mean, peaks, sigma, size.
void Fit::setLabel(Label const &label)
Set the label.
References label, m_label.
auto Fit::size() const
Returns the number of peaks used for calibration.
References peaks.
Referenced by resize.
bool Fit::too_few_counts(bool few_counts)
Set if there was not enough counts :
References bool_cast, m_enough_counts.