Clovers
std::array< uchar, Clovers::nb_det > Clovers::cristaux_index
Referenced by Fill, InitialiseArrays.
std::array< uchar, Clovers::nb_det > Clovers::cristaux_index_BGO
Referenced by InitialiseArrays.
Gates Clovers::delayedBGOgate
Gates Clovers::delayedGeGate
float Clovers::Emin
Referenced by FillFast, setEnergyThreshold.
std::array< bool, Clovers::nb_det > Clovers::isBGO
Referenced by InitialiseArrays.
std::array< bool, Clovers::nb_det > Clovers::isClover
Referenced by Fill, FillFast, InitialiseArrays.
std::array< bool, Clovers::nb_det > Clovers::isGe
Referenced by Fill, FillFast, InitialiseArrays.
std::array< uchar, Clovers::nb_det > Clovers::labels
Referenced by Fill, FillFast, InitialiseArrays.
constexpr int Clovers::nb_det
Referenced by InitialiseArrays.
Gate Clovers::promptBGOgate
Gate Clovers::promptGeGate
Referenced by Clovers::PromptGate::operator().
StaticVector<uchar> Clovers::Bgo
Referenced by Analyse, Reset.
StaticVector<uchar> Clovers::BGOonly
Referenced by Analyse, Reset.
StaticVector<uchar> Clovers::CleanGe
Referenced by Analyse, PrintClean, Reset.
StaticVector<uchar> Clovers::cristaux
Referenced by Fill, Reset.
StaticVector<uchar> Clovers::cristaux_BGO
Referenced by Fill, Reset.
std::array<float, 96> Clovers::cristaux_nrj
Referenced by Fill, Reset.
std::array<float, 48> Clovers::cristaux_nrj_BGO
Referenced by Fill, Reset.
std::array<double, 96> Clovers::cristaux_time
Referenced by Fill, Reset.
std::array<double, 48> Clovers::cristaux_time_BGO
Referenced by Fill, Reset.
uchar Clovers::CrystalMult
Referenced by Fill, Reset.
uchar Clovers::CrystalMult_BGO
Referenced by Fill, Reset.
StaticVector<uchar> Clovers::DelayedBGO
Referenced by Reset.
uchar Clovers::DelayedCleanGeMult
Referenced by Reset.
std::vector<uchar> Clovers::delayedClovers
Referenced by CleanFast, FillFast, RunMatrixator::fillMatrixes, SetEvent.
std::vector<CloverModule> Clovers::DelayedClovers
Referenced by CleanFast, Clovers, FillFast, RunMatrixator::fillMatrixes.
class Clovers::DelayedGate Clovers::delayedGate
Referenced by FillFast, isDelayed.
StaticVector<uchar> Clovers::DelayedGe
Referenced by Reset.
uchar Clovers::DelayedMult
Referenced by CleanFast, Reset, SetEvent.
StaticVector<uchar> Clovers::Ge
Referenced by Analyse, Reset, CloverSpectra::runFasterReader.
bool Clovers::has511
Referenced by Reset.
StaticVector<uchar> Clovers::Hits
Referenced by Analyse, Fill, FillFast, mult, operator<<, Reset, size.
std::vector<CloverModule> Clovers::m_clovers
Referenced by Analyse, begin, Clovers, end, Fill, operator[], PrintClean, Reset.
StaticVector<uchar> Clovers::PromptBGO
Referenced by Reset.
uchar Clovers::PromptCleanGeMult
Referenced by Reset.
std::vector<uchar> Clovers::promptClovers
Referenced by CleanFast, FillFast, RunMatrixator::fillMatrixes, SetEvent.
std::vector<CloverModule> Clovers::PromptClovers
Referenced by CleanFast, Clovers, FillFast, RunMatrixator::fillMatrixes.
class Clovers::PromptGate Clovers::promptGate
Referenced by FillFast, isPrompt.
StaticVector<uchar> Clovers::PromptGe
Referenced by Reset.
uchar Clovers::PromptMult
Referenced by CleanFast, Reset, SetEvent.
StaticVector<uchar> Clovers::rawBGO
Referenced by Fill, Reset.
StaticVector<uchar> Clovers::rawGe
Referenced by Fill, Reset.
StaticVector<uchar> Clovers::RejectedGe
Referenced by Analyse, Reset.
uchar Clovers::TotalMult
Referenced by Reset.
double Clovers::totBGO
Referenced by Analyse, Reset.
double Clovers::totBGO_delayed
Referenced by Reset.
double Clovers::totBGO_prompt
Referenced by Reset.
double Clovers::totGe
Referenced by Analyse, Reset.
double Clovers::totGe_delayed
Referenced by Reset.
double Clovers::totGe_prompt
Referenced by Reset.
thread_local bool Clovers::s_initialised
Referenced by InitialiseArrays.
bool Clovers::s_time_ps
Referenced by Fill, FillFast, timePs.
static void Clovers::InitialiseArrays()
Static Initialise. Allows one to use the arrays event if no object has been instantiated.
References cristaux_index, cristaux_index_BGO, is_clover, is_clover_BGO, is_clover_Ge, isBGO, isClover, isGe, label_to_clover, label_to_cristal, labels, MTObject::mutex, nb_det, s_initialised.
Referenced by Clovers.
static bool Clovers::is_clover(Label const &l)
Referenced by InitialiseArrays, is_clover_BGO, is_clover_Ge.
static bool Clovers::is_clover_BGO(Label const &l)
References is_clover.
Referenced by InitialiseArrays.
static bool Clovers::is_clover_Ge(Label const &l)
References is_clover.
Referenced by InitialiseArrays.
static uchar Clovers::label_to_clover(Label const &l)
Referenced by RunMatrixator::fillMatrixes, InitialiseArrays.
uchar Clovers::label_to_cristal(Label const &l)
References positive_modulo, uchar_cast.
Referenced by InitialiseArrays.
static void Clovers::setEnergyThreshold(float const &emin)
References Emin.
static void Clovers::timePs(bool const &time_ps)
References s_time_ps.
Referenced by CloverSpectra::Initialise.
void Clovers::Analyse()
References Bgo, BGOonly, CleanGe, Ge, Hits, m_clovers, StaticVector< T >::push_back, RejectedGe, totBGO, totGe.
Referenced by EventAnalyse::Set, SetEvent.
void Clovers::Analyse_more()
auto Clovers::begin() const
References m_clovers.
void Clovers::CleanFast()
References delayedClovers, DelayedClovers, DelayedMult, promptClovers, PromptClovers, PromptMult.
Referenced by Clovers, SetEvent.
Clovers::Clovers()
References CleanFast, DelayedClovers, InitialiseArrays, m_clovers, PromptClovers, Reset, CloverModule::resetGlobalLabel.
auto Clovers::end() const
References m_clovers.
bool Clovers::Fill(Event const &event, size_t const &index)
References cristaux, cristaux_BGO, cristaux_index, cristaux_nrj, cristaux_nrj_BGO, cristaux_time, cristaux_time_BGO, CrystalMult, CrystalMult_BGO, Hits, isClover, isGe, labels, m_clovers, StaticVector< T >::push_back, StaticVector< T >::push_back_unique, rawBGO, rawGe, s_time_ps, Event::time2s, Event::times.
Referenced by SetEvent.
bool Clovers::FillFast(Event const &event, size_t const &hit_index)
References delayedClovers, DelayedClovers, delayedGate, Emin, Hits, isClover, isGe, labels, promptClovers, PromptClovers, promptGate, push_back_unique, StaticVector< T >::push_back_unique, s_time_ps, Event::time2s, Event::times.
Referenced by SetEvent.
bool Clovers::isDelayed(CloverModule const &clover)
References delayedGate, CloverModule::nrj, CloverModule::time.
bool Clovers::isPrompt(CloverModule const &clover)
References CloverModule::nrj, promptGate, CloverModule::time.
auto Clovers::mult() const
References Hits, int_cast, StaticVector< T >::size.
CloverModule Clovers::operator[](uchar const &i)
References m_clovers.
CloverModule Clovers::operator[](uchar const &i) const
References m_clovers.
void Clovers::PrintClean()
References CleanGe, m_clovers, print, StaticVector< T >::size.
void Clovers::Reset()
References Bgo, BGOonly, CleanGe, StaticVector< T >::clear, cristaux, cristaux_BGO, cristaux_nrj, cristaux_nrj_BGO, cristaux_time, cristaux_time_BGO, CrystalMult, CrystalMult_BGO, DelayedBGO, DelayedCleanGeMult, DelayedGe, DelayedMult, Ge, has511, Hits, m_clovers, PromptBGO, PromptCleanGeMult, PromptGe, PromptMult, rawBGO, rawGe, RejectedGe, TotalMult, totBGO, totBGO_delayed, totBGO_prompt, totGe, totGe_delayed, totGe_prompt.
Referenced by Clovers, SetEvent.
void Clovers::SetEvent(Event const &event)
Fills the CloverModules for a whole event.
Two modes : 1 : normal mode, skip the compton cleaning 2 : new mode
References Analyse, Fill, Reset.
Referenced by RunMatrixator::loadData_faster, RunMatrixator::loadData_root, CloverSpectra::runFasterReader.
void Clovers::SetEvent(Event const &event, char const &analyse_mode)
Fills the CloverModules for a whole event.
Two modes : 1 : normal mode, skip the compton cleaning 2 : new mode
References CleanFast, delayedClovers, DelayedMult, Fill, FillFast, promptClovers, PromptMult, Reset.
auto const& Clovers::size() const
References Hits, StaticVector< T >::size.