AnalysedSpectra
std::string AnalysedSpectra::detector
double AnalysedSpectra::m_apb
Referenced by fitPeaks, setChannelsPerBin.
TH1F* AnalysedSpectra::m_histo
Referenced by choosePeaks, fitPeak, fitPeaks, load, operator->, selectX, setMaximumRange, setMinimumRange.
double AnalysedSpectra::m_kpb
Referenced by fitPeaks, setKevPerBin.
TPad* AnalysedSpectra::m_pad
Referenced by autoCanvas, cd, choosePeaks, fitPeak, fitPeaks, getCanvas, selectX.
std::vector<FittedPeak> AnalysedSpectra::m_peaks
Referenced by choosePeaks, clearPeaks, fitPeak, fitPeaks, getPeaks.
double AnalysedSpectra::range_max
Referenced by load, setMaximumRange, setMinimumRange.
double AnalysedSpectra::range_min
Referenced by load, setMaximumRange, setMinimumRange.
double AnalysedSpectra::ratio_range_max
Referenced by fitPeaks, setRatioRange.
double AnalysedSpectra::ratio_range_min
Referenced by fitPeaks, setRatioRange.
AnalysedSpectra::AnalysedSpectra() noexcept=default
AnalysedSpectra::AnalysedSpectra(TH1F *histo) noexcept
void AnalysedSpectra::autoCanvas()
References cd, m_pad, print.
Referenced by choosePeaks, fitPeak, fitPeaks.
void AnalysedSpectra::cd(TVirtualPad *vpad)
References m_pad.
Referenced by autoCanvas.
void AnalysedSpectra::choosePeaks(std::vector< double > const &peaks)
References autoCanvas, GetPoint, m_histo, m_pad, m_peaks, print.
void AnalysedSpectra::clearPeaks()
References m_peaks.
FittedPeak & AnalysedSpectra::fitPeak(double const &peaks, bool const &adjustRange=false)
References autoCanvas, concatenate, PeakFitter::getConstante, PeakFitter::getMean, PeakFitter::getSigma, m_histo, m_pad, m_peaks, selectX, setMaximumRange, setMinimumRange.
std::vector< FittedPeak > & AnalysedSpectra::fitPeaks(std::vector< double > peaks, bool const &adjustRange=false)
References autoCanvas, concatenate, PeakFitter::getConstante, PeakFitter::getMean, PeakFitter::getSigma, m_apb, m_histo, m_kpb, m_pad, m_peaks, print, ratio_range_max, ratio_range_min, selectX, setMaximumRange, setMinimumRange.
auto AnalysedSpectra::getCanvas()
References m_pad.
auto const AnalysedSpectra::getCanvas() const
References m_pad.
auto const& AnalysedSpectra::getPeaks() const
References m_peaks.
Referenced by operator<<.
void AnalysedSpectra::load(TH1F *const histo)
References m_histo, range_max, range_min.
auto AnalysedSpectra::operator->()
References m_histo.
double AnalysedSpectra::selectX(std::string const &instructions)
References GetPoint, m_histo, m_pad.
Referenced by fitPeak, fitPeaks.
void AnalysedSpectra::setChannelsPerBin(double const &cpb)
References m_apb.
void AnalysedSpectra::setKevPerBin(double const &kpb)
References m_kpb.
void AnalysedSpectra::setMaximumRange(double const &_max)
References m_histo, range_max, range_min.
Referenced by fitPeak, fitPeaks.
void AnalysedSpectra::setMinimumRange(double const &_min)
References m_histo, range_max, range_min.
Referenced by fitPeak, fitPeaks.
void AnalysedSpectra::setRatioRange(double const &min, double const &max)
References ratio_range_max, ratio_range_min.