Bools
bool* Bools::m_data
Referenced by begin, Bools, end, operator=, operator[], push_back, resize, ~Bools.
size_t Bools::m_reserved_size
Referenced by Bools, operator=, resize.
size_t Bools::m_size
Referenced by Bools, end, operator=, push_back, resize, size.
bool Bools::AND() const noexcept
auto Bools::begin()
References m_data.
auto Bools::begin() const
References m_data.
Bools::Bools() noexcept=default
Bools::Bools(Bools &&other) noexcept
Bools::Bools(const Bools &other) noexcept
References m_data, m_size.
Bools::Bools(size_t size, bool const &value=false) noexcept
References m_data, m_reserved_size, m_size.
auto Bools::end()
References m_data, m_size.
auto Bools::end() const
References m_data, m_size.
Bools& Bools::operator=(Bools &&other) noexcept
References m_data, m_size.
Bools& Bools::operator=(const Bools &other) noexcept
References m_data, m_reserved_size, m_size.
bool& Bools::operator[](size_t const &index)
References m_data.
bool const& Bools::operator[](size_t const &index) const
References m_data.
bool Bools::OR() const noexcept
void Bools::push_back(bool const &value)
References m_data, m_size, resize.
void Bools::resize(size_t size)
References m_data, m_reserved_size, m_size, size.
Referenced by push_back, Detectors::readFile, Detectors::resize, CobaltCalorimeter::work.
void Bools::resize(size_t size, bool const &value)
References m_data, m_reserved_size, m_size, size.
size_t const& Bools::size() const
References m_size.
Referenced by resize.
bool Bools::XOR() const noexcept
Bools::~Bools()
References m_data.