Filename
std::string Filename::m_extension
Referenced by extension, fill, operator=, setExtension, update.
std::string Filename::m_fullName
Referenced by c_str, fill, fullName, get, operator std::string, operator=, string, update.
std::string Filename::m_shortName
Referenced by fill, operator=, shortName, update.
std::string Filename::c_str() const
References m_fullName.
std::string const& Filename::extension() const
References m_extension.
Referenced by File::extension.
Filename::Filename()
Filename::Filename(Filename const &_filename)
Filename::Filename(std::string const &_filename)
References fill.
std::string const& Filename::fullName() const
Full name stands for the file name with the path nor the extension.
References m_fullName.
Referenced by operator<<.
std::string const& Filename::get() const
References m_fullName.
Referenced by operator+.
Filename::operator std::string() const &
References m_fullName.
Filename& Filename::operator=(const char *_filename)
References fill.
Filename& Filename::operator=(Filename const &_filename)
References m_extension, m_fullName, m_shortName.
Filename& Filename::operator=(std::string const &_filename)
References fill.
void Filename::setExtension(std::string const &new_extension)
References m_extension, remove, update.
Referenced by File::setExtension.
std::string const& Filename::shortName() const
Short name stands for the file name withpout the path nor the extension.
References m_shortName.
Referenced by File::shortName.
std::string const& Filename::string() const
References m_fullName.
Referenced by File::update.
void Filename::fill(std::string const &filename)
References getExtension, hasPath, m_extension, m_fullName, m_shortName, print, rmPathAndExt, update.
Referenced by Filename, operator=.
void Filename::update()
References m_extension, m_fullName, m_shortName.
Referenced by fill, setExtension.