Folder
std::string Folder::m_folder
Referenced by get, make, name, operator+=, operator=, operator==, string.
bool Folder::m_ok
Referenced by make, operator bool.
Folder::Folder()
Folder::Folder(const char *folder)
References make.
Folder::Folder(std::string const &folder)
Turns a string to a folder's name.
Basically, it is simply ensures that the name ends with a '/' Also, it is the base class of Path class
References make.
std::string const& Folder::get() const
References m_folder.
Referenced by Path::addFolder, Path::operator+.
void Folder::make()
References m_folder, m_ok.
Referenced by Folder, operator=.
std::string Folder::name() const
References m_folder.
Referenced by Path::addFolder.
Folder::operator bool() const &
References m_ok.
Folder& Folder::operator+=(Folder const &folder)
References m_folder.
Folder& Folder::operator=(const char *folder)
Folder& Folder::operator=(std::string const &folder)
References m_folder, make.
bool Folder::operator==(const char *string) const
References m_folder.
bool Folder::operator==(std::string const &string) const
References m_folder, string.
std::string Folder::string()
References m_folder.
std::string const& Folder::string() const
References m_folder.
Referenced by operator+, operator+=, operator<<, operator==, RunMatrixator::Write.