Nuball2Tree
bool Nuball2Tree::file_opened
Referenced by Close, Open, ~Nuball2Tree.
TFile* Nuball2Tree::m_file
Referenced by Close, Open.
std::string Nuball2Tree::m_filename
Referenced by Close, filename, Nuball2Tree.
std::string Nuball2Tree::m_name
bool Nuball2Tree::m_ok
Referenced by ok, Open.
std::string Nuball2Tree::m_title
TTree* Nuball2Tree::m_tree
Referenced by get, Open, operator TTree *, operator->.
void Nuball2Tree::Close()
References Close, file_opened, m_file, m_filename, print.
Referenced by Close, ~Nuball2Tree.
auto const& Nuball2Tree::filename()
References m_filename.
Referenced by Open.
TTree* Nuball2Tree::get()
References m_tree.
Referenced by operator<<, MTRootReader::Read.
auto const Nuball2Tree::get() const
References m_tree.
Nuball2Tree::Nuball2Tree(std::string const &filename)
References m_filename, Open.
Nuball2Tree::Nuball2Tree(std::string const &filename, Event &event)
References m_filename, Open.
bool const& Nuball2Tree::ok() const
References m_ok.
bool Nuball2Tree::Open(std::string const &filename)
References file_opened, filename, m_file, m_ok, m_tree, print.
Referenced by Nuball2Tree.
Nuball2Tree::operator TTree *()
References m_tree.
TTree* Nuball2Tree::operator->()
References m_tree.
Nuball2Tree::~Nuball2Tree()
References Close, file_opened.