FittedPeak
double FittedPeak::m_constante
Referenced by constante.
double FittedPeak::m_energy
Referenced by energy.
double FittedPeak::m_mean
Referenced by mean.
double FittedPeak::m_sigma
Referenced by sigma.
auto const& FittedPeak::constante() const
References m_constante.
Referenced by operator<<.
auto const& FittedPeak::energy() const
References m_energy.
Referenced by operator<<.
FittedPeak::FittedPeak(double const &energy, double const &constante, double const &mean, double const &sigma=-1)
FittedPeak::FittedPeak(double const &energy, PeakFitter const &fit)
FittedPeak::FittedPeak(PeakFitter const &fit)
auto const& FittedPeak::mean() const
References m_mean.
Referenced by operator<<.
auto const& FittedPeak::sigma() const
References m_sigma.
Referenced by operator<<.