MTFilesManager
MTList<std::string> MTFilesManager::m_listFiles
bool FilesManager::isReadable
Referenced by FilesManager::operator=.
size_t FilesManager::m_filesCursor
Referenced by FilesManager::flushFiles, FilesManager::getCursor, FilesManager::getFile, FilesManager::nextFileName, FilesManager::operator=, FilesManager::setCursor.
std::map<std::string, ListFiles> FilesManager::m_listFilesInFolder
Referenced by FilesManager::addFolder, FilesManager::getFilesInFolder, FilesManager::operator=.
ListFolders FilesManager::m_listFolder
Referenced by FilesManager::getListFolders, FilesManager::operator=, FilesManager::printFolders.
Path FilesManager::m_path
Referenced by FilesManager::addFiles, FilesManager::operator=, FilesManager::path.
bool FilesManager::verbose
Referenced by FilesManager::addFolder, FilesManager::operator=, FilesManager::setVerbose.
virtual bool FilesManager::addFile(std::string const &_filename)
References FilesManager::addFiles.
Referenced by Faster2Histo::addFile.
bool FilesManager::addFiles(std::string const &_filename)
References extension, getPath, FilesManager::m_listFiles, FilesManager::m_path.
Referenced by MTFasterReader::addFile, FilesManager::addFile, FilesManager::setListFiles.
virtual bool FilesManager::addFolder(Path const &folder, long nb_files=-1, std::vector< std::string > const &extensions={"root", "fast"})
bool FilesManager::addFolder(std::string folder, long nb_files=-1, std::vector< std::string > const &extensions={"root", "fast"})
References list_files_in_folder, long_cast, FilesManager::m_listFiles, FilesManager::m_listFilesInFolder, print, push_back_if_none, FilesManager::verbose.
Referenced by Faster2Histo::addFolder, MTFasterReader::addFolder, MTRootReader::addFolder, FilesManager::FilesManager, Calibrator::loadRootData, Timeshifts::treatFolder.
auto FilesManager::begin()
References FilesManager::m_listFiles.
auto FilesManager::begin() const
References FilesManager::m_listFiles.
float FilesManager::diskSize() const
References FilesManager::m_listFiles, FilesManager::size, size_file.
auto FilesManager::end()
References FilesManager::m_listFiles.
auto FilesManager::end() const
References FilesManager::m_listFiles.
void FilesManager::flushFiles()
References FilesManager::m_filesCursor, FilesManager::m_listFiles.
Referenced by FilesManager::setListFiles.
auto& FilesManager::get()
References FilesManager::m_listFiles.
auto const& FilesManager::get() const
References FilesManager::m_listFiles.
size_t const& FilesManager::getCursor() const
References FilesManager::m_filesCursor.
virtual std::string FilesManager::getFile(int const &n=-1)
References FilesManager::m_filesCursor, FilesManager::m_listFiles.
Referenced by FilesManager::operator[].
ListFiles const& FilesManager::getFilesInFolder(std::string folder)
References FilesManager::m_listFilesInFolder.
ListFiles const& FilesManager::getListFiles() const
References FilesManager::m_listFiles.
Referenced by Calibrator::loadRootData, MTRootReader::read, MTFasterReader::readAligned, MTFasterReader::readRaw, Timeshifts::treatFolder.
ListFolders const& FilesManager::getListFolders() const
References FilesManager::m_listFolder.
bool FilesManager::isEmpty() const
References FilesManager::size.
Referenced by FilesManager::operator bool.
bool FilesManager::nextFileName(std::string &filename, size_t const &step=1)
References FilesManager::m_filesCursor, FilesManager::m_listFiles.
Referenced by FilesManager::operator>>, Timeshifts::treatFolder.
FilesManager::operator bool() const
References FilesManager::isEmpty.
bool FilesManager::operator>>(std::string &filename)
References FilesManager::nextFileName.
std::string FilesManager::operator[](int const &n)
References FilesManager::getFile.
Path const& FilesManager::path() const
References FilesManager::m_path.
void FilesManager::Print()
References FilesManager::m_listFiles, print.
void FilesManager::printFolders()
References FilesManager::m_listFolder, print.
void FilesManager::setCursor(int const &_filesCursor)
References FilesManager::m_filesCursor.
void FilesManager::setCursor(size_t const &_filesCursor)
References FilesManager::m_filesCursor.
void FilesManager::setListFiles(ListFiles const &list)
References FilesManager::addFiles, FilesManager::flushFiles.
Referenced by FilesManager::operator=.
void FilesManager::setVerbose(bool const &v)
References FilesManager::verbose.
size_t FilesManager::size() const
References FilesManager::m_listFiles.
Referenced by FilesManager::diskSize, FilesManager::isEmpty, Faster2Histo::load, EvolutionPeaks::run.