RWMat
bool RWMat::deleted
Referenced by ~RWMat.
double RWMat::fMaxCounts
std::string RWMat::fName
Referenced by Read, Reset, RWMat, Write, ~RWMat.
unsigned short RWMat::fNChannels
Referenced by Add, Fill, FindMinChan, FindMinMax, Integral, Read, Reset, ReSymmetrise, RWMat, Write, ~RWMat.
int** RWMat::fRWMat
Referenced by Add, Fill, FindMinChan, FindMinMax, Get, Integral, Read, Reset, ReSymmetrise, RWMat, Set, Write, ~RWMat.
double RWMat::fTotalCounts
bool RWMat::m_ok
Referenced by Reset, RWMat, Write, ~RWMat.
RWMat * RWMat::Add(RWMat *Matrix, double val)
References fNChannels, fRWMat, Get, RWMat, Set.
void RWMat::Fill(unsigned short i, unsigned short j)
References fNChannels, fRWMat.
int RWMat::FindMinChan()
References fNChannels, fRWMat.
double RWMat::FindMinMax()
References fNChannels, fRWMat.
double RWMat::Get(unsigned short i, unsigned short j)
References fRWMat.
Referenced by Add.
double RWMat::Integral()
References fNChannels, fRWMat.
Referenced by Write.
void RWMat::Read(std::string Filename="", bool IsInteger=true)
References fName, fNChannels, fRWMat.
void RWMat::Reset(THist *RootMat)
References fName, fNChannels, fRWMat, m_ok, print.
Referenced by RWMat.
void RWMat::ReSymmetrise()
References fNChannels, fRWMat.
RWMat::RWMat(MTTHist< T > &MTRootMat)
References MTTHist< THist >::get, MTTHist< THist >::GetName, MTTHist< THist >::Integral, m_ok, MTTHist< THist >::Merge, print, Reset.
RWMat::RWMat(std::string name="test.m4b", int nchans=4096)
References fName, fNChannels, fRWMat.
Referenced by Add.
RWMat::RWMat(TH2F *RootMat)
References Reset.
void RWMat::Set(unsigned short i, unsigned short j, double val)
References fRWMat.
void RWMat::Set(unsigned short i, unsigned short j, int val)
References fRWMat.
Referenced by Add.
void RWMat::Write(std::string name="", std::string path="./")
References fName, fNChannels, fRWMat, Integral, m_ok, print.
RWMat::~RWMat()
References deleted, fName, fNChannels, fRWMat, m_ok, print.