MTObject
bool MTObject::activated
Referenced by parallelise_function, signalHandler.
bool MTObject::kill
Referenced by MTFasterReader::Read, signalHandler.
std::mutex MTObject::mutex
Referenced by create_folder_if_none, Faster2Histo::fillHisto, Clovers::InitialiseArrays, DSSD::InitialiseArrays, Paris::InitialiseArrays, pauseCo, MTVariable< T >::resize, FasterReader::setMaxHits, signalHandler, CobaltCalorimeter::work.
size_t MTObject::nb_threads
Referenced by adjustThreadsNumber, getThreadsNb, getThreadsNumber, Initialise, parallelise_function, setThreadsNb.
bool MTObject::ON
Referenced by adjustThreadsNumber, MTTHist< THist >::cleanMove, Initialise, MTTHist< THist >::Merge, parallelise_function, MTTHist< THist >::reset, Manip::setMT, Timeshifts::treatFolder, MTTHist< THist >::Write.
bool MTObject::m_Initialised
Referenced by Initialise.
thread_local size_t MTObject::m_thread_index
Referenced by getThreadIndex, index, parallelise_function.
std::vector< std::thread > MTObject::m_threads
Referenced by parallelise_function, signalHandler.
std::thread::id MTObject::master_thread_id
Referenced by Initialise, isMasterThread.
MTObject::MTObject()
MTObject::MTObject(size_t &_nb_threads)
References Initialise.
static void MTObject::adjustThreadsNumber(size_t const &limiting_number, std::string const &print_if_limit_reached="")
References nb_threads, ON, setThreadsNb.
static auto const& MTObject::getThreadIndex()
References m_thread_index.
Referenced by MTTHist< THist >::Fill, MTTHist< THist >::Get, MTTHist< THist >::GetBinContent, MTFasterReader::Read, MTTHist< THist >::reset, MTTHist< THist >::SetBinContent, Timeshifts::treatFasterFile, CobaltCalorimeter::work.
static auto const& MTObject::getThreadsNb()
References nb_threads.
Referenced by MTVariable< T >::MTVariable, MTTHist< THist >::reset, Timeshifts::treatFolder.
static auto const& MTObject::getThreadsNumber()
References nb_threads.
Referenced by Timeshifts::Initialise.
static auto const& MTObject::index()
References m_thread_index.
static void MTObject::Initialise()
References m_Initialised, master_thread_id, nb_threads, ON, signalHandler.
Referenced by CloverSpectra::Initialise, CobaltCalorimeter::Initialise, Initialise, Faster2Root::load, MTObject, Faster2Histo::multirun.
static void MTObject::Initialise(size_t const &_nb_threads, bool force=false)
References Initialise, setThreadsNb.
static bool MTObject::isMasterThread()
References master_thread_id.
Referenced by MTTHist< THist >::reset, MTTHist< THist >::Write.
static void MTObject::parallelise_function(Func &&func, ARGS &&... args)
Todocheck if I can replace Func by std::function
References activated, m_thread_index, m_threads, nb_threads, ON.
Referenced by Calibrator::loadRootData, MTRootReader::read, MTFasterReader::readAligned, MTFasterReader::readRaw, Timeshifts::treatFolder.
static void MTObject::setThreadsNb(int const &n, bool force=false) noexcept
Sets the number of threads.
Check the number of threads. Usually, over 75% of cores is the optimal. Set force parameter to true if you want to use all the cores
References setThreadsNb.
Referenced by adjustThreadsNumber, Initialise, Faster2Histo::setNbThreads, setThreadsNb.
static void MTObject::setThreadsNb(size_t const &n, bool force=false) noexcept
Sets the number of threads.
Check the number of threads. Usually, over 75% of cores is the optimal. Set force parameter to true if you want to use all the cores
References nb_threads.
static void MTObject::signalHandler(int signal)
References activated, kill, m_threads, mutex.
Referenced by Initialise.