Counters
std::array< Bool_t, 24 > Counters::BGO_Clover
Referenced by clear, clover_analyse, count_event, Counters, set_hit.
uchar Counters::Clovers
Referenced by clover_analyse, count_event.
uchar Counters::DSSDMult
Referenced by clear, count_event, set_hit.
std::array< Bool_t, 24 > Counters::Ge_Clover
Referenced by clear, clover_analyse, count_event, Counters, set_hit.
uchar Counters::GeCleanClovers
Referenced by clear, clover_analyse, count_event.
uchar Counters::GeClovers
Referenced by clear, clover_analyse, count_event.
uchar Counters::LaBr3Mult
Referenced by clear, count_event, set_hit.
StaticVector<uchar,24> Counters::list_clovers
Referenced by clear, clover_analyse, count_event, Counters, set_hit.
StaticVector<uchar> Counters::list_clovers
uchar Counters::Modules
Referenced by clear, clover_analyse, count_event, set_hit.
uchar Counters::mult
Referenced by clear, count_event, set_hit.
uchar Counters::ParisMult
Referenced by clear, count_event, set_hit.
uchar Counters::RawBGO
Referenced by clear, count_event, set_hit.
uchar Counters::RawGe
Referenced by clear, count_event, set_hit.
bool Counters::trig
Referenced by hasTrigged.
void Counters::clear()
References BGO_Clover, DSSDMult, Ge_Clover, GeCleanClovers, GeClovers, LaBr3Mult, list_clovers, Modules, mult, ParisMult, RawBGO, RawGe, StaticVector< T >::resize.
Referenced by count_event, countEvent.
void Counters::clear()
void Counters::clover_analyse()
References BGO_Clover, Clovers, Ge_Clover, GeCleanClovers, GeClovers, list_clovers, Modules, StaticVector< T >::size, uchar_cast.
void Counters::count_event(Event const &event)
References BGO_Clover, clear, Clovers, DSSDMult, Ge_Clover, GeCleanClovers, GeClovers, isBGO, isDSSD, isGe, isLaBr3, isParis, labelToClover, LaBr3Mult, list_clovers, Modules, mult, ParisMult, StaticVector< T >::push_back_unique, RawBGO, RawGe, StaticVector< T >::size, uchar_cast.
Counters::Counters()
References BGO_Clover, Ge_Clover, list_clovers, StaticVector< T >::resize.
Counters::Counters()
References BGO_Clover, Ge_Clover, list_clovers, StaticVector< T >::resize.
void Counters::countEvent(Event const &event)
References clear, set_hit.
bool Counters::hasTrigged()
References trig.
bool Counters::hasTrigged()
void Counters::set_hit(Event const &event, int const &i)
References BGO_Clover, DSSDMult, Ge_Clover, isBGO, isDSSD, isGe, isLaBr3, isParis, labelToClover, LaBr3Mult, list_clovers, Modules, mult, ParisMult, StaticVector< T >::push_back_unique, RawBGO, RawGe.
Referenced by countEvent.