Calibration
struct Calibration::histograms Calibration::m_histos
Referenced by fillHisto, fillRootDataHisto, Initialize, loadRootHisto, peakFinder, verify, writeCalibratedData, writeCalibratedHisto, writeRawRoot.
std::vector<std::vector<std::vector<NRJ> > > Calibration::calibration_tables
Referenced by setCalibrationTables.
std::vector<NRJ> Calibration::m_binom
Referenced by calibrate, Calibration, getBinom, load, operator=, operator[], Print, set.
bool Calibration::m_calibrate_data
Referenced by calibrate_data, calibrateFasterData, calibrateRootData, fillRootDataHisto.
std::string Calibration::m_filename
Referenced by file, load.
Fits Calibration::m_fits
Referenced by analyse, Initialize, peakFinder, verify, writeData, writePosPeaks.
std::vector<NRJ> Calibration::m_intercept
Referenced by calibrate, Calibration, getIntercept, load, operator=, operator[], Print, set.
Label Calibration::m_nb_detectors
Referenced by Calibration, load, operator=, size.
bool Calibration::m_ok
Referenced by Calibration, isFilled, load, operator bool, operator=.
std::vector<char> Calibration::m_order
Referenced by calibrate, Calibration, fillHisto, getOrder, load, operator=, operator[], Print, set.
std::string Calibration::m_outCalib
std::string Calibration::m_outDir
std::string Calibration::m_outRoot
bool Calibration::m_outRoot_b
bool Calibration::m_residus
Label Calibration::m_size
Referenced by calibrate, Calibration, load, operator bool, operator=, Print, setCalibrationTables.
std::vector<NRJ> Calibration::m_slope
Referenced by calibrate, Calibration, getSlope, load, operator=, operator[], Print, set.
std::string Calibration::m_source
Referenced by setSource.
std::vector<NRJ> Calibration::m_trinom
Referenced by calibrate, Calibration, getTrinom, load, operator=, operator[], Print, set.
bool Calibration::m_verbose
Referenced by fitCalibration, peakFinder, verbose, verify.
bool Calibration::m_treatOnlyGe
Referenced by peakFinder, treatOnlyGe.
bool Calibration::m_treatOnlyParis
Referenced by peakFinder, treatOnlyParis.
void Calibration::analyse(std::string const &source="152Eu")
Analyse the spectra to extract calibration coefficients.
The peak finding follows the following principle : We start from the bin at the very right side of the spectra. Then we add the value of the bin to the integral counter. Then we add the value of the next bin on the left, then the next, etc.. That is, we integrate the spectra from right to left The moment the first peak is found, the higher energy one, the integral will suddenly increase Then we have to determine a threshold above which we say "we have found the first peak" From this we determine a really rough first linear calibration. This allows us to find, for each other peak, an energy windows in which it should be. Once this window established, we find its centroid. Then we create a smaller window and find again the centroid. A third window (which may not me important ?) event narrower is set around the peak. Then the peak is fitted and the mean value of the gaussian fit added to the calibration curve. Finally, the fit of the calibration curve gives the calibration coefficients. The threshold is taken as the ratio between the integral and the total integral of the spectra, so that the process do not depend neither on different counting rates nor on different calibration duration. Only issue : it depends on the kind of detector and to some extend to the geometry. That is, this calibration is not well suited for paris detectors... Also, if a peak is absent due to for instance high energy threshold of the detector (typically 121keV of 152Eu is absent in some noisy channels) then the calibration will fail The most difficult part is to find the value of the threshold, wich must be different for each kind of detector. If it is different for differents detectors of the same type (e.g. paris) then the calibration requires additionnal work. Take care of the binning of the spectra. If there is too much or not enough bins then the peak fitting will fail, if the maximum ADC value is lower than the higher energy peak then the peak findind will fail. Also, everything supposes the minimum bin corresponds to 0, otherwise it might fail.
References fitCalibration, m_fits, peakFinder, print.
Referenced by calculate.
void Calibration::calculate(std::string const &dataDir, int nb_files=-1, std::string const &source="152Eu", std::string const &type="fast")
References analyse, loadFasterData, loadRootData, print, writeData, writeRawRoot.
void Calibration::calculate(std::string const &histograms, std::string const &source="152Eu")
Calculate calibration from .root histograms.
TODO
References analyse, Initialize, print, writeData, writeRawRoot.
void Calibration::calibrate(Hit &hit) const
avoid using this one
References Hit::adc, Hit::label, m_size, Hit::nrj, Hit::nrj2, Hit::qdc2.
Referenced by fillHisto, fillRootDataHisto, RunMatrixator::loadData_faster, operator().
NRJ Calibration::calibrate(NRJ const &nrj, Label const &label) const
calibrate the ADC value using the parameters extracted from the calibration data
calibrate the nrj value using the parameters extracted from the calibration data
References m_binom, m_intercept, m_order, m_slope, m_trinom, random_uniform.
bool const& Calibration::calibrate_data()
References m_calibrate_data.
bool const& Calibration::calibrate_data() const
References m_calibrate_data.
Referenced by fillHisto.
void Calibration::calibrateFasterData(std::string const &folder, int const &nb_files=-1)
References loadFasterData, m_calibrate_data.
void Calibration::calibrateRootData(std::string const &folder, int const &nb_files=-1)
References loadRootData, m_calibrate_data.
Calibration::Calibration()
References m_ok.
Calibration::Calibration(Calibration const &otherCalib)
Copy constructor.
References m_binom, m_intercept, m_nb_detectors, m_ok, m_order, m_size, m_slope, m_trinom.
Calibration::Calibration(const char *calibFileName)
References load.
Calibration::Calibration(std::string const &calibFileName)
Loading calibration from file name.
References load.
auto const& Calibration::file() const
References m_filename.
Referenced by fillRootDataHisto, loadRootHisto.
void Calibration::fillRootDataHisto(std::string const &filename)
References Event::adcs, Calibration::histograms::all_calib, Calibration::histograms::calib_spectra, calibrate, compressedLabel, detectors, file, isParis, m_calibrate_data, m_histos, print, Event::qdc2s, Calibration::histograms::raw_spectra, Event::reading, Detectors::typeIndex.
Referenced by loadRootDataThread.
void Calibration::fitCalibration(Fits &fits)
References Fit::chi2, Fit::cmeasures, detectors, Fit::ex, Fit::exists, Fit::ey, isDSSD, isGe, isLaBr3, isParis, m_verbose, Fit::name, Fit::order, Fit::parameter0, Fit::parameter1, Fit::parameter2, Fit::peaks, Fit::scalefactor, Detectors::size, Fit::x, Fit::y.
Referenced by analyse.
auto const& Calibration::getBinom() const
References m_binom.
auto const& Calibration::getIntercept() const
References m_intercept.
auto const& Calibration::getOrder() const
References m_order.
auto const& Calibration::getSlope() const
References m_slope.
auto const& Calibration::getTrinom() const
References m_trinom.
void Calibration::Initialize()
References Calibration::histograms::Initialize, m_fits, m_histos.
Referenced by calculate, loadFasterData, loadRootData.
bool const& Calibration::isFilled() const
References m_ok.
bool Calibration::load(std::string const &calibFileName)
References detectors, file_is_empty, m_binom, m_filename, m_intercept, m_nb_detectors, m_ok, m_order, m_size, m_slope, m_trinom, print, Detectors::resize, set, Detectors::size, size.
Referenced by Calibration, CloverSpectra::loadCalibration, Faster2Root::loadCalibration, Faster2Histo::loadCalibration, operator=.
void Calibration::loadFasterData(std::string const &dataDir, int const &nb_files=-1)
References MTFasterReader::addFolder, fillHisto, Initialize, print, MTFasterReader::readRaw.
Referenced by calculate, calibrateFasterData.
void Calibration::loadRootData(std::string const &dataDir, int const &nb_files=-1)
References FilesManager::addFolder, FilesManager::getListFiles, Initialize, loadRootDataThread, MTObject::parallelise_function, print.
Referenced by calculate, calibrateRootData.
void Calibration::loadRootHisto(std::string const &histograms)
References Calibration::histograms::calib_spectra, detectors, file, Detectors::getLabel, m_histos, Calibration::histograms::raw_spectra, Calibration::histograms::spectra, throw_error.
Calibration::operator bool() const &
References m_ok, m_size.
auto Calibration::operator()(ARGS &&... args) const
Call for calibrate method.
References calibrate.
Calibration const& Calibration::operator=(Calibration const &otherCalib)
Copy operator.
References m_binom, m_intercept, m_nb_detectors, m_ok, m_order, m_size, m_slope, m_trinom.
Calibration const& Calibration::operator=(std::string const &calibFileName)
References load.
std::vector<NRJ> Calibration::operator[](Label const &label) const
References m_binom, m_intercept, m_order, m_slope, m_trinom.
void Calibration::peakFinder(std::string const &source)
References ADC_cast, AddTH1, Calibration::histograms::all_raw_spectra, detectors, Detectors::exists, MTTHist< THist >::get, int_cast, isTripleAlpha, m_fits, m_histos, m_treatOnlyGe, m_treatOnlyParis, m_verbose, print, Calibration::histograms::raw_spectra, Detectors::size, Detectors::type.
Referenced by analyse.
void Calibration::Print()
References m_binom, m_intercept, m_order, m_size, m_slope, m_trinom.
void Calibration::setCalibrationTables()
References calibration_tables, m_size, print.
void Calibration::setSource(std::string const &source)
References m_source.
auto const& Calibration::size() const
DEV.
References m_nb_detectors.
Referenced by load.
void Calibration::verbose(bool const &_verbose)
References m_verbose.
void Calibration::verify(std::string const &outfilename="verify")
References Calibration::histograms::all_calib, Calibration::histograms::calib_spectra, detectors, double_cast, Detectors::exists, gRandom, m_fits, m_histos, m_verbose, Detectors::nbTypes, NRJ_cast, print, Calibration::histograms::raw_spectra, Detectors::type, Detectors::typeIndex, writeCalibratedHisto.
void Calibration::writeCalibratedData(std::string const &outfilename)
References Calibration::histograms::all_calib, Calibration::histograms::calib_spectra, m_histos, print.
void Calibration::writeCalibratedHisto(std::string const &outfilename)
References Calibration::histograms::all_calib, Calibration::histograms::calib_spectra, m_histos, print.
Referenced by verify.
void Calibration::writeData(std::string const &outfilename)
References detectors, Detectors::exists, m_fits, File::makePath, print, File::setExtension.
Referenced by calculate.
void Calibration::writePosPeaks(std::string const &outfilename)
References m_fits, File::makePath, print, File::setExtension.
void Calibration::writeRawRoot(std::string const &outfilename)
References Calibration::histograms::all_raw_spectra, m_histos, print, Calibration::histograms::raw_spectra, MTTHist< THist >::Write.
Referenced by calculate.
void Calibration::fillHisto(Hit &hit, FasterReader &reader, Calibration &calib)
References Hit::adc, Calibration::histograms::all_calib, Calibration::histograms::calib_spectra, calibrate, calibrate_data, compressedLabel, detectors, Hit::label, m_histos, m_order, Calibration::histograms::raw_spectra, FasterReader::Read, Detectors::type, Detectors::typeIndex.
Referenced by loadFasterData.
void Calibration::loadRootDataThread(Calibration &calib, MTList &list)
References fillRootDataHisto, MTVector< T >::getNext.
Referenced by loadRootData.
static void Calibration::treatOnlyGe(bool const &b=true)
References m_treatOnlyGe.
static void Calibration::treatOnlyParis(bool const &b=true)
References m_treatOnlyParis.
void Calibration::set(Label label, NRJ intercept, NRJ slope, NRJ binom, NRJ trinom)
References m_binom, m_intercept, m_order, m_slope, m_trinom.
Referenced by load.