Sorted_Event
float Sorted_Event::m_max_E_dssd
Referenced by setDSSDVeto, sortEvent.
float Sorted_Event::m_max_time_dssd
Referenced by setDSSDVeto, sortEvent.
float Sorted_Event::m_min_time_dssd
Referenced by setDSSDVeto, sortEvent.
std::array< Int_t, 24 > Sorted_Event::BGO
Referenced by initialise, reset, sortEvent.
size_t Sorted_Event::BGOMult
Referenced by reset, sortEvent.
size_t Sorted_Event::CleanGeMult
Referenced by reset, sortEvent.
std::vector<uchar> Sorted_Event::clover_hits
Referenced by reset, sortGeClover.
size_t Sorted_Event::CloverGeMult
Referenced by reset, sortEvent.
size_t Sorted_Event::CloverMult
Referenced by reset, sortEvent.
size_t Sorted_Event::ComptonVetoMult
Referenced by reset, sortEvent.
std::array< Bool_t, 24 > Sorted_Event::delayed_Ge
Referenced by initialise, reset, sortEvent.
size_t Sorted_Event::DelayedGeMult
Referenced by reset.
size_t Sorted_Event::DelayedMult
Referenced by reset.
std::vector<uchar> Sorted_Event::DSSD_hits
Referenced by reset, sortEvent.
std::vector<char> Sorted_Event::DSSD_is_Prompt
Referenced by reset, sortEvent.
std::vector<char> Sorted_Event::DSSD_is_Ring
Referenced by reset, sortEvent.
std::vector<uchar> Sorted_Event::DSSD_Rings
Referenced by reset, sortEvent.
std::vector<uchar> Sorted_Event::DSSD_Sectors
Referenced by reset, sortEvent.
bool Sorted_Event::dssd_veto
Referenced by reset, sortEvent.
size_t Sorted_Event::DSSDMult
Referenced by reset, sortEvent.
Bool_t Sorted_Event::DSSDPrompt
Referenced by reset, sortEvent.
size_t Sorted_Event::DSSDRingMult
Referenced by reset, sortEvent.
size_t Sorted_Event::DSSDSectorMult
Referenced by reset, sortEvent.
std::array< Int_t, 24 > Sorted_Event::Ge
Referenced by initialise, reset, sortEvent, sortGeClover.
LaBr3_Event Sorted_Event::LaBr3_event
Referenced by reset, sortEvent.
size_t Sorted_Event::LaBr3Mult
Referenced by reset, sortEvent.
RF_Manager* Sorted_Event::m_rf
Referenced by setRF, sortEvent.
std::array< Float_t, 24 > Sorted_Event::maxE
Referenced by addGeGateTrig, initialise, reset, sortGeClover.
std::array< Int_t, 24 > Sorted_Event::maxE_hit
Referenced by initialise, reset, sortGeClover.
size_t Sorted_Event::ModuleDelayedMult
size_t Sorted_Event::ModulePromptMult
size_t Sorted_Event::ModulesMult
Referenced by reset, sortEvent.
std::array< Float_t, 24 > Sorted_Event::nrj_clover
Referenced by initialise, reset, sortEvent, sortGeClover.
std::vector<uchar> Sorted_Event::paris_hits
Referenced by reset, sortEvent.
size_t Sorted_Event::ParisLaBr3Mult
Referenced by reset.
size_t Sorted_Event::ParisMult
Referenced by reset, sortEvent.
std::array< Bool_t, 24 > Sorted_Event::prompt_Ge
Referenced by initialise, reset, sortEvent.
size_t Sorted_Event::PromptGeMult
Referenced by reset.
size_t Sorted_Event::PromptMult
Referenced by reset.
size_t Sorted_Event::RawGeMult
Referenced by reset, sortEvent.
size_t Sorted_Event::RawMult
Referenced by fillEvent, reset, sortEvent.
std::array<Float_t, 2000> Sorted_Event::time2s
Referenced by sortEvent, sortGeClover.
std::array< Float_t, 24 > Sorted_Event::time_clover
Referenced by initialise, reset, sortEvent, sortGeClover.
size_t Sorted_Event::m_CloverTrig
Referenced by getGatedClover, reset, sortEvent.
Event* Sorted_Event::m_event
Referenced by setEvent, sortEvent.
bool Sorted_Event::m_gateON
Referenced by addGeGateTrig, sortEvent.
int Sorted_Event::m_Ge_gate
Referenced by gateGe, reset, sortEvent.
std::vector<std::pair<Float_t,Float_t> > Sorted_Event::m_Ge_gates
Referenced by addGeGateTrig, sortEvent.
Float_t Sorted_Event::m_max_time
Referenced by setMaxTime, sortEvent.
Timewalks Sorted_Event::m_Timewalks_DSSD
Referenced by setTWcorrectionsDSSD, sortEvent.
bool Sorted_Event::m_TW_DSSD
Referenced by setTWcorrectionsDSSD, sortEvent.
void Sorted_Event::addGeGateTrig(Float_t const &minE, Float_t const &maxE)
References m_gateON, m_Ge_gates, maxE.
void Sorted_Event::addGeGateTrig(std::pair< Float_t, Float_t > const &Egate)
References m_gateON, m_Ge_gates.
void Sorted_Event::fillEvent(Event &event)
References RawMult.
int const& Sorted_Event::gateGe() const
References m_Ge_gate.
auto const& Sorted_Event::getGatedClover() const
References m_CloverTrig.
void Sorted_Event::initialise()
References BGO, delayed_Ge, Ge, maxE, maxE_hit, nrj_clover, prompt_Ge, time_clover.
Referenced by Sorted_Event.
void Sorted_Event::reset()
References BGO, BGOMult, CleanGeMult, clover_hits, CloverGeMult, CloverMult, ComptonVetoMult, delayed_Ge, DelayedGeMult, DelayedMult, DSSD_hits, DSSD_is_Prompt, DSSD_is_Ring, DSSD_Rings, DSSD_Sectors, dssd_veto, DSSDMult, DSSDPrompt, DSSDRingMult, DSSDSectorMult, Ge, LaBr3_event, LaBr3Mult, m_CloverTrig, m_Ge_gate, maxE, maxE_hit, ModulesMult, nrj_clover, paris_hits, ParisLaBr3Mult, ParisMult, prompt_Ge, PromptGeMult, PromptMult, RawGeMult, RawMult, time_clover.
Referenced by Sorted_Event, sortEvent.
void Sorted_Event::setEvent(Event *event)
References m_event.
Referenced by Sorted_Event.
void Sorted_Event::setRF(RF_Manager *rf)
References m_rf.
Sorted_Event::Sorted_Event()
References initialise, reset.
Sorted_Event::Sorted_Event(Event *event)
References initialise, reset, setEvent.
void Sorted_Event::sortEvent()
References m_event, sortEvent.
Referenced by sortEvent.
void Sorted_Event::sortEvent(Event const &event)
References _ns, BGO, BGOMult, CleanGeMult, CloverGeMult, CloverMult, ComptonVetoMult, delayed_Ge, DSSD_hits, DSSD_is_Prompt, DSSD_is_Ring, DSSD_Rings, DSSD_Sectors, dssd_veto, DSSDMult, DSSDPrompt, DSSDRingMult, DSSDSectorMult, Ge, Timewalks::get, isBGO, isDSSD, isGe, isLaBr3, isParis, isRing, LaBr3_Hit::label, Event::labels, labelToClover, LaBr3_event, LaBr3Mult, m_CloverTrig, m_gateON, m_Ge_gate, m_Ge_gates, m_max_E_dssd, m_max_time, m_max_time_dssd, m_min_time_dssd, m_rf, m_Timewalks_DSSD, m_TW_DSSD, ModulesMult, nrj_clover, LaBr3_Hit::nrjcal, paris_hits, ParisMult, prompt_Ge, RF_Manager::pulse_ToF, RawGeMult, RawMult, Event::read, reset, sortGeClover, IOptions::t, IOptions::T, LaBr3_Hit::time, time2s, Event::time2s, time_clover.
bool Sorted_Event::sortGeClover(Event const &event, int const &i)
References clover_hits, Ge, labelToClover, maxE, maxE_hit, nrj_clover, push_back_unique, Event::read, IOptions::T, time2s, time_clover.
Referenced by sortEvent.
static void Sorted_Event::Initialize()
static void Sorted_Event::setDSSDVeto(Float_t const &min_time, Float_t const &max_time, Float_t const &max_E)
References m_max_E_dssd, m_max_time_dssd, m_min_time_dssd.
void Sorted_Event::setMaxTime(Float_t const &max_time)
References m_max_time.
void Sorted_Event::setTWcorrectionsDSSD(std::string const &filename)
References Timewalks::loadFile, m_Timewalks_DSSD, m_TW_DSSD, Timewalks::resize.