Hit
ADC Hit::adc
Referenced by Faster2Root::convertFile, Calibrator::fillHisto, Faster2Histo::fillHisto, RunMatrixator::loadData_faster, CobaltCalorimeter::NaI_pid, operator<<, Event::operator=, operator=, Event::operator[], Event::push_back, Event::push_front, reading, reset, RF_Manager::setHit, FasterReader::TreatCRRC4, Timeshifts::treatFasterFile, FasterReader::TreatQDC1, FasterReader::TreatQDC2, FasterReader::TreatQDC3, FasterReader::TreatRF, FasterReader::TreatTrapez, writting.
Label Hit::label
Referenced by calibBGO, Faster2Root::convertFile, Calibrator::fillHisto, Faster2Histo::fillHisto, get_first_RF_of_file, RunMatrixator::loadData_faster, CobaltCalorimeter::NaI_pid, operator<<, Event::operator=, operator=, Event::operator[], Event::push_back, Event::push_front, FasterReader::ReadData, reading, MTFasterReader::Realign, reset, CloverSpectra::runFasterReader, EventBuilder::setFirstRF, RF_Manager::setHit, Timeshifts::treatFasterFile, CobaltCalorimeter::work, writting.
NRJ Hit::nrj
Referenced by calibBGO, Faster2Root::convertFile, Faster2Histo::fillHisto, RunMatrixator::loadData_faster, operator<<, Event::operator=, operator=, Event::operator[], Event::push_back, Event::push_front, reading, reset, CloverSpectra::runFasterReader, RF_Manager::setHit, Timeshifts::treatFasterFile, CobaltCalorimeter::work, writting.
NRJ Hit::nrj2
Referenced by Faster2Root::convertFile, Faster2Histo::fillHisto, RunMatrixator::loadData_faster, operator<<, Event::operator=, operator=, Event::operator[], Event::push_back, Event::push_front, reading, reset, writting.
NRJ Hit::nrj3
Referenced by operator<<, operator=, reading, reset, writting.
bool Hit::pileup
Referenced by operator<<, Event::operator=, operator=, Event::push_back, Event::push_front, reading, reset, FasterReader::TreatCRRC4, FasterReader::TreatQDC1, FasterReader::TreatQDC2, FasterReader::TreatQDC3, FasterReader::TreatRF, FasterReader::TreatTrapez, writting.
ADC Hit::qdc2
Referenced by Faster2Root::convertFile, Faster2Histo::fillHisto, RunMatrixator::loadData_faster, CobaltCalorimeter::NaI_pid, operator<<, Event::operator=, operator=, Event::operator[], Event::push_back, Event::push_front, FasterReader::ReadData, reading, reset, FasterReader::TreatCRRC4, FasterReader::TreatQDC1, FasterReader::TreatQDC2, FasterReader::TreatQDC3, FasterReader::TreatRF, FasterReader::TreatTrapez, writting.
ADC Hit::qdc3
Referenced by operator<<, operator=, reading, reset, FasterReader::TreatCRRC4, FasterReader::TreatQDC1, FasterReader::TreatQDC2, FasterReader::TreatQDC3, FasterReader::TreatRF, FasterReader::TreatTrapez, writting.
Timestamp Hit::stamp
Referenced by CoincBuilder::coincidence, Faster2Root::convertFile, RunMatrixator::loadData_faster, operator<<, Event::operator=, operator=, Event::operator[], RF_Manager::pulse_ToF, Event::push_back, Event::push_front, reading, MTFasterReader::Realign, reset, RF_Manager::setHit, Timeshifts::treatFasterFile, CobaltCalorimeter::work, writting.
IOptions Hit::read
Referenced by reading.
IOptions Hit::write
Referenced by writting.
Hit::Hit()
References reset.
Hit::Hit(Hit const &hit)
Hit& Hit::operator=(Hit const &hit)
References adc, label, nrj, nrj2, nrj3, pileup, qdc2, qdc3, stamp.
void Hit::reading(TTree *tree)
References adc, IOptions::e, IOptions::E, IOptions::l, label, nrj, nrj2, nrj3, IOptions::p, pileup, print, IOptions::q, IOptions::Q, IOptions::q3, IOptions::Q3, qdc2, qdc3, read, reset, IOptions::s, stamp.
Referenced by Faster2Root::convertFile, RunMatrixator::loadData_faster, MTFasterReader::Realign.
void Hit::reading(TTree *tree, std::string const &options)
References adc, IOptions::e, IOptions::E, IOptions::l, label, nrj, nrj2, nrj3, IOptions::p, pileup, print, IOptions::q, IOptions::Q, IOptions::q3, IOptions::Q3, qdc2, qdc3, read, reset, IOptions::s, IOptions::setOptions, stamp.
void Hit::reset()
References adc, label, nrj, nrj2, nrj3, pileup, qdc2, qdc3, stamp.
Referenced by Hit, RunMatrixator::loadData_faster, reading, MTFasterReader::Realign.
void Hit::writting(TTree *tree, std::string const &options="lseqp")
References adc, IOptions::e, IOptions::E, IOptions::l, label, nrj, nrj2, nrj3, IOptions::p, pileup, print, IOptions::q, IOptions::Q, IOptions::q3, IOptions::Q3, qdc2, qdc3, IOptions::s, IOptions::setOptions, stamp, write.
Referenced by Faster2Root::convertFile, MySimpleConvertor::convertFile, RunMatrixator::loadData_faster, MTFasterReader::Realign.