SiStrip
float SiStrip::nrj
Referenced by Reset.
double SiStrip::time
Referenced by Reset.
double SiStrip::m_angle
Referenced by angle, setAngle, SiStrip.
ushort SiStrip::m_label
Referenced by label, SiStrip.
auto const& SiStrip::angle()
References m_angle.
auto const& SiStrip::angle() const
References m_angle.
Referenced by setAngle, SiStrip.
auto const& SiStrip::label()
References m_label.
auto const& SiStrip::label() const
References m_label.
Referenced by SiStrip.
void SiStrip::Reset()
References nrj, time.
void SiStrip::setAngle(double const &angle)
References angle, m_angle.
SiStrip::SiStrip(ushort const &label)
References label, m_label.
SiStrip::SiStrip(ushort const &label, double const &angle)
References angle, label, m_angle, m_label.