FilesManager
bool FilesManager::isReadable
Referenced by operator=.
size_t FilesManager::m_filesCursor
Referenced by flushFiles, getCursor, getFile, nextFileName, operator=, setCursor.
ListFiles FilesManager::m_listFiles
Referenced by addFiles, addFolder, begin, diskSize, end, flushFiles, get, getFile, getListFiles, nextFileName, operator=, Print, size.
std::map<std::string, ListFiles> FilesManager::m_listFilesInFolder
Referenced by addFolder, getFilesInFolder, operator=.
ListFolders FilesManager::m_listFolder
Referenced by getListFolders, operator=, printFolders.
Path FilesManager::m_path
Referenced by addFiles, operator=, path.
bool FilesManager::verbose
Referenced by addFolder, operator=, setVerbose.
bool FilesManager::addFiles(std::string const &_filename)
References extension, getPath, m_listFiles, m_path.
Referenced by MTFasterReader::addFile, setListFiles.
bool FilesManager::addFolder(std::string folder, long nb_files=-1, std::vector< std::string > const &extensions={"root", "fast"})
References list_files_in_folder, m_listFiles, m_listFilesInFolder, print, push_back_if_none, verbose.
Referenced by MTFasterReader::addFolder, MTRootReader::addFolder, FilesManager, Calibration::loadRootData, Timeshifts::treatFolder.
auto FilesManager::begin()
References m_listFiles.
auto FilesManager::begin() const
References m_listFiles.
float FilesManager::diskSize() const
References m_listFiles, size, size_file.
auto FilesManager::end()
References m_listFiles.
auto FilesManager::end() const
References m_listFiles.
FilesManager::FilesManager()
FilesManager::FilesManager(Path &folder, long nb_files=-1)
References addFolder.
FilesManager::FilesManager(std::string const &folder, long nb_files=-1)
References addFolder.
void FilesManager::flushFiles()
References m_filesCursor, m_listFiles.
Referenced by setListFiles.
auto& FilesManager::get()
References m_listFiles.
auto const& FilesManager::get() const
References m_listFiles.
size_t const& FilesManager::getCursor() const
References m_filesCursor.
virtual std::string FilesManager::getFile(int const &n=-1)
References m_filesCursor, m_listFiles.
Referenced by operator[].
ListFiles const& FilesManager::getFilesInFolder(std::string folder)
References m_listFilesInFolder.
ListFiles const& FilesManager::getListFiles() const
References m_listFiles.
Referenced by MTRootReader::execute, Calibration::loadRootData, MTFasterReader::readAligned, MTFasterReader::readRaw, Timeshifts::treatFolder.
ListFolders const& FilesManager::getListFolders() const
References m_listFolder.
bool FilesManager::isEmpty() const
References size.
Referenced by operator bool.
bool FilesManager::nextFileName(std::string &filename, size_t const &step=1)
References m_filesCursor, m_listFiles.
Referenced by Timeshifts::treatFolder.
FilesManager::operator bool() const
References isEmpty.
FilesManager const& FilesManager::operator=(FilesManager const &other)
References isReadable, m_filesCursor, m_listFiles, m_listFilesInFolder, m_listFolder, m_path, verbose.
void FilesManager::operator=(ListFiles const &list)
References setListFiles.
std::string FilesManager::operator[](int const &n)
References getFile.
Path const& FilesManager::path() const
References m_path.
void FilesManager::Print()
References m_listFiles, print.
void FilesManager::printFolders()
References m_listFolder, print.
void FilesManager::setCursor(int const &_filesCursor)
References m_filesCursor.
void FilesManager::setCursor(size_t const &_filesCursor)
References m_filesCursor.
void FilesManager::setListFiles(ListFiles const &list)
References addFiles, flushFiles.
Referenced by operator=.
void FilesManager::setVerbose(bool const &v)
References verbose.
size_t FilesManager::size() const
References m_listFiles.
Referenced by diskSize, isEmpty.