Minimisator
Vertices Minimisator::g_minima_history
std::vector<double> Minimisator::g_minimums
std::vector<Simplex> Minimisator::g_simplex_history
struct Minimisator::NelderMeadParameters Minimisator::nmParam
double Minimisator::tolerance
int Minimisator::g_nb_rounds
int Minimisator::g_order
Vertices Minimisator::m_grad_vertices
Vertice Minimisator::m_initial_vertice
Vertice Minimisator::m_minimum
int Minimisator::m_nb_steps_grad
Vertice Minimisator::m_steps
Vertice Minimisator::m_weights
auto const& Minimisator::getMinimum() const
Referenced by SpectraAlignator::newAlignement.
Minimisator::Minimisator()=default
void Minimisator::nelderMead(ObjectiveFunction const &function)
References Simplex::begin, Simplex::centroid, Vertice::copy, debug, Simplex::dim, Simplex::end, Vertice::evaluate, Simplex::evaluate, extension, print, Vertice::set, Simplex::size, throw_error.
Referenced by SpectraAlignator::newAlignement.
void Minimisator::setInitialGuess(Vertice const &init_vertice)
References Vertice::size.
Referenced by SpectraAlignator::newAlignement.
void Minimisator::setInitialSteps(Vertice const &steps)
Referenced by SpectraAlignator::newAlignement.
void Minimisator::simpleGrad(ObjectiveFunction &func)
C'est peut-être une fausse piste ...
func
References ObjectiveFunction::evaluate.