StaticVector
T* StaticVector< T >::m_data
Referenced by StaticVector< T >::at, StaticVector< T >::begin, StaticVector< T >::data, StaticVector< T >::deallocate, StaticVector< T >::end, StaticVector< T >::fill, StaticVector< T >::fill_static, StaticVector< T >::move_back, StaticVector< T >::operator=, StaticVector< T >::operator[], StaticVector< T >::push_back, StaticVector< T >::reserve, StaticVector< T >::static_resize, StaticVector< T >::StaticVector, StaticVector< T >::~StaticVector.
bool StaticVector< T >::m_deleted
Referenced by StaticVector< T >::~StaticVector.
size_t StaticVector< T >::m_dynamic_size
Referenced by StaticVector< T >::checkCapacity, StaticVector< T >::clear, StaticVector< T >::deallocate, StaticVector< T >::end, StaticVector< T >::fill, StaticVector< T >::move_back, StaticVector< T >::operator=, StaticVector< T >::push_back, StaticVector< T >::resize, StaticVector< T >::size, StaticVector< T >::static_resize.
size_t StaticVector< T >::m_static_size
Referenced by StaticVector< T >::at, StaticVector< T >::checkCapacity, StaticVector< T >::deallocate, StaticVector< T >::fill_static, StaticVector< T >::operator=, StaticVector< T >::reserve, StaticVector< T >::static_resize, StaticVector< T >::~StaticVector.
T const& StaticVector< T >::at(std::size_t const &i) const
Return the ith element and check i do not exceed the size of the vector.
References StaticVector< T >::m_data, StaticVector< T >::m_static_size.
virtual T* StaticVector< T >::begin()
Return iterator to the beginning of the vector.
References StaticVector< T >::m_data.
Referenced by StaticVector< T >::has.
virtual T* StaticVector< T >::begin() const
Return iterator to the beginning of the vector.
References StaticVector< T >::m_data.
void StaticVector< T >::checkCapacity()
References StaticVector< T >::m_dynamic_size, StaticVector< T >::m_static_size.
void StaticVector< T >::checkCapacity() const
References StaticVector< T >::m_dynamic_size, StaticVector< T >::m_static_size.
Referenced by StaticVector< T >::move_back, StaticVector< T >::operator[], StaticVector< T >::push_back.
void StaticVector< T >::clear()
References StaticVector< T >::m_dynamic_size.
Referenced by Clovers::Reset.
T* StaticVector< T >::data()
Return a pointer to the underlying data.
References StaticVector< T >::m_data.
void StaticVector< T >::deallocate()
Deletes the underlying data.
References StaticVector< T >::m_data, StaticVector< T >::m_dynamic_size, StaticVector< T >::m_static_size.
virtual T* StaticVector< T >::end()
Return iterator to the end of the vector.
References StaticVector< T >::m_data, StaticVector< T >::m_dynamic_size.
Referenced by StaticVector< T >::has.
virtual T* StaticVector< T >::end() const
Return iterator to the end of the vector.
References StaticVector< T >::m_data, StaticVector< T >::m_dynamic_size.
void StaticVector< T >::fill(T const &e)
Fills the vector with element e within user size.
References StaticVector< T >::m_data, StaticVector< T >::m_dynamic_size.
void StaticVector< T >::fill_static(T const &e)
Fills the vector with element e within static size.
References StaticVector< T >::m_data, StaticVector< T >::m_static_size.
Referenced by StaticVector< T >::static_resize, StaticVector< T >::StaticVector.
virtual bool StaticVector< T >::has(T &t) const
Does the vector contain element e ?
t direct access to the variable
References StaticVector< T >::begin, StaticVector< T >::end.
virtual bool StaticVector< T >::has(T const &t) const
Does the vector contain element e ?
t variable in read-only mode
References StaticVector< T >::begin, StaticVector< T >::end.
Referenced by StaticVector< T >::push_back_unique.
void StaticVector< T >::move_back(T &&e)
Move the element to the back of the vector. Use for performances. Unsafe. define SAFE for less performance but size checking.
References StaticVector< T >::checkCapacity, StaticVector< T >::m_data, StaticVector< T >::m_dynamic_size.
StaticVector& StaticVector< T >::operator=(StaticVector< T > const &vector)
Copy the values of another vector.
References StaticVector< T >::m_data, StaticVector< T >::m_dynamic_size, StaticVector< T >::m_static_size.
T& StaticVector< T >::operator[](std::size_t const &i) const
Return the ith element.
References StaticVector< T >::checkCapacity, StaticVector< T >::m_data.
void StaticVector< T >::push_back(T const &e)
Add element to the back of the vector. Use for performances. Unsafe. define SAFE for less performance but size checking.
References StaticVector< T >::checkCapacity, StaticVector< T >::m_data, StaticVector< T >::m_dynamic_size.
Referenced by Clovers::Analyse, Clovers::Fill, StaticVector< T >::push_back_unique.
void StaticVector< T >::push_back_unique(T const &t)
Add element to the back of the vector only if the vector do not contain it.
References StaticVector< T >::has, StaticVector< T >::push_back.
Referenced by Counters::count_event, Clovers::Fill, Clovers::FillFast, Counters::set_hit.
void StaticVector< T >::reserve()
References StaticVector< T >::m_data, StaticVector< T >::m_static_size.
Referenced by StaticVector< T >::static_resize, StaticVector< T >::StaticVector.
void StaticVector< T >::resize(std::size_t const &new_size=0)
Only reset the user size to new_size (default 0). Do not touch the data. Use for performances.
References StaticVector< T >::m_dynamic_size.
Referenced by Counters::clear, Counters::Counters.
auto const& StaticVector< T >::size() const
Return the position of the write cursor.
References StaticVector< T >::m_dynamic_size.
Referenced by Counters::clover_analyse, Counters::count_event, Clovers::mult, operator<<, Clovers::PrintClean, CloverSpectra::runFasterReader, Clovers::size.
void StaticVector< T >::static_resize(std::size_t const &new_size, T const &t)
References StaticVector< T >::fill_static, StaticVector< T >::static_resize.
void StaticVector< T >::static_resize(std::size_t const &new_size=0)
Delete memory, reset the user size to 0 and allocate new_size memory.
References StaticVector< T >::m_data, StaticVector< T >::m_dynamic_size, StaticVector< T >::m_static_size, StaticVector< T >::reserve.
Referenced by StaticVector< T >::static_resize.
StaticVector< T >::StaticVector()=default
StaticVector< T >::StaticVector(StaticVector< T > &&other)
Move contructor.
StaticVector< T >::StaticVector(StaticVector< T > const &vector)
Create a new Static_vector by copy (duplicate)
References StaticVector< T >::m_data, StaticVector< T >::reserve.
StaticVector< T >::StaticVector(std::size_t const &static_size)
Create a new Static_vector with size static_size.
References StaticVector< T >::reserve.
StaticVector< T >::StaticVector(std::size_t const &static_size, T const &e)
Create a new Static_vector with size static_size and fill it with element e.
References StaticVector< T >::fill_static, StaticVector< T >::reserve.
StaticVector< T >::~StaticVector()
References StaticVector< T >::m_data, StaticVector< T >::m_deleted, StaticVector< T >::m_static_size, print.