MTRootReader
FilesManager MTRootReader::m_files
Referenced by addFolder, read.
MTList MTRootReader::m_MTfiles
Referenced by nextFilename, read.
bool MTRootReader::addFolder(Path path, int const &nb_files=-1)
References FilesManager::addFolder, m_files.
Referenced by MTRootReader.
MTRootReader::MTRootReader()
MTRootReader::MTRootReader(Path foldername, int const &nb_files=-1)
References addFolder.
bool MTRootReader::nextFilename(std::string &filename)
References MTVector< T >::getNext, m_MTfiles.
Referenced by Read.
void MTRootReader::read(Func &&func, ARGS &&... args)
References FilesManager::getListFiles, m_files, m_MTfiles, MTObject::parallelise_function, print.
Referenced by CobaltCalorimeter::launchRoot.
void MTRootReader::Read(MTRootReader &MTreader, Func function, ARGS &&... args)
References Nuball2Tree::get, nextFilename.