DataFileReader
uchar DataFileReader::m_alias
Referenced by ReadFastData, switch_alias.
ULong64_t DataFileReader::m_cursor
Referenced by Initialise, Read, ReadRoot.
faster_data_p DataFileReader::m_data
Referenced by ReadFast, ReadFastGroup.
Hit* DataFileReader::m_empty_hit
Referenced by DataFileReader, Initialise, ReadFastGroup, ~DataFileReader.
std::string DataFileReader::m_filename
Referenced by Initialise, InitialiseFasterRead, InitialiseRootRead.
Buffer_ptr DataFileReader::m_group_buffer
Referenced by Initialise, ReadFastData, ReadFastGroup.
UShort_t DataFileReader::m_group_read_cursor
Referenced by Initialise, ReadFastGroup.
UShort_t DataFileReader::m_group_write_cursor
Referenced by Initialise, ReadFastData, ReadFastGroup.
Hit* DataFileReader::m_hit
Referenced by DataFileReader, getHit, Read, ReadFastData, ReadFastGroup, switch_alias.
Bool_t DataFileReader::m_isGroup
Referenced by ReadFastData, ReadFastGroup, readFastGroup.
Bool_t DataFileReader::m_kReady
Referenced by DataFileReader, Initialise, InitialiseFasterRead, InitialiseRootRead, isReady.
Bool_t DataFileReader::m_QDCx[4][4]
Referenced by InitialiseRootRead.
char DataFileReader::m_quick_rootOrFast
Referenced by cd, Initialise, Read, ~DataFileReader.
faster_file_reader_p DataFileReader::m_reader
Referenced by InitialiseFasterRead, ReadFast, ReadFastGroup, ~DataFileReader.
TTree* DataFileReader::m_ReadTree
Referenced by InitialiseRootRead, ReadRoot, ~DataFileReader.
std::string DataFileReader::m_rootORfast
Referenced by Initialise, isRootOrFast.
std::unique_ptr<TFile> DataFileReader::m_TFile
Referenced by cd, InitialiseRootRead.
bool DataFileReader::m_verbose
Bool_t DataFileReader::m_write
Referenced by isWritable, ReadFast, ReadFastGroup.
void DataFileReader::cd()
References m_quick_rootOrFast, m_TFile.
DataFileReader::DataFileReader()
References m_empty_hit, m_hit.
DataFileReader::DataFileReader(Hit *_hit)
References m_empty_hit.
DataFileReader::DataFileReader(Hit *_hit, std::string _filename)
References Initialise, m_empty_hit, m_kReady.
DataFileReader::DataFileReader(std::string _filename)
References Initialise, m_kReady.
Hit* DataFileReader::getHit() const
References m_hit.
Bool_t DataFileReader::Initialise()
References extension, InitialiseFasterRead, InitialiseRootRead, m_cursor, m_empty_hit, m_filename, m_group_buffer, m_group_read_cursor, m_group_write_cursor, m_kReady, m_quick_rootOrFast, m_rootORfast, print.
Referenced by DataFileReader, Initialise.
Bool_t DataFileReader::Initialise(std::string const &_filename)
References Initialise, m_filename.
Bool_t const& DataFileReader::isReady() const
References m_kReady.
std::string const& DataFileReader::isRootOrFast() const
References m_rootORfast.
Bool_t const& DataFileReader::isWritable() const
References m_write.
Bool_t DataFileReader::Read()
References m_cursor, m_quick_rootOrFast, ReadFast, ReadFastGroup, ReadRoot.
Referenced by Read.
Bool_t DataFileReader::Read(Hit *hit)
References m_hit, Read.
Bool_t DataFileReader::ReadFast()
References m_data, m_reader, m_write, ReadFastData.
Referenced by Read.
Bool_t DataFileReader::ReadFastData(faster_data_p const &_data)
References Hit::label, m_alias, m_group_buffer, m_group_write_cursor, m_hit, m_isGroup, readFastGroup, switch_alias.
Referenced by ReadFast, ReadFastGroup, readFastGroup.
Bool_t DataFileReader::ReadFastGroup()
References Hit::label, m_data, m_empty_hit, m_group_buffer, m_group_read_cursor, m_group_write_cursor, m_hit, m_isGroup, m_reader, m_write, ReadFastData.
Referenced by Read.
void DataFileReader::readFastGroup(faster_data_p const &_data)
References m_isGroup, ReadFastData.
Referenced by ReadFastData.
Bool_t DataFileReader::ReadRoot(Int_t const &pos)
References m_cursor, m_ReadTree.
Referenced by Read.
void DataFileReader::switch_alias(uchar const &_alias, faster_data_p const &_data, Bool_t &_write)
References Hit::label, m_alias, m_hit.
Referenced by ReadFastData.
DataFileReader::~DataFileReader()
References m_empty_hit, m_quick_rootOrFast, m_reader, m_ReadTree.
Bool_t DataFileReader::InitialiseFasterRead()
References m_filename, m_kReady, m_reader.
Referenced by Initialise.
Bool_t DataFileReader::InitialiseRootRead()
References m_filename, m_kReady, m_QDCx, m_ReadTree, m_TFile.
Referenced by Initialise.