RunMatrixator
MTTHist<TH1F> RunMatrixator::clover_singles_delayed
Referenced by fillMatrixes, Initialise, Write.
MTTHist<TH1F> RunMatrixator::clover_singles_delayed_Compton_veto
Referenced by fillMatrixes, Initialise, Write.
MTTHist<TH1F> RunMatrixator::clover_singles_prompt
Referenced by fillMatrixes, Initialise, Write.
MTTHist<TH1F> RunMatrixator::clover_singles_prompt_Compton_veto
Referenced by fillMatrixes, Initialise, Write.
Calibration RunMatrixator::m_calibration
Referenced by loadData_faster, run, setCalibration.
std::vector<Label> RunMatrixator::m_dontMatrixateLabel
Referenced by dontMatrixate, fillMatrixes, Initialise, Initialise_dontMatrixate.
std::unordered_map<dType, bool> RunMatrixator::m_dontMatrixateType
Referenced by dontMatrixate, Initialise, Initialise_dontMatrixate.
bool RunMatrixator::m_keep_singles
Referenced by Initialise, keepSingles.
uchar RunMatrixator::m_max_multiplicity
Referenced by fillMatrixes, Initialise, maxRawMult.
Path RunMatrixator::m_runpath
Referenced by run, Write.
Timeshifts RunMatrixator::m_timeshifts
Referenced by loadData_faster, run, setTimeshifts.
std::unordered_map<dType, Vector_MTTHist<TH2F> > RunMatrixator::matricesDelayed
Referenced by fillMatrixes, Initialise, Write.
std::unordered_map<dType, Vector_MTTHist<TH2F> > RunMatrixator::matricesDelayed2
Referenced by fillMatrixes, Initialise, Write.
std::unordered_map<dType, Vector_MTTHist<TH2F> > RunMatrixator::matricesPrompt
Referenced by fillMatrixes, Initialise, Write.
std::unordered_map<dType, Vector_MTTHist<TH2F> > RunMatrixator::matricesPrompt2
Referenced by fillMatrixes, Initialise, Write.
MTTHist<TH2F> RunMatrixator::matrix_Clovers_delayed
Referenced by fillMatrixes, Initialise, Write.
MTTHist<TH2F> RunMatrixator::matrix_Clovers_delayed_vs_prompt
Referenced by fillMatrixes, Initialise, Write.
MTTHist<TH2F> RunMatrixator::matrix_Clovers_prompt
Referenced by fillMatrixes, Initialise, Write.
std::unordered_map<dType, Vector_MTTHist<TH1F> > RunMatrixator::singlesDelayed
Referenced by fillMatrixes, Initialise, Write.
std::unordered_map<dType, Vector_MTTHist<TH1F> > RunMatrixator::singlesDelayed2
Referenced by Initialise, Write.
std::unordered_map<dType, Vector_MTTHist<TH1F> > RunMatrixator::singlesPrompt
Referenced by fillMatrixes, Initialise, Write.
std::unordered_map<dType, Vector_MTTHist<TH1F> > RunMatrixator::singlesPrompt2
Referenced by Initialise, Write.
MTTHist<TH2F> RunMatrixator::test_paris_vs_mult
Referenced by Initialise, Write.
void RunMatrixator::dontMatrixate(dType const &type)
References detectors, found, Initialise_dontMatrixate, m_dontMatrixateLabel, m_dontMatrixateType, throw_error, Detectors::types, Detectors::typesArray.
void RunMatrixator::dontMatrixate(Label const &label)
References Initialise_dontMatrixate, m_dontMatrixateLabel, throw_error.
void RunMatrixator::fillMatrixes(Clovers const &clovers, Event const &event)
References clover_singles_delayed, clover_singles_delayed_Compton_veto, clover_singles_prompt, clover_singles_prompt_Compton_veto, Clovers::delayedClovers, Clovers::DelayedClovers, detectors, Detectors::exists, MTTHist< THist >::Fill, Detectors::index, isClover, isParis, Clovers::label_to_clover, m_dontMatrixateLabel, m_max_multiplicity, matricesDelayed, matricesDelayed2, matricesPrompt, matricesPrompt2, matrix_Clovers_delayed, matrix_Clovers_delayed_vs_prompt, matrix_Clovers_prompt, parisIsLaBr, parisIsNaI, Event::pileups, Clovers::promptClovers, Clovers::PromptClovers, singlesDelayed, singlesPrompt, Detectors::type.
Referenced by loadData_faster, loadData_root.
void RunMatrixator::Initialise()
References clover_singles_delayed, clover_singles_delayed_Compton_veto, clover_singles_prompt, clover_singles_prompt_Compton_veto, detectors, Detectors::energyBidimBin, Detectors::energyBin, Initialise_dontMatrixate, Builder::keepSingles, Detectors::label, m_dontMatrixateLabel, m_dontMatrixateType, m_keep_singles, m_max_multiplicity, matricesDelayed, matricesDelayed2, matricesPrompt, matricesPrompt2, matrix_Clovers_delayed, matrix_Clovers_delayed_vs_prompt, matrix_Clovers_prompt, Detectors::name, Detectors::nbOfType, print, MTTHist< THist >::reset, singlesDelayed, singlesDelayed2, singlesPrompt, singlesPrompt2, test_paris_vs_mult, throw_error, Detectors::types.
Referenced by run.
void RunMatrixator::Initialise_dontMatrixate()
References detectors, m_dontMatrixateLabel, m_dontMatrixateType, Detectors::nbTypes, Detectors::size, Detectors::types.
Referenced by dontMatrixate, Initialise.
void RunMatrixator::keepSingles(bool const &b=true)
References m_keep_singles.
void RunMatrixator::loadData_faster(Hit &hit, FasterReader &reader)
References Hit::adc, Calibration::calibrate, RF_Extractor::cursor, fillMatrixes, Hit::label, m_calibration, m_timeshifts, Hit::nrj, Hit::nrj2, Hit::qdc2, FasterReader::Read, Hit::reading, Hit::reset, Clovers::SetEvent, Hit::stamp, Hit::writting.
Referenced by dispatch_faster_reader.
void RunMatrixator::loadData_root(TTree *tree, Event &event)
References fillMatrixes, Clovers::SetEvent.
Referenced by dispatch_root_reader.
void RunMatrixator::maxRawMult(uchar const &max_multiplicity=20)
References m_max_multiplicity.
bool RunMatrixator::parisIsLaBr(NRJ const &nrj, NRJ const &nrj2)
References parisRatio.
Referenced by fillMatrixes.
bool RunMatrixator::parisIsNaI(NRJ const &nrj, NRJ const &nrj2)
References parisRatio.
Referenced by fillMatrixes.
auto RunMatrixator::parisRatio(NRJ const &nrj, NRJ const &nrj2)
Referenced by parisIsLaBr, parisIsNaI.
void RunMatrixator::run(std::string const &runpath, std::string const &data="fast")
References dispatch_faster_reader, dispatch_root_reader, Initialise, m_calibration, m_runpath, m_timeshifts, print, MTFasterReader::readRaw, throw_error, Timer::unit, Write.
RunMatrixator::RunMatrixator()=default
void RunMatrixator::setCalibration(Calibration const &calibration)
References m_calibration.
void RunMatrixator::setTimeshifts(Timeshifts const &timeshifts)
References m_timeshifts.
void RunMatrixator::Write()
References clover_singles_delayed, clover_singles_delayed_Compton_veto, clover_singles_prompt, clover_singles_prompt_Compton_veto, error, Path::folder, m_runpath, matricesDelayed, matricesDelayed2, matricesPrompt, matricesPrompt2, matrix_Clovers_delayed, matrix_Clovers_delayed_vs_prompt, matrix_Clovers_prompt, print, removeExtension, singlesDelayed, singlesDelayed2, singlesPrompt, singlesPrompt2, Folder::string, test_paris_vs_mult, throw_error, MTTHist< THist >::Write.
Referenced by run.
void RunMatrixator::dispatch_faster_reader(Hit &hit, FasterReader &reader, RunMatrixator &rm)
Multithreading of loadData_faster (you have to pass by a static method in order to multi-thread it)
References loadData_faster.
Referenced by run.
void RunMatrixator::dispatch_root_reader(TTree *tree, Event &event, RunMatrixator &rm)
Multithreading of loadData_ (you have to pass by a static method in order to multi-thread it)
References loadData_root.
Referenced by run.