Folders
std::vector<Folder> Folders::m_folders
Referenced by begin, clear, end, erase, Folders, get, list, operator std::vector< Folder >, operator=, operator[], push_back, resize, size, string.
auto Folders::begin() const
References m_folders.
void Folders::clear()
References m_folders.
Referenced by Path::load.
auto Folders::end() const
References m_folders.
auto Folders::erase(size_t const &pos)
References m_folders.
Referenced by Path::cleanPath.
auto Folders::erase(size_t const &pos, size_t const &size)
References m_folders, size.
Folders::Folders()
Folders::Folders(Folders const &folders)
References m_folders.
Folders::Folders(std::vector< Folder > const &folders)
References m_folders.
Folders::Folders(std::vector< std::string > const &folders)
References m_folders.
auto const& Folders::get() const
References m_folders.
Referenced by Path::folder, operator<<.
auto const& Folders::list() const
References m_folders.
Folders::operator std::string()
References operator std::string.
Referenced by operator std::string.
Folders::operator std::vector< Folder >() const &
References m_folders.
Folders& Folders::operator=(Folders const &folders)
References m_folders.
Folders& Folders::operator=(std::vector< std::string > const &folders)
References m_folders.
Folder const& Folders::operator[](size_t const &i) const
References m_folders.
void Folders::push_back(Folder const &folder)
References m_folders.
Referenced by Path::addFolder.
Folders& Folders::resize(int const &size)
References m_folders, size.
auto const Folders::size() const
References m_folders.
Referenced by Path::cleanPath, erase, resize, Path::size.
std::string Folders::string() const
References m_folders.
Referenced by Path::cleanPath.