CloverModule
bool CloverModule::isBGODelayed
Referenced by Reset.
bool CloverModule::isBGOPrompt
Referenced by Reset.
bool CloverModule::isGeDelayed
Referenced by Reset.
bool CloverModule::isGePrompt
Referenced by Reset.
uchar CloverModule::maxE_Ge_cristal
Referenced by operator<<, Reset.
uchar CloverModule::nb
Referenced by addGe, nbCrystals, operator<<, Reset.
uchar CloverModule::nb_BGO
Referenced by addBGO, nbCrystals, operator<<, Reset.
float CloverModule::nrj
Referenced by addGe, Clovers::isDelayed, Clovers::isPrompt, operator<<, Reset.
float CloverModule::nrj_BGO
Referenced by addBGO, Reset.
double CloverModule::time
Referenced by addGe, Clovers::isDelayed, Clovers::isPrompt, operator<<, Reset.
double CloverModule::time_BGO
Referenced by addBGO, Reset.
uchar const CloverModule::m_label
Referenced by label.
uchar thread_local CloverModule::glabel
Referenced by CloverModule, resetGlobalLabel.
void CloverModule::addBGO(float const &_nrj, double const &_time)
References nb_BGO, nrj_BGO, time_BGO.
void CloverModule::addGe(float const &_nrj, double const &_time)
References nb, nrj, time.
void CloverModule::clean()
References Reset.
void CloverModule::clear()
References Reset.
CloverModule::CloverModule()
References glabel.
auto const& CloverModule::label() const
References m_label.
Referenced by operator<<.
uchar CloverModule::nbCrystals() const
References nb, nb_BGO.
void CloverModule::Reset()
References isBGODelayed, isBGOPrompt, isGeDelayed, isGePrompt, maxE_Ge_cristal, nb, nb_BGO, nrj, nrj_BGO, time, time_BGO.
Referenced by clean, clear.
static void CloverModule::resetGlobalLabel()
References glabel.
Referenced by Clovers::Clovers.