Alignator
ULong64_t Alignator::m_cursor
Referenced by cursor, next, reset.
std::vector<int> Alignator::m_index
Referenced by begin, end, GetEntry, loadNewIndex, next, operator[].
ULong64_t Alignator::m_nb_data
Referenced by loadNewIndex.
TTree* Alignator::m_out_tree
TTree* Alignator::m_tree
Referenced by GetEntry, getTree, loadNewIndex, operator->.
Alignator::Alignator(TTree *inputTree, TTree *outputTree)
TBD.
References align, loadNewIndex.
Alignator::Alignator(TTree *tree)
References loadNewIndex.
auto Alignator::begin()
References m_index.
auto const& Alignator::cursor() const
References m_cursor.
auto Alignator::end()
References m_index.
auto Alignator::GetEntry(int i)
References m_index, m_tree.
Referenced by loadNewIndex, CloverSpectra::runFasterReader, CobaltCalorimeter::work.
auto Alignator::getTree()
References m_tree.
auto const& Alignator::next()
References m_cursor, m_index.
auto Alignator::operator->()
References m_tree.
auto const& Alignator::operator[](int const &i) const
References m_index.
void Alignator::reset()
References m_cursor.
void Alignator::align()
TBD.
L'objectif c'est de faire une méthode pour aligner en temps un root tree automatiquement. Pour ça par contre, il faut une méthode qui lise automatiquement le contenu du fichier root et connecte l'event correctement
Referenced by Alignator.
void Alignator::loadNewIndex()
References GetEntry, m_index, m_nb_data, m_tree, print.
Referenced by Alignator.