Timewalks
float Timewalks::Emax
Referenced by get, loadFile.
float Timewalks::Emin
Referenced by loadFile.
bool Timewalks::isON
Referenced by loadFile.
std::vector<TWparameters> Timewalks::m_parameters
Referenced by loadFile, resize.
std::vector<std::vector<float> > Timewalks::m_timewalks
Referenced by get, loadFile, operator[], resize.
float Timewalks::Tmax
Referenced by get.
float Timewalks::Tmin
Referenced by get, loadFile.
float const & Timewalks::get(int const &label, float const &Q)
References Emax, m_timewalks, Tmax, Tmin.
Referenced by Sorted_Event::sortEvent.
void Timewalks::loadFile(std::string const &filename)
References Emax, Emin, isON, m_parameters, m_timewalks, print, timewalk, Tmin.
Referenced by Sorted_Event::setTWcorrectionsDSSD.
std::vector<float>& Timewalks::operator[](int const &i)
References m_timewalks.
void Timewalks::resize(int const &i=0)
References m_parameters, m_timewalks.
Referenced by Sorted_Event::setTWcorrectionsDSSD.
float Timewalks::timewalk(float Q, float a, float b, float t0, float factor)
Referenced by loadFile.
float Timewalks::timewalk(float Q, TWparameters const &p)
Timewalks::Timewalks()
static void Timewalks::setMax(float const &_max)
References Timewalk::setMax.