Builder
Event* Builder::m_event
Referenced by CoincBuilder::build, EventBuilder::build, EventBuilder::EventBuilder, getEvent, isSingle, CoincBuilder::printEvent, reset, CoincBuilder::reset, EventBuilder::reset, size.
Hit Builder::m_last_hit
Referenced by CoincBuilder::build, EventBuilder::build, CoincBuilder::coincidence, getLastHit, EventBuilder::reset, set_first_hit, set_last_hit, EventBuilder::set_last_hit.
uchar Builder::m_status
Referenced by CoincBuilder::build, EventBuilder::build, isBuilding, isBuilt, reset, CoincBuilder::reset, EventBuilder::reset, status.
bool Builder::m_keep_singles
Referenced by CoincBuilder::build, keepSingles.
virtual bool Builder::build(Hit const &_hit)=0
Add Hits to the event. Return true when an event is complete, i.e. current hit is outside of time window.
3 status : 0: single | 1: begin of coincidence | 2: coincidence complete
Builder::Builder()
Builder::Builder(Event *event)
virtual bool Builder::coincidence(Hit const &hit)=0
Event* Builder::getEvent() const
References m_event.
Hit const& Builder::getLastHit() const
References m_last_hit.
bool Builder::isBuilding() const
References m_status.
bool Builder::isBuilt() const
References m_status.
bool Builder::isSingle() const
References Event::isSingle, m_event.
virtual void Builder::reset()
References Event::clear, m_event, m_status.
void Builder::set_first_hit(Hit const &hit)
References m_last_hit.
void Builder::set_last_hit(Hit const &hit)
References m_last_hit.
size_t Builder::size() const
References m_event, size.
Referenced by size.
uchar const& Builder::status() const
References m_status.
static void Builder::keepSingles(bool const &b=true)
References m_keep_singles.
Referenced by Faster2Root::convertFile, CloverSpectra::Initialize, RunMatrixator::Initialize.