EventBuilder
RF_Manager* EventBuilder::m_rf
Referenced by build, reset, set_last_hit, setFirstRF, setRF.
Time EventBuilder::m_shift
Referenced by getShift, reset, set_last_hit, setShift, setShift_ns.
Time EventBuilder::RF_ref_time
Referenced by build, get_RF_ref_time, reset, set_last_hit, setFirstRF, setRFTime.
Bool_t EventBuilder::build(Hit const &_hit)
Add Hits to the event. Return true when an event is complete, i.e. current hit is outside of time window.
3 status : 0: single | 1: begin of coincidence | 2: coincidence complete
References Builder::m_event, Builder::m_last_hit, m_rf, Builder::m_status, Event::mult, RF_Manager::period, reset, RF_ref_time, set_last_hit.
virtual bool Builder::coincidence(Hit const &hit)=0
EventBuilder::EventBuilder()
References Builder::m_event.
EventBuilder::EventBuilder(Event *_event)
References Builder::m_event.
EventBuilder::EventBuilder(Event *_event, RF_Manager *_rf)
References Builder::m_event.
Time const& EventBuilder::get_RF_ref_time() const
References RF_ref_time.
Event* Builder::getEvent() const
References Builder::m_event.
Hit const& Builder::getLastHit() const
References Builder::m_last_hit.
ULong64_t const& EventBuilder::getShift() const
References m_shift.
bool Builder::isBuilding() const
References Builder::m_status.
bool Builder::isBuilt() const
References Builder::m_status.
bool Builder::isSingle() const
References Event::isSingle, Builder::m_event.
void EventBuilder::reset()
References RF_Manager::last_hit, Builder::m_event, Builder::m_last_hit, m_rf, m_shift, Builder::m_status, RF_Manager::period, RF_ref_time.
Referenced by build.
void Builder::set_first_hit(Hit const &hit)
References Builder::m_last_hit.
void EventBuilder::set_last_hit(Hit const &hit)
References RF_Manager::last_hit, Builder::m_last_hit, m_rf, m_shift, RF_Manager::period, RF_ref_time.
Referenced by build.
void EventBuilder::setFirstRF(Hit const &hit)
References Hit::label, m_rf, RF_ref_time.
void EventBuilder::setRF(RF_Manager *rf)
References m_rf.
void EventBuilder::setRFTime(Time const &_RF_ref_time)
References RF_ref_time.
void EventBuilder::setShift(Long64_t const &shift)
References m_shift.
void EventBuilder::setShift_ns(Long64_t const &shift)
References m_shift.
size_t Builder::size() const
References Builder::m_event, Builder::size.
Referenced by Builder::size.
uchar const& Builder::status() const
References Builder::m_status.
Event* Builder::m_event
Referenced by CoincBuilder::build, build, EventBuilder, Builder::getEvent, Builder::isSingle, CoincBuilder::printEvent, Builder::reset, CoincBuilder::reset, reset, Builder::size.
Hit Builder::m_last_hit
Referenced by CoincBuilder::build, build, CoincBuilder::coincidence, Builder::getLastHit, reset, Builder::set_first_hit, Builder::set_last_hit, set_last_hit.
uchar Builder::m_status
Referenced by CoincBuilder::build, build, Builder::isBuilding, Builder::isBuilt, Builder::reset, CoincBuilder::reset, reset, Builder::status.
bool Builder::m_keep_singles
Referenced by CoincBuilder::build, Builder::keepSingles.
static void Builder::keepSingles(bool const &b=true)
References Builder::m_keep_singles.
Referenced by Faster2Root::convertFile, CloverSpectra::Initialize, RunMatrixator::Initialize.