HistoAnalyse
bool HistoAnalyse< THist >::m_exists
Referenced by HistoAnalyse< THist >::reset.
THist* HistoAnalyse< THist >::m_histo
Referenced by HistoAnalyse< THist >::operator->, HistoAnalyse< THist >::reset.
HistoAnalyse< THist >::HistoAnalyse(MTTHist< THist > &histo)
References HistoAnalyse< THist >::reset.
HistoAnalyse< THist >::HistoAnalyse(THist *histo)
References HistoAnalyse< THist >::reset.
void HistoAnalyse< THist >::normalizeX(Float_t const &factor=1)
References print.
Referenced by NormalizeX.
void HistoAnalyse< THist >::normalizeXY(Float_t const &factor=1, int const &min_x=0, int const &min_y=0)
void HistoAnalyse< THist >::normalizeY(Float_t const &factor=1)
References print.
Referenced by NormalizeY.
THist* HistoAnalyse< THist >::operator->()
References HistoAnalyse< THist >::m_histo.
Float_t HistoAnalyse< THist >::peaksOverBackground(std::vector< Gate > gates)
void HistoAnalyse< THist >::removeBackground(int const &nsmooth=10)
References CoAnalyse::removeBackground.
void HistoAnalyse< THist >::reset()
References HistoAnalyse< THist >::m_exists.
Referenced by HistoAnalyse< THist >::HistoAnalyse.
void HistoAnalyse< THist >::reset(MTTHist< THist > &histo)
References bool_cast, MTTHist< THist >::get, MTObject::getThreadIndex, MTObject::isMasterThread, HistoAnalyse< THist >::m_exists, HistoAnalyse< THist >::m_histo, MTTHist< THist >::Merge.
void HistoAnalyse< THist >::reset(THist *histo)
References HistoAnalyse< THist >::m_exists, HistoAnalyse< THist >::m_histo, print.
HistoAnalyse< THist >::~HistoAnalyse()