Faster2Root
bool Faster2Root::m_calibrate
Calibration Faster2Root::m_calibration
Referenced by convertFile, loadCalibration, setCalibration.
bool Faster2Root::m_eventbuilding
Referenced by buildEvents, convertFile, load.
bool Faster2Root::m_loaded_trigger
Referenced by convertFile, loadTriggerFile.
int Faster2Root::m_nb_files
Referenced by convert, setNbFiles.
int Faster2Root::m_nb_threads
Referenced by load, setNbThreads.
bool Faster2Root::m_ok
Referenced by Faster2Root.
bool Faster2Root::m_overwrite
Referenced by convertFile, overwrite.
bool Faster2Root::m_throw_single
Referenced by convertFile, load, throwSingles.
Long64_t Faster2Root::m_time_window
Referenced by buildEvents, convertFile.
Timeshifts Faster2Root::m_timeshifts
Referenced by convertFile, load, loadTimeshifts, setTimeshifts.
MTCounter Faster2Root::m_total_events
Referenced by convertFile, load.
MTCounter Faster2Root::m_total_hits
Referenced by convertFile, load.
Timer Faster2Root::m_total_timer
Referenced by load.
MTCounter Faster2Root::m_trigg_events
Referenced by convertFile.
TriggerEvent Faster2Root::m_trigger
Referenced by convertFile, setTrigger.
std::string Faster2Root::m_trigger_file
Referenced by convertFile, loadTriggerFile.
std::vector<Label> Faster2Root::m_triggering_labels
Referenced by loadTriggerFile.
bool Faster2Root::m_use_RF
Referenced by load.
bool Faster2Root::m_use_trigger
Referenced by convertFile, load, setTrigger.
void Faster2Root::buildEvents(int time_window_ns)
References m_eventbuilding, m_time_window, print.
Referenced by Faster2Root, load.
void Faster2Root::convert(std::string const &dataFolder, std::string const &outputFolder, int const &nb_files=-1)
References dispatch_threads, m_nb_files, print, MTFasterReader::readRaw.
Referenced by Faster2Root, load.
Faster2Root::Faster2Root()
Faster2Root::Faster2Root(int argc, char **argv)
References load.
Faster2Root::Faster2Root(int argc, char **argv, TriggerEvent trigger)
References load, setTrigger.
Faster2Root::Faster2Root(Path const &inputFolder, Path const &outputFolder, int const &nb_files=-1, bool const &buildEvents=false)
Raw conversion :
Deprecated
References buildEvents, convert, m_ok, print, setNbFiles, Path::string, Timer::unit.
void Faster2Root::loadCalibration(std::string const &calibFile)
References Calibration::load, m_calibration.
Referenced by load.
void Faster2Root::loadTimeshifts(std::string const &dTfile)
References Timeshifts::load, m_timeshifts.
Referenced by load.
void Faster2Root::loadTriggerFile(std::string const &file)
Loads a trigger file.
A trigger file contains a list of the detectors's labels (the number, not the name) that are required in the event (e.g. a germanium trigger file would list all the labels of the germaniums). If you want more specific trigger you have to create your own executable, include Faster2Root and follow the example 2 of the documentation of the class.
References found, Event::labels, m_loaded_trigger, m_trigger_file, m_triggering_labels, setTrigger.
Referenced by load.
void Faster2Root::overwrite(bool const &_overwrite)
References m_overwrite.
Referenced by load.
void Faster2Root::setCalibration(Calibration const &calibration)
References m_calibration.
void Faster2Root::setNbFiles(int const &nb_files=-1)
References m_nb_files.
Referenced by Faster2Root, load.
void Faster2Root::setNbThreads(int const &nb_threads=-1)
References m_nb_threads.
Referenced by load.
void Faster2Root::setTimeshifts(Timeshifts const &timeshifts)
References m_timeshifts.
void Faster2Root::setTrigger(TriggerEvent other)
References m_trigger, m_use_trigger.
Referenced by Faster2Root, loadTriggerFile.
void Faster2Root::throwSingles(bool const &_throw_single=true)
References m_throw_single.
void Faster2Root::convertFile(Hit &hit, FasterReader &reader, Path const &outPath)
hit reader outPath
References Hit::adc, alignator, CoincBuilder::build, File::c_str, File::exists, FasterReader::filename, FasterReader::getCounter, FasterReader::getFilename, Builder::keepSingles, Hit::label, m_calibration, m_eventbuilding, m_loaded_trigger, m_overwrite, m_throw_single, m_time_window, m_timeshifts, m_total_events, m_total_hits, m_trigg_events, m_trigger, m_trigger_file, m_use_trigger, Hit::nrj, Hit::nrj2, print, Hit::qdc2, FasterReader::Read, Hit::reading, File::shortName, Hit::stamp, throw_error, Hit::writting.
Referenced by dispatch_threads.
void Faster2Root::load(int argc, char **argv)
References buildEvents, convert, detectors, error_message, MTObject::Initialise, Detectors::load, loadCalibration, loadTimeshifts, loadTriggerFile, m_eventbuilding, m_nb_threads, m_throw_single, m_timeshifts, m_total_events, m_total_hits, m_total_timer, m_use_RF, m_use_trigger, overwrite, print, printParameters, FasterReader::setMaxHits, setNbFiles, setNbThreads, Path::string, throw_error, Timer::TimeSec.
Referenced by Faster2Root.
void Faster2Root::printParameters() const
References print.
Referenced by load.
static void Faster2Root::dispatch_threads(Hit &hit, FasterReader &reader, Faster2Root &convertor, Path const &outPath)
Dispatch the Faster2Root::convertFile() method through the threads.
References convertFile.
Referenced by convert.