DataFile
using DataFile< Index, T >::DataPoints = std::vector<T>
using DataFile< Index, T >::Indexes = std::vector<Index>
bool DataFile< Index, T >::m_all_column_name_casted
int DataFile< Index, T >::m_chosen_column
Referenced by DataFile< Index, T >::operator[], DataFile< Index, T >::readColumn, DataFile< Index, T >::setColumn.
Bools DataFile< Index, T >::m_column_name_casted
std::vector<int> DataFile< Index, T >::m_columns_to_read
Referenced by DataFile< Index, T >::setColumns.
std::map<Index, DataPoints> DataFile< Index, T >::m_data
Referenced by DataFile< Index, T >::data, DataFile< Index, T >::operator bool, DataFile< Index, T >::operator[], DataFile< Index, T >::readColumn.
DataPoints DataFile< Index, T >::m_data_points
std::vector<DataPoints> DataFile< Index, T >::m_data_vector
char DataFile< Index, T >::m_delim
bool DataFile< Index, T >::m_has_header
DataLine DataFile< Index, T >::m_header
Referenced by DataFile< Index, T >::setHeader.
Indexes DataFile< Index, T >::m_indexes
Referenced by DataFile< Index, T >::indexes.
std::string DataFile< Index, T >::m_input_filename
Referenced by DataFile< Index, T >::setColumn.
int DataFile< Index, T >::m_label_index
Strings DataFile< Index, T >::m_labels_column
Referenced by DataFile< Index, T >::setColumn.
DataLine DataFile< Index, T >::m_labels_rows
Referenced by DataFile< Index, T >::readColumn.
int DataFile< Index, T >::m_nb_columns
Referenced by DataFile< Index, T >::setColumns.
bool DataFile< Index, T >::m_ok
Referenced by DataFile< Index, T >::operator bool.
std::string DataFile< Index, T >::m_output_filename
std::string DataFile< Index, T >::m_reader
int DataFile< Index, T >::m_size
Referenced by DataFile< Index, T >::size.
bool DataFile< Index, T >::m_warning_is_error
void DataFile< Index, T >::checkOutputfile(std::ofstream &outputfile)
References print.
DataPoints DataFile< Index, T >::column()
Returns the given column.
This involves a copy of the data !!
References DataFile< Index, T >::readColumn.
Referenced by DataFile< Index, T >::column, DataFile< Index, T >::readColumn, DataFile< Index, T >::setColumn.
DataPoints DataFile< Index, T >::column(COL &&columns)
Returns the given column.
COL Either std::string (name of the column), or int (the column index) This involves a copy of the data !!
References DataFile< Index, T >::column, DataFile< Index, T >::readColumn, DataFile< Index, T >::setColumn.
auto& DataFile< Index, T >::data()
References DataFile< Index, T >::m_data.
auto const& DataFile< Index, T >::data() const
References DataFile< Index, T >::m_data.
Referenced by operator<<.
DataFile< Index, T >::DataFile()=default
DataFile< Index, T >::DataFile(std::string const &filename, bool const &has_header=true)
References DataFile< Index, T >::load.
auto const& DataFile< Index, T >::indexes() const
References DataFile< Index, T >::m_indexes.
Referenced by EvolutionPeaks::run.
void DataFile< Index, T >::load(std::string const &filename, bool const &has_header=true)
Referenced by DataFile< Index, T >::DataFile, EvolutionPeaks::loadRebin.
DataFile< Index, T >::operator bool() const
References DataFile< Index, T >::m_data, DataFile< Index, T >::m_ok.
T& DataFile< Index, T >::operator[](T t)
References DataFile< Index, T >::m_chosen_column, DataFile< Index, T >::m_data.
T const& DataFile< Index, T >::operator[](T t) const
References DataFile< Index, T >::m_chosen_column, DataFile< Index, T >::m_data.
void DataFile< Index, T >::readColumn(std::map< Index, T2 > &map)
References DataFile< Index, T >::m_chosen_column, DataFile< Index, T >::m_data, DataFile< Index, T >::m_labels_rows.
void DataFile< Index, T >::readColumn(std::map< Index, T2 > &map, COL &&column)
COL Either std::string (name of the column), or int (the column index)
References DataFile< Index, T >::column, DataFile< Index, T >::m_chosen_column, DataFile< Index, T >::m_data, DataFile< Index, T >::m_labels_rows, DataFile< Index, T >::setColumn.
void DataFile< Index, T >::readColumn(std::vector< T2 > &vector)
References DataFile< Index, T >::m_chosen_column, DataFile< Index, T >::m_data, DataFile< Index, T >::m_labels_rows.
Referenced by DataFile< Index, T >::column.
void DataFile< Index, T >::readColumn(std::vector< T2 > &vector, COL &&column)
COL Either std::string (name of the column), or int (the column index)
References DataFile< Index, T >::column, DataFile< Index, T >::m_chosen_column, DataFile< Index, T >::m_data, DataFile< Index, T >::m_labels_rows, DataFile< Index, T >::setColumn.
void DataFile< Index, T >::setColumn(int const &choice)
Setup the reading to the wanted column.
References DataFile< Index, T >::m_chosen_column.
Referenced by DataFile< Index, T >::column, DataFile< Index, T >::readColumn.
void DataFile< Index, T >::setColumn(std::string const &column)
Setup the reading to the wanted column.
References DataFile< Index, T >::column, concatenate, first_index_in, DataFile< Index, T >::m_chosen_column, DataFile< Index, T >::m_input_filename, DataFile< Index, T >::m_labels_column, throw_error.
void DataFile< Index, T >::setColumns(std::vector< int > columns)
A vector containing the list of the column index to read. By default, reads only the first lines.
References int_cast, DataFile< Index, T >::m_columns_to_read, DataFile< Index, T >::m_nb_columns.
void DataFile< Index, T >::setHeader(DataLine const &header)
References DataFile< Index, T >::m_header.
auto& DataFile< Index, T >::size()
References DataFile< Index, T >::m_size.
auto const& DataFile< Index, T >::size() const
References DataFile< Index, T >::m_size.
bool DataFile< Index, T >::vectorize()
Todoif needed true if the vectorisation is successfull
void DataFile< Index, T >::write(std::string const &filename)
void DataFile< Index, T >::writeData(std::ofstream &outputfile)
References print.
void DataFile< Index, T >::writeHeader(std::ofstream &outputfile)
void DataFile< Index, T >::checkInputfile(std::ifstream &inputfile)
References print.
void DataFile< Index, T >::loadData(std::ifstream &inputfile)
References fillList, print.
void DataFile< Index, T >::loadHeader(std::ifstream &inputfile)
References fillList, go_to_beginning.
void DataFile< Index, T >::setupContainers()
References CastImpossible::what.