FasterReader
thread_local int FasterReader::m_verbose
Referenced by Initialise, InitialiseReader, setVerbose.
ulonglong FasterReader::s_maxHits
Referenced by getMaxHits, Read, setMaxHits.
std::unordered_map<std::string, bool> FasterReader::error_message
Referenced by TreatQDC2, TreatQDC3.
uchar FasterReader::m_alias
Referenced by ReadData, Reset.
ulonglong FasterReader::m_counter
Referenced by getCounter, Read, Reset.
faster_data_p FasterReader::m_data
Referenced by ReadGroup, ReadSimple, Reset.
Hit FasterReader::m_empty_hit
Referenced by Initialise.
std::string FasterReader::m_filename
Referenced by filename, getFilename, Initialise, InitialiseReader.
ushort FasterReader::m_group_read_cursor
Referenced by Initialise, ReadGroup, Reset.
ushort FasterReader::m_group_write_cursor
Referenced by Initialise, ReadData, ReadGroup, Reset.
Hit* FasterReader::m_hit
Referenced by getHit, ReadData, ReadGroup, setHit, TreatCRRC4, TreatQDC1, TreatQDC2, TreatQDC3, TreatRF, TreatTrapez.
std::vector<Hit*> FasterReader::m_hit_group_buffer
Referenced by Initialise, ReadData, ReadGroup.
ushort FasterReader::m_inGroup
Referenced by ReadData, ReadDataGroup, ReadGroup, Reset.
bool FasterReader::m_kReady
Referenced by FasterReader, Initialise, InitialiseReader, isReady, operator bool.
faster_file_reader_p FasterReader::m_reader
Referenced by InitialiseReader, ReadGroup, ReadSimple, Reset, ~FasterReader.
bool FasterReader::m_write
Referenced by Read, ReadData, ReadGroup, ReadSimple.
FasterReader::FasterReader(Hit *_hit, std::string _filename)
Construct a new Faster Reader object.
References Initialise, m_kReady.
auto const& FasterReader::filename() const
Get the name of the file being read.
References m_filename.
Referenced by Faster2Root::convertFile.
auto const& FasterReader::getCounter() const
Returns the hits counter.
References m_counter.
Referenced by Faster2Root::convertFile.
auto const& FasterReader::getFilename() const
Get the name of the file being read.
References m_filename.
Referenced by Faster2Root::convertFile, Faster2Histo::treatFile.
Hit* FasterReader::getHit() const
DeprecatedGet the current Hit
References m_hit.
bool const& FasterReader::isReady() const
If the initialization went badly then returns false.
References m_kReady.
FasterReader::operator bool() const &
If the initialization went badly then returns false.
References m_kReady.
bool FasterReader::Read()
Main method. Extract the next hit from the data file and fills the Hit *m_hit object.
Hit hit; FasterReader reader(&hit, filename); while(reader.Read()) { // This hit is filled/updated at each iteration print(hit); } true if the end of the file is reached, false otherwise
References m_counter, m_write, ReadGroup, ReadSimple, s_maxHits.
Referenced by Faster2Root::convertFile, MySimpleConvertor::convertFile, Calibrator::fillHisto, get_first_RF_of_file, RunMatrixator::loadData_faster, MTFasterReader::Realign, Timeshifts::treatFasterFile, Faster2Histo::treatFile.
bool FasterReader::Reset()
Reset the cursor to the begining of the document.
References Initialise, m_alias, m_counter, m_data, m_group_read_cursor, m_group_write_cursor, m_inGroup, m_reader.
void FasterReader::setHit(Hit *hit)
TestSet the Hit object \nNever tested, but should work !
References m_hit.
FasterReader::~FasterReader()
Destroy the Faster Reader object.
References m_reader.
static auto FasterReader::getMaxHits()
References s_maxHits.
static void FasterReader::setMaxHits(ulonglong maxHits)
Set the number of hits to read inside each file.
References MTObject::mutex, print, s_maxHits.
Referenced by CloverSpectra::Initialise, Faster2Root::load, Faster2Histo::load, NearLine::readParam.
static void FasterReader::setVerbose(int i=1)
References m_verbose.
bool FasterReader::Initialise()
Setup the fasterac.h library to read the data.
References extension, InitialiseReader, m_empty_hit, m_filename, m_group_read_cursor, m_group_write_cursor, m_hit_group_buffer, m_kReady, m_verbose, print.
Referenced by FasterReader, Reset.
bool FasterReader::InitialiseReader()
References m_filename, m_kReady, m_reader, m_verbose, print.
Referenced by Initialise.
bool FasterReader::ReadData(faster_data_p const &_data)
Treats faster data.
References Hit::label, m_alias, m_group_write_cursor, m_hit, m_hit_group_buffer, m_inGroup, m_write, print, Hit::qdc2, ReadDataGroup, switch_alias, Timestamp_cast.
Referenced by ReadDataGroup, ReadGroup, ReadSimple.
void FasterReader::ReadDataGroup(faster_data_p const &_data)
Treats the faster data groups.
References m_inGroup, ReadData.
Referenced by ReadData.
bool FasterReader::ReadGroup()
Replace the standard ReadSimple if the faster data contains groups First of all, the m_write variable is used to make sure only the handled types are managed (see switch_alias() definition) First hit read : goes inside ReadData() if it isn't a GROUP_TYPE_ALIAS then read it normally else : recursively read the data inside of the group and fill in m_hit_group_buffer returns the first hit // TO CHECK THIS !!! and sets m_inGroup to true The other hits : if we still are in a group (m_inGroup is true): reads the next hit in m_hit_group_buffer else : if it isn't a GROUP_TYPE_ALIAS then read it normally else : recursively read the data inside of the group and fill in m_hit_group_buffer returns the first hit // TO CHECK THIS !!! and sets m_inGroup to true.
References m_data, m_group_read_cursor, m_group_write_cursor, m_hit, m_hit_group_buffer, m_inGroup, m_reader, m_write, ReadData.
Referenced by Read.
bool FasterReader::ReadSimple()
Read triggerless data.
This function is replaced by ReadGroup if the faster data contains groups, this one is simply faster
References m_data, m_reader, m_write, ReadData.
Referenced by Read.
bool FasterReader::switch_alias(uchar const &_alias, faster_data_p const &_data)
Treat the specific part of data (QDC gates, spectro ADC ...)
Internal method that is used to fill hit.adc depending on the alias of the data, that correspond to a certain kind of faster data.
References TreatCRRC4, TreatQDC1, TreatQDC2, TreatQDC3, TreatRF, TreatTrapez.
Referenced by ReadData.
void FasterReader::TreatCRRC4(faster_data_p const &_data)
Load CRRC4 data.
Internal method used to extract ADC value from CRRC4 filter m_hit->pileup = (false); //TO BE LOOKED AT
References Hit::adc, m_hit, Hit::pileup, Hit::qdc2, Hit::qdc3.
Referenced by switch_alias.
void FasterReader::TreatQDC1(faster_data_p const &_data)
Load QDC1 data.
Internal method used to extract QDC values with 1 gate
References Hit::adc, m_hit, Hit::pileup, Hit::qdc2, Hit::qdc3.
Referenced by switch_alias.
void FasterReader::TreatQDC2(faster_data_p const &_data)
Load qdc2 data.
Internal method used to extract QDC values with 2 gates
References Hit::adc, error_message, m_hit, Hit::pileup, print, Hit::qdc2, Hit::qdc3.
Referenced by switch_alias.
void FasterReader::TreatQDC3(faster_data_p const &_data)
Load qdc3 data.
Internal method used to extract QDC values with 2 gates
References Hit::adc, error_message, m_hit, Hit::pileup, print, Hit::qdc2, Hit::qdc3.
Referenced by switch_alias.
void FasterReader::TreatRF(faster_data_p const &_data)
Load RF data.
Internal method used to extract RF period
References Hit::adc, ADC_cast, m_hit, Hit::pileup, Hit::qdc2, Hit::qdc3.
Referenced by switch_alias.
void FasterReader::TreatTrapez(faster_data_p const &_data)
Load Trapez data.
Internal method used to extract ADC value from trapezoid filter
References Hit::adc, m_hit, Hit::pileup, Hit::qdc2, Hit::qdc3.
Referenced by switch_alias.