RF_Manager
Timestamp RF_Manager::last_downscale
Referenced by operator<<, pulse_ToF, set, Timeshifts::treatFasterFile.
Time RF_Manager::period
Referenced by EventBuilder::build, last_time_ns, operator<<, period_ns, pulse_ToF, EventBuilder::reset, RF_Manager, set, EventBuilder::set_last_hit, set_period_ns, Timeshifts::treatFasterFile.
thread_local Label RF_Manager::label
Referenced by Timeshifts::analyse, get_first_RF_of_file, RF_Manager, setHit.
thread_local Time RF_Manager::m_offset
Referenced by last_time_ns, offset, offset_ns, pulse_ToF, set_offset, set_offset_ns.
auto RF_Manager::last_time_ns() const
Returns the value of the end of the time window ( = period-offset)
References m_offset, period.
auto RF_Manager::period_ns() const
References period.
Time RF_Manager::pulse_ToF(Hit const &hit) const
References pulse_ToF, Hit::stamp.
Referenced by pulse_ToF.
Time RF_Manager::pulse_ToF(Timestamp const &timestamp) const
References last_downscale, m_offset, period, Time_cast.
Referenced by Timeshifts::Fill, pulse_ToF_ns, refTime, Sorted_Event::sortEvent.
float RF_Manager::pulse_ToF_ns(ARGS... args)
References pulse_ToF.
Timestamp RF_Manager::refTime(Timestamp const &timestamp) const
References pulse_ToF.
RF_Manager::RF_Manager(Time const &_period=400000, Label const &label_RF=251)
References label, period.
void RF_Manager::set(Timestamp new_timestamp, Timestamp _period)
References double_cast, last_downscale, period, Time_cast.
Referenced by setHit.
void RF_Manager::set_period_ns(Time const &_period)
References period.
Referenced by Timeshifts::treatFasterFile.
bool RF_Manager::setHit(Hit const &hit)
References Hit::adc, Hit::label, label, Hit::nrj, set, Hit::stamp, Timestamp_cast.
Referenced by get_first_RF_of_file.
static auto const& RF_Manager::offset()
References m_offset.
Referenced by set_offset.
static auto RF_Manager::offset_ns()
References m_offset.
Referenced by set_offset_ns.
static void RF_Manager::set_offset(Time const &offset)
References m_offset, offset.
Referenced by Timeshifts::setRFOffset, Timeshifts::setRFOffset_ns, Timeshifts::setRFShift.
static void RF_Manager::set_offset_ns(Time const &offset_ns)
References m_offset, offset_ns.