ParisBidimAngles
std::unordered_map<std::string, double> ParisBidimAngles::m_angleLaBr
Referenced by angleLaBr, LaBr_angles, set.
std::unordered_map<std::string, double> ParisBidimAngles::m_angleNaI
Referenced by angleNaI, NaI_angles, set.
std::unordered_map<std::string, std::pair<double, double> > ParisBidimAngles::m_angles
Referenced by operator[], set.
std::string ParisBidimAngles::m_filename
std::vector<std::string> ParisBidimAngles::m_names
Referenced by names, printDeg, set, sortNames.
bool ParisBidimAngles::m_ok
std::string ParisBidimAngles::m_extension
Referenced by load, write.
double ParisBidimAngles::angleLaBr(std::string name)
References m_angleLaBr.
double const& ParisBidimAngles::angleLaBr(std::string name) const
References m_angleLaBr.
Referenced by load, operator<<, printDeg, set.
double ParisBidimAngles::angleNaI(std::string name)
References m_angleNaI.
double const& ParisBidimAngles::angleNaI(std::string name) const
References m_angleNaI.
Referenced by load, operator<<, printDeg, set.
std::unordered_map<std::string, double> const& ParisBidimAngles::LaBr_angles()
References m_angleLaBr.
void ParisBidimAngles::load(std::string const &filename)
References angleLaBr, angleNaI, File::exists, file_is_empty, m_extension, print, set, File::setExtension, File::string, throw_error.
Referenced by ParisBidimAngles.
std::unordered_map<std::string, double> const& ParisBidimAngles::NaI_angles()
References m_angleNaI.
auto ParisBidimAngles::names()
References m_names.
auto const& ParisBidimAngles::names() const
References m_names.
Referenced by operator<<.
std::pair<double, double> const& ParisBidimAngles::operator[](std::string name)
References m_angles.
ParisBidimAngles::ParisBidimAngles() noexcept=default
ParisBidimAngles::ParisBidimAngles(std::string const &filename)
References load.
void ParisBidimAngles::printDeg()
References angleLaBr, angleNaI, m_names, sortNames.
void ParisBidimAngles::set(std::string const &name, double const &angleLaBr, double const &angleNaI)
References angleLaBr, angleNaI, m_angleLaBr, m_angleNaI, m_angles, m_names.
Referenced by Paris::calculateBidimAngles, load.
void ParisBidimAngles::sortNames()
References m_names.
Referenced by operator<<, printDeg.
void ParisBidimAngles::write(std::string const &filename)
References File::exists, m_extension, File::makePath, print, File::setExtension, File::string.
Referenced by Paris::calculateBidimAngles.