Manip
uint Manip::i
Referenced by getNext, reset.
std::vector<std::string> Manip::list_runs
Referenced by addFolder, get, getNext, readFile, setFolder.
MTList Manip::list_runs_MT
Referenced by addFolder, getNext, readFile, setFolder.
Path Manip::m_datapath
Referenced by readFile, setDataPath.
std::string Manip::m_file
Referenced by readFile, setFileName.
Folder Manip::m_manip
Referenced by readFile, setManipName.
bool Manip::m_MTOn
Referenced by addFolder, getNext, readFile, setFolder, setMT.
bool Manip::m_ok
Referenced by operator bool, readFile, setFolder.
std::string Manip::m_runs_files
Referenced by Manip, readFile.
void Manip::addFolder(std::string const &folder)
Clears the previously set list of folders and replace it with folder.
References list_runs, list_runs_MT, m_MTOn, MTVector< T >::push_back.
auto const& Manip::get() const
References list_runs.
Referenced by operator<<.
bool Manip::getNext(std::string &run)
References MTVector< T >::getNext, i, list_runs, list_runs_MT, m_MTOn.
Referenced by operator>>.
Manip::Manip()
Manip::Manip(std::string const &runs_file)
References m_runs_files, readFile.
Manip::operator bool() const &
References m_ok.
bool Manip::operator>>(std::string &string)
References getNext.
void Manip::readFile()
Reads the list file containing the list of folders.
References m_datapath, m_file, m_manip, m_runs_files.
Referenced by Manip.
void Manip::readFile(std::string const &runs_file)
References list_runs, list_runs_MT, m_MTOn, m_ok, print.
void Manip::reset()
References i.
void Manip::setDataPath(std::string const &datapath)
DeprecatedSet the path of the list file containing the list of folders
References m_datapath.
void Manip::setFileName(std::string const &filename)
References m_file.
void Manip::setFolder(std::string const &folder)
Clears the previously set list of folders and replace it with folder.
References list_runs, list_runs_MT, m_MTOn, m_ok.
void Manip::setManipName(std::string const &manipname)
DeprecatedSet the name of the folder inside the datapath containing the list file containing the list of folders
References m_manip.
bool Manip::setMT(bool const &MTOn=true)
To allow several threads to work on different runs on parallel.
MTObject needs to have been Initialised before creating the
References m_MTOn, MTObject::ON, print.