ParisCluster
StaticVector<uchar> ParisCluster< nb_phoswitch >::Hits
StaticVector<uchar> ParisCluster< nb_phoswitch >::hits_LaBr3
StaticVector<uchar> ParisCluster< nb_phoswitch >::hits_NaI
std::vector<ParisPhoswitch> ParisCluster< nb_phoswitch >::phoswitches
Referenced by ParisCluster< nb_phoswitch >::operator[].
uchar const ParisCluster< nb_phoswitch >::m_label
Referenced by ParisCluster< nb_phoswitch >::label.
thread_local std::atomic< uchar > ParisCluster< nb_phoswitch >::glabel
Referenced by ParisCluster< nb_phoswitch >::nb_clusters, ParisCluster< nb_phoswitch >::ParisCluster.
void ParisCluster< nb_phoswitch >::Analyse()
Referenced by Paris::Analyse.
void ParisCluster< nb_phoswitch >::Fill(Event const &event, int const &i, uchar const &label)
Referenced by Paris::Fill.
void ParisCluster< nb_phoswitch >::Initialize()
Referenced by Paris::Initialize, ParisCluster< nb_phoswitch >::ParisCluster.
void ParisCluster< nb_phoswitch >::InitializeBidims()
auto const& ParisCluster< nb_phoswitch >::label() const
References ParisCluster< nb_phoswitch >::m_label.
ParisPhoswitch& ParisCluster< nb_phoswitch >::operator[](int const &i)
References ParisCluster< nb_phoswitch >::phoswitches.
ParisCluster< nb_phoswitch >::ParisCluster()
References ParisCluster< nb_phoswitch >::glabel, ParisCluster< nb_phoswitch >::Initialize.
void ParisCluster< nb_phoswitch >::Reset()
Referenced by Paris::Reset.
auto const& ParisCluster< nb_phoswitch >::size() const
static auto const& ParisCluster< nb_phoswitch >::nb_clusters()
References ParisCluster< nb_phoswitch >::glabel.