CobaltCalorimeter
MTTHist<TH2F> CobaltCalorimeter::BGO_calo_VS_Clover_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::BGO_calo_VS_smeared_calorimetry
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::BGO_VS_smeared_calorimetry
Referenced by Initialise, work.
MTTHist<TH2F> CobaltCalorimeter::calo_double_cascades_VS_multiplicity
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::calorimetry_BGO_histo
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::calorimetry_Ge_histo
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::calorimetry_LaBr_histo
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::calorimetry_NaI_histo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Clover_calo_VS_BGO_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Clover_calo_VS_smeared_calorimetry
Referenced by Initialise, work.
MTTHist<TH1F> CobaltCalorimeter::Clover_calo_without_Paris
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Clover_VS_smeared_calorimetry
Referenced by Initialise, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_BGO
Referenced by Initialise, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_BGO_trigger
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_calo_VS_BGO_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_calo_VS_Clover_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_calo_VS_Paris_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_calo_VS_smeared_calorimetry
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_Ge
Referenced by Initialise, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_Ge_trigger
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_LaBr
Referenced by Initialise, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_LaBr_trigger
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_NaI
Referenced by Initialise, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_NaI_trigger
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_VS_BGO_calorimetry
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Ge_VS_smeared_calorimetry
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::labels
Referenced by Initialise, work.
MTTHist<TH2F> CobaltCalorimeter::labels2D_trigger
Referenced by Analyse, Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::LaBr3_calo_VS_BGO_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::LaBr3_calo_VS_Clover_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::LaBr3_calo_VS_Paris_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::LaBr_calo_VS_smeared_calorimetry
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::LaBr_VS_smeared_calorimetry
Referenced by Initialise, work, write.
Calibration CobaltCalorimeter::m_calib
Referenced by loadCalibration, work.
double CobaltCalorimeter::m_calo_totale
Referenced by Analyse, work.
double CobaltCalorimeter::m_calo_totale_BGO
Referenced by Analyse, work.
double CobaltCalorimeter::m_calo_totale_Ge
Referenced by Analyse, work.
double CobaltCalorimeter::m_calo_totale_LaBr3
Referenced by Analyse, work.
double CobaltCalorimeter::m_calo_totale_NaI
Referenced by Analyse, work.
std::string CobaltCalorimeter::m_IDfilename
Referenced by launchFaster, launchRoot, loadID.
int CobaltCalorimeter::m_maxE
Referenced by work.
int CobaltCalorimeter::m_minE
Referenced by work.
int CobaltCalorimeter::m_nb_missed
Referenced by Analyse, work.
int CobaltCalorimeter::m_nb_trigg
Referenced by Analyse, work.
int CobaltCalorimeter::m_nb_trigg_BGO
Referenced by Analyse, work.
int CobaltCalorimeter::m_nb_trigg_Ge
Referenced by Analyse, work.
int CobaltCalorimeter::m_nb_trigg_LaBr
Referenced by Analyse, work.
int CobaltCalorimeter::m_nb_trigg_NaI
Referenced by Analyse, work.
std::string CobaltCalorimeter::m_outfilename
Referenced by setOutName, write.
Timeshifts CobaltCalorimeter::m_timeshifts
Referenced by launchFaster, loadTimeshifts.
Time CobaltCalorimeter::m_timewindow
Referenced by Initialise, setTimewindow_ns, work.
MTTHist<TH2F> CobaltCalorimeter::NaI_calo_VS_BGO_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::NaI_calo_VS_Clover_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::NaI_calo_VS_LaBr_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::NaI_calo_VS_Paris_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::NaI_calo_VS_smeared_calorimetry
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::NaI_VS_smeared_calorimetry
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::nrj_each
Referenced by Initialise, work.
MTTHist<TH2F> CobaltCalorimeter::nrj_each_trigger
Referenced by Initialise, work.
MTTHist<TH2F> CobaltCalorimeter::Paris_calo_VS_BGO_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Paris_calo_VS_Clover_calo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::Paris_calo_VS_smeared_calorimetry
Referenced by Initialise, work.
MTTHist<TH1F> CobaltCalorimeter::Paris_calo_without_Clover
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::paris_pid
Referenced by Initialise, NaI_pid, write.
MTTHist<TH2F> CobaltCalorimeter::Paris_VS_smeared_calorimetry
Referenced by Initialise, write.
MTTHist<TH1F> CobaltCalorimeter::smeared_calorimetry_BGO_histo
MTTHist<TH2F> CobaltCalorimeter::smeared_calorimetry_BGO_histo_VS_cristalMult
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::smeared_calorimetry_Clover_histo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::smeared_calorimetry_Clover_histo_VS_cristalMult
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::smeared_calorimetry_Ge_histo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::smeared_calorimetry_Ge_histo_VS_cristalMult
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::smeared_calorimetry_LaBr_histo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::smeared_calorimetry_LaBr_histo_VS_cristalMult
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::smeared_calorimetry_NaI_histo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::smeared_calorimetry_NaI_histo_VS_cristalMult
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::smeared_calorimetry_Paris_histo
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::smeared_calorimetry_Paris_histo_VS_cristalMult
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::spectra_NaI_trigger
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::spectra_trigger
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_BGO
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_BGO_trigger
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_calorimetry
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_Ge
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_Ge_trigger
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_LaBr3
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_LaBr3_trigger
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_NaI
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_NaI_trigger
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_smeared_calorimetry
Referenced by Analyse, Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::spectrum_smeared_calorimetry_double_cascade
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::spectrum_smeared_calorimetry_VS_Multiplicity
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::timewalk_BGO
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::timewalk_Ge
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::timewalk_LaBr
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::timewalk_NaI
Referenced by Initialise, work, write.
MTTHist<TH2F> CobaltCalorimeter::timing_VS_ref
Referenced by Initialise, work.
MTTHist<TH2F> CobaltCalorimeter::timing_VS_trigger
Referenced by Initialise, work, write.
MTTHist<TH1F> CobaltCalorimeter::total_energy_per_detector
Referenced by Initialise, work, write.
CobaltCalorimeter::CobaltCalorimeter()
void CobaltCalorimeter::Initialise()
References BGO_calo_VS_Clover_calo, BGO_calo_VS_smeared_calorimetry, BGO_VS_smeared_calorimetry, calo_double_cascades_VS_multiplicity, calorimetry_BGO_histo, calorimetry_Ge_histo, calorimetry_LaBr_histo, calorimetry_NaI_histo, Clover_calo_VS_BGO_calo, Clover_calo_VS_smeared_calorimetry, Clover_calo_without_Paris, Clover_VS_smeared_calorimetry, Ge_BGO, Ge_BGO_trigger, Ge_calo_VS_BGO_calo, Ge_calo_VS_Clover_calo, Ge_calo_VS_Paris_calo, Ge_calo_VS_smeared_calorimetry, Ge_Ge, Ge_Ge_trigger, Ge_LaBr, Ge_LaBr_trigger, Ge_NaI, Ge_NaI_trigger, Ge_VS_BGO_calorimetry, Ge_VS_smeared_calorimetry, MTObject::Initialise, labels, labels2D_trigger, LaBr3_calo_VS_BGO_calo, LaBr3_calo_VS_Clover_calo, LaBr3_calo_VS_Paris_calo, LaBr_calo_VS_smeared_calorimetry, LaBr_VS_smeared_calorimetry, m_timewindow, NaI_calo_VS_BGO_calo, NaI_calo_VS_Clover_calo, NaI_calo_VS_LaBr_calo, NaI_calo_VS_Paris_calo, NaI_calo_VS_smeared_calorimetry, NaI_VS_smeared_calorimetry, nrj_each, nrj_each_trigger, Paris_calo_VS_BGO_calo, Paris_calo_VS_Clover_calo, Paris_calo_VS_smeared_calorimetry, Paris_calo_without_Clover, paris_pid, Paris_VS_smeared_calorimetry, MTTHist< THist >::reset, smeared_calorimetry_BGO_histo_VS_cristalMult, smeared_calorimetry_Clover_histo, smeared_calorimetry_Clover_histo_VS_cristalMult, smeared_calorimetry_Ge_histo, smeared_calorimetry_Ge_histo_VS_cristalMult, smeared_calorimetry_LaBr_histo, smeared_calorimetry_LaBr_histo_VS_cristalMult, smeared_calorimetry_NaI_histo, smeared_calorimetry_NaI_histo_VS_cristalMult, smeared_calorimetry_Paris_histo, smeared_calorimetry_Paris_histo_VS_cristalMult, spectra_NaI_trigger, spectra_trigger, spectrum_BGO, spectrum_BGO_trigger, spectrum_calorimetry, spectrum_Ge, spectrum_Ge_trigger, spectrum_LaBr3, spectrum_LaBr3_trigger, spectrum_NaI, spectrum_NaI_trigger, spectrum_smeared_calorimetry, spectrum_smeared_calorimetry_double_cascade, spectrum_smeared_calorimetry_VS_Multiplicity, timewalk_BGO, timewalk_Ge, timewalk_LaBr, timewalk_NaI, timing_VS_ref, timing_VS_trigger, total_energy_per_detector.
Referenced by launchFaster, launchRoot.
void CobaltCalorimeter::launchFaster(std::string const &foldername, int nb_files=-1)
legacy
Deprecated. Deprecated
References Analyse, Timeshifts::data, detectors, dispatch_workFaster, Initialise, Detectors::load, m_IDfilename, m_timeshifts, MTFasterReader::readAligned, MTFasterReader::setTimeshifts, write.
void CobaltCalorimeter::launchRoot(std::string const &foldername, int nb_files=-1)
References Analyse, detectors, dispatch_workRoot, Initialise, Detectors::load, m_IDfilename, print, MTRootReader::read, write.
void CobaltCalorimeter::loadCalibration(Calibration calib)
References m_calib.
void CobaltCalorimeter::loadID(std::string const &filename)
References m_IDfilename.
void CobaltCalorimeter::loadTimeshifts(Timeshifts timeshifts)
References m_timeshifts.
void CobaltCalorimeter::setOutName(std::string const &outfilename)
References m_outfilename.
void CobaltCalorimeter::setTimewindow_ns(Time_ns const &time_ns)
References m_timewindow, Time_cast.
void CobaltCalorimeter::work(Hit &hit, Alignator &reader)
legacy
Deprecated. Deprecated
References calibBGO, MTTHist< THist >::Fill, Alignator::GetEntry, isBGO, isGe, isLaBr3, isParis, Hit::label, labels, labels2D_trigger, m_calib, m_timewindow, NaI_pid, Hit::nrj, nrj_each, nrj_each_trigger, smear, spectra_NaI_trigger, spectrum_BGO, spectrum_calorimetry, spectrum_Ge, spectrum_LaBr3, spectrum_smeared_calorimetry, spectrum_smeared_calorimetry_double_cascade, Hit::stamp, Time_cast, timing_VS_ref, timing_VS_trigger.
void CobaltCalorimeter::work(Nuball2Tree &tree, Event &event)
References BGO_calo_VS_Clover_calo, BGO_calo_VS_smeared_calorimetry, BGO_VS_smeared_calorimetry, Calibration::calibrate, calo_double_cascades_VS_multiplicity, calorimetry_BGO_histo, calorimetry_Ge_histo, calorimetry_LaBr_histo, calorimetry_NaI_histo, Clover_calo_VS_BGO_calo, Clover_calo_VS_smeared_calorimetry, Clover_calo_without_Paris, debug, MTTHist< THist >::Fill, Ge_BGO_trigger, Ge_calo_VS_BGO_calo, Ge_calo_VS_Clover_calo, Ge_calo_VS_Paris_calo, Ge_calo_VS_smeared_calorimetry, Ge_Ge_trigger, Ge_LaBr_trigger, Ge_NaI_trigger, Ge_VS_BGO_calorimetry, Ge_VS_smeared_calorimetry, MTTHist< THist >::GetBinContent, MTObject::getThreadIndex, inGate, isBGO, isGe, isLaBr3, isParis, Hit::label, labels2D_trigger, LaBr3_calo_VS_BGO_calo, LaBr3_calo_VS_Clover_calo, LaBr3_calo_VS_Paris_calo, LaBr_calo_VS_smeared_calorimetry, LaBr_VS_smeared_calorimetry, m_calib, m_calo_totale, m_calo_totale_BGO, m_calo_totale_Ge, m_calo_totale_LaBr3, m_calo_totale_NaI, m_maxE, m_minE, m_nb_missed, m_nb_trigg, m_nb_trigg_BGO, m_nb_trigg_Ge, m_nb_trigg_LaBr, m_nb_trigg_NaI, Event::mult, MTObject::mutex, NaI_calo_VS_BGO_calo, NaI_calo_VS_Clover_calo, NaI_calo_VS_LaBr_calo, NaI_calo_VS_Paris_calo, NaI_calo_VS_smeared_calorimetry, NaI_pid, NaI_VS_smeared_calorimetry, Paris_calo_VS_BGO_calo, Paris_calo_VS_Clover_calo, Paris_calo_VS_smeared_calorimetry, Paris_calo_without_Clover, Bools::resize, MTTHist< THist >::SetBinContent, smear, smeared_calorimetry_BGO_histo_VS_cristalMult, smeared_calorimetry_Clover_histo, smeared_calorimetry_Clover_histo_VS_cristalMult, smeared_calorimetry_Ge_histo, smeared_calorimetry_Ge_histo_VS_cristalMult, smeared_calorimetry_LaBr_histo, smeared_calorimetry_LaBr_histo_VS_cristalMult, smeared_calorimetry_NaI_histo, smeared_calorimetry_NaI_histo_VS_cristalMult, smeared_calorimetry_Paris_histo, smeared_calorimetry_Paris_histo_VS_cristalMult, spectra_NaI_trigger, spectra_trigger, spectrum_BGO, spectrum_BGO_trigger, spectrum_calorimetry, spectrum_Ge, spectrum_Ge_trigger, spectrum_LaBr3, spectrum_LaBr3_trigger, spectrum_NaI, spectrum_NaI_trigger, spectrum_smeared_calorimetry, spectrum_smeared_calorimetry_double_cascade, spectrum_smeared_calorimetry_VS_Multiplicity, timewalk_BGO, timewalk_Ge, timewalk_LaBr, timewalk_NaI, timing_VS_trigger, total_energy_per_detector.
Referenced by dispatch_workFaster, dispatch_workRoot.
static void CobaltCalorimeter::dispatch_workFaster(Hit &hit, Alignator &reader, CobaltCalorimeter &cb)
References work.
Referenced by launchFaster.
static void CobaltCalorimeter::dispatch_workRoot(Nuball2Tree &tree, Event &event, CobaltCalorimeter &cb)
References work.
Referenced by launchRoot.
void CobaltCalorimeter::Analyse()
References double_cast, PeakFitter::getBackground, PeakFitter::getMean, int_cast, labels2D_trigger, m_calo_totale, m_calo_totale_BGO, m_calo_totale_Ge, m_calo_totale_LaBr3, m_calo_totale_NaI, m_nb_missed, m_nb_trigg, m_nb_trigg_BGO, m_nb_trigg_Ge, m_nb_trigg_LaBr, m_nb_trigg_NaI, MTTHist< THist >::Merge, pauseCo, print, spectrum_smeared_calorimetry.
Referenced by launchFaster, launchRoot.
bool CobaltCalorimeter::NaI_pid(float nrj, float nrj2)
References double_cast, MTTHist< THist >::Fill, paris_pid.
bool CobaltCalorimeter::NaI_pid(Hit &hit)
References Hit::adc, double_cast, MTTHist< THist >::Fill, isParis, Hit::label, paris_pid, Hit::qdc2.
Referenced by work.
void CobaltCalorimeter::write()
References BGO_calo_VS_Clover_calo, BGO_calo_VS_smeared_calorimetry, File::c_str, calo_double_cascades_VS_multiplicity, calorimetry_BGO_histo, calorimetry_Ge_histo, calorimetry_LaBr_histo, calorimetry_NaI_histo, Clover_calo_VS_BGO_calo, Clover_calo_without_Paris, Clover_VS_smeared_calorimetry, concatenate, Ge_BGO, Ge_BGO_trigger, Ge_calo_VS_BGO_calo, Ge_calo_VS_Clover_calo, Ge_calo_VS_Paris_calo, Ge_calo_VS_smeared_calorimetry, Ge_Ge, Ge_Ge_trigger, Ge_LaBr, Ge_LaBr_trigger, Ge_NaI, Ge_NaI_trigger, Ge_VS_BGO_calorimetry, Ge_VS_smeared_calorimetry, labels2D_trigger, LaBr3_calo_VS_BGO_calo, LaBr3_calo_VS_Clover_calo, LaBr3_calo_VS_Paris_calo, LaBr_calo_VS_smeared_calorimetry, LaBr_VS_smeared_calorimetry, m_outfilename, NaI_calo_VS_BGO_calo, NaI_calo_VS_Clover_calo, NaI_calo_VS_LaBr_calo, NaI_calo_VS_Paris_calo, NaI_calo_VS_smeared_calorimetry, NaI_VS_smeared_calorimetry, Paris_calo_VS_BGO_calo, Paris_calo_VS_Clover_calo, Paris_calo_without_Clover, paris_pid, Paris_VS_smeared_calorimetry, print, File::setExtension, smeared_calorimetry_BGO_histo_VS_cristalMult, smeared_calorimetry_Clover_histo, smeared_calorimetry_Clover_histo_VS_cristalMult, smeared_calorimetry_Ge_histo, smeared_calorimetry_Ge_histo_VS_cristalMult, smeared_calorimetry_LaBr_histo, smeared_calorimetry_LaBr_histo_VS_cristalMult, smeared_calorimetry_NaI_histo, smeared_calorimetry_NaI_histo_VS_cristalMult, smeared_calorimetry_Paris_histo, smeared_calorimetry_Paris_histo_VS_cristalMult, spectra_NaI_trigger, spectra_trigger, spectrum_BGO, spectrum_BGO_trigger, spectrum_calorimetry, spectrum_Ge, spectrum_Ge_trigger, spectrum_LaBr3, spectrum_LaBr3_trigger, spectrum_NaI, spectrum_NaI_trigger, spectrum_smeared_calorimetry, spectrum_smeared_calorimetry_double_cascade, spectrum_smeared_calorimetry_VS_Multiplicity, throw_error, timewalk_BGO, timewalk_Ge, timewalk_LaBr, timewalk_NaI, timing_VS_trigger, total_energy_per_detector, MTTHist< THist >::Write.
Referenced by launchFaster, launchRoot.