Timeshifts
bool Timeshifts::m_biggest_peak_finder
Referenced by analyse, dT_with_biggest_peak_finder.
std::vector<bool> Timeshifts::m_biggest_peak_finder_label
Referenced by analyse, dT_with_biggest_peak_finder, InitialisePreferencesArrays.
std::vector<bool> Timeshifts::m_edge_preferred_label
Referenced by analyse, dT_with_raising_edge, Initialise, InitialisePreferencesArrays.
std::vector<int> Timeshifts::m_nb_shifts_RF_peak
Referenced by Initialise.
std::vector<bool> Timeshifts::m_RF_preferred_label
Referenced by analyse, dT_with_RF, Initialise, InitialisePreferencesArrays.
std::map<dType, Time_ns> Timeshifts::m_bins_per_ns
Referenced by InitialiseCorrected, InitialiseRaw, rebin.
bool Timeshifts::m_check_preprompt
Referenced by analyse, checkForPreprompt.
bool Timeshifts::m_corrected
Referenced by Fill, treatFasterFile, treatRootFile, verify.
std::map<dType, bool> Timeshifts::m_edge_preferred
Referenced by analyse, dT_with_raising_edge.
ADC Timeshifts::m_Emin_ADC
Referenced by Fill, setEminADC.
MTTHist<TH1F> Timeshifts::m_EnergyRef
Referenced by Fill, Initialise, writeRoot.
MTTHist<TH2F> Timeshifts::m_EnergyRef_bidim
bool Timeshifts::m_energySpectraInitialised
Referenced by Initialise.
std::string Timeshifts::m_filename
Referenced by Timeshifts.
FilesManager Timeshifts::m_files
bool Timeshifts::m_folder_treated
Referenced by treatFolder, verify.
MTTHist<TH1F> Timeshifts::m_histo_ref_VS_RF
Referenced by analyse, Fill, InitialiseRaw, writeRoot.
MTTHist<TH2F> Timeshifts::m_histo_ref_vs_RF_VS_mult
Referenced by InitialiseRaw, writeRoot.
Vector_MTTHist<TH1F> Timeshifts::m_histograms_VS_RF
Referenced by analyse, Fill, InitialiseRaw, verify, writeRoot.
bool Timeshifts::m_Initialised
Referenced by Initialise.
bool Timeshifts::m_InitialisedCorrected
Referenced by InitialiseCorrected.
bool Timeshifts::m_InitialisedRaw
Referenced by InitialiseRaw.
ulong Timeshifts::m_max_hits
Referenced by setMaxHits, treatFasterFile.
int Timeshifts::m_max_mult
Referenced by Fill, setMult, setParameters.
int Timeshifts::m_min_mult
Referenced by Fill, setMult, setParameters.
int Timeshifts::m_nb_detectors
Referenced by load.
bool Timeshifts::m_ok
Referenced by Initialise, load, operator bool, operator=, verify, writeData, writeRoot.
std::string Timeshifts::m_outData
Referenced by setOutData, setOutName, setParameters.
std::string Timeshifts::m_outDir
Referenced by setOutDir, setParameters, writeData, writeRoot.
Path Timeshifts::m_outPath
Referenced by writeData, writeRoot.
std::string Timeshifts::m_outRoot
Referenced by setOutName, setOutRoot, setParameters.
bool Timeshifts::m_pref_arrays_init
Referenced by InitialisePreferencesArrays.
Time Timeshifts::m_rf_period
Referenced by InitialiseCorrected, periodRF_ns, treatFasterFile.
std::map<dType, bool> Timeshifts::m_RF_preferred
Referenced by analyse, dT_with_RF.
Label Timeshifts::m_time_ref_label
Referenced by analyse, CheckParameters, Fill, setTimeReference, treatFasterFile.
std::string Timeshifts::m_time_ref_name
Referenced by CheckParameters, setParameters, setTimeReference.
Vector_MTTHist<TH1F> Timeshifts::m_time_spectra
Referenced by analyse, Fill, InitialiseRaw, verify, writeRoot.
Vector_MTTHist<TH1F> Timeshifts::m_time_spectra_corrected
Referenced by Fill, InitialiseCorrected, verify, writeRoot.
MTTHist<TH2F> Timeshifts::m_time_spectra_corrected_bidim
Referenced by Fill, InitialiseCorrected, writeRoot.
MTTHist<TH2F> Timeshifts::m_time_spectra_corrected_bidim_RF
Referenced by Fill, InitialiseCorrected, writeRoot.
Vector_MTTHist<TH1F> Timeshifts::m_time_spectra_corrected_RF
Referenced by Fill, InitialiseCorrected, verify, writeRoot.
MTTHist<TH1F> Timeshifts::m_time_spectra_reference_RF_corrected
Referenced by Fill, InitialiseCorrected.
std::vector<Time> Timeshifts::m_timeshifts
Referenced by analyse, data, get, Initialise, load, operator=, operator[], shiftTimeSpectra, treatFasterFile, treatRootFile, verify, writeData.
Time Timeshifts::m_timewindow
Referenced by InitialiseCorrected, InitialiseRaw, setTimeWindow_ns, treatFasterFile.
Time_ns Timeshifts::m_timewindow_ns
Referenced by InitialiseCorrected, InitialiseRaw, setParameters, setTimeWindow_ns.
std::string Timeshifts::m_ts_outdir
Referenced by writeData, writeRoot.
bool Timeshifts::m_use_rf
Referenced by analyse, Fill, InitialiseCorrected, InitialiseRaw, periodRF_ns, treatFasterFile, verify, writeRoot.
bool Timeshifts::m_verbose
Referenced by analyse, verbose.
bool Timeshifts::m_verification
Referenced by verification.
std::vector<Timestamp> Timeshifts::mt_ref_time
Referenced by Initialise, treatFasterFile.
bool Timeshifts::calculate(std::string const &folder, int const &nb_files=-1)
References analyse, CheckParameters, Initialise, print, treatFolder.
void Timeshifts::checkForPreprompt(bool const &check=true)
check default true.
References m_check_preprompt.
bool Timeshifts::CheckParameters()
References detectors, Detectors::exists, m_time_ref_label, m_time_ref_name, print.
Referenced by calculate.
std::vector<Time> const& Timeshifts::data() const
References m_timeshifts.
Referenced by CobaltCalorimeter::launchFaster.
void Timeshifts::dT_with_biggest_peak_finder()
References m_biggest_peak_finder.
void Timeshifts::dT_with_biggest_peak_finder(Label const &label)
References InitialisePreferencesArrays, m_biggest_peak_finder_label.
void Timeshifts::dT_with_raising_edge(dType const &type)
References m_edge_preferred.
void Timeshifts::dT_with_raising_edge(Label const &label)
References InitialisePreferencesArrays, m_edge_preferred_label.
void Timeshifts::dT_with_RF(dType const &type)
References m_RF_preferred.
void Timeshifts::dT_with_RF(Label const &label)
References InitialisePreferencesArrays, m_RF_preferred_label.
std::vector<Time> const& Timeshifts::get() const
References m_timeshifts.
Referenced by analyse, CloverSpectra::fillHisto, operator<<, verify.
Time const& Timeshifts::get(int const &i) const
References m_timeshifts.
bool Timeshifts::load(std::string const &filename)
Use this method to load timeshifts from a .dT file.
References detectors, file_is_empty, m_nb_detectors, m_ok, m_timeshifts, print, Detectors::size.
Referenced by CloverSpectra::loadTimeshifts, Faster2Root::loadTimeshifts, Timeshifts.
Timeshifts::operator bool() const &
References m_ok.
Timeshifts& Timeshifts::operator=(Timeshifts const &timeshifts)
References m_ok, m_timeshifts.
Time const& Timeshifts::operator[](int const &i) const
References m_timeshifts.
void Timeshifts::periodRF_ns(int const &period_ns)
References m_rf_period, m_use_rf.
void Timeshifts::rebin(std::string const &detector, Time_ns const &bin_size_ns)
References find_key, m_bins_per_ns, throw_error.
void Timeshifts::setEminADC(ADC const &EminADC)
References m_Emin_ADC.
void Timeshifts::setMaxHits(ulong const &max_hits=-1)
Set maximum hits to be read in a file.
Use only if calculate timeshifts
References m_max_hits.
void Timeshifts::setMult(int const &min_mult, int const &max_mult)
Set the multiplicity gate for the events used for coincidence timeshift calculation.
Mandatory only if calculate timeshifts min_mult and max_mult included. example : multiplicity = 2 : setMult(2, 2) example : multiplicity = {2;3;4} : setMult(2, 4) min_mult default min_mult = 2 max_mult default max_mult = 2
References m_max_mult, m_min_mult.
Referenced by setParameters.
void Timeshifts::setOutData(std::string const &outdata)
Use setName instead. Set output file name of the timeshifts data.
Mandatory only if calculate timeshifts If not set, it is automatically named after the root file.
References extension, m_outData, removeExtension.
Referenced by setParameters.
void Timeshifts::setOutDir(std::string const &outDir)
Set the output directory (full path);.
Mandatory only if calculate timeshifts
References m_outDir, push_back_if_none.
Referenced by setParameters.
void Timeshifts::setOutName(std::string const &outdata)
Set output file name of the timeshifts data and root file.
Mandatory only if calculate timeshifts
References m_outData, m_outRoot.
void Timeshifts::setOutRoot(std::string const &outroot)
Use setName instead. Set output root file containing the raw and corrected time spectra.
Mandatory only if calculate timeshifts
References extension, m_outRoot, removeExtension.
Referenced by setParameters.
bool Timeshifts::setParameters(std::string const &parameter)
Use this method to setup the parameters from a string in order to calculate the timeshifts.
References m_max_mult, m_min_mult, m_outData, m_outDir, m_outRoot, m_time_ref_name, m_timewindow_ns, print, removeExtension, setMult, setOutData, setOutDir, setOutRoot, setTimeReference, setTimeWindow_ns, verbose.
void Timeshifts::setRFOffset(Time const &offset_ps)
Set RF offset (synonymous to Timeshifts::setRFShift)
Use only if calculating timeshifts with RF offset default 50000 ps
References RF_Manager::set_offset.
void Timeshifts::setRFOffset_ns(Time_ns const &offset_ns)
Set RF offset (synonymous to Timeshifts::setRFShift)
Use only if calculating timeshifts with RF offset default 50 ns
References RF_Manager::set_offset, Time_cast.
void Timeshifts::setRFShift(Time const &shift)
Set RF shift (synonymous to Timeshifts::setRFOffset)
Use only if calculating timeshifts with RF shift default 50 ns
References RF_Manager::set_offset.
bool Timeshifts::setTimeReference(Label const &timeRef_label)
Set the time reference label.
Mandatory only if calculate timeshifts
References detectors, m_time_ref_label, m_time_ref_name.
Referenced by setParameters, setTimeReference.
bool Timeshifts::setTimeReference(std::string const &timeRef_name)
Set the time reference.
Mandatory only if calculate timeshifts Either the full name, or the label number
References detectors, Detectors::getLabel, isNumber, Label_cast, m_time_ref_name, setTimeReference.
bool Timeshifts::setTimeWindow_ns(std::string const &timewindow_ns_str)
Set the time window in ns.
It is better to keep it at its default value, otherwise you can miss some detectors timewindow_ns default value 1500.f ns
References setTimeWindow_ns, Time_ns_cast.
bool Timeshifts::setTimeWindow_ns(Time_ns const &timewindow_ns)
Setup the time window for the coincidence in ns.
References m_timewindow, m_timewindow_ns, print, Time_cast.
Referenced by setParameters, setTimeWindow_ns.
TH1F * Timeshifts::shiftTimeSpectra(TH1F *histo, Label const &label, std::string const &unit="ps")
References double_cast, int_cast, m_timeshifts, print, Timeshift_cast.
Timeshifts::Timeshifts()
Timeshifts::Timeshifts(const char *filename)
Call the Timeshifts::load() method to load the timeshifts from a .dT file.
References load, m_filename.
Timeshifts::Timeshifts(std::string const &filename)
Call the Timeshifts::load() method to load the timeshifts from a .dT file.
References Initialise, load, m_filename.
Timeshifts::Timeshifts(std::string const &path, std::string const &name)
For faster to root conversion only : Timeshifts::load() loads the timeshifts from a .dT file.
path The path of the out root directory (/path/to/run_name) name The name of the .dT file without the extension (e.g. run_10) Will read a file in /path/Timeshitfs/name.dT
References load, m_filename.
Timeshifts::Timeshifts(Timeshifts const &timeshifts)
Copy constructor.
void Timeshifts::verbose(bool const &_verbose=true)
Set verbosity level.
Mandatory only if calculate timeshifts It will print the fit parameters in the terminal
References m_verbose.
Referenced by setParameters.
bool const& Timeshifts::verification(bool const &verif=true)
Used to create.
Todocaption
References m_verification.
bool Timeshifts::verify(std::string const &folder, int const &nb_files=-1)
To verify an already calculated timeshift .dT data file.
References concatenate, detectors, get, Initialise, Detectors::labels, m_corrected, m_folder_treated, m_histograms_VS_RF, m_ok, m_time_spectra, m_time_spectra_corrected, m_time_spectra_corrected_RF, m_timeshifts, m_use_rf, print, shiftX, treatFolder.
void Timeshifts::write(std::string const &name)
To write down the histograms and the data.
name Will automatically create the following name as output : (name+".dT") and (name+"_dT.root")
References writeData, writeRoot.
void Timeshifts::writeData(std::string const &name)
To write down the data.
name Name of the output data file : (name+".dT")
References m_ok, m_outDir, m_outPath, m_timeshifts, m_ts_outdir, print, File::setExtension.
Referenced by write.
void Timeshifts::writeRoot(std::string const &name)
To write down the histograms.
name Name of the output data file : (name+"_dT.root")
References m_EnergyRef, m_histo_ref_VS_RF, m_histo_ref_vs_RF_VS_mult, m_histograms_VS_RF, m_ok, m_outDir, m_outPath, m_time_spectra, m_time_spectra_corrected, m_time_spectra_corrected_bidim, m_time_spectra_corrected_bidim_RF, m_time_spectra_corrected_RF, m_ts_outdir, m_use_rf, print, MTTHist< THist >::Write.
Referenced by write.
void Timeshifts::analyse()
References detectors, Detectors::exists, forced_shifts, MTTHist< THist >::get, get, PeakFitter::getMean, getMeanPeak, getRFGammaPrompt, int_cast, MTTHist< THist >::Integral, RF_Manager::label, m_biggest_peak_finder, m_biggest_peak_finder_label, m_check_preprompt, m_edge_preferred, m_edge_preferred_label, m_histo_ref_VS_RF, m_histograms_VS_RF, m_RF_preferred, m_RF_preferred_label, m_time_ref_label, m_time_spectra, m_timeshifts, m_use_rf, m_verbose, CoBazar::mean, MTTHist< THist >::Merge, print, Detectors::size, Time_cast, Timeshift_cast, Detectors::type.
Referenced by calculate.
void Timeshifts::Fill(Event const &event, RF_Manager &rf)
event
References MTTHist< THist >::Fill, Event::labels, m_corrected, m_Emin_ADC, m_EnergyRef, m_histo_ref_VS_RF, m_histograms_VS_RF, m_max_mult, m_min_mult, m_time_ref_label, m_time_spectra, m_time_spectra_corrected, m_time_spectra_corrected_bidim, m_time_spectra_corrected_bidim_RF, m_time_spectra_corrected_RF, m_time_spectra_reference_RF_corrected, m_use_rf, RF_Manager::pulse_ToF, Event::stamp, Time_cast.
Referenced by treatFasterFile, treatRootFile.
bool Timeshifts::Initialise(bool const &InitialiseRaw=false, bool const &InitialiseCorrected=false)
References detectors, MTObject::getThreadsNumber, InitialiseCorrected, InitialisePreferencesArrays, InitialiseRaw, m_edge_preferred_label, m_EnergyRef, m_energySpectraInitialised, m_Initialised, m_nb_shifts_RF_peak, m_ok, m_RF_preferred_label, m_timeshifts, mt_ref_time, print, MTTHist< THist >::reset, Detectors::size.
Referenced by calculate, Timeshifts, verify.
bool Timeshifts::InitialiseCorrected()
References detectors, Detectors::exists, m_bins_per_ns, m_InitialisedCorrected, m_rf_period, m_time_spectra_corrected, m_time_spectra_corrected_bidim, m_time_spectra_corrected_bidim_RF, m_time_spectra_corrected_RF, m_time_spectra_reference_RF_corrected, m_timewindow, m_timewindow_ns, m_use_rf, MTTHist< THist >::reset, Detectors::size, Detectors::type.
Referenced by Initialise.
void Timeshifts::InitialisePreferencesArrays()
References detectors, m_biggest_peak_finder_label, m_edge_preferred_label, m_pref_arrays_init, m_RF_preferred_label, Detectors::size.
Referenced by dT_with_biggest_peak_finder, dT_with_raising_edge, dT_with_RF, Initialise.
bool Timeshifts::InitialiseRaw()
References detectors, Detectors::exists, m_bins_per_ns, m_histo_ref_VS_RF, m_histo_ref_vs_RF_VS_mult, m_histograms_VS_RF, m_InitialisedRaw, m_time_spectra, m_timewindow, m_timewindow_ns, m_use_rf, MTTHist< THist >::reset, Detectors::size, Detectors::type.
Referenced by Initialise.
void Timeshifts::treatFasterFile(std::string const &filename)
References Hit::adc, CoincBuilder::build, Fill, get_first_RF_of_file, MTObject::getThreadIndex, isRF, Hit::label, RF_Manager::last_downscale, m_corrected, m_max_hits, m_rf_period, m_time_ref_label, m_timeshifts, m_timewindow, m_use_rf, mt_ref_time, Hit::nrj, NRJ_cast, RF_Manager::period, print, FasterReader::Read, RF_Manager::set_period_ns, Hit::stamp.
Referenced by treatFile.
void Timeshifts::treatFile(std::string const &filename)
References extension, treatFasterFile, treatRootFile.
Referenced by treatFilesMT, treatFolder.
void Timeshifts::treatFolder(std::string const &folder, int const &nb_files=-1)
References FilesManager::addFolder, FilesManager::getListFiles, MTObject::getThreadsNb, m_folder_treated, FilesManager::nextFileName, MTObject::ON, MTObject::parallelise_function, print, treatFile, treatFilesMT.
Referenced by calculate, verify.
void Timeshifts::treatRootFile(std::string const &filename)
References Fill, get_first_RF_of_file, m_corrected, m_timeshifts.
Referenced by treatFile.
void Timeshifts::treatFilesMT(Timeshifts &ts, MTList &files_MT)
References MTVector< T >::getNext, treatFile.
Referenced by treatFolder.