Event
ADC Event::adcs[255][255]
Referenced by adc, Event, Calibrator::fillRootDataHisto, operator<<, operator=, operator[], push_back, push_front, reading, writting.
Label Event::labels[255][255]
Referenced by Event, Timeshifts::Fill, Paris::Fill, label, Faster2Root::loadTriggerFile, operator=, operator[], push_back, push_front, reading, Sorted_Event::sortEvent, writting.
int Event::mult
Referenced by CoincBuilder::build, EventBuilder::build, clear, Event, isEmpty, isSingle, operator=, push_back, push_front, reading, size, timeShift, timeShift_ns, CobaltCalorimeter::work, writting.
NRJ Event::nrj2s[255][255]
Referenced by Event, ParisPhoswitch::Fill, nrj2, operator<<, operator=, operator[], push_back, push_front, reading, writting.
NRJ Event::nrjs[255][255]
Referenced by Event, ParisPhoswitch::Fill, nrj, operator<<, operator=, operator[], push_back, push_front, reading, writting.
Pileup Event::pileups[255][255]
Referenced by Event, RunMatrixator::fillMatrixes, operator<<, operator=, pileup, push_back, push_front, reading, writting.
ADC Event::qdc2s[255][255]
Referenced by Event, Calibrator::fillRootDataHisto, operator<<, operator=, operator[], push_back, push_front, qdc2, reading, writting.
IOptions Event::read
Referenced by isCalibrated, operator=, reading, Sorted_Event::sortEvent, Sorted_Event::sortGeClover, time_ns.
Timestamp Event::stamp
Referenced by Timeshifts::Fill, operator<<, operator=, operator[], push_back, push_front, reading, setT0, writting.
Time_ns Event::time2s[255][255]
Referenced by Event, Clovers::Fill, Clovers::FillFast, operator<<, operator=, reading, Sorted_Event::sortEvent, time2, time_ns, timeShift_ns, writting.
Time Event::times[255][255]
Referenced by Event, ParisPhoswitch::Fill, Clovers::Fill, Clovers::FillFast, operator<<, operator=, operator[], push_back, push_front, reading, time, time_ns, timeShift, writting.
IOptions Event::write
Referenced by isCalibrated, operator=, writting.
bool Event::isReading
Referenced by isCalibrated, operator=, reading, writting.
bool Event::isWritting
Referenced by isCalibrated, operator=, reading, writting.
size_t Event::m_maxSize
Referenced by maxSize.
auto& Event::adc(int const &hit_i)
References adcs.
void Event::clear()
References mult.
Referenced by Builder::reset.
Event::Event()
Event::Event(Event const &event)
References adcs, labels, mult, nrj2s, nrjs, pileups, qdc2s, time2s, times.
Event::Event(Hit const &hit)
Event::Event(TTree *tree)
References reading.
Event::Event(TTree *tree, std::string const &options)
References reading.
bool Event::isCalibrated() const
References IOptions::e, IOptions::E, isReading, isWritting, print, read, write.
bool Event::isEmpty() const
References mult.
bool Event::isSingle() const
References mult.
Referenced by Builder::isSingle.
auto& Event::label(int const &hit_i)
References labels.
size_t const& Event::maxSize() const
References m_maxSize.
auto& Event::nrj(int const &hit_i)
References nrjs.
auto& Event::nrj2(int const &hit_i)
References nrj2s.
Event & Event::operator=(Event const &evt)
References adcs, IOptions::e, IOptions::E, isReading, isWritting, IOptions::l, labels, mult, nrj2s, nrjs, IOptions::p, pileups, IOptions::q, IOptions::Q, qdc2s, read, IOptions::s, stamp, IOptions::t, IOptions::T, time2s, times, write.
Event & Event::operator=(Hit const &hit)
References Hit::adc, adcs, Hit::label, labels, mult, Hit::nrj, Hit::nrj2, nrj2s, nrjs, Hit::pileup, pileups, Hit::qdc2, qdc2s, stamp, Hit::stamp, times.
Hit Event::operator[](int const &hit_i)
References Hit::adc, adcs, Hit::label, labels, Hit::nrj, Hit::nrj2, nrj2s, nrjs, Hit::qdc2, qdc2s, stamp, Hit::stamp, times.
auto& Event::pileup(int const &hit_i)
References pileups.
void Event::Print() const
References print.
void Event::push_back(Hit const &hit)
References Hit::adc, adcs, Hit::label, labels, mult, Hit::nrj, Hit::nrj2, nrj2s, nrjs, Hit::pileup, pileups, print, Hit::qdc2, qdc2s, stamp, Hit::stamp, Time_cast, times.
void Event::push_front(Hit const &hit)
Sometimes, we want to select pre-prompt events. In such case, we have to put in in front of the others.
About the timestamp of the event, we keep the same as this additionnal event is located before the first hit that really represents the "0" of the event
References Hit::adc, adcs, Hit::label, labels, mult, Hit::nrj, Hit::nrj2, nrj2s, nrjs, Hit::pileup, pileups, print, Hit::qdc2, qdc2s, stamp, Hit::stamp, Time_cast, times.
auto& Event::qdc2(int const &hit_i)
References qdc2s.
void Event::reading(TTree *tree)
Automatically set branches based on the presence or not of branches in the root tree. Reserved for "Nuball2" type of trees.
References adcs, IOptions::e, IOptions::E, isReading, isWritting, IOptions::l, labels, mult, nrj2s, nrjs, IOptions::p, pileups, print, IOptions::q, IOptions::Q, qdc2s, read, IOptions::s, stamp, IOptions::t, IOptions::T, time2s, times.
Referenced by Event, Calibrator::fillRootDataHisto.
void Event::reading(TTree *tree, std::string const &options)
References adcs, IOptions::e, IOptions::E, isReading, isWritting, IOptions::l, labels, mult, nrj2s, nrjs, IOptions::p, pileups, print, IOptions::q, IOptions::Q, qdc2s, read, IOptions::s, IOptions::setOptions, stamp, IOptions::t, IOptions::T, time2s, times.
void Event::setT0(Timestamp const &timestamp)
References stamp, Time_cast, timeShift.
size_t Event::size() const
References mult, size_cast.
auto& Event::time(int const &hit_i)
References times.
auto& Event::time2(int const &hit_i)
References time2s.
Time_ns Event::time_ns(int const &i) const
References read, IOptions::T, time2s, Time_ns_cast, times.
void Event::timeShift(Time const &shift)
References mult, times.
Referenced by setT0.
void Event::timeShift_ns(double const &shift)
References mult, time2s.
void Event::writting(TTree *tree, std::string const &options="lstTeEqQ")
References adcs, createBranch, createBranchArray, IOptions::e, IOptions::E, isReading, isWritting, IOptions::l, labels, mult, nrj2s, nrjs, IOptions::p, pileups, print, IOptions::q, IOptions::Q, qdc2s, IOptions::s, IOptions::setOptions, stamp, IOptions::t, IOptions::T, time2s, times, write.