CloverSpectra
char CloverSpectra::dataKind
Referenced by fillHisto.
Calibration CloverSpectra::m_calibration
Referenced by fillHisto, loadCalibration, runFasterReader, setCalibration.
MTTHist<TH1F> CloverSpectra::m_clovers
Referenced by Initialize, runFasterReader, writeHisto.
MTTHist<TH2F> CloverSpectra::m_clovers_bidim
Referenced by Initialize, runFasterReader, writeHisto.
MTTHist<TH1F> CloverSpectra::m_clovers_crystal
Referenced by Initialize, runFasterReader, writeHisto.
Path CloverSpectra::m_dataPath
Referenced by fillHisto, setDataPath.
int CloverSpectra::m_nb_files
Referenced by fillHisto, setNbFiles.
int CloverSpectra::m_nb_threads
Referenced by Initialize, setNbThreads.
File CloverSpectra::m_outName
Referenced by setOutName, writeHisto.
bool CloverSpectra::m_throw_single
Referenced by Initialize.
Timeshifts CloverSpectra::m_timeshifts
Referenced by fillHisto, loadTimeshifts, setTimeshifts.
Time CloverSpectra::m_timewindow
Referenced by runFasterReader, setTimeWindow_ns.
bool CloverSpectra::m_writeHisto
Referenced by Initialize, setOutName.
CloverSpectra::CloverSpectra()=default
CloverSpectra::CloverSpectra(int argc, char **argv)
References Initialize.
void CloverSpectra::fillHisto(std::string const &datapath="", int nb_files=-1)
References dataKind, Timeshifts::get, m_calibration, m_dataPath, m_nb_files, m_timeshifts, MTFasterReader::readAligned, runMTFasterReader, Path::string, throw_error.
Referenced by Initialize.
void CloverSpectra::Initialize()
References MTObject::Initialize, Builder::keepSingles, m_clovers, m_clovers_bidim, m_clovers_crystal, m_nb_threads, m_throw_single, MTTHist< THist >::reset, Clovers::timePs.
Referenced by CloverSpectra, Initialize.
void CloverSpectra::Initialize(int argc, char **argv)
References detectors, fillHisto, Initialize, Detectors::load, loadCalibration, loadTimeshifts, m_throw_single, m_writeHisto, print, printParameters, setDataPath, FasterReader::setMaxHits, setNbFiles, setNbThreads, setOutName, setTimeWindow_ns, throw_error, writeHisto.
void CloverSpectra::loadCalibration(std::string const &calibFile)
References Calibration::load, m_calibration.
Referenced by Initialize.
void CloverSpectra::loadTimeshifts(std::string const &dTfile)
References Timeshifts::load, m_timeshifts.
Referenced by Initialize.
void CloverSpectra::printParameters()
References print.
Referenced by Initialize.
void CloverSpectra::setCalibration(Calibration const &calibration)
References m_calibration.
void CloverSpectra::setDataPath(std::string const &datapath)
References m_dataPath.
Referenced by Initialize.
void CloverSpectra::setNbFiles(int const &nb_files=-1)
References m_nb_files.
Referenced by Initialize.
void CloverSpectra::setNbThreads(int const &nb_threads=-1)
References m_nb_threads.
Referenced by Initialize.
void CloverSpectra::setOutName(std::string const &outname)
References m_outName, m_writeHisto.
Referenced by Initialize.
void CloverSpectra::setTimeshifts(Timeshifts const &timeshifts)
References m_timeshifts.
void CloverSpectra::setTimeWindow_ns(int const &timewindow=1500)
References m_timewindow.
Referenced by Initialize.
void CloverSpectra::writeHisto(std::string const &outName="")
References File::c_str, m_clovers, m_clovers_bidim, m_clovers_crystal, m_outName, print, throw_error, MTTHist< THist >::Write.
Referenced by Initialize.
void CloverSpectra::runFasterReader(Hit &hit, Alignator &tree)
References CoincBuilder::build, MTTHist< THist >::Fill, Clovers::Ge, Alignator::GetEntry, isClover, isGe, Hit::label, m_calibration, m_clovers, m_clovers_bidim, m_clovers_crystal, m_timewindow, Hit::nrj, print, Clovers::SetEvent, StaticVector< T >::size.
Referenced by runMTFasterReader.
static void CloverSpectra::runMTFasterReader(Hit &hit, Alignator &tree, CloverSpectra &ce)
References runFasterReader.
Referenced by fillHisto.