Detectors
Strings Detectors::types_handled
Referenced by makeArrays.
Bools Detectors::m_exists
Referenced by exists, getExistsArray, makeArrays, readFile, resize.
std::string Detectors::m_filename
Referenced by file, readFile.
bool Detectors::m_Initialised
std::unordered_map<dType, Label_vec> Detectors::m_labels
Referenced by label, makeArrays.
std::unordered_map<std::string, Label> Detectors::m_labels_map
Referenced by getLabel, getLabelsMap, label, operator[], readFile.
std::vector<Label> Detectors::m_labels_vector
Referenced by labels, readFile.
Strings Detectors::m_list
Referenced by begin, end, get, getName, list, makeArrays, names, operator[], readFile, resize, size.
bool Detectors::m_loaded
Referenced by makeArrays, readFile.
std::unordered_map<dType, Strings> Detectors::m_names
Referenced by makeArrays, name.
ushort Detectors::m_nb_detectors
Referenced by makeArrays, number.
bool Detectors::m_ok
Referenced by operator bool, readFile.
std::unordered_map<dType, int> Detectors::m_type_counter
Referenced by makeArrays, nbOfType.
Strings Detectors::m_types
Referenced by makeArrays, nbOfType, resize, type, typesArray.
Strings Detectors::m_types_ID
Referenced by getTypeName, makeArrays, nbTypes, types.
std::unordered_map<dType, int> Detectors::m_types_index
Referenced by makeArrays, typeIndex.
std::unordered_map< dType, THBinning > Detectors::ADC_bins
Referenced by ADCBin, getADCBin.
std::unordered_map< dType, THBinning > Detectors::energy_bidim_bins
Referenced by energyBidimBin, getBidimBin.
std::unordered_map< dType, THBinning > Detectors::energy_bins
Referenced by energyBin, getEnergyBin.
auto Detectors::begin()
References m_list.
auto Detectors::begin() const
References m_list.
Detectors::Detectors()
auto Detectors::end()
References m_list.
auto Detectors::end() const
References m_list.
bool Detectors::exists(Label const &label)
Does this label correspond to a detector ?
References label, m_exists.
Referenced by Timeshifts::analyse, Timeshifts::CheckParameters, RunMatrixator::fillMatrixes, Timeshifts::InitialiseCorrected, Timeshifts::InitialiseRaw, Calibrator::peakFinder, Calibrator::writeData.
auto const& Detectors::file()
References m_filename.
auto const& Detectors::file() const
References m_filename.
auto const& Detectors::get() const
References m_list.
auto const& Detectors::getExistsArray() const
References m_exists.
auto const& Detectors::getLabel(std::string const &name)
References m_labels_map, name.
Referenced by Timeshifts::setTimeReference.
auto const& Detectors::getLabelsMap() const
References m_labels_map.
auto const& Detectors::getName(Label const &label)
References label, m_list.
auto const& Detectors::getTypeName(int const &type_i) const
References m_types_ID.
auto const& Detectors::index(Label const &label) const
Get the type index of the detector. Each type of detector has its own indexing system if you have 3 Germaniums, the Ge indexes ranges from 0 to 2)
References label, m_index.
Referenced by RunMatrixator::fillMatrixes, label, makeArrays, name.
auto const& Detectors::label(dType const &type, int const &index)
Get the global label of a detector given its type and type index.
References index, m_labels, type.
auto const& Detectors::label(std::string const &name)
References m_labels_map, name.
Referenced by exists, getName, index, Calibrator::histograms::Initialise, RunMatrixator::Initialise, makeArrays, operator[], readFile, type, typeIndex.
auto const& Detectors::labels() const
References m_labels_vector.
Referenced by Calibrator::analyse2, Timeshifts::verify, Calibrator::verify.
auto const& Detectors::list() const
References m_list.
void Detectors::load(std::string const &filename)
Reads the file and extracts the list of detectors, then fills the lookup tables.
References makeArrays, readFile.
Referenced by CloverSpectra::Initialise, CobaltCalorimeter::launchFaster, CobaltCalorimeter::launchRoot, Faster2Root::load, Faster2Histo::load, EvolutionPeaks::loadDetectors, operator=, NearLine::readParam.
void Detectors::makeArrays()
Fills the lookup tables.
References clover_pos, compressedLabel, index, int_cast, isBack, isBGO, isClover, isDSSD, isEden, isFront, isGe, isLaBr3, isParis, isRF, isRing, isS1, isS2, isSector, label, labelToClover, m_exists, m_index, m_labels, m_list, m_loaded, m_names, m_nb_detectors, m_type_counter, m_types, m_types_ID, m_types_index, replaceCharacter, size, type, types_handled, uchar_cast.
Referenced by load.
auto const& Detectors::name(dType const &type, int const &index)
Get the name of a detector given its type and type index.
References index, m_names, type.
Referenced by getLabel, Calibrator::histograms::Initialise, RunMatrixator::Initialise, label, operator[], readFile.
auto const& Detectors::names() const
References m_list.
Referenced by loadFormattedTH1F.
auto const& Detectors::nbOfType(dType const &type)
Returns the number of detector of each type.
References found, m_type_counter, m_types, throw_error, type.
Referenced by Calibrator::histograms::Initialise, RunMatrixator::Initialise.
auto Detectors::nbTypes()
Returns the number of types in the ID file.
References m_types_ID.
Referenced by Calibrator::histograms::Initialise, RunMatrixator::Initialise_dontMatrixate, Calibrator::verify.
auto Detectors::nbTypes() const
References m_types_ID.
auto const& Detectors::number()
Return the number of detectors.
References m_nb_detectors.
Detectors::operator bool() const &
Returns true only of the detectors ID file has been loaded successfully.
References m_ok.
void Detectors::operator=(std::string const &filename)
References load.
auto const& Detectors::operator[](Label const &label) const
Extracts the name of the detector given its global label.
References label, m_list.
auto const& Detectors::operator[](std::string const &name)
Extracts the global label given the detector's name.
References m_labels_map, name.
void Detectors::Print()
Prints out the list of labels.
void Detectors::readFile(std::string const &file)
Reads the file and extracts the list of detectors.
References concatenate, error, file_is_empty, label, m_exists, m_filename, m_labels_map, m_labels_vector, m_list, m_loaded, m_ok, name, print, Bools::resize, size.
Referenced by load.
void Detectors::resize(ushort const &new_size)
References m_exists, m_list, m_types, print, Bools::resize.
Referenced by Calibration::load.
Label Detectors::size() const
Return the value of the maximum label, i.e. the size of the lookup tables.
References Label_cast, m_list.
Referenced by Timeshifts::analyse, Calibrator::fitCalibration, Calibrator::histograms::Initialise, Timeshifts::Initialise, RunMatrixator::Initialise_dontMatrixate, Timeshifts::InitialiseCorrected, Timeshifts::InitialisePreferencesArrays, Timeshifts::InitialiseRaw, Calibration::load, Timeshifts::load, makeArrays, Calibrator::peakFinder, readFile.
auto const& Detectors::type(Label const &label)
References label, m_types.
Referenced by ADCBin, Timeshifts::analyse, energyBidimBin, energyBin, RunMatrixator::fillMatrixes, Timeshifts::InitialiseCorrected, Timeshifts::InitialiseRaw, label, makeArrays, name, nbOfType, Calibrator::peakFinder, typeIndex, Calibrator::verify.
auto const& Detectors::typeIndex(dType const &type)
References m_types_index, type.
Referenced by Calibrator::fillHisto, Calibrator::fillRootDataHisto, Calibrator::histograms::Initialise, Calibrator::verify.
auto const& Detectors::typeIndex(Label const &label)
References label, m_types_index, type.
auto const& Detectors::types() const
References m_types_ID.
Referenced by RunMatrixator::dontMatrixate, Calibrator::histograms::Initialise, RunMatrixator::Initialise, RunMatrixator::Initialise_dontMatrixate.
auto const& Detectors::typesArray() const
References m_types.
Referenced by RunMatrixator::dontMatrixate.
static auto const& Detectors::ADCBin(dType const &type="")
Get the default ADC histogram binning for each type of detectors.
References ADC_bins, type.
Referenced by Calibrator::histograms::Initialise.
static auto const& Detectors::energyBidimBin(dType const &type="")
Get the default energy (keV) bidimensionnal histogram binning for each type of detectors.
References energy_bidim_bins, type.
Referenced by Calibrator::histograms::Initialise, RunMatrixator::Initialise.
static auto const& Detectors::energyBin(dType const &type="")
Get the default energy (keV) histogram binning for each type of detectors.
References energy_bins, type.
Referenced by Calibrator::histograms::Initialise, RunMatrixator::Initialise.
static auto& Detectors::getADCBin()
Get the default energy (keV) bidimensionnal histogram binning for all types of detectors.
References ADC_bins.
Referenced by Calibrator::histograms::setTypeBins.
static auto& Detectors::getBidimBin()
Get the default energy (keV) bidimensionnal histogram binning for all types of detectors.
References energy_bidim_bins.
static auto& Detectors::getEnergyBin()
Get the default energy (keV) bidimensionnal histogram binning for all types of detectors.
References energy_bins.
Referenced by Calibrator::histograms::setTypeBins.