MTTHist
std::vector<THist*> MTTHist< THist >::m_collection
Referenced by MTTHist< THist >::clean, MTTHist< THist >::cleanMove, MTTHist< THist >::Get, MTTHist< THist >::getCollection, MTTHist< THist >::MTTHist, MTTHist< THist >::operator[], MTTHist< THist >::reset, MTTHist< THist >::size.
std::string MTTHist< THist >::m_comment
Referenced by MTTHist< THist >::clean, MTTHist< THist >::cleanMove, MTTHist< THist >::readComment, MTTHist< THist >::reset, MTTHist< THist >::setComment.
bool MTTHist< THist >::m_exists
Referenced by MTTHist< THist >::clean, MTTHist< THist >::cleanMove, MTTHist< THist >::exists, MTTHist< THist >::MTTHist, MTTHist< THist >::operator bool, MTTHist< THist >::reset.
ulonglong MTTHist< THist >::m_integral
Referenced by MTTHist< THist >::clean, MTTHist< THist >::cleanMove, MTTHist< THist >::Integral, MTTHist< THist >::MTTHist, MTTHist< THist >::reset.
bool MTTHist< THist >::m_is_merged
Referenced by MTTHist< THist >::clean, MTTHist< THist >::cleanMove, MTTHist< THist >::MTTHist, MTTHist< THist >::reset.
THist* MTTHist< THist >::m_merged
Referenced by MTTHist< THist >::clean, MTTHist< THist >::cleanMove, MTTHist< THist >::get, MTTHist< THist >::MTTHist, MTTHist< THist >::operator->, MTTHist< THist >::reset.
bool MTTHist< THist >::m_merged_deleted
std::mutex MTTHist< THist >::m_mutex
Referenced by MTTHist< THist >::mutex.
std::string MTTHist< THist >::m_name
Referenced by MTTHist< THist >::clean, MTTHist< THist >::cleanMove, MTTHist< THist >::GetName, MTTHist< THist >::MTTHist, MTTHist< THist >::name, MTTHist< THist >::operator->, MTTHist< THist >::reset, MTTHist< THist >::setName.
bool MTTHist< THist >::m_outscope
Referenced by MTTHist< THist >::MTTHist.
std::string MTTHist< THist >::m_title
Referenced by MTTHist< THist >::MTTHist, MTTHist< THist >::setTitle, MTTHist< THist >::title.
bool MTTHist< THist >::m_written
Referenced by MTTHist< THist >::clean, MTTHist< THist >::cleanMove, MTTHist< THist >::reset.
bool MTTHist< THist >::m_verbose
Referenced by MTTHist< THist >::verbose, MTTHist< THist >::verbosity.
void MTTHist< THist >::clean()
References MTTHist< THist >::m_collection, MTTHist< THist >::m_comment, MTTHist< THist >::m_exists, MTTHist< THist >::m_integral, MTTHist< THist >::m_is_merged, MTTHist< THist >::m_merged, MTTHist< THist >::m_name, MTTHist< THist >::m_written.
Referenced by MTTHist< THist >::MTTHist.
void MTTHist< THist >::cleanMove()
References MTTHist< THist >::m_collection, MTTHist< THist >::m_comment, MTTHist< THist >::m_exists, MTTHist< THist >::m_integral, MTTHist< THist >::m_is_merged, MTTHist< THist >::m_merged, MTTHist< THist >::m_name, MTTHist< THist >::m_written, MTObject::ON.
bool const& MTTHist< THist >::exists() const
References MTTHist< THist >::m_exists.
void MTTHist< THist >::Fill(ARGS &&... args) noexcept
References MTObject::getThreadIndex.
Referenced by Timeshifts::Fill, RunMatrixator::fillMatrixes, CobaltCalorimeter::NaI_pid, CloverSpectra::runFasterReader, CobaltCalorimeter::work.
THist* MTTHist< THist >::get()
References MTTHist< THist >::m_merged.
Referenced by Timeshifts::analyse, operator<<, Calibrator::peakFinder.
THist* MTTHist< THist >::Get()
References MTObject::getThreadIndex, MTTHist< THist >::m_collection.
THist* MTTHist< THist >::get() const
References MTTHist< THist >::m_merged.
THist* MTTHist< THist >::Get(ushort const &thread_nb)
References MTTHist< THist >::m_collection.
auto MTTHist< THist >::GetBinContent(ARGS &&... args) noexcept
References MTObject::getThreadIndex.
Referenced by CobaltCalorimeter::work.
std::vector<THist*>& MTTHist< THist >::getCollection()
References MTTHist< THist >::m_collection.
std::vector<THist*> const& MTTHist< THist >::getCollection() const
References MTTHist< THist >::m_collection.
Referenced by operator<<.
std::string const& MTTHist< THist >::GetName() const
References MTTHist< THist >::m_name.
auto const& MTTHist< THist >::Integral() const
References MTTHist< THist >::m_integral.
Referenced by Timeshifts::analyse, operator<<.
THist * MTTHist< THist >::Merge()
Merges the histograms.
Can merge only once
References debug, MTObject::ON.
Referenced by CobaltCalorimeter::Analyse, Timeshifts::analyse, MTTHist< THist >::operator->.
THist* MTTHist< THist >::Merge() const
void MTTHist< THist >::Merge_t()
THist * MTTHist< THist >::Merged()
References debug.
MTTHist< THist >::MTTHist()
Default initialisator.
References MTTHist< THist >::reset.
MTTHist< THist >::MTTHist(ARGS &&... args)
Construct a new MTTHist object and send the arguments directly to the underlying root histogramm.
References MTTHist< THist >::reset.
MTTHist< THist >::MTTHist(MTTHist< THist > &&hist)
Move constructor.
MTTHist< THist >::MTTHist(MTTHist< THist > const &hist)
Copy constructor.
References MTTHist< THist >::clean, MTTHist< THist >::m_collection, MTTHist< THist >::m_exists, MTTHist< THist >::m_integral, MTTHist< THist >::m_is_merged, MTTHist< THist >::m_merged, MTTHist< THist >::m_name, MTTHist< THist >::m_outscope, MTTHist< THist >::m_title.
MTTHist< THist >::MTTHist(THist *hist)
Wrapper around an already existing histograms.
References MTTHist< THist >::m_collection, MTTHist< THist >::m_exists, MTTHist< THist >::m_integral, MTTHist< THist >::m_is_merged, MTTHist< THist >::m_merged, MTTHist< THist >::m_name, MTTHist< THist >::m_outscope, MTTHist< THist >::m_title.
auto& MTTHist< THist >::mutex()
References MTTHist< THist >::m_mutex.
std::string& MTTHist< THist >::name()
References MTTHist< THist >::m_name.
std::string const& MTTHist< THist >::name() const
References MTTHist< THist >::m_name.
Referenced by MTTHist< THist >::CopyError::CopyError, operator<<.
MTTHist< THist >::operator bool() const &
References MTTHist< THist >::m_exists.
THist* MTTHist< THist >::operator->()
References debug, MTTHist< THist >::m_merged, MTTHist< THist >::m_name, MTTHist< THist >::Merge.
THist* MTTHist< THist >::operator->() const
References MTTHist< THist >::m_merged.
MTTHist<THist>& MTTHist< THist >::operator=(MTTHist< THist > const &hist)
References MTTHist< THist >::reset.
void MTTHist< THist >::operator=(THist *hist)
THist* MTTHist< THist >::operator[](int const &thread_nb)
References MTTHist< THist >::m_collection.
void MTTHist< THist >::Print()
References print.
std::string const& MTTHist< THist >::readComment() const
References MTTHist< THist >::m_comment.
MTTHist<THist>& MTTHist< THist >::reset(MTTHist< THist > const &hist)
Copy Initialiser.
References MTTHist< THist >::m_collection, MTTHist< THist >::m_comment, MTTHist< THist >::m_exists, MTTHist< THist >::m_integral, MTTHist< THist >::m_is_merged, MTTHist< THist >::m_merged, MTTHist< THist >::m_name, MTTHist< THist >::m_written.
Referenced by Calibrator::histograms::Initialise, CloverSpectra::Initialise, CobaltCalorimeter::Initialise, RunMatrixator::Initialise, Timeshifts::Initialise, Timeshifts::InitialiseCorrected, Timeshifts::InitialiseRaw, MTTHist< THist >::MTTHist, MTTHist< THist >::operator=.
void MTTHist< THist >::reset(std::nullptr_t)
References MTTHist< THist >::m_collection, MTTHist< THist >::m_exists, MTTHist< THist >::m_merged, MTObject::ON.
void MTTHist< THist >::reset(std::string name, ARGS &&... args)
References MTObject::getThreadIndex, MTObject::getThreadsNb, MTObject::isMasterThread, MTObject::ON.
void MTTHist< THist >::SetBinContent(ARGS &&... args) noexcept
References MTObject::getThreadIndex.
Referenced by CobaltCalorimeter::work.
void MTTHist< THist >::setComment(std::string const &comment)
References MTTHist< THist >::m_comment.
std::string const& MTTHist< THist >::setName(std::string const &_name)
References MTTHist< THist >::m_name.
std::string const& MTTHist< THist >::setTitle(std::string const &_title)
References MTTHist< THist >::m_title.
auto MTTHist< THist >::size() const
References MTTHist< THist >::m_collection.
Referenced by operator<<.
std::string& MTTHist< THist >::title()
References MTTHist< THist >::m_title.
std::string const& MTTHist< THist >::title() const
References MTTHist< THist >::m_title.
void MTTHist< THist >::Write()
MTTHIST_MONO.
References MTObject::isMasterThread, MTObject::ON, print.
Referenced by CobaltCalorimeter::write, RunMatrixator::Write, CloverSpectra::writeHisto, Calibrator::writeRawRoot, Timeshifts::writeRoot.
MTTHist< THist >::~MTTHist()
static bool const& MTTHist< THist >::verbose(bool const &_verbose=true)
References MTTHist< THist >::m_verbose.
static bool& MTTHist< THist >::verbosity()
References MTTHist< THist >::m_verbose.