Paris
std::array< uchar, 1000 > Paris::cluster
Referenced by InitialiseArrays.
std::array< uchar, 1000 > Paris::index
Referenced by Fill, InitialiseArrays.
std::array< bool, 1000 > Paris::is
Referenced by InitialiseArrays.
ParisCluster<28> Paris::clusterBack
Referenced by Analyse, back, Fill, Initialise, Reset.
ParisCluster<36> Paris::clusterFront
Referenced by Analyse, Fill, front, Initialise, Reset.
StaticVector<uchar> Paris::Hits
bool Paris::s_initialised
Referenced by InitialiseArrays.
bool Paris::m_initialised
Referenced by Initialise.
void Paris::calculateBidimAngles(std::string file, std::string const &outfilename, bool write_graphs=true)
References findAngles, print, remove, ParisBidimAngles::set, CoProgressBar< T >::show, ParisBidimAngles::write.
std::pair< double, double > Paris::findAngles(TH2F *bidim, int nb_bins=10, bool write_graphs=false)
References concatenate, findNextBinAbove, findNextBinBelow, PeakFitter::getMean, maximum.
Referenced by calculateBidimAngles, findAnglesDeg.
std::pair< double, double > Paris::findAnglesDeg(TH2F *bidim, int nb_bins=10, bool write_graphs=false)
References findAngles.
static void Paris::InitialiseArrays()
References cluster, index, is, is_paris, label_to_index, MTObject::mutex, paris_labels, print, s_initialised.
Referenced by Paris.
static bool Paris::is_paris(Label const &l)
References paris_labels.
Referenced by InitialiseArrays, label_to_index.
static uchar Paris::label_to_index(Label const &l)
References is_paris, paris_labels.
Referenced by InitialiseArrays.
TH2F * Paris::rotate(TH2F *bidim, double angleLaBr, double angleNaI, bool quickNdirty=false)
References concatenate, print, throw_error.
void Paris::Analyse()
References ParisCluster< nb_phoswitch >::Analyse, clusterBack, clusterFront.
Referenced by EventAnalyse::Set.
auto& Paris::back()
References clusterBack.
void Paris::Fill(Event const &event, size_t const &i)
References clusterBack, clusterFront, ParisCluster< nb_phoswitch >::Fill, index, Event::labels.
auto& Paris::front()
References clusterFront.
void Paris::Initialise()
References clusterBack, clusterFront, ParisCluster< nb_phoswitch >::Initialise, m_initialised.
Referenced by EventAnalyse::EventAnalyse.
Paris::Paris()
References InitialiseArrays.
void Paris::Reset()
References clusterBack, clusterFront, ParisCluster< nb_phoswitch >::Reset.