Calibrator
Path Calibrator::dataPath
Calibration Calibrator::m_calib
Referenced by calib, calibration, fillRootDataHisto, loadCalibration, verify.
bool Calibrator::m_calibrate_data
Referenced by calibrate_data, calibrateFasterData, calibrateRootData, fillRootDataHisto.
Fits Calibrator::m_fits
Referenced by analyse, Initialise, peakFinder, verify, writeData, writePosPeaks.
bool Calibrator::m_histo_loaded
Referenced by loadRootHisto, verify.
bool Calibrator::m_Initialised
Referenced by Initialise.
std::map<int, int> Calibrator::m_nb_bins_below
Referenced by analyse2, loadFitInfo.
std::string Calibrator::m_outCalib
std::string Calibrator::m_outDir
std::string Calibrator::m_outRoot
bool Calibrator::m_outRoot_b
std::map<int, int> Calibrator::m_rebin
Referenced by analyse2, loadFitInfo.
bool Calibrator::m_residus
std::string Calibrator::m_source
Referenced by setSource.
std::map<int, double> Calibrator::m_threshold
Referenced by analyse2, loadFitInfo.
bool Calibrator::m_verbose
Referenced by fitCalibration, peakFinder, verbose, verify.
TFile* Calibrator::readFile
Referenced by loadRootHisto, ~Calibrator.
bool Calibrator::m_treatOnlyGe
Referenced by peakFinder, treatOnlyGe.
bool Calibrator::m_treatOnlyParis
Referenced by peakFinder, treatOnlyParis.
struct Calibrator::histograms Calibrator::m_histos
Referenced by analyse2, fillRootDataHisto, Initialise, loadRootHisto, peakFinder, verify, writeCalibratedHisto, writeRawRoot.
void Calibrator::analyse(std::string const &source="152Eu")
Analyse the spectra to extract calibration coefficients.
The peak finding follows the following principle : We start from the bin at the very right side of the spectra. Then we add the value of the bin to the integral counter. Then we add the value of the next bin on the left, then the next, etc.. That is, we integrate the spectra from right to left The moment the first peak is found, the higher energy one, the integral will suddenly increase Then we have to determine a threshold above which we say "we have found the first peak" From this we determine a really rough first linear calibration. This allows us to find, for each other peak, an energy windows in which it should be. Once this window established, we find its centroid. Then we create a smaller window and find again the centroid. A third window (which may not me important ?) event narrower is set around the peak. Then the peak is fitted and the mean value of the gaussian fit added to the calibration curve. Finally, the fit of the calibration curve gives the calibration coefficients. The threshold is taken as the ratio between the integral and the total integral of the spectra, so that the process do not depend neither on different counting rates nor on different calibration duration. Only issue : it depends on the kind of detector and to some extend to the geometry. That is, this calibration is not well suited for paris detectors... Also, if a peak is absent due to for instance high energy threshold of the detector (typically 121keV of 152Eu is absent in some noisy channels) then the calibration will fail The most difficult part is to find the value of the threshold, wich must be different for each kind of detector. If it is different for differents detectors of the same type (e.g. paris) then the calibration requires additionnal work. Take care of the binning of the spectra. If there is too much or not enough bins then the peak fitting will fail, if the maximum ADC value is lower than the higher energy peak then the peak findind will fail. Also, everything supposes the minimum bin corresponds to 0, otherwise it might fail.
References fitCalibration, m_fits, peakFinder, print.
Referenced by calculate.
void Calibrator::analyse2(std::vector< double > peaks)
Uses the second version of the peak finder to extract calibration coefficients.
Uses the second derivative spectra in order to find the peaks. To do so, uses an input file to set the three main parameter for each detector : The number of bins to use The threshold for peak detection The number of bins below threshold (by default 2) The spectra's name must be the detector's name (ex R3A1_red) source
References bubble_sort, debug, detectors, find_key, GREY, invert, Detectors::labels, m_histos, m_nb_bins_below, m_rebin, m_threshold, maximum, print, printC, RESET, Calibrator::histograms::spectra, unpack.
Referenced by calculate2.
void Calibrator::calculate(std::string const &dataDir, int nb_files=-1, std::string const &source="152Eu", std::string const &type="fast")
References analyse, loadFasterData, loadRootData, print, writeData, writeRawRoot.
void Calibrator::calculate(std::string const &histograms, std::string const &source="152Eu")
Calculate calibration from .root histograms.
Calculate the calibration coefficients from already calculated histograms. TODO The name of the histograms must correspond either to the name of the detector or the label declared in the ID file
References analyse, Initialise, loadRootHisto, print, writeData, writeRawRoot.
void Calibrator::calculate2(std::string const &histogramsFilename, std::vector< double > peaks, std::string const &fit_info_file="fit_info.data")
References analyse2, Initialise, loadFitInfo, loadRootHisto, print, writeData, writeRawRoot.
auto& Calibrator::calib()
References m_calib.
auto const& Calibrator::calib() const
References m_calib.
Referenced by fillHisto, loadCalibration, loadRootDataThread.
bool const& Calibrator::calibrate_data()
References m_calibrate_data.
bool const& Calibrator::calibrate_data() const
References m_calibrate_data.
void Calibrator::calibrateFasterData(std::string const &folder, int const &nb_files=-1)
References loadFasterData, m_calibrate_data.
void Calibrator::calibrateRootData(std::string const &folder, int const &nb_files=-1)
References loadRootData, m_calibrate_data.
Calibration& Calibrator::calibration()
References m_calib.
Calibration const& Calibrator::calibration() const
References m_calib.
Calibrator::Calibrator()=default
void Calibrator::fillRootDataHisto(std::string const &filename)
References Event::adcs, Calibrator::histograms::all_calib, Calibrator::histograms::calib_spectra, compressedLabel, detectors, isParis, m_calib, m_calibrate_data, m_histos, print, Event::qdc2s, Calibrator::histograms::raw_spectra, Event::reading, Detectors::typeIndex.
void Calibrator::fitCalibration(Fits &fits)
References Fit::chi2, Fit::cmeasures, detectors, Fit::ex, Fit::exists, Fit::ey, isDSSD, isGe, isLaBr3, isParis, m_verbose, Fit::name, Fit::order, Fit::parameter0, Fit::parameter1, Fit::parameter2, Fit::peaks, Fit::scalefactor, Detectors::size, Fit::x, Fit::y.
Referenced by analyse.
void Calibrator::Initialise()
References detectors, Calibrator::histograms::Initialise, m_fits, m_histos, m_Initialised, Fits::resize.
Referenced by calculate, calculate2, loadFasterData, loadRootData, loadRootHisto.
bool Calibrator::loadCalibration(Calibration const &calib)
Loading calibration from file name.
References calib, m_calib.
bool Calibrator::loadCalibration(std::string const &calib_file)
References m_calib.
void Calibrator::loadFasterData(std::string const &dataDir, int const &nb_files=-1)
References MTFasterReader::addFolder, fillHisto, Initialise, print, MTFasterReader::readRaw.
Referenced by calculate, calibrateFasterData.
void Calibrator::loadFitInfo(std::string const &fit_info_file)
References concatenate, detectors, getList, m_nb_bins_below, m_rebin, m_threshold, throw_error.
Referenced by calculate2.
void Calibrator::loadRootData(std::string const &dataDir, int const &nb_files=-1)
References FilesManager::addFolder, FilesManager::getListFiles, Initialise, loadRootDataThread, MTObject::parallelise_function, print.
Referenced by calculate, calibrateRootData.
void Calibrator::loadRootHisto(std::string const &histograms)
Loads non-calibrated spectra.
histograms
References Initialise, loadFormattedTH1F, m_histo_loaded, m_histos, print, readFile, Calibrator::histograms::spectra, throw_error.
Referenced by calculate, calculate2.
Calibrator::operator bool() const &
Todo
void Calibrator::peakFinder(std::string const &source)
References ADC_cast, AddTH1, Calibrator::histograms::all_raw_spectra, detectors, Detectors::exists, MTTHist< THist >::get, information, int_cast, isTripleAlpha, m_fits, m_histos, m_treatOnlyGe, m_treatOnlyParis, m_verbose, CoBazar::mean, print, Calibrator::histograms::raw_spectra, Detectors::size, sum, Detectors::type.
Referenced by analyse.
void Calibrator::setSource(std::string const &source)
References m_source.
void Calibrator::verbose(bool const &_verbose)
References m_verbose.
void Calibrator::verify(std::string const &outfilename="verify")
if some spectra and calibration coefficients have been loaded, or after the calibration coefficients have been calculated, this allows one to check the calibration
outfilename
References Calibrator::histograms::all_calib, Calibration::binom, compressedLabel, detectors, double_cast, information, Calibration::intercept, Detectors::labels, m_calib, m_fits, m_histo_loaded, m_histos, m_verbose, Detectors::nbTypes, Calibration::order, print, Calibrator::histograms::raw_spectra, Calibration::size, Calibration::slope, Calibrator::histograms::spectra, Detectors::type, Detectors::typeIndex.
void Calibrator::writeCalibratedHisto(std::string const &outfilename)
References Calibrator::histograms::all_calib, Calibrator::histograms::calib_spectra, m_histos, print.
void Calibrator::writeData(std::string const &outfilename)
References detectors, Detectors::exists, m_fits, File::makePath, print, File::setExtension.
Referenced by calculate, calculate2.
void Calibrator::writePosPeaks(std::string const &outfilename)
References m_fits, File::makePath, print, File::setExtension.
void Calibrator::writeRawRoot(std::string const &outfilename)
References Calibrator::histograms::all_raw_spectra, m_histos, print, Calibrator::histograms::raw_spectra, MTTHist< THist >::Write.
Referenced by calculate, calculate2.
Calibrator::~Calibrator()
References readFile.
void Calibrator::fillHisto(Hit &hit, FasterReader &reader, Calibrator &calib)
Fills histograms.
There are two modes : You can either fill the histograms with raw values Or you can use the loaded or calculated calibration factors to fille calibrated histograms hit reader calib
References Hit::adc, calib, compressedLabel, detectors, Hit::label, FasterReader::Read, Detectors::typeIndex.
Referenced by loadFasterData.
void Calibrator::loadRootDataThread(Calibrator &calib, MTList &list)
References calib, MTVector< T >::getNext.
Referenced by loadRootData.
static void Calibrator::treatOnlyGe(bool const &b=true)
References m_treatOnlyGe.
static void Calibrator::treatOnlyParis(bool const &b=true)
References m_treatOnlyParis.
void Calibrator::printParameters()