Simplex
std::vector<double> Simplex::m_angles
Vertice Simplex::m_centroid
Referenced by centroid, getCentroid, operator=.
size_t Simplex::m_dim
Referenced by dim, operator=.
size_t Simplex::m_size
Referenced by centroid, operator=, setVertice, Simplex, size.
Vertices Simplex::m_vertices
Referenced by begin, centroid, end, evaluate, operator=, operator[], setVertice, Simplex.
auto Simplex::begin()
References m_vertices.
Referenced by Minimisator::nelderMead.
auto Simplex::begin() const
References m_vertices.
auto Simplex::centroid()
References centroid, m_size.
Referenced by centroid.
auto Simplex::centroid(size_t const &n_best)
References debug, double_cast, m_centroid, m_size, m_vertices, Vertice::size, throw_error.
Referenced by Minimisator::nelderMead.
auto& Simplex::dim()
References m_dim.
auto const& Simplex::dim() const
References m_dim.
Referenced by Minimisator::nelderMead, Simplex.
auto Simplex::end()
References m_vertices.
Referenced by Minimisator::nelderMead.
auto Simplex::end() const
References m_vertices.
void Simplex::evaluate(std::function< double(const Vertice &)> objective_function)
References m_vertices.
Referenced by Minimisator::nelderMead.
auto const& Simplex::getCentroid() const
References m_centroid.
Simplex& Simplex::operator=(Simplex &&other)
References m_centroid, m_dim, m_size, m_vertices.
Simplex& Simplex::operator=(Simplex const &other)
References m_centroid, m_dim, m_size, m_vertices.
Simplex& Simplex::operator=(Vertices const &vertices)
References m_dim, m_size, m_vertices.
auto& Simplex::operator[](int const &i)
References m_vertices.
auto const& Simplex::operator[](int const &i) const
References m_vertices.
void Simplex::setVertice(int const &bin, Vertice &&vertice)
References m_size, m_vertices, size_cast.
void Simplex::setVertice(int const &bin, Vertice const &vertice)
References m_size, m_vertices, size_cast.
Simplex::Simplex(Simplex &&other)
Simplex::Simplex(Simplex const &other)
Simplex::Simplex(size_t const &dim)
References dim, m_size, m_vertices.
Simplex::Simplex(Vertice const &vertice)
Construct a simplex based on a vertice.
The simplex is built based on the dimension of the given vertex, which is then duplicated
References m_size, m_vertices, print, Vertice::size.
Simplex::Simplex(Vertices const &vertices)
References throw_error.
auto& Simplex::size()
References m_size.
auto const& Simplex::size() const
References m_size.
Referenced by Minimisator::nelderMead, operator<<.