EvolutionPeaks
Calibration EvolutionPeaks::m_calib
Referenced by loadCalibration, run.
Path EvolutionPeaks::m_dataPath
Referenced by loadParameters, run.
int EvolutionPeaks::m_nb_files
Referenced by setNbFiles.
File EvolutionPeaks::m_output
Referenced by run, setOutputName.
bool EvolutionPeaks::m_overwrite
Referenced by overwrite, run.
std::vector<double> EvolutionPeaks::m_peaks
Referenced by setPeaks.
DataFile<Label, int> EvolutionPeaks::m_rebins
Referenced by loadRebin, run.
Calibration EvolutionPeaks::m_recalibration
EvolutionPeaks::EvolutionPeaks()=default
EvolutionPeaks::EvolutionPeaks(int argc, char **argv)
References loadParameters, run.
void EvolutionPeaks::loadCalibration(ARGS &&... args)
References Calibration::load, m_calib.
Referenced by loadParameters.
void EvolutionPeaks::loadDetectors(std::string const &filename)
References detectors, Detectors::load.
Referenced by loadParameters.
void EvolutionPeaks::loadParameters(int argc, char **argv)
References loadCalibration, loadDetectors, loadRebin, m_dataPath, overwrite, print, printParameters, setNbFiles, setOutputName, throw_error.
Referenced by EvolutionPeaks.
void EvolutionPeaks::loadRebin(File const &filename)
References DataFile< Index, T >::load, m_rebins.
Referenced by loadParameters.
void EvolutionPeaks::overwrite(bool const &_overwrite=true)
References m_overwrite.
Referenced by loadParameters.
void EvolutionPeaks::printParameters() const
References print.
Referenced by loadParameters.
void EvolutionPeaks::run()
References File::c_str, concatenate, detectors, error, Path::exists, File::exists, found, DataFile< Index, T >::indexes, information, lastPart, m_calib, m_dataPath, m_output, m_overwrite, m_rebins, Calibration::order, print, CoAnalyse::removeBackground, removeExtension, FilesManager::size, throw_error, ushort_cast.
Referenced by EvolutionPeaks.
void EvolutionPeaks::setNbFiles(int const &nb)
References m_nb_files.
Referenced by loadParameters.
void EvolutionPeaks::setOutputName(std::string const &_output)
References m_output.
Referenced by loadParameters.
void EvolutionPeaks::setPeaks(std::vector< double > const &peaks)
References m_peaks.