CoincBuilder
Time CoincBuilder::m_time_window
Referenced by coincidence, setTimeWindow, setTimeWindow_ns.
bool CoincBuilder::build(Hit const &_hit)
Add Hits to the event. Return true when an event is complete, i.e. current hit is outside of time window.
3 status : 0: single | 1: begin of coincidence | 2: coincidence complete
References coincidence, Builder::m_event, Builder::m_keep_singles, Builder::m_last_hit, Builder::m_status, Event::mult, reset.
Referenced by Faster2Root::convertFile, CloverSpectra::runFasterReader, Timeshifts::treatFasterFile.
CoincBuilder::CoincBuilder()
CoincBuilder::CoincBuilder(Event *_event)
CoincBuilder::CoincBuilder(Event *_event, Time const &_timeWindow)
bool CoincBuilder::coincidence(Hit const &hit)
References Builder::m_last_hit, m_time_window, Hit::stamp, Time_cast.
Referenced by build.
Event* Builder::getEvent() const
References Builder::m_event.
Hit const& Builder::getLastHit() const
References Builder::m_last_hit.
bool Builder::isBuilding() const
References Builder::m_status.
bool Builder::isBuilt() const
References Builder::m_status.
bool Builder::isSingle() const
References Event::isSingle, Builder::m_event.
void CoincBuilder::printEvent()
References Builder::m_event.
void CoincBuilder::reset()
References Builder::m_event, Builder::m_status.
Referenced by build.
void Builder::set_first_hit(Hit const &hit)
References Builder::m_last_hit.
void Builder::set_last_hit(Hit const &hit)
References Builder::m_last_hit.
void CoincBuilder::setTimeWindow(Time const &timewindow)
References m_time_window.
void CoincBuilder::setTimeWindow_ns(Time_ns const &timewindow_ns)
References m_time_window.
size_t Builder::size() const
References Builder::m_event, Builder::size.
Referenced by Builder::size.
uchar const& Builder::status() const
References Builder::m_status.
Event* Builder::m_event
Referenced by build, EventBuilder::build, EventBuilder::EventBuilder, Builder::getEvent, Builder::isSingle, printEvent, Builder::reset, reset, EventBuilder::reset, Builder::size.
Hit Builder::m_last_hit
Referenced by build, EventBuilder::build, coincidence, Builder::getLastHit, EventBuilder::reset, Builder::set_first_hit, Builder::set_last_hit, EventBuilder::set_last_hit.
uchar Builder::m_status
Referenced by build, EventBuilder::build, Builder::isBuilding, Builder::isBuilt, Builder::reset, reset, EventBuilder::reset, Builder::status.
bool Builder::m_keep_singles
Referenced by build, Builder::keepSingles.
static void Builder::keepSingles(bool const &b=true)
References Builder::m_keep_singles.
Referenced by Faster2Root::convertFile, CloverSpectra::Initialize, RunMatrixator::Initialize.