Timer
duration_milli_t Timer::d_milli
Referenced by Stop, TimeElapsed, TimeElapsedSec.
hr_clock_t Timer::m_clock
Referenced by Now, Restart, Stop.
time_point_t Timer::m_now
Referenced by Now, Time, TimeSec.
time_point_t Timer::m_start
Referenced by Restart, Stop, Time, TimeSec.
time_point_t Timer::m_stop
Referenced by Stop.
std::string Timer::m_unit
Referenced by operator(), unit, Unit.
time_point_t const& Timer::Now()
References m_clock, m_now.
Referenced by Stop, Time, TimeSec.
auto Timer::operator()()
References m_unit, Time.
time_point_t const& Timer::Restart()
References m_clock, m_start.
Referenced by Timer.
time_point_t const& Timer::Stop()
References d_milli, m_clock, m_start, m_stop, Now.
auto Timer::Time()
References m_now, m_start, Now.
Referenced by operator().
auto Timer::TimeElapsed()
References d_milli.
auto Timer::TimeElapsedSec()
References d_milli.
Timer::Timer()
References Restart.
auto Timer::TimeSec()
References m_now, m_start, Now.
Referenced by Faster2Root::load, Faster2Histo::treatFile.
std::string Timer::unit()
References m_unit.
Referenced by Faster2Root::Faster2Root, RunMatrixator::run, Faster2Histo::treatFile.
float Timer::Unit()
References m_unit.