DSSD
std::array< uchar, 1000 > DSSD::indexes
Referenced by Fill, InitialiseArrays.
std::array< bool, 1000 > DSSD::isRing
Referenced by Fill, InitialiseArrays.
std::array< bool, 1000 > DSSD::isS1
Referenced by InitialiseArrays.
std::array< bool, 1000 > DSSD::isS2
Referenced by InitialiseArrays.
std::array< bool, 1000 > DSSD::isSector
Referenced by InitialiseArrays.
double const DSSD::distance
Referenced by DSSD.
double const DSSD::innerRadius
Referenced by DSSD.
int const DSSD::nb_rings
Referenced by DSSD.
int const DSSD::nb_sectors
Referenced by DSSD.
double const DSSD::outerRadius
std::vector<uchar> DSSD::Ring_Hits
Referenced by angle, Fill, Reset, rings.
double const DSSD::ring_thickness
Referenced by DSSD.
std::size_t DSSD::RingMult
Referenced by Fill, Reset.
std::vector<SiStrip> DSSD::Rings
Referenced by angle, DSSD, Fill, Reset.
std::vector<uchar> DSSD::Sector_Hits
Referenced by energy, Fill, Reset, sectors, time.
std::size_t DSSD::SectorMult
Referenced by Fill, Reset.
std::vector<SiStrip> DSSD::Sectors
Referenced by begin, DSSD, end, energy, Fill, Reset, time.
bool DSSD::s_Initialised
Referenced by InitialiseArrays.
static void DSSD::InitialiseArrays()
References indexes, isRing, isS1, isS2, isSector, Label_cast, MTObject::mutex, print, s_Initialised, uchar_cast.
Referenced by DSSD.
auto const& DSSD::angle() const
Don't return any angle but really the label of the ring.
References Ring_Hits, Rings.
auto DSSD::begin() const
References Sectors.
DSSD::DSSD()
References distance, InitialiseArrays, innerRadius, nb_rings, nb_sectors, ring_thickness, Rings, Sectors.
auto DSSD::end() const
References Sectors.
auto const& DSSD::energy() const
References Sector_Hits, Sectors.
void DSSD::Fill(Event const &evt, int const &index)
References indexes, isDSSD, isRing, Ring_Hits, RingMult, Rings, Sector_Hits, SectorMult, Sectors, time.
Referenced by SetEvent.
bool DSSD::oneParticle() const
References rings, sectors.
void DSSD::Reset()
References Ring_Hits, RingMult, Rings, Sector_Hits, SectorMult, Sectors.
Referenced by SetEvent.
auto DSSD::rings() const
References Ring_Hits.
Referenced by oneParticle.
auto DSSD::sectors() const
References Sector_Hits.
Referenced by oneParticle.
void DSSD::SetEvent(Event const &event)
References Fill, Reset.
auto const& DSSD::time() const
References Sector_Hits, Sectors.
Referenced by Fill.