MTFasterReader
FilesManager MTFasterReader::m_files
Referenced by addFile, addFolder, files, MTFasterReader, readAligned, readRaw.
MTList MTFasterReader::m_MTfiles
Referenced by getFilesList, nextFilename, printMTFiles, readAligned, readRaw.
std::vector<Time> MTFasterReader::m_timeshifts
Referenced by readAligned, setTimeshifts, timeshift.
bool MTFasterReader::s_progressBar
Referenced by Read, showProgressBar.
bool MTFasterReader::addFile(File file)
References FilesManager::addFiles, m_files, File::string.
bool MTFasterReader::addFolder(Path path, int const &nb_files=-1)
References FilesManager::addFolder, m_files.
Referenced by Calibrator::loadFasterData, MTFasterReader.
auto& MTFasterReader::files()
References m_files.
auto const& MTFasterReader::files() const
References m_files.
Referenced by MTFasterReader, Faster2Histo::multirun.
auto& MTFasterReader::getFilesList()
References m_MTfiles.
Referenced by Read.
MTFasterReader::MTFasterReader()
Default constructor.
MTFasterReader::MTFasterReader(FilesManager const &files)
References files, m_files.
MTFasterReader::MTFasterReader(Path path, int const &nb_files=-1)
Regular constructor.
path : The path to the path containing the .fast files to read nb_files : Default -1, takes all the files
References addFolder.
void MTFasterReader::printMTFiles()
References m_MTfiles, print.
void MTFasterReader::readAligned(Func &&func, ARGS &&... args)
Reads many faster files in parallel, providing a time-aligned.
Use this function in the same way as readRaw, with a function like this : func(Hit & hit, Alignator & alignedTree, args...) func : Must be of the form func(Hit & hit, Alignator & alignedTree, args...). Alignator is a simple wrapper around a tree. Use alignedTree::GetEntry
References FilesManager::getListFiles, m_files, m_MTfiles, m_timeshifts, MTObject::parallelise_function, print.
Referenced by CloverSpectra::fillHisto, CobaltCalorimeter::launchFaster, readAligned.
void MTFasterReader::readAligned(std::vector< Time > timeshifts, Func &&func, ARGS &&... args)
References m_timeshifts, readAligned.
void MTFasterReader::readRaw(Func &&func, ARGS &&... args)
Reads many faster files in parallel.
func Function used on each file in parallel. CAREFULL : must be a function or a static method The declared function MUST have its two first parameters as follow : type function(Hit & hit, FasterReader & reader, ...); You can add any other parameter in the ..., but then you have to call them in the readRaw method call e.g. : void my_function(Hit & hit, FasterReader & reader, MTCounter & counter){do something...} in main MTFasterReader readerMT(/path/to/data/folder/, wanted_number_of_files); MTCounter counterMT; readerMT.readRaw(my_function, counterMT); That way, my_function will be executed in parallel on each file in /path/to/data/folder/
References FilesManager::getListFiles, m_files, m_MTfiles, MTObject::parallelise_function, print.
Referenced by Faster2Root::convert, Calibrator::loadFasterData, Faster2Histo::multirun, RunMatrixator::run.
void MTFasterReader::setTimeshifts(std::vector< Time > const &timeshifts)
References m_timeshifts.
Referenced by CobaltCalorimeter::launchFaster.
auto const& MTFasterReader::timeshift(Label const &label) const
References m_timeshifts.
Referenced by Realign.
static void MTFasterReader::showProgressBar(bool const &choice=true)
References s_progressBar.
void MTFasterReader::Read(MTFasterReader &MTreader, Func function, ARGS &&... args)
References getFilesList, MTObject::getThreadIndex, MTObject::kill, nextFilename, print, s_progressBar, CoProgressBar< T >::show.
void MTFasterReader::Realign(MTFasterReader &MTreader, Func function, ARGS &&... args)
References Hit::label, nextFilename, FasterReader::Read, Hit::reading, Hit::reset, Hit::stamp, timeshift, Hit::writting.
bool MTFasterReader::nextFilename(std::string &filename)
References MTVector< T >::getNext, m_MTfiles.
Referenced by Read, Realign.