files_functions.hpp
std::map<std::string, float> size_file_unit
Referenced by size_file, size_file_conversion.
int check_new_file(std::string &folderName, std::string &lastFile)
References push_back_if_none.
void create_folder_if_none(std::string const &folderName)
References folder_exists, MTObject::mutex, print.
Referenced by Path::make.
std::string extension(std::string const &string)
Referenced by FilesManager::addFiles, FasterReader::Initialise, Minimisator::nelderMead, Timeshifts::setOutData, Timeshifts::setOutRoot, Timeshifts::treatFile.
bool file_exists(std::string fileName)
References getPath, removePath.
Referenced by Path::addFolder, File::check, File::exists.
bool file_is_empty(std::ifstream &file)
Referenced by Calibration::load, ParisBidimAngles::load, Timeshifts::load, Detectors::readFile.
std::vector<std::string> findFilesWildcard(std::string const &expression)
Referenced by findFilesWildcard.
void findFilesWildcard(std::string const &expression, std::vector< std::string > &vec)
References findFilesWildcard.
bool folder_exists(std::string folderName)
References push_back_if_none.
Referenced by create_folder_if_none, folder_exists, Path::loadPath, Path::operator bool.
bool folder_exists(std::string folderName, bool const &verbose)
References folder_exists, push_back_if_none.
std::string get_filename_at(std::string &folderName, int pos)
References push_back_if_none.
std::string getExtension(std::string const &string)
Referenced by Filename::fill.
std::string getPath(std::string const &string)
Referenced by FilesManager::addFiles, file_exists, File::fill, hasPath.
void go_to_beginning(std::ifstream &file)
Referenced by DataFile< Index, T >::loadHeader.
bool hasPath(std::string const &file)
References getPath.
Referenced by File::fill, Filename::fill.
std::vector<std::string> list_file_names_in_folder(std::string const &foldername="./", std::vector< std::string > const &extensions={"*"}, bool const &reorder=true)
std::vector<std::string> list_files_in_folder(std::string const &foldername="./", std::vector< std::string > const &extensions={"*"}, bool const &reorder=true)
Referenced by FilesManager::addFolder, fuse_all_histo.
std::vector<std::string> listFileReader(std::string const &filename)
References print.
int nb_files_in_folder(std::string &folderName)
References push_back_if_none.
Referenced by Path::nbFiles.
Folder operator+(const char *string, Folder const &folder)
References Folder::string.
std::string operator+(Path const &path, Filename const &filename)
References Path::get, Filename::get.
Folder operator+(std::string const &string, Folder const &folder)
References Folder::string.
std::ostream& operator<<(std::ostream &cout, File const &file)
References File::get.
std::ostream& operator<<(std::ostream &cout, Folder const &folder)
References Folder::string.
std::ostream& operator<<(std::ostream &cout, Folders const &folders)
References Folders::get.
std::ostream& operator<<(std::ostream &cout, Path const &p)
References Path::path.
std::ostream& operator<<(std::ostream &os, Filename const &filename)
References Filename::fullName.
std::string procent(N const &n, D const &d)
std::string& push_back_if_none(std::string &string, char const &character)
Referenced by FilesManager::addFolder, check_new_file, folder_exists, get_filename_at, Path::loadPath, nb_files_in_folder, Path::operator+=, Timeshifts::setOutDir.
std::string removeExtension(std::string const &string)
Referenced by rmPathAndExt, EvolutionPeaks::run, Timeshifts::setOutData, Timeshifts::setOutRoot, Timeshifts::setParameters, RunMatrixator::Write.
std::string removePath(std::string const &string)
Referenced by file_exists, File::fill, rmPathAndExt.
std::string rmPathAndExt(std::string const &string)
References removeExtension, removePath.
Referenced by Faster2Histo::addFile, Faster2Histo::addFolder, Filename::fill, Timewalk::loadFile.
float size_file(std::ifstream &file, std::string const &unit="o")
References size_file_unit.
Referenced by FilesManager::diskSize, File::size, size_file.
float size_file(std::string filename, std::string const &unit="o")
References size_file.
float size_file_conversion(float const &size, std::string const &unit_i, std::string const &unit_o)
References size_file_unit.