libCo.hpp
_GLIBCXX_USE_CXX11_ABI
using Ints = std::vector<int>
using longlong = long long int
using size_t = std::size_t
using Strings = std::vector<std::string>
using T_is_number = void
using uchar = unsigned char
using uint = unsigned int
using ulong = unsigned long int
using ulonglong = unsigned long long int
using ushort = unsigned short int
std::map<std::string, std::string> error_message
Referenced by Calibrator::histograms::Initialise, Faster2Root::load.
bool bool_cast(T const &t)
Casts a any type into an bool.
Referenced by Fit::exists, Fit::peaks_found, Fit::too_few_counts.
char char_cast(T const &t)
Casts a number into an char.
Referenced by TypeRootMap::TypeRootMap.
double double_cast(T const &t)
Casts a number into an double.
Referenced by CobaltCalorimeter::Analyse, Simplex::centroid, SpectraCo::createTH1D, getData, SpectraCo::load, CoBazar::mean, CobaltCalorimeter::NaI_pid, SpectraCo::resizeBin, RF_Manager::set, Timeshifts::shiftTimeSpectra, SpectraCo::SpectraCo, TypeRootMap::TypeRootMap, Calibrator::verify.
bool find_key(std::map< K, V > const &map, K const &key)
Returns yes if the key is found in the map.
This method is only looking in the keys, not in the values
bool find_key(std::unordered_map< K, V > const &map, K const &key)
Referenced by Calibrator::analyse2, Timeshifts::rebin.
bool find_value(std::map< K, V > const &map, V const &value)
Returns yes if the value is found in the map.
This method is only looking in the values, not in the keys
bool find_value(std::unordered_map< K, V > const &map, V const &value)
float float_cast(T const &t)
Casts a number into a float.
Referenced by Calibration::calibrate, getData, CoProgressBar< T >::show, CoProgressBar< T >::showFast, TypeRootMap::TypeRootMap.
std::pair<K,V> get_max_element(std::map< K, V > const &map)
Returns the element with the maximum value.
This method is only comparing values, not keys
K get_max_key(std::map< K, V > const &map)
Returns the maximum key stored in the map.
This method is only looking for values, not keys
V get_max_value(std::map< K, V > const &map)
Returns the maximum value stored in the map.
This method is only lookinf for values, not keys
std::pair<K,V> get_min(std::map< K, V > const &map)
K get_min_key(std::map< K, V > const &map)
V get_min_value(std::map< K, V > const &map)
int int_cast(T const &t)
Casts a number into an int.
Referenced by CobaltCalorimeter::Analyse, Timeshifts::analyse, SpectraCo::calibrate, Faster2Histo::fillHisto, SpectraCo::getBin, goingAbove, goingBelow, Detectors::makeArrays, Clovers::mult, operator<<, Calibrator::peakFinder, CoBazar::progress_bar, DataFile< Index, T >::setColumns, Timeshifts::shiftTimeSpectra, CoProgressBar< T >::show, CoProgressBar< T >::showFast, TypeRootMap::TypeRootMap.
bool is_int(double const &x)
Check if the given double holds an integer.
std::vector<K> list_of_keys(std::map< K, V > const &map)
Returns the list of keys in a map.
This method is only looking in the keys, not the values
long long_cast(T const &t)
Casts a number into an long.
Referenced by FilesManager::addFolder, TypeRootMap::TypeRootMap.
longlong longlong_cast(T const &t)
Casts a number into long long (longlong)
std::ostream& operator<<(std::ostream &cout, Bools const &bools)
std::ostream& operator<<(std::ostream &cout, std::array< E, size > const &a)
References print.
std::ostream& operator<<(std::ostream &cout, std::map< K, V > const &m)
std::ostream& operator<<(std::ostream &cout, std::pair< F, S > const &p)
std::ostream& operator<<(std::ostream &cout, std::unordered_map< K, V > const &m)
std::ostream& operator<<(std::ostream &cout, std::vector< E > const &v)
std::ostream& operator<<(std::ostream &cout, uchar const &uc)
auto pauseCo()
References MTObject::mutex.
Referenced by CobaltCalorimeter::Analyse, OutputTFile::OutputTFile, pauseDebug.
auto pauseCo(std::string const &message)
References MTObject::mutex.
void pauseDebug(std::string const &message="")
References pauseCo.
T positive_modulo(T const &dividend, T const &divisor)
Referenced by Clovers::label_to_cristal.
short short_cast(T const &t)
Casts a number into an short.
Referenced by TypeRootMap::TypeRootMap.
size_t size_cast(T const &t)
Casts a number into std::size_t.
Referenced by MTCounter::add, MTCounter::operator+=, MTCounter::operator=, Simplex::setVertice, Event::size.
T string_to(std::string const &string)
References concatenate, type_of.
void throw_error(std::string const &message)
References concatenate, RED, RESET.
Referenced by SpectraCo::calibrateAndScale, Simplex::centroid, Gates_t< T >::check, Faster2Root::convertFile, Vertice::copy, create_map_of, RunMatrixator::dontMatrixate, CloverSpectra::fillHisto, RunMatrixator::Initialise, CloverSpectra::Initialise, Calibration::load, Faster2Root::load, Faster2Histo::load, ParisBidimAngles::load, SpectraCo::load, Calibrator::loadFitInfo, loadFormattedTH1F, EvolutionPeaks::loadParameters, Calibrator::loadRootHisto, Detectors::nbOfType, NearLine::NearLine, Minimisator::nelderMead, Vertice::operator*, Vertice::operator+, Vertice::operator-, PeaksCalibrator::PeaksCalibrator, CoAnalyse::projectX, CoAnalyse::projectY, Timeshifts::rebin, Paris::rotate, EvolutionPeaks::run, RunMatrixator::run, DataFile< Index, T >::setColumn, Calibrator::histograms::setTypeBins, CoAnalyse::setX, CoAnalyse::setY, CoProgressBar< T >::show, CoProgressBar< T >::showFast, Simplex::Simplex, CobaltCalorimeter::write, RunMatrixator::Write, CloverSpectra::writeHisto.
std::string time_string()
Returns a string in the format mm_hh_dd_mm_yy.
std::string time_string_inverse()
Returns a string in the format yy_mm_dd_hh_mm.
uchar uchar_cast(T const &t)
Casts a number into unsigned char (uchar)
Referenced by Counters::clover_analyse, Counters::count_event, DSSD::InitialiseArrays, Clovers::label_to_cristal, Detectors::makeArrays, TypeRootMap::TypeRootMap.
uint uint_cast(T const &t)
Casts a number into unsigned int (uint)
Referenced by TypeRootMap::TypeRootMap.
ulong ulong_cast(T const &t)
Casts a number into unsigned long (ulong)
Referenced by TypeRootMap::TypeRootMap.
ulonglong ulonglong_cast(T const &t)
Casts a number into unsigned long long (ulonglong)
ushort ushort_cast(T const &t)
Casts a number into unsigned short (ushort)
Referenced by EvolutionPeaks::run, TypeRootMap::TypeRootMap.