libRoot.hpp
using TH1F_map = std::map<std::string, TH1F*>
using unique_TFile = std::unique_ptr<TFile>
using unique_TH1F = std::unique_ptr<TH1F>
using unique_TH2F = std::unique_ptr<TH2F>
using unique_tree = std::unique_ptr<TTree>
class TypeRootMap typeRootMap
Referenced by createBranch, createBranchArray.
void AddTH1(TH1 *histo_total, TH1 *histo)
Patch to the TH1::Add method when the histograms limits are inconsistent.
Referenced by AddTH1ByValue, Calibrator::peakFinder.
bool AddTH1(TH2 *histo2, TH1 *histo1, int index, bool x=true)
References print.
bool AddTH1ByValue(TH2 *histo2, TH1 *histo1, int index, bool x=true)
Like AddTH1 but adjusts the binning first.
Tododoesn't work for some reason ... histo2 histo1 index x true false
References AddTH1, print.
void alignator(TTree *tree, int *NewIndex)
Referenced by Faster2Root::convertFile.
std::map<std::string, T> create_map_of(TFile *file)
References throw_error.
auto createBranch(TTree *tree, T *value, std::string const &name, int buffsize=64000)
Create a branch for a given value and name.
References typeRootMap.
Referenced by Event::writting.
auto createBranchArray(TTree *tree, T *array, std::string const &name, std::string const &name_size, int buffsize=64000)
Create a branch for a given array and name.
name_size The name of the leaf that holds the size of the array
References typeRootMap.
Referenced by Event::writting.
void draw_all_TH1(std::string const &filename, int minX=0, int maxX=0, int rebin=1, std::string pattern="")
Draws all the TH1F of a given file one by one.
Only works in CINT environnement (= macro only)
References found, print.
int findNextBinAbove(TH1 *histo, int &bin, double threshold)
Referenced by Paris::findAngles.
int findNextBinBelow(TH1 *histo, int &bin, double threshold)
Referenced by Paris::findAngles.
void fuse_all_histo(std::string const &folder, std::string const &outRoot="fused_histo.root", bool const &bidim=true)
allows one to fuse all the histograms with the same name from different files
References list_files_in_folder, print.
std::vector<std::string> get_names_of(TFile *file)
References print.
TH1F_map get_TH1F_map(TFile *file)
References get_TH1F_names.
Referenced by loadFormattedTH1F.
TH1F_map get_TH1F_map(TFile *file, std::vector< std::string > &names)
References get_TH1F_names.
std::vector<std::string> get_TH1F_names(std::string const &filename)
References get_TH1F_names.
std::vector<std::string> get_TH1F_names(TFile *file)
References print.
Referenced by get_TH1F_map, get_TH1F_names.
int getBin0(TH1F *spectra)
Get which bin holds the X = 0.
void getData(TH1 *histo, std::vector< double > &data)
References double_cast.
void getData(TH1 *histo, std::vector< float > &data)
References float_cast.
bool getMeanPeak(TH1F *spectra, double &mean)
Get the mean of the peak of a histogram with one nice single peak.
References CoBazar::mean.
Referenced by Timeshifts::analyse.
void GetPoint(TVirtualPad *vpad, double &x, double &y)
This method allows one to get the x and y values of where the user clicks on the graph.
References print.
Referenced by AnalysedSpectra::choosePeaks, AnalysedSpectra::selectX.
void libRoot()
References print.
Long64_t Long64_cast(T const &t)
Casts a number into unsigned short.
Referenced by TypeRootMap::TypeRootMap.
float maxXaxis(TH1 *histo)
Referenced by CoAnalyse::projectX.
float maxYaxis(TH1 *histo)
Referenced by CoAnalyse::projectY.
double MeanBetweenEdges(TH1F *hist, double edge1, double edge2)
References sum.
float minXaxis(TH1 *histo)
Referenced by CoAnalyse::projectX.
float minYaxis(TH1 *histo)
Referenced by CoAnalyse::projectY.
std::ostream& operator<<(std::ostream &cout, THBinning binning)
References THBinning::bins, THBinning::max, THBinning::min.
std::ostream& operator<<(std::ostream &out, TTree *tree)
void removeFits(TH1 *histo)
void resize_view_range(TH1F *histo)
void resize_view_range(TH1F *histo, float const &min)
void shiftX(TH1 *histo, double shift)
Shifts a histogram by 'shift' X value.
shift Shifts each bin content by 'shift' units of the x axis
References concatenate.
Referenced by Timeshifts::verify.
void test_alignator(TTree *tree, int *NewIndex=nullptr, bool useNewIndex=false)
bool THist_exists(TH1 *histo)
ULong64_t ULong64_cast(T const &t)
Casts a number into unsigned short.
Referenced by TypeRootMap::TypeRootMap.