CoAnalyse
using CoAnalyse::ProjectionsBins = typedef std::vector<std::pair<double,double> >
Vector of pairs of min and max bins.
std::vector<double> CoAnalyse::extractBackgroundArray(std::vector< double > &source, int const &nsmooth=10)
Deprecated
References print.
std::vector<double> CoAnalyse::extractBackgroundArray(TH1F *histo, int const &nsmooth=10)
Deprecated
References print.
void CoAnalyse::normalizeBidim(TH2 *matrix, double const &factor=1.0)
Normalise the whole bidim.
void CoAnalyse::normalizeY(TH2 *matrix, double const &factor=1)
For each X bin, normalise the Y histogram.
void CoAnalyse::projectX(TH2 *matrix, TH1 *proj)
Project the whole matrix on the X axis. This fills proj.
References maxXaxis, minXaxis, throw_error.
Referenced by projectX, removeBackground.
void CoAnalyse::projectX(TH2 *matrix, TH1 *proj, double const &binYmin, double const &binYmax)
Project on Y axis between values binYmin and binYmax included [binYmin;binYmax]. This fills proj.
References projectX.
void CoAnalyse::projectX(TH2 *matrix, TH1 *proj, int const &binY)
Project on X axis at a given Y bin. This fills proj.
References maxXaxis, minXaxis, throw_error.
void CoAnalyse::projectX(TH2 *matrix, TH1 *proj, int const &binYmin, int const &binYmax)
Project on X axis between bin binYmin included and binYmax excluded [binYmin;binYmax[. This fills proj.
References maxXaxis, minXaxis, throw_error.
void CoAnalyse::projectY(TH2 *matrix, TH1 *proj, double const &valueXmin, double const &valueXmax)
Project matrix on Y axis between values valueXmin and valueXmax included [valueXmin;valueXmax]. This fills proj.
References projectY.
void CoAnalyse::projectY(TH2 *matrix, TH1 *proj, int const &binX)
Project matrix on Y axis at a given X bin. This fills proj.
References maxYaxis, minYaxis, throw_error.
Referenced by projectY, removeBackground.
void CoAnalyse::projectY(TH2 *matrix, TH1 *proj, int const &binXmin, int const &binXmax)
Project matrix on Y axis between bin binXmin included and binXmax excluded [binXmin;binXmax[. This fills proj.
References maxYaxis, minYaxis, throw_error.
void CoAnalyse::removeBackground(TH1 *histo, int const &niter=10, std::string const &fit_options="", std::string const &bidim_options="X") noexcept
Remove the background in the given histo.
histo Can be TH1 or TH2 histogram niter Choose a higher number of iterations if the peaks have high resultion (5-10 for LaBr3, 20 for Ge) fit_options options from TH1::ShowBackground bidim_options "X" (default) : Loop through the X bins, find the background on the Y projection "Y" : Loop through the Y bins, find the background on the X projection "S" (symmetric): Loop through the X bins, find the background on the Y projection, then symmetrise the bidim
References print, projectX, projectY, setX, setY.
Referenced by SpectraCo::removeBackground, EvolutionPeaks::run.
void CoAnalyse::removeRandomBidim(TH2 *matrix, int iterations=1, bool save_intermediate=false, ProjectionsBins projectionsY={{}}, ProjectionsBins projectionsX={{}})
Deprecated
void CoAnalyse::removeRandomY(TH2 *matrix, int _stopX=-1, int _stopY=-1, bool writeIntermediate=false, ProjectionsBins projections={{}})
LEGACY.
void CoAnalyse::setX(TH2 *matrix, TH1 *proj, int const &binX)
Set Y histogram proj in matrix at binX.
References throw_error.
Referenced by removeBackground.
void CoAnalyse::setY(TH2 *matrix, TH1 *proj, int const &binY)
Set X histogram proj in matrix at binY.
References throw_error.
Referenced by removeBackground.