CoBazar
void CoBazar::long_progress_bar(float const &progress_procent)
References progress_bar.
double CoBazar::mean(ARGS... args)
References double_cast, sum.
Referenced by Timeshifts::analyse, BiggestPeakFitter::BiggestPeakFitter, PeakFitter::fit, randomCo::gaussian, getMeanPeak, SpectraCo::meanInRange, SpectraCo::meanInRangeBin, Calibrator::peakFinder.
void CoBazar::progress_bar(float const &progress_procent, int width=50)
References int_cast.
Referenced by long_progress_bar, short_progress_bar.
void CoBazar::short_progress_bar(float const &progress_procent)
References progress_bar.
T CoBazar::sum(T i, ARGS... args)
Referenced by mean.