print.hpp
_GLIBCXX_USE_CXX11_ABI
BLACK
BLUE
BRIGHTBLACK
BRIGHTBLUE
BRIGHTCYAN
BRIGHTGREEN
BRIGHTMAGENTA
BRIGHTRED
BRIGHTWHITE
BRIGHTYELLOW
CYAN
GREEN
GREY
MAGENTA
RED
RESET
WHITE
YELLOW
void debug(ARGS &&... args)
Requires #define DEBUG or -DDEBUG in the compile line.
References print.
Referenced by Calibrator::analyse2, Simplex::centroid, MTTHist< THist >::Merge, MTTHist< THist >::Merged, Minimisator::nelderMead, MTTHist< THist >::operator->, CobaltCalorimeter::work.
void error(T const &... t)
Print in red.
References print, RED, RESET.
Referenced by SpectraCo::calibrate, SpectraCo::chi2, MTTHist< THist >::CopyError::CopyError, SpectraCo::derivative, SpectraCo::derivative2, Timeshifts::EmptyError::EmptyError, Detectors::EmptyError::EmptyError, Detectors::Error::Error, ParisBidimAngles::FileError::FileError, Faster2Histo::fillHisto, SpectraCo::findPeaks, loadFormattedTH1F, Timeshifts::NotFoundError::NotFoundError, SpectraCo::operator/, OverwriteError::OverwriteError, Detectors::readFile, EvolutionPeaks::run, RunMatrixator::Write.
void information(T const &... t)
Print in grey.
References GREY, print, RESET.
Referenced by Calibrator::peakFinder, EvolutionPeaks::run, Calibrator::verify.
void print()
New line.
Referenced by FilesManager::addFolder, AddTH1, AddTH1ByValue, Minimisator::NelderMeadParameters::adjustToDimension, SpectraAlignator::alignSpectra, CobaltCalorimeter::Analyse, Timeshifts::analyse, Calibrator::analyse, Calibrator::analyse2, HitBuffer::at, AnalysedSpectra::autoCanvas, BiggestPeakFitter::BiggestPeakFitter, Faster2Root::buildEvents, Calibrator::calculate, Timeshifts::calculate, Calibrator::calculate2, Paris::calculateBidimAngles, File::check, DataFile< Index, T >::checkInputfile, DataFile< Index, T >::checkOutputfile, Timeshifts::CheckParameters, AnalysedSpectra::choosePeaks, Nuball2Tree::Close, Faster2Root::convert, Faster2Root::convertFile, create_folder_if_none, debug, draw_all_TH1, error, ObjectiveFunctionChi2::evaluate, CoAnalyse::extractBackgroundArray, Faster2Root::Faster2Root, Filename::fill, Calibrator::fillRootDataHisto, AnalysedSpectra::fitPeaks, fuse_all_histo, get_names_of, get_TH1F_names, GetPoint, information, FasterReader::Initialise, Calibrator::histograms::Initialise, RunMatrixator::Initialise, Timeshifts::Initialise, CloverSpectra::Initialise, DSSD::InitialiseArrays, Paris::InitialiseArrays, FasterReader::InitialiseReader, Event::isCalibrated, CobaltCalorimeter::launchRoot, libRoot, listFileReader, Calibration::load, Faster2Root::load, Faster2Histo::load, ParisBidimAngles::load, Timeshifts::load, DataFile< Index, T >::loadData, Calibrator::loadFasterData, Timewalk::loadFile, Timewalks::loadFile, Alignator::loadNewIndex, EvolutionPeaks::loadParameters, Path::loadPath, Calibrator::loadRootData, Calibrator::loadRootHisto, MyError::MyError, Minimisator::nelderMead, SpectraAlignator::newAlignement, Nuball2Tree::Open, operator<<, ParisXY::ParisXY, Calibrator::peakFinder, PositionXY::Print, Minimisator::NelderMeadParameters::Print, Calibration::Print, FilesManager::Print, Timewalk::Print, MTVector< T >::Print, MTTHist< THist >::Print, Event::Print, print, Clovers::PrintClean, FilesManager::printFolders, MTFasterReader::printMTFiles, CloverSpectra::printParameters, EvolutionPeaks::printParameters, Faster2Root::printParameters, Faster2Histo::printParameters, Event::push_back, Event::push_front, MTRootReader::read, MTFasterReader::Read, MTFasterReader::readAligned, FasterReader::ReadData, Detectors::readFile, Manip::readFile, Event::reading, Hit::reading, NearLine::readParam, MTFasterReader::readRaw, CoAnalyse::removeBackground, RWMat::Reset, Detectors::resize, SpectraCo::resizeX, Paris::rotate, EvolutionPeaks::run, RunMatrixator::run, CloverSpectra::runFasterReader, FasterReader::setMaxHits, Manip::setMT, IOptions::setOptions, Timeshifts::setParameters, Timeshifts::setTimeWindow_ns, Timeshifts::shiftTimeSpectra, Simplex::Simplex, Timeshifts::treatFasterFile, Faster2Histo::treatFile, Timeshifts::treatFolder, FasterReader::TreatQDC2, FasterReader::TreatQDC3, Timeshifts::verify, Calibrator::verify, warning, CobaltCalorimeter::write, RunMatrixator::Write, MTTHist< THist >::Write, OutputTFile::Write, ParisBidimAngles::write, Faster2Histo::write, Calibration::write, RWMat::Write, Calibrator::writeCalibratedHisto, DataFile< Index, T >::writeData, Timeshifts::writeData, Calibrator::writeData, CloverSpectra::writeHisto, Calibrator::writePosPeaks, Calibrator::writeRawRoot, Timeshifts::writeRoot, Hit::writting, Event::writting, RWMat::~RWMat, StaticVector< T >::~StaticVector.
void print(T const &t)
Generic print.
Automatically adds space between each input. Terminate the output with a "\\n"
void print(T const &t, T2 const &... t2)
Generic print.
Automatically adds space between each input. Terminate the output with a "\\n"
References print.
void print_precision(int n=6)
Set the floating point precision displayed.
void printC(T const &t)
Generic print concatenated.
Concatenate the ouput, i.e. do not add space between each input. Terminate the output with a "\\n"
Referenced by Calibrator::analyse2, bubble_sort, SpectraCo::HistoNull::HistoNull, SpectraCo::HistoZombie::HistoZombie, printC.
void printC(T const &t, T2 const &... t2)
Generic print concatenated.
Concatenate the ouput, i.e. do not add space between each input. Terminate the output with a "\\n"
References printC.
void println(T const &t)
Generic print in one line.
Concatenate the ouput, i.e. do not add space between each input. Do not terminate the output with a "\\n"
Referenced by println.
void println(T const &t, T2 const &... t2)
Generic print in one line.
Concatenate the ouput, i.e. do not add space between each input. Do not terminate the output with a "\\n"
References println.
std::string type_of(T const &t)
Referenced by string_to, type_of< SpectraCo >.
void warning(T const &... t)
Print in bright black.
References print, RESET, YELLOW.
Referenced by SpectraCo::SizeMissmatch::SizeMissmatch.