random.hpp
std::random_device rd
std::mt19937 gen(rd())
Referenced by random_uniform.
double random_uniform()
References gen, uniform_random_generator_double.
Referenced by Calibration::calibrate.
std::uniform_real_distribution<double> uniform_random_generator_double(0, 1)
Referenced by random_uniform.