string_functions.hpp
std::string argv_to_string(char **argv, int const &start_i=0)
Convert i_th first arguments of argv into a string (), by default starting at the first.
argv MUST be null-terminated Each argument starts with a space
std::string concatenate(ARGS &&... args)
References my_to_string.
Referenced by concatenate_c, ctcstr, ctstr, SpectraCo::draw, Paris::findAngles, AnalysedSpectra::fitPeak, AnalysedSpectra::fitPeaks, Calibrator::loadFitInfo, loadFormattedTH1F, PeaksCalibrator::PeaksCalibrator, Detectors::readFile, SpectraCo::rebin, Paris::rotate, EvolutionPeaks::run, DataFile< Index, T >::setColumn, shiftX, string_to, throw_error, Timeshifts::verify, CobaltCalorimeter::write.
const char* concatenate_c(ARGS &&... args)
concatenate string, returns a c_str (char**)
References concatenate.
std::string ctcstr(ARGS &&... args)
concatenate string, returns a c_str (char**)
References concatenate.
std::string ctstr(ARGS &&... args)
Concatenate a series of arguments into a big string (alias)
References concatenate.
void delete_argv(char **argv)
Delete an argv manually created by string_to_argv()
void fillList(std::vector< std::string > &list, std::string string, char const &separator, bool const &removeVoids=false)
Cuts a string into pieces separated by the given separator like ';' or ' ' or ','.
removeVoids For instance, we have string = ";1;2;3;;5". without removeVoids this function returns {"1", "2", "3", "5"} with removeVoids this function returns {"", "1", "2", "3", "", "5"}
Referenced by getList, DataFile< Index, T >::loadData, DataFile< Index, T >::loadHeader.
std::string firstPart(std::string const &string, char const &sep)
Returns the string to the left of the first occurence of sep in the string.
std::string firstPart(std::string const &string, std::string const &sep)
Returns the string to the left of the first occurence of sep in the string.
bool found(std::string const &string, std::string const &_substr)
Returns true if the string has at least one occurence of substr.
Referenced by RunMatrixator::dontMatrixate, draw_all_TH1, Faster2Histo::fillHisto, loadFormattedTH1F, Faster2Root::loadTriggerFile, Detectors::nbOfType, Fit::peaks_found, EvolutionPeaks::run.
std::vector<std::string> getList(std::string string, char const &separator, bool const &removeVoids=false)
References fillList.
Referenced by Calibrator::loadFitInfo, Path::makeFolderList, replaceCharacter, split, string_to_argv.
bool isNumber(std::string const &string)
Returns true if all its characters are digits.
Referenced by Timeshifts::setTimeReference.
std::string lastPart(std::string const &string, char const &sep)
Returns the string to the right of the last occurence of sep in the string.
std::string lastPart(std::string const &string, std::string const &sep)
Returns the string to the right of the last occurence of sep in the string.
Referenced by EvolutionPeaks::run.
std::string my_to_string(const T &value)
Convert any type into string, including vector of any type.
Referenced by concatenate.
std::string& pop_front(std::string &string)
Removes the first character of a string.
Careful, time complexity makes it really heavy on big string
bool remove(std::string &string, char const &c)
Remove the first char 'c' to the string if found.
bool remove(std::string &string, std::string const &_substr)
Remove the first substr to the string if found.
Referenced by Paris::calculateBidimAngles, loadFormattedTH1F, Filename::setExtension.
std::string removeBlankSpace(std::string str)
Remove all the blank space in a string.
std::string removeFirstPart(std::string const &string, char const &sep)
Returns the string to the right of the first occurence of sep in the string.
std::string removeFirstPart(std::string const &string, std::string const &sep)
Returns the string to the right of the first occurence of sep in the string.
std::string removeLastPart(std::string const &string, char const &sep)
Returns the string to the left of the last occurence of sep in the string.
std::string removeLastPart(std::string const &string, std::string const &sep)
Returns the string to the left of the last occurence of sep in the string.
bool replace(std::string &string, std::string const &substr_init, std::string const &substr_substitue)
Replace substr to the string if it exists.
Referenced by SpectraCo::calibrate.
std::string replaceCharacter(std::string const &istring, char const &ichar, char const &ochar)
Replaces all the instances of one character with another.
For instance : std::string istring = "je_suis_ton_pere"; std::string ostring = replaceCharacter(istring, '_', ' '); print(ostring); // output : "je suis ton pere"
References getList.
Referenced by Detectors::makeArrays.
std::string rpCommaWDots(std::string str)
Replace all the commas of a std::string with dots.
std::vector<std::string> split(std::string string, char const &separator, bool const &removeVoids=false)
References getList.
char** string_to_argv(std::string const &string)
Create a null terminated C-style array of char from a string.
you'll have to delete the allocated memory
References getList.