vector_functions.hpp
using vector2D = std::vector<std::vector<T> >
std::vector<int> bubble_sort(std::vector< T > const &vector)
Order the vector from lower to higher value.
References bubble_sort.
std::vector<int>& bubble_sort(std::vector< T > const &vector, std::vector< int > &ordered_indexes)
Order the vector from lower to higer value.
References printC, RED, RESET.
Referenced by Calibrator::analyse2, bubble_sort, Faster2Histo::write.
void fill2D(vector2D< T > &vec2, size_t const &size_x, size_t const &size_y, T const &obj)
int first_index_in(std::vector< T > &vec, T &t)
Referenced by DataFile< Index, T >::setColumn.
int first_index_in(std::vector< T > &vec, T const &t)
int first_index_in(std::vector< T > const &vec, T &t)
int first_index_in(std::vector< T > const &vec, T const &t)
bool found(std::vector< T > &vec, T &t)
bool found(std::vector< T > &vec, T const &t)
bool found(std::vector< T > const &vec, T &t)
bool found(std::vector< T > const &vec, T const &t)
void invert(std::vector< T > &vector)
Referenced by Calibrator::analyse2.
T maximum(std::vector< T > const &vector)
Referenced by Calibrator::analyse2, Paris::findAngles.
T maximum_index(std::vector< T > const &vector)
T minimum(std::vector< T > const &vector)
T minimum_index(std::vector< T > const &vector)
std::ostream& operator<<(std::ostream &cout, StaticVector< T > const &vector)
std::istream& operator>>(std::istream &input, std::vector< T > vector)
std::istringstream& operator>>(std::istringstream &is, std::vector< T > &v)
std::vector<T> push_back(std::vector< T > const &target, std::vector< T > const &source)
std::vector<T> push_back(std::vector< T > const &target, T const &value)
Referenced by CoincBuilder::build, EventBuilder::build.
bool push_back_unique(std::vector< T > &vector, T const &t)
Referenced by Clovers::FillFast, Sorted_Event::sortGeClover.
auto sub_vec(std::vector< T > const &vec, int const &start, int const &length)
Returns the vector in the range [start, start+length[.
E.g. vec = {1,2,3,4,5} ; sub_vec(vec, 1, 3) -> {2, 3, 4};
Referenced by SpectraCo::calibrateAndScale.
T sum(std::vector< T > const &source)
Referenced by MeanBetweenEdges, Calibrator::peakFinder, SpectraCo::resizeBin.
void unpack(std::vector< std::pair< K, V >> const &pairs, std::vector< K > &keys, std::vector< V > &values)
Referenced by Calibrator::analyse2.